<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:1680px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/project_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>筹资项目</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                   	  <?php foreach ($this->my_jjh_pm as $key => $value){
                   	  		if ($value['c_name'] != "推荐项目"){?>
                      	<li>
	                      	<a href="/jjhpm/index?cid=<?php echo $value['c_id'];?>">
	                      		<?php if($this->pm_info[0]['c_id'] == $value['c_id']){?><span><?php }?>
	                      			<?php echo $value['c_name'];?>
	                      		<?php if($this->pm_info[0]['c_id'] == $value['c_id']){?></span><?php }?>
	                      	</a>
                      	</li>
                      <?php }}?>
                   </ul>
                   <div class="jjh_sub_nav_recommond"><a href="/jjhpm/tuijian">推荐项目</a></div>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><em><?php echo $this->pm_info[0]['c_name']?></em><span>当前位置：
              <a href="/jjhpm">筹资项目</a> > <?php echo $this->pm_info[0]['c_name']?></span></div>
              <div class="jjh_sub_con_content" style="height:1500px;">
              <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/projectadv.jpg" /></div>
                <ul class="jjh_project">
                <?php foreach ($this->jjh_info as $key => $value){?>
                    <li>
                      <div class="protit"><?php echo $value['c_name'];?></div>
                      <div class="procon"><?php echo $value['c_describe'];?></div>
                      <div class="prolink">
	                      <a href="/donate/index?cid=<?php echo $value['c_id'];?>&cname=<?php echo $value['c_name'];?>">
	                      <img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/prodonate.jpg" border="0" align="absmiddle" />
	                      </a>&nbsp;&nbsp;
	                      <a href="/jjhpm/jincheng?cid=<?php echo $value['c_id'];?>">了解项目进展</a>
                      </div>
                    </li>
                 <?php }?>  
                </ul>
              </div>
         </div>
     </div>
     
<?= $this->partial("common/footer.phtml");?>