<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="min-height:1010px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/project_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>项目介绍</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                   	  <?php foreach ($this->my_jjh_pm as $key => $value){
                   	  		if ($value['c_name'] != "推荐项目"){?>
                      	<li>
	                      	<a href="/jjhpm/index?cid=<?php echo $value['c_id'];?>">
	                      		<?php if($this->pm_info[0]['c_id'] == $value['c_id']){?><span><?php }?>
	                      			<?php echo $value['c_name'];?>
	                      		<?php if($this->pm_info[0]['c_id'] == $value['c_id']){?></span><?php }?>
	                      	</a>
                      	</li>
                      <?php }}?>
                   </ul>
                   <div class="jjh_sub_nav_recommond"><a href="/jjhpm/tuijian">推荐项目</a></div>
              </div>
         </div>
         <div class="jjh_content_sub_right">
             <div class="jjh_sub_con_content" style="min-height:880px; padding:0px; width:690px;">
               <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/procomadv4.jpg" /></div><br />
               <div class="jjh_prorecom_detail_left">
                <div class="jjh_prorecom_detit1">项目介绍</div> 
                <div class="jjh_prorecom_decon">
                <span style="font-size:20px; font-weight:bold; text-align:center; display:block; margin-bottom:10px;">迎接120年校庆    共建美好新家园</span>
				<span class="jjh_font4" style="text-align:center;  display:block;">为母校新校区建设“添砖加瓦”捐款倡议书</span><br />
		<p style="text-indent:20px;">五十元，可以为勤工助学的学弟学妹购置一本正版图书</p>
		<p style="text-indent:20px;">一百元，可以为学生活动室添置一把新座椅；</p>
		<p style="text-indent:20px;">五百元，可以变成一块“砖瓦”，筑我们共同的梦，建我们共同的家。</p>
		<p style="text-indent:20px;">津南大地，海河中游，在那片充满无限向往和期待的土地上，天津大学新校区建设如火如荼地进行。这是天大人的梦，每个人的梦；这是北洋人的家，每个人的家。</p>
		<p style="text-indent:20px;">梦是起点，点亮灿烂的明天！</p>
		<p style="text-indent:20px;">新校区将是母校实现世界一流大学之梦的起点，是母校投身中国民族伟大复兴建设之梦的起点，也是你我他丰富而多彩的个人梦的起点。</p>
		<p style="text-indent:20px;">家是港湾，憧憬美好的未来！</p>
		<p style="text-indent:20px;">新校区将是莘莘学子成长成才扬帆竞发的港湾；将是巍巍学府在新时代蓄势起航的港湾；也将是海内外校友寻找记忆抚慰心灵的港湾。</p>
		<p style="text-indent:20px;">亲爱的校友，踏入校门那一刻，你是北洋的孩子，多少年来青春化作回忆，注定一生的缘；迈向社会那一刻，你就是天大的家人，多少年来精神融入血脉，唯有情谊久远。</p>
		<p style="text-indent:20px;">让我们一起来参与，凝聚你我他，融汇成大家！衷心期盼每一位北洋人、天大人贡献一份力量、播种一份希望、回馈一份心意、谱写一段情缘。</p>
		<p style="text-indent:20px;">所有捐款将落实到120年校庆和新校区图书馆建设两个具体项目中，我们将为您铭刻印记，恒久记录您对母校的爱与支持。</p>
		<p style="text-indent:20px;">北洋人千千万，齐心协力，同筑天大梦；</p>
		<p style="text-indent:20px;">每个人五百元，添砖加瓦，共建新家园。</p>
                </div>

               </div>
			   <style>
				.jjh_prorecom_detail_right1{background:none;}
			   </style>
               <div class="jjh_prorecom_detail_right1">
                    <div class="jjh_prorecom_detail_btn">
                    <!--<a href="/donate/index?cid=34&cname=校园基本建设基金（校园建筑物新建或冠名）">我要捐赠</a>-->
                    </div>
                    <!--<div class="jjh_prorecom_detail_news">
                         <div class="jjh_prorecom_detail_news_tit">最新动态</div>
                           <marquee direction="up" height="200" scrollamount="2" style="margin-top:10px;">
                              <ul>
                                <li>张洁莹 ￥100</li>
                                <li>戴晓橙 ￥200</li>
                                <li>匿名 ￥100</li>
                                <li>谌敦华 ￥500 </li>
                                <li>匿名 ￥1500 </li>
                                <li>匿名 ￥100 </li>
                                <li>孙闻宇 ￥3500 </li>
                                <li>胡腾 ￥200 </li>
                                <li>郑悦 ￥1000 </li>
                                <li>陈华青 ￥200 </li>
                              </ul>
                           </marquee>
                    </div>-->
               </div>
             </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>