<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">
    <h2><i class="fa fa-tachometer"></i> Dashboard<span>添加支出信息</span></h2>
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目支出管理</li>
            <li class="active">添加支出信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->
	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-12">
				<section class="tile color transparent-white">
			<div class="detailedbox tile-body">
			<form  class="form-horizontal" id="form1"  name="search_form" action="addrsshiyong" method="post" encType="multipart/form-data">

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">认领到协议：</label>
                    <div class="col-sm-4">
                        <select class="chosen-select-1 chosen-transparent form-control" id="sign_id">
                            <option value="">请选择协议名称</option>
                            <?php if($this->pm_mg_signDAO != ""){
                                foreach ($this->pm_mg_signDAO as $k => $v){
                                    ?>
                                    <option value="<?php echo $v['id'];?>_<?php echo $v['pm_id'];?>_<?php echo $v['pname'];?>">
                                        <?php if($v['type'] !=1){echo "（".$this->types_array[$v['type']]."）";}?><?php echo $v['sign_name'];?>； 协议金额：<?php echo $v['xyje'];?>元；
                                    </option>
                                <?php }}?>
                        </select>
                        <input id="pm_sign_id" type="hidden" suvalue="" name="pm_sign_id" value=""/>
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">项目名称：</label>
                    <div class="col-sm-4">
                        <input id="pname_info12" class="form-control" readonly="readonly" type="text" name="pname" value=""/>
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">项目支出类型：</label>
                    <div class="col-sm-4">
                        <label class="radio-inline"><input type="radio" size="14" checked="checked" value="1" name="shiyong_type"> 基金会列支 </label>
                        <label class="radio-inline"><input type="radio" size="14" value="2" name="shiyong_type"> 转财务处 </label>
                        <?php /*if($this->type == 1){*/?><!--
                            <input class="form-control" type="text" value="基金会列支" readonly="readonly" name=""  size="14"/>
                            <input class="form-control" type="hidden" value="1" readonly="readonly" name="shiyong_type"  size="14"/>
                        <?php /*}else {*/?>
                            <input class="form-control" type="text" value="转财务处" readonly="readonly" name=""  size="14"/>
                            <input class="form-control" type="hidden" value="2" readonly="readonly" name="shiyong_type"  size="14"/>
                        --><?php /*}*/?>

                    </div>
                    <span class="col-sm-2" > </span>
                </div>

			  <!--<div class="form-group">
                <label class="col-sm-2 control-label" for="input01">项目捐赠类型：</label>
                    <div class="col-sm-4">
                            <select class="form-control" name="pm_cate">
                                    <option value="" >请选择类型</option>
                                    <?php /*if($this->pcatelist != ""){
                                    foreach ($this->pcatelist as $k => $v){*/?>
                                        <option value="<?php /*echo $v['id']*/?>" ><?php /*echo $v['catename']*/?></option>
                                    <?php /*}}*/?>
                                </select>
                    </div>
                    <span class="col-sm-2" > * 教育基金、研究基金等</span>
                </div>-->


					  <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">项目支出日期：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" type="text"  id="datepicker"  name="shiyong_zhichu_datetime" size="14"/>
                            </div>
                            <span class="col-sm-2" > * </span>
                            </div>

             <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">项目支出金额：</label>
                    <div class="col-sm-4">
                        <input class="form-control" type="text" name="shiyong_zhichu_jiner"  size="14"/>
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>
					
				<div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">捐赠范围：</label>
                    <div class="col-sm-4">
                    <select class="form-control" name="fanwei">
                                        <option value="" >请选择类型</option>
                                        <option value="本科生" >本科生</option>
                                        <option value="研究生" >研究生</option>
                                        <option value="本科研究生" >本科研究生</option>
                                        <option value="其他" >其他</option>
                                    </select>
                    </div>
                    <span class="col-sm-3" > 本科生、研究生、本科研究生、其他 </span>
                </div>

                <?php //if($this->type == 2){?>
					 <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">资助人数：</label>
                        <div class="col-sm-4">
                            <input class="form-control" type="text" name="jiangli_renshu"  size="14"/>
                        </div>
                    </div>
                <?php //}?>

                <div class="form-group transparent-editor">
                    <label class="col-sm-2 control-label" for="input14">是否执行：</label>
                    <div class="col-sm-3">
                        <div class="checkbox check-transparent" style="padding-left:0px;">
                            <input type="checkbox" id="opt03" name="is_zhixing" value="4">
                            <label for="opt03">已执行</label>
                        </div>
                    </div>
                </div>

			<div class="form-group">
                <label class="col-sm-2 control-label" for="input01">上传发放明细：</label>
                <div class="col-sm-4">
                <input type="file" name="pm_files"  size="14"/>
                </div>
                <!--<span class="col-sm-2" >* 相关文档已打包形式上传 格式为*.rar </span>-->
            </div>

			<div class="form-group">
                <label class="col-sm-2 control-label" for="input01">备注：</label>
                <div class="col-sm-8">
                    <textarea parsley-validation-minlength="1" name="beizhu" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                </div>
            </div>	
					
					<div class="form-group form-footer">
						<div class="col-sm-offset-5 col-sm-7">
							<!--<input class="btn btn-primary" onclick="javascript:noTips();" value="提 交" />--><input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
							<input class="btn btn-default" type="reset" value="重 置" /> 
						</div>
					</div>
			</form>
            </div>
            </section>
		  </div>
		</div>

        <script language="javascript">
            $(document).ready(function(){
                $("#xmxxbj").addClass("open");
                // 选择协议时触发
                $(".chosen-select-1").change(function(){
                    var sid = $("#sign_id").val();
                    var arr = sid.split('_');
                    if($(".chosen-single span").html() != "请选择协议名称"){
                        $("#pm_sign_id").val(arr[0]);
                        //GetZWxm( arr[1] );
                        $("#pname_info12").val( arr[2] );
                    }
                });
            });
        </script>
		