<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加使用信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目使用管理</li>
            <li class="active">添加使用信息/li>
        </ol>
    </div>

</div>
<!-- /page header -->
	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-12">
				<section class="tile color transparent-black">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" action="addrsshiyong" method="post" encType="multipart/form-data">
            
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">项目名称：</label>
            <div class="col-sm-8">
            <select class="form-control" name="pname">
							<?php if($this->pmlist != ""){
									foreach ($this->pmlist as $k => $v){
								?>
								<option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
							<?php }}?>
						</select>
            </div>
            <span class="col-sm-2" > * </span>
            </div>	


			  <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">项目捐赠类型：</label>
            <div class="col-sm-8">
            <select class="form-control" name="pm_cate">
								<option value="" >请选择类型</option>
								<?php if($this->pcatelist != ""){
								foreach ($this->pcatelist as $k => $v){?>
									<option value="<?php echo $v['id']?>" ><?php echo $v['catename']?></option>
								<?php }}?>
							</select>
            </div>
            <span class="col-sm-2" > * 教育基金、研究基金等</span>
            </div>	


					  <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">项目支出日期：</label>
            <div class="col-sm-8">
            <input class="form-control" type="text"  id="dateinput1"  name="shiyong_zhichu_datetime"  size="14"/>
            </div>
            <span class="col-sm-2" > * </span>
            </div>	

				<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">项目支出金额：</label>
            <div class="col-sm-8">
            <input class="form-control" type="text" name="shiyong_zhichu_jiner"  size="14"/>
            </div>
            <span class="col-sm-2" > * </span>
            </div>	


					
					<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">捐赠范围：</label>
            <div class="col-sm-8">
            <select class="form-control" name="fanwei">
								<option value="" >请选择类型</option>
								<option value="本科生" >本科生</option>
								<option value="研究生" >研究生</option>
								<option value="本科研究生" >本科研究生</option>
								<option value="其他" >其他</option>
							</select>
            </div>
            <span class="col-sm-2" > 本科生、研究生、本科研究生、其他 </span>
            </div>	


					 <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">奖励人数：</label>
            <div class="col-sm-8">
            	<input class="form-control" type="text" name="jiangli_renshu"  size="14"/>
            </div>
            </div>	

					<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">相关文档：</label>
            <div class="col-sm-8">
            <input type="file" name="pm_files"  size="14"/>
            </div>
            <span class="col-sm-2" >* 相关文档已打包形式上传 格式为*.rar </span>
            </div>	

				<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">备注：</label>
            <div class="col-sm-8">
            	<textarea class="ckeditor" name="beizhu"></textarea>
            </div>
            </div>	
					
					<div class="form-group form-footer">
						<div class="col-sm-offset-5 col-sm-7">
							<input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; 
							<input class="btn btn-default" type="reset" value="重 置" /> 
						</div>
					</div>
			</form>
            </div>
            </section>
		  </div>
		</div>
	
			<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput1').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>
		