<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>认领列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目进度管理</li>
            <li class="active">认领列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="tile-body">

                <form action="#" method="get">
                    <div class="form-group">

                        <div class="row">
                            <div class="form-group col-sm-4">
                                <label for="input05">项目名称：</label>
                                <input type="text" class="form-control" name="pm_name" value="<?php if($_REQUEST['pm_name'] != ''){echo $_REQUEST['pm_name'];}?>" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-sm-3">
                                <label for="input01">是否已认领：</label>
                                <select name="is_renling" class="form-control">
                                    <option value="0" <?php if($_REQUEST['is_renling'] == ''){echo 'selected=selected';}?>>未认领</option>
                                    <option value="1" <?php if($_REQUEST['is_renling'] == 1){echo 'selected=selected';}?>>已认领</option>
                                    <option value="2" <?php if($_REQUEST['is_renling'] == 2){echo 'selected=selected';}?>>已删除</option>
                                </select>
                            </div>
                            <div class="form-group col-sm-3">
                                <label for="input02"> </label>
                                <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                            </div>
                        </div>
                        <div class="row">
                            <span class="col-sm-3" >* 是否已认领：“已删除”用于支出的调账或废除，删除为逻辑删除。 </span>
                        </div>
                        <div class="row">
                            <span class="col-sm-3" >* 默认按照支出日期倒序排序 </span>
                        </div>
                    </div>
                </form>

			</div>
			</section>

            <?php
/*                if(!empty($this->cf_DAO)){
            */?><!--
                <section class="tile color transparent-white">
                    <div class="tile-body nopadding">
                    </div>
                </section>
            --><?php /*}*/?>

			<section class="tile color transparent-white">
				<div class="tile-body nopadding">
				<?php if($this->claimlist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="24%">项目名称</td>
                          <td width="18%">支出日期</td>
						<td width="20%">支出金额</td>
						<td width="13%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php 
						foreach($this->claimlist as $k=>$v){?>
						 <tr>
						 	<td>
                                <?php echo $v['pm_name'];?>&nbsp;
                            </td>
                             <td>
                                 <?php echo $v['shiyong_zhichu_datetime'];?>
                             </td>
                             <td>
                                 <?php echo $v['shiyong_zhichu_jiner'];?> 元
                             </td>
							<td>
                                <?php if($this->is_renling == 0){?>
                                <a onclick="javascript:noTips_click(<?php echo $v['id'];?>);">
                                    <button class="btn btn-greensea margin-bottom-20" type="button">认领项目</button>
                                </a>

                                <a onclick="javascript:delete_click(<?php echo $v['id'];?>);">
                                    <button class="btn btn-red margin-bottom-20" type="button">删除</button>
                                </a>

                                <?php }else{ ?>
                                    <a href="/management/shiyong/editshiyong?id=<?php echo $v['id'];?>">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">编辑</button>
                                    </a>

                                    <a href="/management/shiyong/delshiyong?id=<?php echo $v['id'];?>">
                                        <button class="btn btn-red margin-bottom-20" type="button">放入回收站</button>
                                    </a>
                                <?php }?>
                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer">
					<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条项目认领信息          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无支出！</div>
				 <?php }?>
				 </div>
				 </div>
				 </section>
		  </div>
		</div>

        <script>
            var pm_id;
            function noTips_click(pm_id){
                if(confirm("确定要认领该笔款项吗？认领将不能修改。")) {
                    location.href = "/management/shiyong/binding-claim?pm_id="+pm_id;
                }
            }

            function delete_click(id){
                if(confirm("确定要删除该笔款项吗？删除将不能找回！")) {
                    location.href = "/management/shiyong/del-claim?lsh="+id;
                }
            }

            jQuery(document).ready(function($) {
                $('.theme-poptit .close').click(function(){
                    $('.theme-popover-mask').fadeOut(100);
                    $('.theme-popover').slideUp(200);
                    if($('#popover-close').attr("name") != '') {
                        location.href = $('#popover-close').attr("name");
                    }
                });
            });
        </script>

		
		    <script language="javascript">
                $(".menu li:eq(8)").addClass("open");
			</script>
