<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>来款认领</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目进度管理</li>
            <li class="active">支出认领</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	<div id="main" class="main">
   
		<div id="rightstyle02" class="row">
        
        <div class="col-md-12">
			<section class="tile color transparent-white">
				<div class="tile-body nopadding">
                <form method="post" action="savebindingclaim" id="form1" encType="multipart/form-data"> 
                        <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                         <thead>
                              <tr>
                                   <td width="30%">栏目名称</td>
                                   <td width="70%">明细</td>
                              </tr>
                        </thead>
                         <tbody>
                            <input type="hidden" name="pm_id" value="<?php echo $_REQUEST['pm_id'];?>"/>
                            <!--<input type="hidden" name="lsh" value="<?/*echo $this->zw_mg_pzfl_log[0]['lsh'];*/?>"/>
                            <input type="hidden" name="lrrq	" value="<?/*echo $this->zw_mg_pzfl_log[0]['lrrq'];*/?>"/>
                            <input type="hidden" name="lrr" value="<?/*echo $this->zw_mg_pzfl_log[0]['lrr'];*/?>"/>-->

                            <!-- 项目相关 start-->
                            <tr>
                                <td>认领到协议：</td>
                                <td>
                                    <select name="sign_id" class="chosen-select-1 chosen-transparent form-control" id="sign_id">
                                        <option value="">请选择协议名称</option>
                                        <?php if($this->pm_mg_signDAO != ""){
                                            foreach ($this->pm_mg_signDAO as $k => $v){
                                                ?>
                                                <option value="<?php echo $v['id'];?>_<?php echo $v['pm_id'];?>_<?php echo $v['pname'];?>">
                                                    <?php if($v['type'] !=1){echo "（".$this->types_array[$v['type']]."）";}?><?php echo $v['sign_name'];?>； 协议金额：<?php echo $v['xyje'];?>元；
                                                </option>
                                            <?php }}?>
                                    </select>
                                    <input id="pm_sign_id" type="hidden" suvalue="" name="pm_sign_id" value="<?php echo $this->pm_mg_info[0]['sign']?>"/>
                                </td>
                            </tr>

                            <!-- 项目相关 start-->
                            <tr>
                                <td>项目名称：</td>
                                <td>
                                    <input id="pname_info12" size="60" readonly="readonly" type="text" name="pname" value="<?php echo $this->pm_mg_info[0]['pm_name']?>"/>
                                </td>
                            </tr>

                            <tr>
                                <td>项目支出类型：</td>
                                <td>
                                    <select class="form-control"  name="shiyong_type">
                                        <option value="1" checked="checked">基金会列支</option>
                                        <option value="2" >转财务处</option>
                                    </select>
                                </td>
                            </tr>

                            <tr>
                                <td>项目支出日期：</td>
                                <td>
                                    <input size="38" type="text" id="shiyong_zhichu_datetime" name="shiyong_zhichu_datetime" value="<?php echo $this->pm_mg_info[0]['shiyong_zhichu_datetime'];?>"/>
                                </td>
                            </tr>


                            <tr>
                                <td>确认金额：</td>
                                <td><input name="shiyong_zhichu_jiner" size="36" type="text" value="<?php echo $this->pm_mg_info[0]['shiyong_zhichu_jiner'];?>"/> 元</td>
                            </tr>

                            <tr>
                                <td>捐赠范围：</td>
                                <td>
                                    <select class="form-control"  name="fanwei">
                                        <option value="" >请选择类型</option>
                                        <option value="本科生" >本科生</option>
                                        <option value="研究生" >研究生</option>
                                        <option value="本科研究生" >本科研究生</option>
                                        <option value="其他" >其他</option>
                                    </select>
                                </td>
                            </tr>

                            <tr>
                                <td>资助人数：</td>
                                <td>
                                    <input size="38" type="text" id="jiangli_renshu" name="jiangli_renshu" value="<?php echo $this->pm_mg_info[0]['jiangli_renshu'];?>"/>
                                </td>
                            </tr>

                            <tr>
                                <td>上传发放明细：</td>
                                <td>
                                    <input class="form-control" type="file" name="pm_files"  size="14"/><!--<font color="#0474d6" > * 相关文档已打包形式上传 格式为*.rar</font>--><br/>
                                    <?php if($this->pm_mg_info[0]['pm_file'] != ""){?>
                                        <a href="<?php echo $this->pm_mg_info[0]['pm_file'];?>">已经存在该文件如果再次上传,那么之前文件将被覆盖    -- 点击下载源文件</a>
                                    <?php }?>
                                </td>
                            </tr>


                            <!--<tr>
                                <td>是否执行：</td>
                                <td><input name="is_zhixing" type="checkbox" value="4" />已执行</td>
                            </tr>-->

                            <tr>
                                <td>补充其它信息：</td>
                                <td><textarea parsley-validation-minlength="1" name="beizhu" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php echo $this->pm_mg_info[0]['beizhu'];?></textarea></td>
                            </tr>

                            <tr>
                                <td></td>
                                <td><input type="submit" value="点击认领" class="btn btn-primary btn-block"></td>
                            </tr>

                        </tbody>
                        </table>
                   </form>
                   
				 </div> 
		  </section>
         </div>
         
		 </div>

        <script language="javascript">
            $("#xmxxbj").addClass("open");

            $(document).ready(function(){

                // 选择协议时触发
                $(".chosen-select-1").change(function(){
                    var sid = $("#sign_id").val();
                    var arr = sid.split('_');
                    if($(".chosen-single span").html() != "请选择协议名称"){
                        $("#pm_sign_id").val(arr[0]);
                        $("#pname_info12").val( arr[2] );
                    }
                });

                $(".addfapiao").hide();

                // 切换项目ajax对应财务项目信息
                $("#pname").change(function(){
                    GetZWxm($(this).children('option:selected').val());
                });

                // 切换部门ajax对应财务部门信息
                $("#department").change(function(){
                    GetZWbm($(this).children('option:selected').val());
                });

                // 切换发票状态
                /*$(".radioItem").change(function(){
                    var $selectedvalue = $("input[name='piaoju']:checked").val();
                    if ($selectedvalue == 0) {
                        $(".addfapiao").hide();
                    } else if($selectedvalue == 1 || $selectedvalue == 2) {
                        $(".addfapiao").show();
                    }
                });*/
            });

            function GetZWxm(pm_id){
                $.ajax({
                    type:'post',
                    url: '/management/zijin/ajaxgetzwxm?pm_id='+pm_id,
                    data:{},
                    cache:false,
                    dataType:'json',
                    success:function(data){
                        if( data != null)
                        {
                            //console.log(data);
                            $("#zw_xmbh").val(data.zw_xmbh);
                            $("#zw_xmmc").val(data.zw_xmmc);

                            //关联部门
                            //$("#department").val(data.department);
                           /* $("#department option[value='"+data.department+"']").attr("selected","selected");
                            $("#department").chosen();

                            $("#department").trigger("liszt:updated");
                            $("#department").trigger("chosen:updated");

                            GetZWbm(data.department);*/

                        }else {
                            $("#zw_xmbh").attr("value","");
                            $("#zw_xmbh").val("");
                            $("#zw_xmmc").attr("value","");
                            $("#zw_xmmc").val("");
                            alert("对不起，没有对应财务系统项目或父类项目，请添加对照关系后认领");
                        }
                    },
                    error:function(){}
                });
            }

            /*function GetZWbm(pm_pid){
                $.ajax({
                    type:'post',
                    url: '/management/zijin/ajaxgetzwbm?pm_pid='+pm_pid,
                    data:{},
                    cache:false,
                    dataType:'json',
                    success:function(data){
                        if( data != null)
                        {
                            //console.log(data);
                            $("#zw_bmbh").val(data.zw_bmbh);
                            $("#zw_bmmc").val(data.zw_bmmc);
                        }else {
                            $("#zw_bmbh").attr("value","");
                            $("#zw_bmbh").val("");
                            $("#zw_bmmc").attr("value","");
                            $("#zw_bmmc").val("");
                            alert("对不起，没有对应财务系统部门目，请添加对照关系后认领");
                        }
                    },
                    error:function(){}
                });
            }*/

            $("#pname").val('<?php echo $pm_id;?>');//设置值
            $("#pname").trigger("chosen:updated");  //更新选项
        </script>
