<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑车辆信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>车辆信息</li>
            <li class="active">编辑车辆信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-black">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" id="form1" action="to-addcarmain" method="post" encType="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆名称：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['name'];?>" type="text" name="name" />
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆车牌照：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['car_number'];?>" type="text" name="car_number" />
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆信息（颜色、规格）：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['description'];?>" type="text" name="description" />
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆所属人：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['clssr'];?>" type="text" name="clssr" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">登记机关：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['djjg'];?>" type="text" name="djjg" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">登记日期：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['djrp'];?>" type="text" name="djrp" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">机动车登记编号：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['jdcdjbh'];?>" type="text" name="jdcdjbh" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆类型：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['cllx'];?>" type="text" name="cllx" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆品牌：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['clpp'];?>" type="text" name="clpp" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆型号：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['clxh'];?>" type="text" name="clxh" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车身颜色：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['csys'];?>" type="text" name="csys" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆识别代码：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['clsbdm'];?>" type="text" name="clsbdm" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">国产、进口：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['gcjk'];?>" type="text" name="gcjk" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">发动机号：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['fdjh'];?>" type="text" name="fdjh" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">发动机型号：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['fdjxh'];?>" type="text" name="fdjxh" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">燃油型号：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['yrlx'];?>" type="text" name="yrlx" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">排量、功率：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['plgl'];?>" type="text" name="plgl" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">制造厂名称：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['zzcmc'];?>" type="text" name="zzcmc" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">轮距：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['lj'];?>" type="text" name="lj" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">轮胎数：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['lts'];?>" type="text" name="lts" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">轮胎规格：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['ltgg'];?>" type="text" name="ltgg" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">钢板弹簧片数：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['gbthps'];?>" type="text" name="gbthps" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">轴距：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['zj'];?>" type="text" name="zj" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">外轮廓尺寸：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['wlkcc'];?>" type="text" name="wlkcc" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">总质量：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['zzl'];?>" type="text" name="zzl" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">核定载客：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['hdzk'];?>" type="text" name="hdzk" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">使用性质：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['syxz'];?>" type="text" name="syxz" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆获得方式：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['clhdfs'];?>" type="text" name="clhdfs" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">车辆出厂日期：</label>
                            <div class="col-sm-3">
                                <input class="form-control" value="<?php echo $this->car_info[0]['ckccrq'];?>" type="text" name="ckccrq" />
                            </div>
                            <span class="col-sm-1" ></span>
                        </div>

                        <input class="btn btn-default" name="id" type="hidden" value="<?php echo $this->car_info[0]['id'];?>" />
                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>

                    </form>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $("#clgl").addClass("open");
    </script>

