<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

    <!-- page header -->
    <div class="pageheader">

        <h2><i class="fa fa-tachometer"></i> Dashboard
            <span>使用车辆信息列表</span></h2>

        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li>您的位置</li>
                <li>车辆信息</li>
                <li class="active">使用车辆信息列表</li>
            </ol>
        </div>

    </div>
    <!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">

			<div class="col-md-12">

                <section class="tile color transparent-white">
                    <div class="tile-body">
                        <div class="form-group">
                            <div class="row">
                                <div class="form-group col-sm-3">
                                    <label for="input05">在途车辆：</label>
                                </div>
                                <div class="form-group">
                                    <div class="form-group col-sm-2">
                                        <label for="input01">1111 </label>
                                    </div>
                                    <div class="form-group col-sm-3">
                                        <label for="input02">11111 </label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-sm-3">
                                    <label for="input05">空闲车辆：</label>
                                </div>
                                <div class="form-group">
                                    <div class="form-group col-sm-2">
                                        <label for="input01">1111 </label>
                                    </div>
                                    <div class="form-group col-sm-3">
                                        <label for="input02">11111 </label>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </section>



			<section class="tile color transparent-white">
			<div class="tile-body">
			<form action="#" method="post">
				<div class="form-group">
				<div class="row">
					<div class="form-group col-sm-3">
						<label for="input05">车辆车牌照：</label>
						<input type="text" class="form-control" name="car_number" />
					</div>
					<div class="form-group">
                        <div class="form-group col-sm-2">
                            <label for="input01"> </label>
                            <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                        </div>
                        <div class="form-group col-sm-3">
                            <label for="input02"> </label>
                            <input class="btn btn-primary btn-block" type="button" value="添加使用车辆信息" onclick="window.location.href='/management/car/addusecar'"/>
                        </div>
                    </div>
				</div>
				</div>
			</form>
			</div>
			</section>

			<section class="tile color transparent-white">
				<div class="tile-body nopadding">
				<?php if(count($this->pageData) > 0){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="8%">车号</td>
						<td width="12%">目的地及用途</td>
                          <td width="6%">公里数</td>
                          <td width="12%">出车时间</td>
                          <td width="12%">返回时间</td>
                          <td width="6%">加油数</td>
                          <td width="6%">金额</td>
                          <td width="12%">停车过路</td>
                          <td width="6%">使用人</td>
                          <td width="6%">驾驶人</td>
						<td width="13%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php
						foreach($this->pageData as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['car_number'];?>&nbsp;</td>
							<td><?php echo $v['destination_use'];?>&nbsp;</td>
                             <td><?php echo $v['kilometers'];?>&nbsp;公里</td>
                             <td><?php echo $v['use_starttime'];?>&nbsp;</td>
                             <td><?php echo $v['use_endtime'];?>&nbsp;</td>
                             <td><?php echo $v['cost_oil_counts'];?>&nbsp;L</td>
                             <td><?php echo $v['cost_price'];?>&nbsp;元</td>
                             <td><?php echo $v['cost_road_toll'];?>&nbsp;元</td>
                             <td><?php echo $v['user'];?>&nbsp;</td>
                             <td><?php echo $v['driver'];?>&nbsp;</td>

							<td><a href="/management/car/editusecar?id=<?php echo $v['id'];?>">
                            <button type="button" class="btn btn-greensea margin-bottom-20">编辑</button></a>
                             <a href="/management/car/delusecar?id=<?php echo $v['id'];?>">
                             <button type="button" class="btn btn-danger margin-bottom-20" onclick= "if(confirm( '是否确定删除！ 删除将无法找回有关该车辆的所有信息。')==false) return false; ">删除</button></a>
                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer">
					<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->totalItems;?> 条车辆使用信息          <?php echo $this->page['all'];?></div>
					
				 <?php }else{?>
                     <div class="form-group">
                         <div class="row">
                             <div class="col-md-offset-1 col-sm-2">
                                 <label for="input02">暂无车辆使用信息！ </label>
                                 <input class="btn btn-primary btn-block" type="button" value="添加车辆使用信息" onclick="window.location.href='/management/car/addusecar'"/>
                             </div>
                         </div>
                     </div>
				 <?php }?>
				 </div>
				 </div>
				 </section>
		  </div>
		</div>


        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(53)").addClass("open");
        </script>