<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />

<link href="/include/support/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/include/support/css/prettify.css" rel="stylesheet">

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>筹资立项申请</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li class="active">筹资立项申请</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div class="row">

        <div class="col-md-12">

            <section class="tile color transparent-white">

                <div id="rootwizard" class="tabbable tabs-left">

                    <ul>
                        <li><a href="#tab1" data-toggle="tab">第1步</a></li>
                        <li><a href="#tab2" data-toggle="tab">第2步</a></li>
                        <li><a href="#tab3" data-toggle="tab">第3步</a></li>
                        <li><a href="#tab4" data-toggle="tab">第4步</a></li>
                        <li><a href="#tab5" data-toggle="tab">第5步</a></li>
                    </ul>

                    <div class="tab-content">
                        <div class="tab-pane" id="tab1">
                            <p>下载电子版立项模板并认真填写立项信息，确认无误后，提交电子版立项文档( 以word的形式 )。</p>
                            <div>
                                <form class="form-horizontal" id="form1" action="savestep1" method="post" encType="multipart/form-data">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="input01">项目名称：</label>
                                        <div class="col-sm-4">
                                            <input class="form-control" type="text" name="pname" value="<?php echo $this->project_info[0]['p_name'];?>"/>
                                        </div>
                                        <span class="col-sm-1" > * </span>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="input01">电子版立项文档：</label>
                                        <div class="col-sm-4">
                                            <input name="img" type="file" value="" />
                                        </div>
                                        <!--<div><a  id="dzb" href="<?php echo $this->project_info_log[0]['img'];?>" target="_blank">已上传电子版立项文档，点击查看</a></div>
                                        <span class="col-sm-2" > * </span>-->
                                    </div>

                                    <div class="form-group transparent-editor">
                                        <label class="col-sm-2 control-label" for="input14">申请说明：</label>
                                        <div class="col-sm-4">
                                            <textarea parsley-validation-minlength="1" name="instruction" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php echo $this->project_info[0]['instruction'];?></textarea>
                                        </div>
                                        <span class="col-sm-1" >  </span>
                                    </div>

                                    <!--<div class="form-group">
                                        <label class="col-sm-2 control-label" for="input02">所属项目：</label>
                                        <div class="col-sm-4">
                                            <select class="chosen-select chosen-transparent form-control" name="pm_id">
                                                <option value="0" >请选择所属项目名称</option>
                                                <?php /*if($this->chouzi_lists != ""){
                                                    foreach ($this->chouzi_lists as $k => $v){*/?>
                                                        <option value="<?php /*echo $v['id']*/?>" ><?php /*echo $v['pname']*/?></option>
                                                    <?php /*}}*/?>
                                            </select>
                                        </div>
                                        <span class="col-sm-2" > 如果有父类项目请选择此项 选填</span>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="input02">所属部门：</label>
                                        <div class="col-sm-4">
                                            <select class="chosen-select chosen-transparent form-control" name="department">
                                                <option value="" >请选择所属部门</option>
                                                <?php /*if($this->departmentlist != ""){
                                                    foreach ($this->departmentlist as $k => $v){*/?>
                                                        <option value="<?php /*echo $v['id']*/?>" ><?php /*echo $v['pname']*/?></option>
                                                    <?php /*}}*/?>
                                            </select>
                                        </div>
                                        <span class="col-sm-1" > * </span>
                                    </div>-->

                                    <input type="hidden" name="id" value="<?php echo $this->project_info[0]['id'];?>"/>

                                    <?php if($this->project_info[0]['status'] == 0 || $this->project_info[0]['status'] == 2){?>
                                    <div class="form-group">
                                        <div class="col-sm-offset-5 col-sm-7">
                                            <input class="btn btn-primary" type="submit" value="提交审核，进入下一步" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                            <!--<input class="btn btn-default" type="reset" value="重 置" />-->
                                        </div>
                                    </div>
                                    <?php }?>

                                </form>
                            </div>

                        </div>

                        <div class="tab-pane" id="tab2">
                            <p>等待项目负责人审核，若通过则通知可以进行第三步，如不符合要求，则需修改并重新上传立项文档电子版。</p>

                            <p>
                                <button class="btn btn-large btn-primary" type="button"> 项目申请已提交，请等待审核结果。</button>
                            </p>

                            <p>温馨提示：审核结果通过会以邮件或短信的方式提醒您。</p>

                        </div>

                        <div class="tab-pane" id="tab3">
                            <p>电子版本通过后，打印并签字盖章，扫描成pdf格式，再次上传并等待审核。</p>
                            <div>
                                <form class="form-horizontal" id="form1" action="savestep3" method="post" encType="multipart/form-data">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="input01">项目名称：</label>
                                        <div class="col-sm-2">
                                            <?php echo $this->project_info[0]['p_name'];?>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="input01">签字盖章pdf文档：</label>
                                        <div class="col-sm-4">
                                            <input name="img" type="file" value="" />
                                        </div>
                                        <!--<div><a  id="dzb" href="<?php echo $this->project_info_log[0]['img'];?>" target="_blank">已上传电子版立项文档，点击查看</a></div>
                                        <span class="col-sm-2" > * </span>-->
                                    </div>

                                    <div class="form-group transparent-editor">
                                        <label class="col-sm-2 control-label" for="input14">申请说明：</label>
                                        <div class="col-sm-4">
                                            <textarea parsley-validation-minlength="1" placeholder="请填写申请说明" name="instruction" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php /*echo $this->project_info[0]['instruction'];*/?></textarea>
                                        </div>
                                        <span class="col-sm-1" >  </span>
                                    </div>

                                    <input type="hidden" name="id" value="<?php echo $this->project_info[0]['id'];?>"/>

                                    <?php if($this->project_info[0]['status'] == 3 || $this->project_info[0]['status'] == 5){?>
                                        <div class="form-group">
                                            <div class="col-sm-offset-5 col-sm-7">
                                                <input class="btn btn-primary" type="submit" value="提交审核，进入下一步" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                            </div>
                                        </div>
                                    <?php }?>

                                </form>
                            </div>
                        </div>

                        <div class="tab-pane" id="tab4">
                            <p>等待领导确认和项目管理人员审核，如有问题返回第三步，如无问题立项申请成功。</p>
                        </div>

                        <div class="tab-pane" id="tab5">
                            <p>立项申请成功后，寄送立项文档到基金会，立项完成。</p>
                        </div>

                        <!--<ul class="pager wizard">
                            <li class="previous first" style="display:none;"><a href="#"> 第一步</a></li>
                            <li class="previous"><a href="#"> 上一步</a></li>
                            <li class="next last" style="display:none;"><a href="#"> 最后一步 </a></li>
                            <li class="next"><a href="#">下一步</a></li>
                        </ul>-->
                    </div>
                </div>

            </section>

            <?php
            if($this->project_info[0]['status'] != 0){
                if($this->project_info[0]['status'] == 2){
                ?>

                <section class="tile color transparent-white">
                    <div style="margin: 10px;"><h5> 立项进度状态：<strong style="color: red;"><?php $number = (int)$this->project_info[0]['status']; echo $this->project_status[$number];?></strong> -- 请重新填写并上传立项电子版文档</h5></div>
                    <div style="margin: 10px;"><h5> 审核失败理由：<?php echo $this->shsb[0]['desc'];?></h5></div>
                    <div style="margin: 10px;"><h5> 审核失败图示：<img src="<?php echo $this->shsb[0]['img'];?>" /></h5></div>
                    <div style="margin: 10px;"><h5> 审核时间：<?php echo date("Y-m-d H:i:s", $this->shsb[0]['lastmodify']);?></h5></div>
                </section>

                <?php }elseif($this->project_info[0]['status'] == 5){ ?>

                <section class="tile color transparent-white">
                    <div style="margin: 10px;"><h5> 立项进度状态：<strong style="color: red;"><?php $number = (int)$this->project_info[0]['status']; echo $this->project_status[$number];?></strong> -- 请重新填写并上传签字盖章pdf文件</h5></div>
                    <div style="margin: 10px;"><h5> 审核失败理由：<?php echo $this->pdfshsb[0]['desc'];?></h5></div>
                    <div style="margin: 10px;"><h5> 审核失败图示：<img src="<?php echo $this->pdfshsb[0]['img'];?>" /></h5></div>
                    <div style="margin: 10px;"><h5> 审核时间：<?php echo date("Y-m-d H:i:s", $this->pdfshsb[0]['lastmodify']);?></h5></div>
                    </section>

                <?php }else{ ?>
                    <section class="tile color transparent-white">
                        <div style="margin: 10px;"><h5> 立项进度状态：<strong style="color: red;"><?php $number = (int)$this->project_info[0]['status']; echo $this->project_status[$number];?></strong></div>
                    </section>
                <?php }?>
            <?php }?>
        </div>
    </div>

</div><!-- tab-pane -->
</div><!-- tab-content -->
</div>
</div>
<!-- Make page fluid-->

</div>
<!-- Wrap all page content end -->
<section class="videocontent" id="video"></section>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/include/management/assets/js/jquery.js"></script>
<script src="/include/management/assets/js/vendor/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/mmenu/js/jquery.mmenu.min.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/sparkline/jquery.sparkline.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/include/support/bootstrap/js/bootstrap.min.js"></script>

<script src="/include/support/js/jquery.bootstrap.wizard.js"></script>
<script src="/include/support/js/prettify.js"></script>

<script language="javascript">
    $(document).ready(function(){

    });

    $('#rootwizard').bootstrapWizard({
        tabClass: 'nav nav-pills',
        onTabClick: function(tab, navigation, index) {
            //alert('on tab click disabled');
            return false;
        },
        onPrevious: function(tab, navigation, index){

        },
        onNext: function(tab, navigation, index){
            var form = $("#form"+index);
            form.submit();
            return false;
            //console.log(form.html());
        },
    });
    $('#rootwizard').bootstrapWizard('show',
        <?php
            if($_REQUEST['step'] !=''){
                echo (int)$_REQUEST['step']-1;
            }else{
                if($this->project_info[0]['status'] != 0) {
                    if ($this->project_info[0]['status'] == 1 || $this->project_info[0]['status'] == 2) {
                        echo 0;
                    } elseif ($this->project_info[0]['status'] == 6 || $this->project_info[0]['status'] == 7) {
                        echo 3;
                    }elseif($this->project_info[0]['status'] == 5) {
                        echo 2;
                    }elseif($this->project_info[0]['status'] > 7) {
                        echo 4;
                    }else {
                        echo (int)$this->project_info[0]['status']-1;
                    }
                }else {
                    echo 0;
                }
            }
        ?>);
</script>

