<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加投资明细</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>投资明细信息</li>
            <li class="active">添加投资明细</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
				<section class="tile color transparent-white">
			<div class="detailedbox tile-body">
                <form class="form-horizontal" action="to-addusecar" method="post" encType="multipart/form-data">

                    <div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">投资账户：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="account_id">
                                    <option value="" >请选择投资账户</option>
                                    <?php if($this->accountList != ""){
                                    foreach ($this->accountList as $k => $v){?>
                                        <option value="<?php echo $v['id']?>" ><?php echo $v['account_name']?></option>
                                    <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                    </div>


                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input06">收支类型：</label>
                        <div class="col-sm-4">
                            收入 <input class="form-control" type="radio"  id="tpye" value="1"  name="tpye" size="14"/>
                            支出 <input class="form-control" type="radio"  id="tpye" value="2"  name="tpye" size="14"/>
                        </div>
                    </div>



                    <div class="form-group receipts">
                        <label class="col-sm-2 control-label" for="input06">收入到账时间：</label>
                        <div class="col-sm-4">
                            <input class="form-control" data-date-format="YYYY-MM-DD HH:mm:00" type="text"  id="datepicker"  name="account_receipts_datetime" size="14"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">收入金额：</label>
                        <div class="col-sm-3">
                            <input class="form-control" type="text" name="account_receipts" />
                        </div>
                        <span class="col-sm-1" >元 * </span>
                    </div>

                    <div class="form-group expenses">
                        <label class="col-sm-2 control-label" for="input06">支出时间：</label>
                        <div class="col-sm-4">
                            <input class="form-control" data-date-format="YYYY-MM-DD HH:mm:00" type="text"  id="datepicker1"  name="account_expenses_datetime" size="14"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">支出金额：</label>
                        <div class="col-sm-3">
                            <input class="form-control" type="text" name="account_expenses" />
                        </div>
                        <span class="col-sm-1" >元 * </span>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">用车费用-金额：</label>
                        <div class="col-sm-3">
                            <input class="form-control" type="text" name="cost_price" />
                        </div>
                        <span class="col-sm-1" >元 * </span>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">用车费用-过路费：</label>
                        <div class="col-sm-3">
                            <input class="form-control" type="text" name="cost_road_toll" />
                        </div>
                        <span class="col-sm-1" >元 * </span>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">使用人：</label>
                        <div class="col-sm-3">
                            <input class="form-control" type="text" name="user" />
                        </div>
                        <span class="col-sm-1" > * </span>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">驾驶员：</label>
                        <div class="col-sm-3">
                            <input class="form-control" type="text" name="driver" />
                        </div>
                        <span class="col-sm-1" > * </span>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">备注：</label>
                        <div class="col-sm-9">
                            <textarea parsley-validation-minlength="1" name="remark" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                        </div>
                    </div>
					
					<div class="form-group form-footer">
						<div class="col-sm-offset-5 col-sm-7">
							<input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
							<input class="btn btn-default" type="reset" value="重 置" /> 
						</div>
					</div>
			</form>
			</div>
		 </section>
			</div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(53)").addClass("open");
        </script>

