<?= $this->partial("common/header.phtml");?>
 <div class="jjh_content_sub" style="height:700px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/donate_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>在线捐赠</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/donate/fangshi"><span>捐赠方式</span></a></li>
                      <li><a href="/donate/zhanghu">基金会账户</a></li>
                      <li><a href="/donate/mianshui">免税政策</a></li>
                      <li><a href="/donate/shuoming">捐赠说明</a></li>
                      <li><a href="/donate">我要捐赠</a></li>
                      <li><a href="/donate/query">捐款到账查询</a></li>
                      <li><a href="/donate/wuxie">捐赠鸣谢</a></li>
                   </ul>
              </div>
              <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/serline.jpg" /></div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><em>捐款方式</em><span>当前位置：<a href="/donate">在线捐赠</a> > 捐款方式</span></div>
              <div class="cle"></div>
              <div class="jjh_sub_con_content" style="height:520px;">
                  <p class="jjh_font4">接收捐赠种类</p>
                  天津大学北洋教育发展基金会接收捐赠人捐赠种类包括：现金、支票、汇票、股票、债券以及其他有价证券，还包括图书、资料、设备、房产、遗产、其他财产及物品。<br />
                  <p class="jjh_font4">接收捐赠方式</p>
                  <div class="jjh_donate_methods">直接捐赠或汇款</div>
                  <div class="jjh_donate_methods_con">地址：天津市南开区卫津路92号<br /> 收款人：天津大学北洋教育发展基金会<br /> 邮政编码：300072<br /><span class="jjh_font5"> 注：请捐赠人在附言中注明捐赠种类及用途。</span></div>
                  <div class="jjh_donate_methods">银行转账或电汇</div>
                  <div class="jjh_donate_methods_con">银行账户名称：天津大学北洋教育发展基金会<br /> 开户银行：天津银行兴科支行 <br /> 银行账号：103601201090035769</div>
                  <div class="jjh_donate_methods">海外现金支票</div>
                  <div class="jjh_donate_methods_con">捐款人若以现金支票的形式为我基金会捐款，请将填写好的现金支票直接寄至如下地址：<br />	Peiyang Education Development Foundation 
	Tianjin University 92 WeiJin Road ,Nankai District Tianjin 300072，P.R. China <br /> 同时，请随信附上捐款用途和捐赠人的电话和通信地址。</div>
                  <p class="jjh_font4">捐赠咨询热线电话</p>
                  <span class="jjh_font2">0086－22－27403247</span>  <br />联系人：李老师  范老师  周老师<br />E-mail：zhouyantj@tju.edu.cn<br />网址：http://pyedf.tju.edu.cn
              </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>