<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"
      xmlns="http://www.w3.org/1999/html"/>
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<link rel="stylesheet" href="/include/management/assets/css/vendor/animate/animate.css">
<link type="text/css" rel="stylesheet" media="all" href="/include/management/assets/js/vendor/mmenu/css/jquery.mmenu.all.css" />
<link rel="stylesheet" href="/include/management/assets/js/vendor/videobackground/css/jquery.videobackground.css">
<link rel="stylesheet" href="/include/management/assets/css/vendor/bootstrap-checkbox.css">

<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote-bs3.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen.min.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen-bootstrap.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/datepicker/css/bootstrap-datetimepicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpalette/bootstrap-colorpalette.css">
<link href="/include/management/assets/css/minimal.css" rel="stylesheet">

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目配比列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目配比管理</li>
            <li class="active">项目配比列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div id="rightstyle02" class="row">

        <div class="col-md-12">
            <section class="tile color transparent-white">
                <div class="tile-body">
                    <form action="#" method="get" name="search_form">
                        <div class="form-group">

                            <div class="row">

                                <div class="form-group col-sm-4">
                                    <label for="pname" class="col-sm-4 control-label">划拨部门：</label>
                                    <select class="chosen-select-1 chosen-transparent form-control" data-live-search="false" name="huabo_department" id="huabo_department">
                                        <option value="">请选择划拨部门</option>
                                        <?php if($this->department != ""){
                                            foreach ($this->department as $k => $v){
                                                ?>
                                                <option <?php if($_REQUEST['huabo_department'] == $k){ echo "selected='selected'";}?>  value="<?php echo $k;?>"><?php echo $v;?></option>
                                            <?php }}?>

                                    </select>
                                </div>

                                <div class="form-group col-sm-4">
                                    <label for="pname" class="col-sm-12 control-label">划拨年份：</label>
                                    <input name="yeartime" data-date-format="YYYY" id="datepicker1"  type="text" value="<?php echo $this->yeartime;?>" class="col-sm-4 control-label"/>
                                </div>

                            </div>

                            <div class="row">
                                <div class="form-group col-sm-6">
                                    <label for="pname" class="col-sm-4 control-label">项目来款：</label>
                                    <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="lk_main_id[]" id="lk_main_id">
                                        <?php if($this->l_lk_list != ""){
                                            foreach ($this->l_lk_list as $k => $v){
                                                ?>
                                                <option <?php if(in_array($k,$_REQUEST['lk_main_id'])){ echo "selected='selected'";}?>  value="<?php echo $k;?>"><?php echo $v;?></option>
                                            <?php }}?>
                                    </select>
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-sm-6">&nbsp;注：项目来款如需多选，可按住Ctrl键进行多选操作。</div>
                            </div>

                            <div class="row">
                                <div class="form-group col-sm-3">
                                    <label for="input02"></label>
                                    <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </section>

            <section class="tile color transparent-white">
                <div class="tile-body nopadding">
                    <?php if($this->pageData != ""){?>
                    <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                        <thead>
                        <tr>
                            <td width="26%">来款项目</td>
                            <td width="10%">划拨部门</td>
                            <td width="10%">配比下发时间</td>
                            <td width="10%">配比金额</td>
                            <td width="14%">卡号</td>
                            <td width="10%">经费负责人</td>
                            <td width="10%">配比审批人</td>
                            <td width="10%">操作</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach($this->pageData as $k=>$v){?>
                            <tr>
                                <td>
                                    <?php echo $v['pm_name'];?>
                                </td>
                                <td>
                                    <?php echo $this->department[$v['huabo_department']];?>
                                </td>

                                <td>
                                    <?php echo $v['peibi_datetime'];?>
                                </td>
                                <td>
                                    <?php echo $v['je'];?>
                                </td>

                                <td>
                                    <?php echo $v['card'];?>
                                </td>
                                <td>
                                    <?php
                                        $_temp = explode(',',$v['jffzr']);
                                        if(is_array($_temp)){
                                            foreach($_temp as $key => $value){
                                                echo $this->jjh_mg_pp_list[$value];
                                            }
                                        }else {
                                            echo $this->jjh_mg_pp_list[$v['jffzr']];
                                        }

                                    ?>
                                </td>
                                <td>
                                    <?php $_temp1 = explode(',',$v['peibi_spr']);
                                    if(is_array($_temp1)){
                                        foreach($_temp1 as $key => $value){
                                            echo $this->jjh_mg_pp_list[$value];
                                        }
                                    }else {
                                        echo $this->jjh_mg_pp_list[$v['peibi_spr']];
                                    }?>
                                </td>

                                <td>
                                    <a href="/management/peibi/edit?id=<?php echo $v['id'];?>">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">编  辑</button>
                                    </a>
                                    <!-- &nbsp;&nbsp;
                                     <a href="#" onclick="alert('对不起，配比清单不提供删除功能，请联系管理员');">
                                         <button class="btn btn-danger margin-bottom-20" type="button">删除</button>
                                     </a>-->

                                    <!--<a href="/management/peibi/del?id=<?php /*echo $v['id']*/?>" >
                                        <button class="btn btn-danger margin-bottom-20" type="button" onclick="window.confirm('确定要删除这个配比信息吗?')">删除</button>
                                    </a>-->
                                </td>
                            </tr>
                        <?php }?>
                        </tbody>
                    </table>
                </div>
                <div class="tile-footer">
                    <div class="row">
                        <div class="page col-md-12" align="right">
                            共  <?php echo $this->totalItems;?> 条配比信息         <?php echo $this->page['all'];?></div>

                        <?php }else{?>
                            <div style="margin: 10px;padding: 10px;">暂无配比信息！<a href="/management/peibi/add">点击添加</a></div>
                        <?php }?>
                    </div>

                    <div class="row">
                        <div class="form-group col-sm-3">
                            <label for="input02"></label>
                            <a href="/management/report/peibitoexcel?<?php
                            $_url = explode('?',$_SERVER['REQUEST_URI']);
                            echo $_url[1];?>"><button class="btn btn-primary btn-block">导出Excel</button></a>
                        </div>
                    </div>

                </div>
            </section>
        </div>
    </div>