<link rel="stylesheet" href="/include/management/datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="/include/management/datepicker/ui.datepicker.css" type="text/css"  /> 
<!--<script src="/include/management/datepicker/jquery.js"></script>-->

<link rel="stylesheet" href="/include/management/jiansuo/base/jquery.ui.all.css">
<script src="/include/management/jiansuo/jquery-1.6.2.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.core.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.widget.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.button.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.position.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.autocomplete.js"></script>

<script src="/include/management/jiansuo/ui/jquery.ui.datepicker.js"></script>
<!--<script src="/include/management/datepicker/ui.datepicker.js"></script>-->

<style>
	.ui-button-icon-only .ui-button-text, .ui-button-icons-only .ui-button-text{
		padding:0em;
	}
	.ui-widget .ui-widget{
		font-size: 12px;
	}
	.ui-menu .ui-menu-item a{
		font-size: 12px;
	}

</style>
<script>
	(function( $ ) {
		$.widget( "ui.combobox", {
			_create: function() {
				var self = this,
					select = this.element.hide(),
					selected = select.children( ":selected" ),
					value = selected.val() ? selected.text() : "";
				var input = this.input = $( "<input>" )
					.insertAfter( select )
					.val( value )
					.autocomplete({
						delay: 0,
						minLength: 0,
						source: function( request, response ) {
							var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
							response( select.children( "option" ).map(function() {
								var text = $( this ).text();
								if ( this.value && ( !request.term || matcher.test(text) ) )
									return {
										label: text.replace(
											new RegExp(
												"(?![^&;]+;)(?!<[^<>]*)(" +
												$.ui.autocomplete.escapeRegex(request.term) +
												")(?![^<>]*>)(?![^&;]+;)", "gi"
											), "<strong style='color:red'>$1</strong>" ),
										value: text,
										option: this
									};
							}) );
						},
						select: function( event, ui ) {
							ui.item.option.selected = true;
							self._trigger( "selected", event, {
								item: ui.item.option
							});
						},
						change: function( event, ui ) {
							if ( !ui.item ) {
								var matcher = new RegExp( "^" + $.ui.autocomplete.escapeRegex( $(this).val() ) + "$", "i" ),
									valid = false;
								select.children( "option" ).each(function() {
									if ( $( this ).text().match( matcher ) ) {
										this.selected = valid = true;
										return false;
									}
								});
								if ( !valid ) {
									// remove invalid value, as it didn't match anything
									$( this ).val( "" );
									select.val( "" );
									input.data( "autocomplete" ).term = "";
									return false;
								}
							}
						}
					})
					.addClass( "ui-widget ui-widget-content ui-corner-left" );

				input.data( "autocomplete" )._renderItem = function( ul, item ) {
					return $( "<li></li>" )
						.data( "item.autocomplete", item )
						.append( "<a>" + item.label + "</a>" )
						.appendTo( ul );
				};

				this.button = $( "<button type='button'>&nbsp;</button>" )
					.attr( "tabIndex", -1 )
					.attr( "title", "Show All Items" )
					.insertAfter( input )
					.button({
						icons: {
							primary: "ui-icon-triangle-1-s"
						},
						text: false
					})
					.removeClass( "ui-corner-all" )
					.addClass( "ui-corner-right ui-button-icon" )
					.click(function() {
						// close if already visible
						if ( input.autocomplete( "widget" ).is( ":visible" ) ) {
							input.autocomplete( "close" );
							return;
						}

						// work around a bug (likely same cause as #5265)
						$( this ).blur();

						// pass empty string as value to search for, displaying all results
						input.autocomplete( "search", "" );
						input.focus();
					});
			},

			destroy: function() {
				this.input.remove();
				this.button.remove();
				this.element.show();
				$.Widget.prototype.destroy.call( this );
			}
		});
	})( jQuery );

	$(function() {
		$( "#combobox" ).combobox();
		$( "#toggle" ).click(function() {
			$( "#combobox" ).toggle();
		});
	});
	</script>
    <!-- page header -->
    <div class="pageheader">

        <h2><i class="fa fa-tachometer"></i> Dashboard
            <span>收支统计管理</span></h2>

        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li>您的位置</li>
                <li>捐赠项目统计管理</li>
                <li class="active">收支统计管理</li>
            </ol>
        </div>

    </div>
    <!-- /page header -->

	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-6">
        <section class="tile color transparent-black">
		<div class="detailedbox tile-body">
		<form class="form-horizontal" action="pmshouzhitoexcel" method="post" name="search_form">
        <div class="form-group">
		<label class="col-sm-4" for="input01">根据名称统计项目收支明细</label></div>
					
						
				<div class="form-group">
				<label class="col-sm-2 control-label" for="input01">	
						项目名称：</label>
                        <div class="col-sm-7">
                            <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                <option value="1">请选择项目名称</option>
                                <?php if($this->pmlist != ""){
                                    foreach ($this->pmlist as $k => $v){
                                        ?>
                                        <option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
                                    <?php }}?>
                            </select>
                            <input id="pname_info" type="hidden" name="pname" value=""/>
                                
							</div>
                            <span class="col-sm-2" > * </span>
						</div>
						<div class="form-group">
            <div class="col-md-offset-2 col-sm-2">
						<input class="btn btn-greensea" type="submit" value="下载excel报表"/></div>
                        </div>
					</form>
				</div>
			</div>
		</div>	
	</div>	
