<link rel="stylesheet" href="/include/management/datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="/include/management/datepicker/ui.datepicker.css" type="text/css"  /> 
<!--<script src="/include/management/datepicker/jquery.js"></script>-->

<link rel="stylesheet" href="/include/management/jiansuo/base/jquery.ui.all.css">
<script src="/include/management/jiansuo/jquery-1.6.2.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.core.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.widget.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.button.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.position.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.autocomplete.js"></script>

<script src="/include/management/jiansuo/ui/jquery.ui.datepicker.js"></script>
<!--<script src="/include/management/datepicker/ui.datepicker.js"></script>-->

<style>
	.ui-button-icon-only .ui-button-text, .ui-button-icons-only .ui-button-text{
		padding:0em;
	}
	.ui-widget .ui-widget{
		font-size: 12px;
	}
	.ui-menu .ui-menu-item a{
		font-size: 12px;
	}

</style>
    <!-- page header -->
    <div class="pageheader">

        <h2><i class="fa fa-tachometer"></i> Dashboard
            <span>收支统计管理</span></h2>

        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li>您的位置</li>
                <li>捐赠项目统计管理</li>
                <li class="active">收支统计管理</li>
            </ol>
        </div>

    </div>
    <!-- /page header -->

	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-6">
        <section class="tile color transparent-black">
		<div class="detailedbox tile-body">
		<form class="form-horizontal" action="pmshouzhitoexcel" method="post" name="search_form">
        <div class="form-group">
		<label class="col-sm-4" for="input01">根据名称统计项目收支明细</label></div>
					
						
				<div class="form-group">
					<label class="col-sm-2 control-label" for="input01">所属项目名称：</label>
                        <div class="col-sm-7">
								<select class="chosen-select-1 chosen-transparent form-control" name="pm_id">
									<option value="">请选择项目名称</option>
									<?php if($this->pmlist != ""){
										foreach ($this->pmlist as $k => $v){
											?>
											<option value="<?php echo $v['id'];?>"><?php echo $v['pname'];?></option>
										<?php }}?>
								</select>
								<input id="pname_info" type="hidden" name="pname" value=""/>
						</div>

                        <div class="col-sm-7">
                            <input class="btn btn-greensea" type="submit" value="下载excel报表"/></div>
                        </div>
					</form>
				</div>
			</div>
		</div>	
	</div>


<script src="/include/management/assets/js/jquery.js"></script>
<script language="javascript">
    $(".menu li:eq(19)").addClass("open");
</script>