<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>
<!-- page header -->
    <div class="pageheader">

        <h2><i class="fa fa-tachometer"></i> Dashboard
            <span>使用统计管理</span></h2>

        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li>您的位置</li>
                <li>捐赠项目统计管理</li>
                <li class="active">使用统计管理</li>
            </ol>
        </div>

    </div>
    <!-- /page header -->
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-6">
        <section class="tile color transparent-white">
		<div class="detailedbox tile-body">
         
		<form class="form-horizontal" action="shiyongtoexcel" method="post">	
        <div class="form-group">
		<label class="col-sm-4" for="input01">
			根据时间统计项目收支明细
			</label>
            </div>	
				<div class="form-group">
				<label class="col-sm-3 control-label" for="input01">	
						项目名称：</label>
                <div class="col-sm-8">
						<select class="form-control" name="pname" size="10">
							<?php if($this->pmlist != ""){
									foreach ($this->pmlist as $k => $v){
								?>
								<option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
							<?php }}?>
						</select>

						</div>
                </div>
				<div class="form-group">							
						<label class="col-sm-3 control-label" for="input01">项目支出日期区间：</label>
                        <div class="col-sm-4">
                        <input class="form-control" type="text"  id="dateinput"  name="shiyong_zhichu_datetime"  size="14"/></div>
                        <div class="col-sm-1"> 至 </div>
						<div class="col-sm-4"><input class="form-control" type="text"  id="dateinput1"  name="shiyong_zhichu_datetime1"  size="14"/></div>
                        </div>
				<div class="form-group">
						<label class="col-sm-3 control-label" for="input01">项目支出金额：</label>
                        <div class="col-sm-9">
                        <input class="form-control" type="text" size="14" name="shiyong_zhichu_jiner" value=""></div>
						
						</div>
                        
				<div class="form-group">
            <div class="col-md-offset-2 col-sm-2">
						<input class="btn btn-greensea" type="submit" value="下载excel报表"/></div>
                        </div>
					</form>
				</div>
		</section>
		</div>	
		</div>	
	
	
			<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>
			
			<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput1').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(19)").addClass("open");
        </script>