<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>
<!-- page header -->
    <div class="pageheader">

        <h2><i class="fa fa-tachometer"></i> Dashboard
            <span>项目收入信息统计管理</span></h2>

        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li>您的位置</li>
                <li>捐赠项目统计管理</li>
                <li class="active">项目收入信息统计管理</li>
            </ol>
        </div>

    </div>
    <!-- /page header -->
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-12">
        <section class="tile color transparent-black">

		<div class="detailedbox tile-body">
			<form class="form-horizontal" action="zijinnewtoexcel" method="get" id="search_form1">

               <!-- <div class="form-group">
                    <label class="col-sm-3 control-label" for="input01">选择类型：</label>
                    <div class="col-sm-8">
                        <input type="radio" name="type" value="1" checked="checked"/>以父类项目统计
                        <input type="radio" name="type" value="2" />以子类项目统计
                    </div>
                </div>-->

                <div class="form-group">
                    <label class="col-sm-1 control-label" for="input01">项目名称：</label>
                    <div class="col-sm-3">
                        <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                            <option value="1">请选择项目名称</option>
                            <?php if($this->pmlist != ""){
                                foreach ($this->pmlist as $k => $v){
                                    ?>
                                    <option value="<?php echo $v['pname'];?>" <?php if($_REQUEST['pname'] == $v['pname'])echo 'selected="selected"';?>><?php echo $v['pname'];?></option>
                                <?php }}?>
                        </select>
                        <input id="pname_info" type="hidden" name="pname" value=""/>
                    </div>

                    <label class="col-sm-1 control-label" for="input01">项目类型：</label>
                    <div class="col-sm-3">
                        <select class="form-control" name="cate">
                            <option value="" >请选择类型</option>
                            <?php if($this->pcatelist != ""){
                                foreach ($this->pcatelist as $k => $v){?>
                                    <option value="<?php echo $v['id']?>" <?php if($_REQUEST['cate'] == $v['id']) echo 'selected="selected"';?>><?php echo $v['catename']?></option>
                                <?php }}?>
                        </select>
                    </div>

                    <label class="col-sm-1 control-label" for="input01">所属部门：</label>
                    <div class="col-sm-3">
                        <select class="form-control" name="department">
                            <option value="" >请选择类型</option>
                            <?php if($this->departmentlist != ""){
                                foreach ($this->departmentlist as $k => $v){?>
                                    <option value="<?php echo $v['id']?>" <?php if($_REQUEST['department'] == $v['id']) echo 'selected="selected"';?>><?php echo $v['pname']?></option>
                                <?php }}?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-1 control-label" for="input01">某一捐赠人的所有捐赠：</label>
                    <div class="col-sm-3">
                        <input type="text" width="100%" class="btn btn-primary btn-block"  style="text-align:left;" value="<?php echo $_REQUEST['pm_pp'];?>" name="pm_pp"/>
                    </div>

                    <label class="col-sm-1 control-label" for="input01">
                        是否校友：</label>
                    <div class="col-sm-3">
                        <label>是
                            <input type="radio" name="pm_is_school" <?php if($_REQUEST['pm_is_school'] == 1) echo 'checked="checked"';?>  value="1" />
                        </label>
                        <label>否
                            <input type="radio" name="pm_is_school" <?php if($_REQUEST['pm_is_school'] == 0) echo 'checked="checked"';?>  value="0"/>
                        </label>
                    </div>

                    <label class="col-sm-1 control-label" for="input03">未开票：</label>
                    <div class="col-sm-3">
                        <input name="piaoju" type="checkbox" value="2" <?php if($_REQUEST['piaoju'] == 2) echo 'checked="checked"';?>>
                    </div>
                </div>

                        <!--<div class="form-group">
                            <label class="col-sm-3 control-label" for="input03">协议已到期：</label>
                            <div class="col-sm-8">
                                <input name="xieyi_daoqi" type="checkbox" value="1">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="input03">未完成到账：</label>
                            <div class="col-sm-8">
                                <input name="jindu" type="checkbox" value="1">
                            </div>
                        </div>-->

                    <div class="form-group">
                        <label class="col-sm-1 control-label" for="input01">起止时间：</label>
                        <div class="col-sm-3">
                            <input type="text" name="start" value="<?php echo $_REQUEST['start'];?>" data-date-format="YYYY-MM-DD" id="datepicker1"/> ~ <input type="text" name="end" data-date-format="YYYY-MM-DD"  value="<?php echo $_REQUEST['end'];?>" id="datepicker2" />
                        </div>

                        <label class="col-sm-1 control-label" for="input03">排序规则：</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="order">
                                <option value="datetime_desc" <?php if($_REQUEST['order'] == "datetime_desc"){echo 'selected="selected"';}?> selected="selected">到账时间降序</option>
                                <option value="datetime_asc" <?php if($_REQUEST['order'] == "datetime_asc"){echo 'selected="selected"';}?>>到账时间升序</option>
                                <option value="m_desc" <?php if($_REQUEST['order'] == "m_desc"){echo 'selected="selected"';}?>>到账金额降序</option>
                                <option value="m_asc" <?php if($_REQUEST['order'] == "m_asc"){echo 'selected="selected"';}?>>到账金额升序</option>
                            </select>
                        </div>
                    </div>

                     <div class="form-group">
                             <div class="col-sm-2 control-label">
                                 <input class="btn btn-greensea" onclick="get_submit()" type="button" value="点击查询"/>
                             </div>

                            <div class="col-sm-1 control-label">
                                <input class="btn btn-greensea" onclick="post_submit()" type="button" value="下载excel报表"/>
                            </div>
                     </div>

                </form>
             </div>
        </section>
      </div>



        <div class="col-md-12">
            <section class="tile color transparent-white">
            <tr class="tile-body nopadding">
                <?php if($this->plistDAO != ""){?>
                <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                    <thead>
                    <tr>
                        <td width="14%">项目名称</td>
                        <td width="8%">所属部门</td>
                        <td width="8%">项目类型</td>
                        <td width="8%">来款方</td>
                        <td width="8%">来款金额</td>
                        <td width="8%">来款时间</td>
                        <td width="8%">捐赠方类型</td>
                        <td width="8%">资金来源</td>
                        <td width="8%">未开票</td>
                        <td width="8%">是否校友</td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach($this->plistDAO as $k=>$v){?>
                        <tr>
                            <td><a href="/management/chouzi/repminfo?id=<?php echo $v['main_id'];?>" target="_blank"><?php echo $v['pm_name'];?></a></td>
                            <td><?php echo $this->department[$v[department]];?></td>
                            <td><?php foreach($this->pcatelist as $key => $value){
                                    if($value['id'] == $v['cate']){
                                        echo $value['catename'];
                                    }
                                };?></td>
                            <td><?php echo $v['pm_pp'];?></td>
                            <td><?php echo sprintf("%.2f",$v['zijin_daozheng_jiner']);?></td>
                            <td><?php echo date("Y-m-d",strtotime($v['zijin_daozhang_datetime']));?></td>
                            <td><?php echo $v['pm_pp_cate'];?></td>
                            <td><?php echo $v['zijin_laiyuan_qudao'];?></td>
                            <td><?php if($v['piaoju'] == 1){
                                    echo '已开票';
                                }else{
                                    echo '未开票';
                                }?></td>
                            <td><?php if($v['piaoju'] == 1){
                                    echo  $pm_is_school = '校友';
                                }else{
                                    echo  $pm_is_school = '非校友';
                                }?></td>
                        </tr>
                    <?php }?>
                    </tbody>
                </table>
            </div>
            <div class="tile-footer">
                <div class="row">
                <div class="page col-md-12" align="right">
                共  <?php echo $this->total;?> 条项目收入信息          <?php echo $this->page;?></div>

                <?php }else{?>
                <div style="padding: 20px;">暂无项目收入信息！<a href="/management/zijin/addzijin">点击添加</a></div>
                <?php }?>
                </div>
            </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $("#xmxxcxytj").addClass("open");

        function get_submit(){
            if($(".chosen-single span").html() != "请选择项目名称"){
                $("#pname_info").val($(".chosen-single span").html());
            }
            //$('#search_form1').attr('method','get');
            $('#search_form1').attr('action','/management/report/zijin/index');
            $('#search_form1').submit();
        }

        function post_submit(){
            if($(".chosen-single span").html() != "请选择项目名称"){
                $("#pname_info").val($(".chosen-single span").html());
            }
            $('#search_form1').attr('action','/management/report/zijinnewtoexcel');
            $('#search_form1').submit();
        }
    </script>