
	<div id="main">
		<div id="rightstyle02">
		<h4>下载中心<span class="font_red"> >> </span><span class="font_red_big">下载文档列表</span></h4>
			<div class="detailedbox">
				<div class="search">
					<form action="#" method="post">
						文档名称：<input type="text" name="fname" />
						<input type="submit" value="搜索"/>
					</form>
				</div>
	
				<?php if($this->my_download != ""){?>
					<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  
					  <tr>
						<td width="20%" bgcolor="#f5f5f5">序号</td>
						<td width="30%" bgcolor="#f5f5f5">下载文档名称</td>
						<td width="20%" bgcolor="#f5f5f5">操作</td>
					  </tr>
					
					  <?php 
						foreach($this->my_download as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['did'];?></td>
						 	<td><?php echo $v['download_title'];?></td>
							<td><a href="/admin/download/editdownload?id=<?php echo $v['did'];?>">编辑</a> 
							|| <a href="/admin/download/deldownload?id=<?php echo $v['did'];?>">删除</a> 
							</td>
						 </tr>
					   <?php }?>
					</table>
					
					<div align="right" style="margin-right: 10px;margin-top: 5px;">
						共  <?php echo $this->total;?> 条下载文档          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无下载文档！</div>
				 <?php }?>
		  </div>
		</div> 

