<div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/about"><span>基金会简介</span></a></li>
                      <li><a href="/about/lingdaotici">领导致辞</a></li>
                      <li><a href="/about/zhangcheng">基金会章程</a></li>
                      <li><a href="/about/zuzhi">组织机构设置</a></li>
					  <li><a href="/about/mishuzhang">秘书长简历</a></li>
                      <li><a href="/about/baogao">年度工作报告</a></li>
                      <li><a href="/about/caiwushenji">财务审计报告</a></li>
                      <li><a href="/about/guanlizhidu">项目管理制度</a></li>
                   </ul>
              </div>