<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:480px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/about_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>基金会概况</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/about">基金会简介</a></li>
                      <li><a href="/about/lingdaotici"><span>领导题词</span></a></li>
                      <li><a href="/about/zhangcheng">基金会章程</a></li>
                      <li><a href="/about/zuzhi">组织机构设置</a></li>
                      <li><a href="/about/baogao">年度报告</a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><em>领导题词</em><span>当前位置：<a href="/about">基金会概况</a> > 领导题词</span></div>
              <div class="jjh_sub_con_content" style="height:400px; background:url(<?php echo __DEFAULTINCLUDEPATH__;?>images/ldtc.jpg) no-repeat 580px 390px;">
              	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;天津大学是教育部直属国家重点大学，其前身为北洋大学，始建于 1895 年 10 月 2 日 ，是中国第一所现代高等教育学府。这所大学承中华五千年文化之滋润，浸六百年津门之风骨，发轫于甲午战败、国运衰败之际，肩负兴学救国、振兴中华之使命，百十年来，以育人为宗旨，实事求是，矢志不渝，严谨治学，求实创新，至今培育国家栋梁 15 万余。<br /><br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;进入新世纪，天津大学以工科之鲜明优势及理、文、管、艺协调发展之综合性学术机构，成为中国主要的研究型大学之一，在国家科技创新体系中发挥着积极作用，其在国内外的影响力日益提升。<br /><br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;天津大学的发展，不仅得到国家长期的重点支持，更离不开广大校友和社会各界的鼎力相助：社会贤达、团体多次资助学科发展或困难学生生活，著名企业在我校设立奖学金、与我校共建实验室、联合培养人才，乃至捐资建设体育馆、资助学生艺术团等等。<br /><br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;学校于 1995 年成立了天津大学北洋教育发展基金会，作为与社会各界沟通的桥梁，愿以更加规范之运作，多方筹措资金，扶助贫弱，奖掖优秀，延揽名师，交流学术，以期进一步培育大学文化、推进素质教育、建设标志性建筑，美化校园环境。<br /><br />
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;在此，学校诚邀社会各界不吝资助，使这所中国现代高等教育的发祥之校早日成为世界知名高水平大学，为中华之振兴，人类之进步创永世之荣光。<br /><br />
              </div>
         </div>
     </div>
<?= $this->partial('common/footer.phtml'); ?>   