<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:850px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/about_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>基金会概况</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/about">基金会简介</a></li>
                      <li><a href="/about/lingdaotici">领导致辞</a></li>
                      <li><a href="/about/zhangcheng">基金会章程</a></li>
                      <li><a href="/about/zuzhi"><span>组织机构设置</span></a></li>
					  <li><a href="/about/mishuzhang">秘书长简历</a></li>
                      <li><a href="/about/baogao">年度工作报告</a></li>
                      <li><a href="/about/caiwushenji">财务审计报告</a></li>
                      <li><a href="/about/guanlizhidu">项目管理制度</a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><em>组织机构设置</em><span>当前位置：<a href="/about">基金会概况</a> > 组织机构设置</span></div><!--
              <div class="jjh_sub_con_content" style="height:780px;">
              	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;天津大学北洋教育发展基金会的决策机构为理事会，并有监事行使监督职权。理事会由理事长、副理事长、理事组成。理事分别由学校领导，学院和机关部处负责人，校友代表组成。秘书处负责基金会的日常工作。<br /><br />
                <font class="jjh_font4">天津大学北洋教育发展基金会第三届理事会名单</font><br />
                <p><font class="jjh_font2">理事长：</font>&nbsp;&nbsp;&nbsp;&nbsp;冯亚青</p>
                <p><font class="jjh_font2">副理事长： </font>杨贤金&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;舒歌群&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;李义丹</p>
                <p><font class="jjh_font2">理事：</font> （排名不分先后）</p>
                <p>杨渝钦&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;杭建民&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;肖松山&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;肖松山&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;古&nbsp;&nbsp;&nbsp;瑶&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;白海力&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;杨福玲&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;马桂秋&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;亢一澜&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;张 维&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;练继建<br />贾绍义&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;徐友浩&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;姜恩永&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;孙雨耕&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;卜冬梅&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;洪再生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;陈毅松&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;王国华&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;马春有&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;李秀民</p>
                <p><font class="jjh_font2">秘书长：</font>&nbsp;&nbsp;&nbsp;&nbsp;李秀民</p>
                <p><font class="jjh_font2">副秘书长：</font>&nbsp;范超英&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;田志宏&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;王  葳&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;潘  峰</p>
                <p><font class="jjh_font2">顾问：</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;单&nbsp;&nbsp;&nbsp;平&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;王玉林&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;高文新</p><br />
                <font class="jjh_font4">天津大学北洋教育发展基金会组织机构</font><br />
                <p><br /><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/zzjg.jpg" /></p>

              </div>
         --><?php echo $this->info[0]['content'];?></div>
     </div>
<?= $this->partial('common/footer.phtml'); ?>   