<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>
	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
				<h4>会议管理<span class="font_#0474d6"> >> </span><span class="font_#0474d6_big">添加会议信息</span></h4>
				<section class="tile color transparent-black">
			<div class="detailedbox tile-body">
                <form class="form-horizontal" id="form1" action="to-add" method="post" encType="multipart/form-data">
				<div class="form-group">
						<label class="col-sm-2 control-label" for="input01">会议名称：</label>
                        <div class="col-sm-9">
                          <input class="form-control" type="text" name="meeting_name" />
                        </div>
						<span class="col-sm-1" > * </span>
				</div>	
				<div class="form-group">
					    <label class="col-sm-2 control-label" for="input02">会议类型：</label>
						<div class="col-sm-9">
							<select class="chosen-select chosen-transparent form-control" name="meeting_cate">
								<option value="" >请选择类型</option>
								<?php if($this->meetingCateList != ""){
								foreach ($this->meetingCateList as $k => $v){?>
									<option value="<?php echo $v['id']?>" ><?php echo $v['catename']?></option>
								<?php }}?>
							</select>
						</div>
						<span class="col-sm-1" > * </span>
				</div>


					<!--<div class="form-group">
					    <label class="col-sm-2 control-label" for="input06">项目签约日期：</label>
						<div class="col-sm-9">
							<input class="form-control" type="text"  id="dateinput"  name="qianyuedate"  size="14"/>
						</div>
					</div>-->

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">参会人员：</label>
                        <div class="col-sm-9">
                            <input class="form-control" type="text" name="meeting_joiner" />
                        </div>
                        <span class="col-sm-1" > * </span>
                    </div>

                    <!--<div class="form-group transparent-editor">
					    <label class="col-sm-2 control-label" for="input14">会议内容摘要：</label>
						<div class="col-sm-9">
							<textarea class="ckeditor form-control" name="meeting_content"></textarea>
						</div>
					</div>-->

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">会议内容摘要：</label>
                        <div class="col-sm-9">
                            <textarea parsley-validation-minlength="1" name="meeting_content" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                        </div>
                    </div>
					
					<div class="form-group form-footer">
						<div class="col-sm-offset-5 col-sm-7">
							<input class="btn btn-primary" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
							<input class="btn btn-default" type="reset" value="重 置" /> 
						</div>
					</div>
			</form>
			</div>
		 </section>
			</div>
		</div>
	
		<script language="javascript">
            $(".menu li:eq(24)").addClass("open");
			/*$(document).ready(function() {
			       $('#dateinput').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   */
		</script>

