<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加会议信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>会议管理</li>
            <li class="active">添加会议信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
				<section class="tile color transparent-black">
			<div class="detailedbox tile-body">
                <form class="form-horizontal" action="to-add" method="post" encType="multipart/form-data">
				<div class="form-group">
						<label class="col-sm-2 control-label" for="input01">会议名称：</label>
                        <div class="col-sm-3">
                          <input class="form-control" type="text" name="meeting_name" />
                        </div>
						<span class="col-sm-1" > * </span>
				</div>	
				<div class="form-group">
					    <label class="col-sm-2 control-label" for="input02">会议类型：</label>
						<div class="col-sm-3">
							<select class="chosen-select chosen-transparent form-control" name="meeting_cate">
								<option value="" >请选择类型</option>
								<?php if($this->meetingCateList != ""){
								foreach ($this->meetingCateList as $k => $v){?>
									<option value="<?php echo $v['id']?>" ><?php echo $v['catename']?></option>
								<?php }}?>
							</select>
						</div>
						<span class="col-sm-1" > * </span>
				</div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议文档：</label>
                        <div class="col-sm-4">
                            <input name="meeting_files" type="file" value="" />
                        </div>
                        <span class="col-sm-2" > * </span>
                    </div>


                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input06">会议开始时间：</label>
                        <div class="col-sm-4">
                            <input class="form-control" data-date-format="YYYY-MM-DD HH:mm:ss" type="text"  id="datepicker"  name="meeting_start_time" size="14"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input06">会议结束时间：</label>
                        <div class="col-sm-4">
                            <input class="form-control" data-date-format="YYYY-MM-DD HH:mm:ss" type="text"  id="datepicker1"  name="meeting_end_time" size="14"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议地点：</label>

                        <div class="col-sm-9">
                            <textarea parsley-validation-minlength="1" name="meeting_address" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">参会人员：</label>

                        <div class="col-sm-9">
                            <textarea parsley-validation-minlength="1" name="meeting_joiner" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                        </div>
                    </div>


                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">会议内容摘要：</label>
                        <div class="col-sm-9">
                            <textarea parsley-validation-minlength="1" name="meeting_content" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                        </div>
                    </div>
					
					<div class="form-group form-footer">
						<div class="col-sm-offset-5 col-sm-7">
							<input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
							<input class="btn btn-default" type="reset" value="重 置" /> 
						</div>
					</div>
			</form>
			</div>
		 </section>
			</div>
		</div>
	
		<script language="javascript">
            $(".menu li:eq(28)").addClass("open");
		</script>

