<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加会议信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>会议管理</li>
            <li class="active">添加会议信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
				<section class="tile color transparent-white">
			<div class="detailedbox tile-body">
                <form class="form-horizontal" action="to-add" method="post" encType="multipart/form-data">
				<div class="form-group">
						<label class="col-sm-2 control-label" for="input01">会议名称：</label>
                        <div class="col-sm-3">
                          <input class="form-control" type="text" name="meeting_name" />
                        </div>
						<span class="col-sm-1" > * </span>
				</div>	
				<div class="form-group">
					    <label class="col-sm-2 control-label" for="input02">会议类型：</label>
						<div class="col-sm-3">
							<select class="chosen-select chosen-transparent form-control" name="meeting_cate">
								<option value="" >请选择类型</option>
								<?php if($this->meetingCateList != ""){
								foreach ($this->meetingCateList as $k => $v){?>
									<option value="<?php echo $v['id']?>" ><?php echo $v['catename']?></option>
								<?php }}?>
							</select>
						</div>
						<span class="col-sm-1" > * </span>
				</div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议文档一：</label>
                        <div class="col-sm-4">
                            <input name="meeting_files" type="file" value="" />
                        </div>
                        <!--<span class="col-sm-2" > * </span>-->
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议文档二：</label>
                        <div class="col-sm-4">
                            <input name="meeting_files1" type="file" value="" />
                        </div>
                        <!--<span class="col-sm-2" > * </span>-->
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议文档三：</label>
                        <div class="col-sm-4">
                            <input name="meeting_files2" type="file" value="" />
                        </div>
                        <!--<span class="col-sm-2" > * </span>-->
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议文档四：</label>
                        <div class="col-sm-4">
                            <input name="meeting_files3" type="file" value="" />
                        </div>
                        <!--<span class="col-sm-2" > * </span>-->
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议文档五：</label>
                        <div class="col-sm-4">
                            <input name="meeting_files4" type="file" value="" />
                        </div>
                        <!--<span class="col-sm-2" > * </span>-->
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议文档六：</label>
                        <div class="col-sm-4">
                            <input name="meeting_files5" type="file" value="" />
                        </div>
                        <!--<span class="col-sm-2" > * </span>-->
                    </div>


                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input06">会议时间：</label>
                        <div class="col-sm-4">
                            <input class="form-control" data-date-format="YYYY-MM-DD HH:mm:ss" type="text"  id="datepicker"  name="meeting_start_time" size="14"/>
                        </div>
                    </div>

                    <!--<div class="form-group">
                        <label class="col-sm-2 control-label" for="input06">会议结束时间：</label>
                        <div class="col-sm-4">
                            <input class="form-control" data-date-format="YYYY-MM-DD" type="text"  id="datepicker1"  name="meeting_end_time" size="14"/>
                        </div>
                    </div>-->

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">会议地点：</label>

                        <div class="col-sm-9">
                            <input class="form-control" type="text"  name="meeting_address" size="14"/>
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">参会人员：</label>

                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="meeting_joiner[]" id="meeting_joiner">
                                <?php if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                        <option value="<?php echo $v['pid']?>"><?php echo $v['ppname']?></option>
                                    <?php }}?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>


                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">会议内容摘要：</label>
                        <div class="col-sm-9">
                            <textarea parsley-validation-minlength="1" name="meeting_content" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                        </div>
                        <span class="col-sm-1" > * </span>
                    </div>
					
					<div class="form-group form-footer">
						<div class="col-sm-offset-5 col-sm-7">
							<input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
							<!--<input class="btn btn-default" type="reset" value="重 置" />-->
						</div>
					</div>
			</form>
			</div>
		 </section>
			</div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>

        <!-- Latest compiled and minified CSS -->
        <!--<link rel="stylesheet" href="/include/management/css/bootstrap-select.min.css">-->

        <!-- Latest compiled and minified JavaScript -->
        <!--<script src="/include/management/js/bootstrap-select.min.js"></script>-->

        <script language="javascript">
            $(".menu li:eq(37)").addClass("open");

           /* $('#meeting_joiner').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });*/
        </script>

