<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>会议活动详细信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>会议活动管理</li>
            <li class="active">会议活动详细信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" id="form1" action="to-add" method="post" encType="multipart/form-data">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">会议活动名称：</label>
                            <div class="col-sm-3">
                                <?php echo $this->meeting_info[0]['meeting_name'];?>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">会议活动类型：</label>
                            <div class="col-sm-3">
                            <?php if($this->meetingCateList != ""){
                                foreach ($this->meetingCateList as $k => $v){?>
                                    <?php if($this->meeting_info[0]["meeting_cate"] == $v['id']) echo $v['catename'];?>
                                <?php }}?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">会议活动文档一：</label>
                            <div class="col-sm-4">
                                <a href="/management/meeting/download?id=<?php echo $this->meeting_info[0]['id'];?>">
                                    <?php echo $this->meeting_info[0]['meeting_files_name'];?>
                                </a>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">会议活动文档二：</label>
                            <div class="col-sm-4">
                                <a href="/management/meeting/download?id=<?php echo $this->meeting_info[0]['id'];?>&fid=1">
                                    <?php echo $this->meeting_info[0]['meeting_files_name1'];?>
                                </a>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">会议活动文档三：</label>
                            <div class="col-sm-4">
                                <a href="/management/meeting/download?id=<?php echo $this->meeting_info[0]['id'];?>&fid=2">
                                    <?php echo $this->meeting_info[0]['meeting_files_name2'];?>
                                </a>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">会议活动文档四：</label>
                            <div class="col-sm-4">
                                <a href="/management/meeting/download?id=<?php echo $this->meeting_info[0]['id'];?>&fid=3">
                                    <?php echo $this->meeting_info[0]['meeting_files_name3'];?>
                                </a>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">会议活动文档五：</label>
                            <div class="col-sm-4">
                                <a href="/management/meeting/download?id=<?php echo $this->meeting_info[0]['id'];?>&fid=4">
                                    <?php echo $this->meeting_info[0]['meeting_files_name4'];?>
                                </a>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">会议活动文档六：</label>
                            <div class="col-sm-4">
                                <a href="/management/meeting/download?id=<?php echo $this->meeting_info[0]['id'];?>&fid=5">
                                    <?php echo $this->meeting_info[0]['meeting_files_name5'];?>
                                </a>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">会议活动时间：</label>
                            <div class="col-sm-4">
                                <?php echo $this->meeting_info[0]['meeting_start_time'];?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">会议活动地点：</label>

                            <div class="col-sm-9">
                                <?php echo $this->meeting_info[0]['meeting_address'];?>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">参会人员：</label>

                            <div class="col-sm-6">
                            <?php if($this->jjh_mg_pp_list != ""){
                                foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                    <?php
                                    if(!empty($this->meeting_info[0]['meeting_joiner'])){
                                        foreach(explode(',',$this->meeting_info[0]['meeting_joiner']) as $key => $value){
                                            if($v['pid'] == $value){
                                                echo $v['ppname'].'&nbsp;&nbsp;';
                                            }
                                        }
                                    }?>
                                <?php }}?>
                            </div>
                        </div>


                        <div class="form-group transparent-editor">
                            <label class="col-sm-2 control-label" for="input14">会议活动内容摘要：</label>
                            <div class="col-sm-9">
                                <?php echo $this->meeting_info[0]['meeting_content'];?>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                    </form>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>

    <!-- Latest compiled and minified CSS -->
    <!--<link rel="stylesheet" href="/include/management/css/bootstrap-select.min.css">-->

    <!-- Latest compiled and minified JavaScript -->
    <!--<script src="/include/management/js/bootstrap-select.min.js"></script>-->

    <script language="javascript">
        $("#hyhdgl").addClass("open");

        /*$('#meeting_joiner').selectpicker({
         selectedText: 'cat',
         liveSearch: true,
         size:8
         });

         var str='<?php echo $this->meeting_info[0]['meeting_joiner']?>';
         var arr=str.split(',');
         $('#meeting_joiner').selectpicker('val', arr);*/
    </script>

