	  		</div><!-- tab-pane -->
          </div><!-- tab-content -->
		</div>
	</div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->
	<section class="videocontent" id="video"></section>

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="/include/management/assets/js/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/include/management/assets/js/vendor/bootstrap/bootstrap.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/mmenu/js/jquery.mmenu.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/sparkline/jquery.sparkline.min.js"></script>

    <?php if($this->controller == "index") {?>
        <script type="text/javascript" src="/include/management/assets/js/vendor/nicescroll/jquery.nicescroll.min.js"></script>
        <script src="/include/management/assets/js/vendor/easypiechart/jquery.easypiechart.min.js"></script>
        <!--<script src="/include/management/assets/js/vendor/flot/jquery.flot.orderBars.js"></script>-->

        <script type="text/javascript" src="/include/management/assets/js/vendor/animate-numbers/jquery.animateNumbers.js"></script>
        <script type="text/javascript" src="/include/management/assets/js/vendor/videobackground/jquery.videobackground.js"></script>
        <script type="text/javascript" src="/include/management/assets/js/vendor/blockui/jquery.blockUI.js"></script>

        <script src="/include/management/assets/js/vendor/flot/jquery.flot.min.js"></script>
        <script src="/include/management/assets/js/vendor/flot/jquery.flot.time.min.js"></script>
        <script src="/include/management/assets/js/vendor/flot/jquery.flot.selection.min.js"></script>
        <script src="/include/management/assets/js/vendor/flot/jquery.flot.animator.min.js"></script>

        <script src="/include/management/assets/js/vendor/rickshaw/raphael-min.js"></script>
        <script src="/include/management/assets/js/vendor/rickshaw/d3.v2.js"></script>
        <script src="/include/management/assets/js/vendor/rickshaw/rickshaw.min.js"></script>

        <script src="/include/management/assets/js/vendor/morris/morris.min.js"></script>
        <script src="/include/management/assets/js/vendor/tabdrop/bootstrap-tabdrop.min.js"></script>
        <script src="/include/management/assets/js/vendor/summernote/summernote.min.js"></script>
        <script src="/include/management/assets/js/vendor/chosen/chosen.jquery.min.js"></script>
    <?php }?>

    <script type="text/javascript" src="/include/management/assets/js/vendor/mmenu/js/jquery.mmenu.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/sparkline/jquery.sparkline.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/nicescroll/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/animate-numbers/jquery.animateNumbers.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/videobackground/jquery.videobackground.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/blockui/jquery.blockUI.js"></script>

    <script src="/include/management/assets/js/vendor/summernote/summernote.min.js"></script>

    <script src="/include/management/assets/js/vendor/chosen/chosen.jquery.min.js"></script>
    
    <script src="/include/management/assets/js/vendor/momentjs/moment-with-langs.min.js"></script>
    <script src="/include/management/assets/js/vendor/datepicker/bootstrap-datetimepicker.min.js"></script>
   
    <script src="/include/management/assets/js/minimal.min.js"></script>


    
    <script>
    $(function(){
    	//initialize datepicker
        $('#datepicker').datetimepicker({
          	icons: {
            	time: "fa fa-clock-o",
            	date: "fa fa-calendar",
            	up: "fa fa-arrow-up",
            	down: "fa fa-arrow-down"
          	}
        });

        $("#datepicker").on("dp.show",function (e) {
          	var newtop = $('.bootstrap-datetimepicker-widget').position().top - 45;
          	$('.bootstrap-datetimepicker-widget').css('top', newtop + 'px');
        });

        //initialize datepicker
        $('#datepicker1').datetimepicker({
          icons: {
            time: "fa fa-clock-o",
            date: "fa fa-calendar",
            up: "fa fa-arrow-up",
            down: "fa fa-arrow-down"
          }
        });

        $("#datepicker1").on("dp.show",function (e) {
          	var newtop1 = $(".bootstrap-datetimepicker-widget").position(relative).top - 45;
            alert(newtop1);
          	$('.bootstrap-datetimepicker-widget').css('top', newtop1 + 'px');
        });

        //initialize datepicker
        $('#datepicker2').datetimepicker({
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            }
        });

        $("#datepicker2").on("dp.show",function (e) {
            var newtop2 = $('.bootstrap-datetimepicker-widget').position(relative).top - 45;
            $('.bootstrap-datetimepicker-widget').css('top', newtop2 + 'px');
        });

        //initialize datepicker
        $('#datepicker3').datetimepicker({
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            }
        });

        $("#datepicker3").on("dp.show",function (e) {
            var newtop3 = $('.bootstrap-datetimepicker-widget').position(relative).top - 45;
            $('.bootstrap-datetimepicker-widget').css('top', newtop3 + 'px');
        });

        //initialize datepicker
        $('#datepicker4').datetimepicker({
            changeYear: true,
            dateFormat: 'YYYY',
            icons: {
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            }
        });

        $("#datepicker4").on("dp.show",function (e) {
            var newtop4 = $('.bootstrap-datetimepicker-widget').position(relative).top - 45;
            $('.bootstrap-datetimepicker-widget').css('top', newtop4 + 'px');
        });

      // Initialize flot chart
      var d1 =[ [1, 715],
            [2, 985],
            [3, 1525],
            [4, 1254],
            [5, 1861],
            [6, 2621],
            [7, 1987],
            [8, 2136],
            [9, 2364],
            [10, 2851],
            [11, 1546],
            [12, 2541]
      ];
      var d2 =[ [1, 463],
                [2, 578],
                [3, 327],
                [4, 984],
                [5, 1268],
                [6, 1684],
                [7, 1425],
                [8, 1233],
                [9, 1354],
                [10, 1200],
                [11, 1260],
                [12, 1320]
      ];
      var months = ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"];

      <?php if($this->module == "management" && $this->controller == "index" && $this->action == "index"){?>
      // flot chart generate
      var plot = $.plotAnimator($("#statistics-chart"), 
        [
          {
            label: 'Sales', 
            data: d1,    
            lines: {lineWidth:3}, 
            shadowSize:0,
            color: '#ffffff'
          },
          { label: "Visits",
            data: d2, 
            animator: {steps: 99, duration: 500, start:200, direction: "right"},   
            lines: {        
              fill: .15,
              lineWidth: 0
            },
            color:['#ffffff']
          },{
            label: 'Sales',
            data: d1, 
            points: { show: true, fill: true, radius:6,fillColor:"rgba(0,0,0,.5)",lineWidth:2 }, 
            color: '#fff',        
            shadowSize:0
          },
          { label: "Visits",
            data: d2, 
            points: { show: true, fill: true, radius:6,fillColor:"rgba(255,255,255,.2)",lineWidth:2 }, 
            color: '#fff',        
            shadowSize:0
          }
        ],{ 
        
        xaxis: {

          tickLength: 0,
          tickDecimals: 0,
          min:1,
          ticks: [[1,"一月"], [2, "二月"], [3, "三月"], [4, "四月"], [5, "五月"], [6, "六月"], [7, "七月"], [8, "八月"], [9, "九月"], [10, "十月"], [11, "十一月"], [12, "十二月  "]],

          font :{
            lineHeight: 24,
            weight: "300",
            color: "#ffffff",
            size: 14
          }
        },
        
        yaxis: {
          ticks: 4,
          tickDecimals: 0,
          tickColor: "rgba(255,255,255,.3)",

          font :{
            lineHeight: 13,
            weight: "300",
            color: "#ffffff"
          }
        },
        
        grid: {
          borderWidth: {
            top: 0,
            right: 0,
            bottom: 1,
            left: 1
          },
          borderColor: 'rgba(255,255,255,.3)',
          margin:0,
          minBorderMargin:0,              
          labelMargin:20,
          hoverable: true,
          clickable: true,
          mouseActiveRadius:6
        },
        
        legend: { show: false}
      });


        $(window).resize(function() {
            // redraw the graph in the correctly sized div
            plot.resize();
            plot.setupGrid();
            plot.draw();
        });

        $('#mmenu').on(
            "opened.mm",
            function()
            {
                // redraw the graph in the correctly sized div
                plot.resize();
                plot.setupGrid();
                plot.draw();
            }
        );

        $('#mmenu').on(
            "closed.mm",
            function()
            {
                // redraw the graph in the correctly sized div
                plot.resize();
                plot.setupGrid();
                plot.draw();
            }
        );

        // tooltips showing
        $("#statistics-chart").bind("plothover", function (event, pos, item) {
            if (item) {
                var x = item.datapoint[0],
                    y = item.datapoint[1];

                $("#tooltip").html('<h1 style="color: #418bca">' + months[x - 1] + '</h1>' + '<strong>' + y + '</strong>' + ' ' + item.series.label)
                    .css({top: item.pageY-30, left: item.pageX+5})
                    .fadeIn(200);
            } else {
                $("#tooltip").hide();
            }
        });

        //tooltips options
        $("<div id='tooltip'></div>").css({
            position: "absolute",
            //display: "none",
            padding: "10px 20px",
            "background-color": "#ffffff",
            "z-index":"99999"
        }).appendTo("body");

        //generate actual pie charts
        $('.pie-chart').easyPieChart();


        //server load rickshaw chart
        var graph;

        var seriesData = [ [], []];
        var random = new Rickshaw.Fixtures.RandomData(50);

        for (var i = 0; i < 50; i++) {
            random.addData(seriesData);
        }

        graph = new Rickshaw.Graph( {
            element: document.querySelector("#serverload-chart"),
            height: 150,
            renderer: 'area',
            series: [
                {
                    data: seriesData[0],
                    color: '#6e6e6e',
                    name:'File Server'
                },{
                    data: seriesData[1],
                    color: '#fff',
                    name:'Mail Server'
                }
            ]
        } );

        var hoverDetail = new Rickshaw.Graph.HoverDetail( {
            graph: graph,
        });

        setInterval( function() {
            random.removeData(seriesData);
            random.addData(seriesData);
            graph.update();

        },1000);

        // Morris donut chart
        Morris.Donut({
            element: 'browser-usage',
            data: [
                {label: "Chrome", value: 25},
                {label: "Safari", value: 5},
                {label: "Firefox", value: 15},
                {label: "Opera", value: 5},
                {label: "Internet Explorer", value: 40},
                {label: "Other", value: 10}
            ],
            colors: ['#00a3d8', '#2fbbe8', '#72cae7', '#d9544f', '#ffc100', '#1693A5']
        });

        $('#browser-usage').find("path[stroke='#ffffff']").attr('stroke', 'rgba(0,0,0,0)');

        //sparkline charts
        $('#projectbar1').sparkline('html', {type: 'bar', barColor: '#22beef', barWidth: 4, height: 20});
        $('#projectbar2').sparkline('html', {type: 'bar', barColor: '#cd97eb', barWidth: 4, height: 20});
        $('#projectbar3').sparkline('html', {type: 'bar', barColor: '#a2d200', barWidth: 4, height: 20});
        $('#projectbar4').sparkline('html', {type: 'bar', barColor: '#ffc100', barWidth: 4, height: 20});
        $('#projectbar5').sparkline('html', {type: 'bar', barColor: '#ff4a43', barWidth: 4, height: 20});
        $('#projectbar6').sparkline('html', {type: 'bar', barColor: '#a2d200', barWidth: 4, height: 20});

        // sortable table
        $('.table.table-sortable th.sortable').click(function() {
            var o = $(this).hasClass('sort-asc') ? 'sort-desc' : 'sort-asc';
            $('th.sortable').removeClass('sort-asc').removeClass('sort-desc');
            $(this).addClass(o);
        });

        //todo's
        $('#todolist li label').click(function() {
            $(this).toggleClass('done');
        });

        // Initialize tabDrop
        $('.tabdrop').tabdrop({text: '<i class="fa fa-th-list"></i>'});

        //load wysiwyg editor
        $('#quick-message-content').summernote({
            toolbar: [
                //['style', ['style']], // no style button
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                //['insert', ['picture', 'link']], // no insert buttons
                //['table', ['table']], // no table button
                //['help', ['help']] //no help button
            ],
            height: 143   //set editable area's height
        });

        //multiselect input
        $(".chosen-select").chosen({disable_search_threshold: 10});

        <?php }?>
    })
      
    </script>

    <!-- //遮罩层效果 -->
    <style>
        .theme-popover-mask {
            z-index: 9998;
            position:fixed;
            top:0;  left:0;  width:100%;
            height:100%;  background:#000;  opacity:0.4;
            filter:alpha(opacity=40);  display:none;
        }
        .theme-popover {
            z-index:9999;  position:fixed;
            top:20%;  left:35%;
            width:45%;
            max-height:220px;
            /*margin:-180px 0 0 -330px;*/
            border-radius:5px;  border:solid 2px #666;
            display:none;
            box-shadow: 0 0 10px #666;
            background-color: #f7f7f7;
            border-bottom: 1px solid #ebebeb;
            border-radius: 5px 5px 0 0;
            font-size: 14px;
        }
        .theme-signin{
            margin-top: 40px;
        }
        #popover-close{
            float: right;
            margin-right: 12px;
            margin-top: 12px;
        }
        #popover-msg{
            margin-top: 12px;
            align-content: center;
            text-align: center;
        }
        #popover-img{
            margin: 0 auto;
            text-align: center;
        }
        #popover-img img{
             display: inline;
			 max-width:30%;
			 height:auto;
			 
         }
    </style>

    <div class="theme-popover">
        <div class="theme-poptit">
            <a href="javascript:void(0);" title="关闭" class="close" id="popover-close" name="">×</a>
        </div>
        <div class="theme-popbod dform">
            <form class="theme-signin" name="loginform" action="" method="post">
                <ol>
                    <li id="popover-img"><img src="/include/management/images/warning.png" width="100" height="100" alt=""></li>
                    <li id="popover-msg"><?php echo $mess = "系统消息提示";?></li>
                </ol>
            </form>
        </div>
    </div>
    <div class="theme-popover-mask"></div>


    <script>
        function noTips(){

            if($(".chosen-single span").html() != "请选择项目名称"){
                $("#pname_info").val($(".chosen-single span").html());
            }

            var formParam = $("#form1").serialize();//序列化表格内容为字符串
            $.ajax({
                type:'post',
                url: $("#form1").attr("action"),
                data:formParam,
                cache:false,
                dataType:'json',
                success:function(data){
                    $('.theme-popover-mask').fadeIn(100);
                    $('.theme-popover').slideDown(200);
                    $('#popover-msg').html(data['msg']);
                    if(data['return_url'] != ''){
                        $('#popover-close').attr("name", data['return_url']);
                    }
                    if(data['error'] != true){
                        $('#popover-img img').attr("src", "/include/management/images/yes.png");
                    }
                },
                complete:function(data){

                },
                error:function(data){
                    $('.theme-popover-mask').fadeIn(100);
                    $('.theme-popover').slideDown(200);
                    $('#popover-msg').html(data['msg']);
                }
            });
        }

        jQuery(document).ready(function($) {
            $('.theme-poptit .close').click(function(){
                $('.theme-popover-mask').fadeOut(100);
                $('.theme-popover').slideUp(200);
                if($('#popover-close').attr("name") != '') {
                    location.href = $('#popover-close').attr("name");
                }
            });
        });
    </script>
    <!-- //遮罩层效果 -->

    <style>
        .margin-bottom-20{
            margin-bottom: 0px;
            padding: 2px 12px;
            font-size: 12px;
        }
    </style>

            <script language="javascript">
                //搜索功能采用get方式 关键词下拉提示，
                $(".chosen-select-1").chosen({
                    search_contains: true,
                    disable_search_threshold: 10
                });

                $("[name='search_form']").submit(function(){
                    if($(".chosen-single span").html() != "请选择项目名称"){
                        $("#pname_info").val($(".chosen-single span").html());
                    }
                    return true;
                });
            </script>