<!-- content main container -->
          <div class="main">
            <!-- cards -->
            <div class="row cards">
              <div class="card-container col-lg-3 col-sm-6 col-sm-12">
                <div class="card card-redbrown hover">
                  <div class="front">

                      <?php
                      $count_total = 0;
                      $income_total = 0;
                      foreach($this->income_cate_array as $key => $value){
                          $count_total = $count_total + (int)$value['counts'];
                          $income_total = $income_total + sprintf("%.2f", $value['income']);
                      }
                      $income_total = sprintf("%.2f", $income_total/10000);
                      $incomes = sprintf("%.2f", $this->income_cate_array['incomes']/10000);
                      ?>

                    <div class="media">
                        <span class="pull-left">
                        <i class="fa fa-star media-object"></i>
                        </span>

                        <div class="media-body">
                            <small>未认领项目</small>
                            <h2 class="media-heading animate-number" data-value="<?php echo count($this->renling_weirenling_list);?>" data-animation-duration="1500"><?php echo count($this->renling_weirenling_list);?></h2>
                        </div>
                    </div>

                   <div class="progress-list">
                      <div class="details">
                        <div class="title">本月来款总数 <?php echo $this->month_income_count;?> 笔，已认领 %</div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?php echo round(($this->month_income_count - count($this->renling_weirenling_list))/$this->month_income_count*100);?>" data-animation-duration="1500"><?php echo ($this->month_income_count - count($this->renling_weirenling_list))/$this->month_income_count*100;?></span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black">
                      <div class="progress-bar animate-progress-bar" data-percentage="<?php echo ($this->month_income_count - count($this->renling_weirenling_list))/$this->month_income_count*100;?>%"></div>
                      </div>
                    </div>

                  </div>
                  <div class="back">
                    <a href="/management/zijin/claimlist" target="_blank">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>点击查看详情</span>
                    </a>  
                  </div>
                </div>
              </div>


              <div class="card-container col-lg-3 col-sm-6 col-sm-12">
                <div class="card card-blue hover">
                  <div class="front">        
                    
                    <div class="media">                  
                      <span class="pull-left">
                        <i class="fa fa-shopping-cart media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>捐赠项目总数</small>
                        <h2 class="media-heading animate-number" data-value="<?php echo $this->total;?>" data-animation-duration="1500"><?php echo $this->total;?></h2>
                      </div>
                    </div> 

                    <div class="progress-list">
                      <div class="details">
                        <div class="title">今年新增项目数 <?php echo $this->create_p_count;?> 项，占总项目数的 %  </div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?php echo round($this->create_p_count/$this->total*100);?>" data-animation-duration="1500"><?php echo round($this->create_p_count/$this->total*100);?></span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black">
                        <div class="progress-bar animate-progress-bar" data-percentage="<?php echo round($this->create_p_count/$this->total*100);?>%"></div>
                      </div>
                    </div>

                  </div>
                  <div class="back">
                    <a href="/management/chouzi/index" target="_blank">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>点击查看详情</span>
                    </a>
                  </div>
                </div>
              </div>


              <div class="card-container col-lg-3 col-sm-6 col-sm-12">
                <div class="card card-greensea hover">
                  <div class="front">        
                    
                    <div class="media">
                      <span class="pull-left">
                        <i class="fa fa-usd media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>捐赠项目总金额（万元）</small>
                        <h2 class="media-heading animate-number" data-value="<?php echo sprintf("%.2f", $this->allsum/10000);?>" data-animation-duration="1500"><?php echo sprintf("%.2f", $this->allsum/10000);?></h2>
                      </div>
                    </div>

                    <div class="progress-list">
                      <div class="details">
                        <div class="title">今年捐赠<?php echo $incomes;?>（万元），占总金额 %</div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?php echo round($incomes/(round($this->allsum/10000,2))*100);?>" data-animation-duration="1500"><?php echo round($incomes/(round($this->allsum/10000,2))*100);?></span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black">
                        <div class="progress-bar animate-progress-bar" data-percentage="<?php echo round($incomes/(round($this->allsum/10000,2))*100);?>>%"></div>
                      </div>
                    </div>

                  </div>
                  <div class="back">
                    <a href="/management/report/zijin" target="_blank">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>点击查看详情</span>
                    </a>
                  </div>
                </div>
              </div>


              <div class="card-container col-lg-3 col-sm-6 col-xs-12">
                <div class="card card-slategray hover">
                  <div class="front"> 

                    <div class="media">                   
                      <span class="pull-left">
                        <i class="fa fa-eye media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>配比项目总数（项）</small>
                        <h2 class="media-heading animate-number" data-value="<?php echo count($this->pm_mg_peibiDAO);?>" data-animation-duration="1500"><?php echo $this->meeting_count;?></h2>
                      </div>
                    </div> 

                    <div class="progress-list">
                      <div class="details">
                        <div class="title">申请金额/审批金额 <?php //echo round($this->sum_je/10000).'/'.round($this->sq_je/10000)."(万元)";?> %</div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?php echo round(($this->sum_je/10000)/($this->sq_je/10000)*100);?>" data-animation-duration="1500"><?php echo round(($this->sum_je/10000)/($this->sq_je/10000)*100);?></span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black">
                        <div class="progress-bar animate-progress-bar" data-percentage="<?php echo round(($this->sum_je/10000)/($this->sq_je/10000)*100);?>%"></div>
                      </div>
                    </div>

                  </div>
                  <div class="back">
                    <a href="/management/peibi/index" target="_blank">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>点击查看详情</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <!-- /cards -->

            <!-- row -->
            <div class="row">
              <!-- col 8 -->
              <div class="col-lg-8 col-md-12">

                  <section class="tile color transparent-white">
                      <div class="tile-header">
                          <h1><?php echo $this->years;?>年捐赠收入情况<strong>捐赠类型分析</strong></h1>
                          <!--<input type="text" placeholder="Search...">-->
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>
                      <div class="tile-body no-vpadding">
                          <div class="table-responsive">
                              <table class="table table-custom table-sortable nomargin">
                                  <thead>
                                  <tr>
                                      <th width="30%" class=""><strong>捐赠项目类型</strong></th>
                                      <th width="14%" class=""><strong>项目数量（个）</strong></th>
                                      <th width="20%" class=""><strong>捐赠收入（万元）</strong></th>
                                      <th width="26%"class=""><strong>捐赠用途</strong></th>
                                      <th width="10%" class=""><strong>所占比例</strong></th>
                                  </tr>
                                  </thead>
                                  <tbody>


                                      <?php $value1 = sprintf("%.2f", ($this->income_cate_array[4]['income']+$this->income_cate_array[5]['income']+$this->income_cate_array[10]['income']+$this->income_cate_array[7]['income'])/10000);?>

                                      <tr>
                                          <td><?php echo $this->income_cate_array[4]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[4]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[4]['income']/10000);?></td>
                                          <td style="vertical-align: middle;" rowspan="4">资助学生</td>
                                          <td style="vertical-align: middle;" rowspan="4"><?php echo sprintf("%.2f", $value1/$incomes*100);?>%</td>
                                      </tr>
                                      <tr>
                                          <td><?php echo $this->income_cate_array[5]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[5]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[5]['income']/10000);?></td>
                                      </tr>
                                      <tr>
                                          <td><?php echo $this->income_cate_array[10]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[10]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[10]['income']/10000);?></td>
                                      </tr>
                                      <tr>
                                          <td><?php echo $this->income_cate_array[7]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[7]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[7]['income']/10000);?></td>
                                      </tr>

                                      <?php $value2 = sprintf("%.2f", ($this->income_cate_array[1]['income']+$this->income_cate_array[8]['income']+$this->income_cate_array[9]['income']+$this->income_cate_array[2]['income']+$this->income_cate_array[6]['income'])/10000);?>

                                      <tr>
                                          <td><?php echo $this->income_cate_array[1]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[1]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[1]['income']/10000);?></td>
                                          <td style="vertical-align: middle;" rowspan="5">学校发展</td>
                                          <td style="vertical-align: middle;" rowspan="5"><?php echo sprintf("%.2f", $value2/$incomes*100);?>%</td>
                                      </tr>
                                      <tr>
                                          <td><?php echo $this->income_cate_array[8]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[8]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[8]['income']/10000);?></td>
                                      </tr>
                                      <tr>
                                          <td><?php echo $this->income_cate_array[9]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[9]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[9]['income']/10000);?></td>
                                      </tr>
                                      <tr>
                                          <td><?php echo $this->income_cate_array[2]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[2]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[2]['income']/10000);?></td>
                                      </tr>
                                      <tr>
                                          <td><?php echo $this->income_cate_array[6]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[6]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[6]['income']/10000);?></td>
                                      </tr>

                                      <?php $value3 = sprintf("%.2f", ($this->income_cate_array[3]['income']+$this->income_cate_array[11]['income'])/10000);?>

                                      <tr>
                                          <td><?php echo $this->income_cate_array[3]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[3]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[3]['income']/10000);?></td>
                                          <td style="vertical-align: middle;" rowspan="2">教师及学科发展</td>
                                          <td style="vertical-align: middle;" rowspan="2"><?php echo sprintf("%.2f", $value3/$incomes*100);?>%</td>
                                      </tr>
                                      <tr>
                                          <td><?php echo $this->income_cate_array[11]['name'];?></td>
                                          <td><?php echo $this->income_cate_array[11]['counts'];?></td>
                                          <td><?php echo sprintf("%.2f", $this->income_cate_array[11]['income']/10000);?></td>
                                      </tr>

                                      <tr>
                                          <td><strong>合计</strong></td>
                                          <td><strong><?php echo $count_total;?></strong></td>
                                          <td><strong><?php echo $incomes;?></strong></td>
                                          <td colspan="2">100%</td>
                                      </tr>
                                  </tbody>
                              </table>
                          </div>
                      </div>

                  </section>


                  <section class="tile color transparent-white">
                      <div class="tile-header">
                          <h1><?php echo $this->years;?>年捐赠收入情况<strong>各学院、部处捐赠情况</strong></h1>
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>
                      <div class="tile-body no-vpadding">
                          <div class="table-responsive">
                              <table class="table table-custom table-sortable nomargin">
                                  <thead>
                                  <tr>
                                      <th width="30%" class=""><strong>所属部门</strong></th>
                                      <th width="15%" class=""><strong>捐赠项目数（个）</strong></th>
                                      <!--<th width="16%" class=""><strong>捐赠笔数（笔）</strong></th>-->
                                      <th width="16%" class=""><strong>捐赠收入（万元）</strong></th>
                                      <th width="18%" class=""><strong>超过十万金额（万元）</strong></th>
                                      <th width="20%" class=""><strong>超过十万元捐赠笔数（笔）</strong></th>
                                  </tr>
                                  </thead>
                                  <tbody>
                                        <?php
                                                $p_counts = 0;
                                                $max_income = 0;
                                                $max_income_count = 0;
                                                $income_department_array = $this->income_department_array;
                                                foreach($this->departmentlist as $key => $value){
                                                    if(array_key_exists($value['id'], $this->income_department_array)){
                                            ?>
                                              <tr>
                                                  <td><?php echo $value['pname'];?></td>
                                                  <td><?php echo $this->income_department_array[$value['id']]['counts'];?></td>
                                                  <!--<td><?php /*echo $this->income_department_array[$value['id']]['pcounts'];*/?></td>-->
                                                  <td><?php echo sprintf("%.2f", $this->income_department_array[$value['id']]['income']/10000);?></td>
                                                  <td style="vertical-align: middle;" ><?php echo sprintf("%.2f", $this->income_department_array[$value['id']]['max_income']/10000);?></td>
                                                  <td style="vertical-align: middle;" ><?php if(!empty($this->income_department_array[$value['id']]['max_income_count'])){echo $this->income_department_array[$value['id']]['max_income_count'];}else{echo 0;}?></td>
                                              </tr>
                                        <?php }
                                                    $p_counts += $this->income_department_array[$value['id']]['counts'];
                                                    $max_income += $this->income_department_array[$value['id']]['max_income'];
                                                    $max_income_count = $max_income_count + $this->income_department_array[$value['id']]['max_income_count'];
                                                }?>
                                      <tr>
                                          <td><strong>合计</strong></td>
                                          <td><strong><?php echo $p_counts;?></strong></td>
                                          <!--<td><strong><?php /*echo $this->income_department_pcounts;*/?></strong></td>-->
                                          <td><strong><?php echo sprintf("%.2f", $this->income_department_incomes/10000);?></strong></td>
                                          <td style="vertical-align: middle;" ><strong><?php echo sprintf("%.2f", $max_income/10000);?></strong></td>
                                          <td style="vertical-align: middle;" ><strong><?php echo $max_income_count;?></strong></td>
                                      </tr>
                                  </tbody>
                              </table>
                          </div>
                      </div>

                  </section>

                  <section class="tile color transparent-white">
                      <div class="tile-header">
                          <h1><?php echo $this->years;?>年公益支出情况</h1>
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>
                      <div class="tile-body no-vpadding">
                          <div class="table-responsive">
                              <table class="table table-custom table-sortable nomargin">
                                  <thead>
                                  <tr>
                                      <th width="30%" class=""><strong>捐赠项目类型</strong></th>
                                      <th width="14%" class=""><strong>项目数量（个）</strong></th>
                                      <th width="16%" class=""><strong>公益支出（万元）</strong></th>
                                      <th width="14%" class=""><strong>资助人数</strong></th>
                                      <th width="16%" class=""><strong>捐赠用途</strong></th>
                                      <th width="10%" class=""><strong>所占比例</strong></th>
                                  </tr>
                                  </thead>
                                  <tbody>
                                  <?php
                                      $count_total = 0;
                                      $pay_total = 0;
                                      $jiangli_renshu_hj = 0;
                                      foreach($this->pay_array as $key => $value){
                                          $count_total = $count_total + (int)$value['counts'];
                                          $pay_total = $pay_total + sprintf("%.2f", $value['pay']);
                                          $jiangli_renshu_hj += $value['jiangli_renshu'];
                                      }
                                      $pay_total = sprintf("%.2f", $pay_total/10000);
                                      $pays = sprintf("%.2f", $this->pay_array['pays']/10000);
                                  ?>

                                  <?php $value1 = sprintf("%.2f", ($this->pay_array[4]['pay']+$this->pay_array[5]['pay']+$this->pay_array[10]['pay']+$this->pay_array[7]['pay'])/10000);?>

                                  <tr>
                                      <td><?php echo $this->pay_array[4]['name'];?></td>
                                      <td><?php echo $this->pay_array[4]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[4]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[4]['jiangli_renshu'])){echo $this->pay_array[4]['jiangli_renshu'];}else{echo 0;}?></td>
                                      <td style="vertical-align: middle;" rowspan="4">资助学生</td>
                                      <td style="vertical-align: middle;" rowspan="4"><?php echo sprintf("%.2f", $value1/$pays*100);?>%</td>
                                  </tr>
                                  <tr>
                                      <td><?php echo $this->pay_array[5]['name'];?></td>
                                      <td><?php echo $this->pay_array[5]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[5]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[5]['jiangli_renshu'])){echo $this->pay_array[5]['jiangli_renshu'];}else{echo 0;}?></td>
                                  </tr>
                                  <tr>
                                      <td><?php echo $this->pay_array[10]['name'];?></td>
                                      <td><?php echo $this->pay_array[10]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[10]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[10]['jiangli_renshu'])){echo $this->pay_array[10]['jiangli_renshu'];}else{echo 0;}?></td>
                                  </tr>
                                  <tr>
                                      <td><?php echo $this->pay_array[7]['name'];?></td>
                                      <td><?php echo $this->pay_array[7]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[7]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[7]['jiangli_renshu'])){echo $this->pay_array[7]['jiangli_renshu'];}else{echo 0;}?></td>
                                  </tr>

                                  <?php $value2 = sprintf("%.2f", ($this->pay_array[1]['pay']+$this->pay_array[8]['pay']+$this->pay_array[9]['pay']+$this->pay_array[2]['pay']+$this->pay_array[6]['pay'])/10000);?>

                                  <tr>
                                      <td><?php echo $this->pay_array[1]['name'];?></td>
                                      <td><?php echo $this->pay_array[1]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[1]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[1]['jiangli_renshu'])){echo $this->pay_array[1]['jiangli_renshu'];}else{echo 0;}?></td>
                                      <td style="vertical-align: middle;" rowspan="5">学校发展</td>
                                      <td style="vertical-align: middle;" rowspan="5"><?php echo sprintf("%.2f", $value2/$pays*100);?>%</td>
                                  </tr>
                                  <tr>
                                      <td><?php echo $this->pay_array[8]['name'];?></td>
                                      <td><?php echo $this->pay_array[8]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[8]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[8]['jiangli_renshu'])){echo $this->pay_array[8]['jiangli_renshu'];}else{echo 0;}?></td>
                                  </tr>
                                  <tr>
                                      <td><?php echo $this->income_cate_array[9]['name'];?></td>
                                      <td><?php echo $this->income_cate_array[9]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->income_cate_array[9]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[9]['jiangli_renshu'])){echo $this->pay_array[9]['jiangli_renshu'];}else{echo 0;}?></td>
                                  </tr>
                                  <tr>
                                      <td><?php echo $this->pay_array[2]['name'];?></td>
                                      <td><?php echo $this->pay_array[2]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[2]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[2]['jiangli_renshu'])){echo $this->pay_array[2]['jiangli_renshu'];}else{echo 0;}?></td>
                                  </tr>
                                  <tr>
                                      <td><?php echo $this->pay_array[6]['name'];?></td>
                                      <td><?php echo $this->pay_array[6]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[6]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[6]['jiangli_renshu'])){echo $this->pay_array[6]['jiangli_renshu'];}else{echo 0;}?></td>
                                  </tr>

                                  <?php $value3 = sprintf("%.2f", ($this->pay_array[3]['pay']+$this->pay_array[11]['pay'])/10000);?>

                                  <tr>
                                      <td><?php echo $this->pay_array[3]['name'];?></td>
                                      <td><?php echo $this->pay_array[3]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[3]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[3]['jiangli_renshu'])){echo $this->pay_array[3]['jiangli_renshu'];}else{echo 0;}?></td>
                                      <td style="vertical-align: middle;" rowspan="2">教师及学科发展</td>
                                      <td style="vertical-align: middle;" rowspan="2"><?php echo sprintf("%.2f", $value3/$pays*100);?>%</td>
                                  </tr>

                                  <tr>
                                      <td><?php echo $this->pay_array[11]['name'];?></td>
                                      <td><?php echo $this->pay_array[11]['counts'];?></td>
                                      <td><?php echo sprintf("%.2f", $this->pay_array[11]['pay']/10000);?></td>
                                      <td><?php if(!empty($this->pay_array[11]['jiangli_renshu'])){echo $this->pay_array[11]['jiangli_renshu'];}else{echo 0;}?></td>
                                  </tr>

                                  <tr>
                                      <td><strong>合计</strong></td>
                                      <td><strong><?php echo $count_total;?></strong></td>
                                      <td><strong><?php echo $pays;?></strong></td>
                                      <td><strong><?php echo $jiangli_renshu_hj;?></strong></td>
                                      <td colspan="2">100%</td>
                                  </tr>
                                  </tbody>
                              </table>
                          </div>
                      </div>

                  </section>


                  <!-- tile -->
                  <!--<section class="tile color transparent-white">
                      <div class="tile-header">
                          <h1>项目进程<strong>Projects  Progress</strong> </h1>
                          <input type="text" placeholder="Search...">
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>
                      <div class="tile-body no-vpadding">
                          <div class="table-responsive">
                              <table class="table table-custom table-sortable nomargin">
                                  <thead>
                                  <tr>
                                      <th width="10%" class="">项目编号</th>
                                      <th width="40%" class="">项目名称</th>
                                      <th width="20%" class="">项目状态</th>
                                      <th width="20%"class="">项目进度</th>
                                      <th width="10%" class="">操作</th>
                                  </tr>
                                  </thead>
                                  <tbody>
                                  <?php /*foreach($this->chouzilist as $key => $value){ $nn = 0;*/?>
                                      <tr>
                                          <td><?php /*echo $value['id'];*/?></td>
                                          <td><?php /*echo $value['pname'];*/?></td>
                                          <td class="priority">
                                              <?php /*if($value['pm_rate'] == ""){*/?>
                                                  ---
                                              <?php /*}if(preg_match("/1/", $value['pm_rate'])){ $nn += 10;*/?>
                                                  洽谈中&nbsp;
                                              <?php /*}if(preg_match("/2/", $value['pm_rate'])){ $nn += 40;*/?>
                                                  已签订&nbsp;
                                              <?php /*}if(preg_match("/3/", $value['pm_rate'])){ $nn += 60;*/?>
                                                  已到帐&nbsp;
                                              <?php /*}*/?>
                                          </td>
                                          </td>
                                          <td class="progress-cell">
                                              <div class="progress-info">
                                                  <div class="percent"><span class="animate-number" data-value="<?php /*echo $nn*/?>" data-animation-duration="1500">0</span>%</div>
                                              </div>
                                              <div class="progress progress-little">
                                                  <div class="progress-bar progress-bar-transparent-white animate-progress-bar" data-percentage="<?php /*echo $nn*/?>%"></div>
                                              </div>
                                          </td>
                                          <td class="progress-cell">
                                              <a href="/management/chouzi/pminfo?id=<?php /*echo $value['id'];*/?>" target="_blank">查看基本信息&gt;&gt;</a>
                                          </td>
                                      </tr>
                                  <?php /*}*/?>
                                  </tbody>
                              </table>
                          </div>
                      </div>-->
                      <!-- /tile body -->


                  <!--<div>
                      <select id="tongji_type" class="form-control" >
                          <option class="form-control"  value ="1" <?php /*if($this->tongji_type ==1 ){echo 'selected="selected"';}*/?>>年度筹资金额统计</option>
                          <option class="form-control"  value ="2" <?php /*if($this->tongji_type ==2 ){echo 'selected="selected"';}*/?>>年度使用金额统计</option>
                      </select>
                  </div>
                  <script type="text/javascript" src="/include/management/js/echarts.min.js"></script>
                  <section class="tile color transparent-white">
                      <div id="zhouzi_main" style="width: 100%;height:400px ;"></div>
                      <?php /*if($this->tongji_type == 1){
                          $type = '筹资';
                      }else{
                          $type = '使用';
                      }*/?>
                      <script type="text/javascript">
                          // 基于准备好的dom，初始化echarts实例
                          var myChart = echarts.init(document.getElementById('zhouzi_main'));

                          // 指定图表的配置项和数据
                          var option = {
                              title: {
                                  text: '（万元）'
                              },
                              tooltip : {
                                  trigger: 'axis'
                              },
                              legend: {
                                  data:[<?php /*foreach($this->rs_year as $key => $value){
                                        if($key == count($value) - 1){
                                            echo "'".$key."年度".$type."金额'";
                                        }else {
                                            echo "'".$key."年度".$type."金额'".",";
                                        }
                                  }*/?>'过往三年平均筹资金额']
                              },
                              toolbox: {
                                  feature: {
                                      saveAsImage: {}
                                  }
                              },
                              grid: {
                                  left: '3%',
                                  right: '4%',
                                  bottom: '3%',
                                  containLabel: true
                              },
                              xAxis : [
                                  {
                                      type : 'category',
                                      boundaryGap : false,
                                      data : ['1月', '2月', '3月', '4月', '5月', '6月','7月', '8月', '9月', '10月', '11月', '12月']
                                  }
                              ],
                              yAxis : [
                                  {
                                      type : 'value'
                                  }
                              ],
                              series : [
                                  <?php
/*                                        foreach($this->rs_year as $key => $value){
                                            echo "{
                                              name:'".$key."年度".$type."金额',
                                              type:'line',
                                              areaStyle: {normal: {}},
                                              data:[".$value['json']."]
                                          },";

                                        }
                                  */?>
                                  {
                                      name:'<?php /*echo "过往三年平均".$type."金额";*/?>',
                                      type:'line',
                                      areaStyle: {normal: {}},
                                      data:[
                                      <?php /*foreach($this->rs_avg as $key => $value){
                                            if($key == count($this->rs_avg)){
                                                echo $value;
                                            }else{
                                                echo $value.",";
                                            }
                                          }
                                      */?>]
                                  }
                              ]
                          };

                          // 使用刚指定的配置项和数据显示图表。
                          myChart.setOption(option);
                      </script>
                  </section>

                  <?php /*if(!empty($this->tixing)){*/?>
                  <section class="tile color transparent-white">

                      <div class="tile-header">
                          <h1>待办工作提醒<strong>TodoList</strong> </h1>
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>

                      <div class="tile-body">

                          <div class="panel-group accordion" id="multi-accordion">

                              <?php /*$colorarray = array(2=>'blue', 1=>'dutch',4=>'red',0=>'green',5=>'drank',3=>'default');*/?>

                              <?php /*foreach($this->tixing as $k => $v){*/?>
                              <div class="panel panel-<?php /*echo $colorarray[$k]*/?>">
                                  <div class="panel-heading">
                                      <h4 class="panel-title">
                                          <a data-toggle="collapse" href="#multicollapse<?php /*echo $v['id'];*/?>" class="collapsed">
                                              <?php /*echo $v['title'];*/?>
                                          </a>
                                      </h4>
                                  </div>
                                  <div id="multicollapse<?php /*echo $v['id'];*/?>" class="panel-collapse collapse" style="height: 0px;">
                                      <div class="panel-body">
                                          <div>开始时间：<?php /*echo $v['start_time'];*/?> - 结束时间：<?php /*echo $this->tixing[0]['end_time'];*/?></div>
                                          <div>报送部门：<?php /*echo $v['department'];*/?></div>
                                          <div>报送途径：<?php /*echo $v['tujing'];*/?></div>
                                          <div>所需材料：<?php /*echo $v['files'];*/?></div>
                                          <div>具体流程：<?php /*echo $v['process'];*/?></div>
                                      </div>
                                  </div>
                              </div>
                              <?php /*}*/?>

                          </div>

                      </div>

                  </section>
                  <?php /*}*/?>



                      <div class="tile-footer text-center">
                            <ul class="pagination pagination-sm nomargin pagination-custom">
                                <?php
/*                                    $this->page = str_replace("<a","<li><a",$this->page);
                                    $this->page = str_replace("/a>","/a></li>",$this->page);
                                    $this->page = str_replace('<span class="current">',"<li class='active'><a href='#'>",$this->page);
                                    $this->page = str_replace('</span>',"</a></li>",$this->page);
                                    echo $this->page;
                                */?>
                            </ul>
                      </div>

                  </section>-->
                  <!-- /tile -->

                <!-- tile -->
                <!--<section class="tile transparent">
                    <div class="tile-header color transparent-black textured rounded-top-corners">
                        <h1>静态统计图<strong>Statistic Chart</strong></h1>
                        <div class="controls">
                            <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                            <a href="#" class="remove"><i class="fa fa-times"></i></a>
                        </div>
                    </div>

                    <div class="tile-widget color transparent-black textured">
                        <div id="statistics-chart" class="chart statistics" style="height: 250px;"></div>
                    </div>

                    <div class="tile-body color transparent-white rounded-bottom-corners">
                        <div class="row">
                            <ul class="inline">
                                <li class="col-md-8 col-sm-12 col-xs-12 text-center">

                                <h4 class="underline text-left"><strong>Actual Statistics</strong> 访问者</h4>

                                <div class="inner-container inline">
                                    <div data-percent="100" data-size="140" class="pie-chart inline" data-scale-color="false" data-track-color="rgba(0,0,0,0)" data-bar-color="#ffffff" data-line-width="5">
                                        <div class="text-center">
                                            <i class="fa fa-usd fa-5x"></i>
                                        </div>
                                    </div>
                                    <p class="chart-overall text-center medium-thin uppercase"><span class="big-medium animate-number" data-value="6175" data-animation-duration="2500">0</span> Sales</p>
                                </div>

                                <div class="inner-container inline">
                                    <div data-percent="85" data-size="140" class="pie-chart inline" data-scale-color="false" data-track-color="rgba(0,0,0,0)" data-bar-color="rgba(0,0,0,.4)" data-line-width="5">
                                        <div class="text-center">
                                            <span><i class="fa fa-eye fa-5x color-transparent-black"></i></span>
                                        </div>
                                    </div>
                                    <p class="chart-overall text-center medium-thin uppercase color-transparent-black"><span class="big-medium animate-number" data-value="8213" data-animation-duration="2500">0</span> Visits</p>
                                </div>

                                </li>

                                <li class="col-md-4 col-sm-12 col-xs-12">
                                    <h4 class="underline"><strong>Visitors</strong> 访问者统计</h4>
                                    <ul class="progress-list">
                                        <li>
                                            <div class="details">
                                                <div class="title">Asia</div>
                                                <div class="description">来至亚洲</div>
                                            </div>
                                            <div class="status pull-right">
                                                <span class="animate-number" data-value="40" data-animation-duration="1500">0</span>%
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="progress progress-little">
                                                <div class="progress-bar progress-bar-green animate-progress-bar" data-percentage="40%" style="width: 0%;"></div>
                                            </div>
                                        </li>

                                        <li>
                                            <div class="details">
                                                <div class="title">Europe</div>
                                                <div class="description">来至欧洲</div>
                                            </div>
                                            <div class="status pull-right">
                                                <span class="animate-number" data-value="38" data-animation-duration="1000">0</span>%
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="progress progress-little">
                                                <div class="progress-bar progress-bar-cyan animate-progress-bar" data-percentage="35%" style="width: 0%;"></div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="details">
                                                <div class="title">America</div>
                                                <div class="description">来至美洲</div>
                                            </div>
                                            <div class="status pull-right">
                                                <span class="animate-number" data-value="12" data-animation-duration="800">0</span>%
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="progress progress-little">
                                                <div class="progress-bar progress-bar-amethyst animate-progress-bar" data-percentage="12%" style="width: 0%;"></div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="details">
                                                <div class="title">Africa</div>
                                                <div class="description">来至非洲</div>
                                            </div>
                                            <div class="status pull-right">
                                                <span class="animate-number" data-value="7" data-animation-duration="600">0</span>%
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="progress progress-little">
                                                <div class="progress-bar progress-bar-orange animate-progress-bar" data-percentage="7%" style="width: 0%;"></div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="details">
                                                <div class="title">Other 其他</div>
                                            </div>
                                            <div class="status pull-right">
                                                <span class="animate-number" data-value="6" data-animation-duration="400">0</span>%
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="progress progress-little">
                                                <div class="progress-bar progress-bar-red animate-progress-bar" data-percentage="6%" style="width: 0%;"></div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>-->
                <!-- /tile -->


              </div>




              <!-- /col 8 -->
              <!-- col 4 -->
              <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">

                  <!-- tile -->
                  <!--<section class="tile transparent">
                      <div class="tile-header color redbrown rounded-top-corners text-center">
                          <button class="btn pull-left btn-black-transparent" type="button"><i class="fa fa-caret-square-o-down"></i></button>
                          <h2>待办事宜 <strong>Todo List</strong></h2>
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>

                      <div class="tile-body color transparent-black rounded-bottom-corners">
                          <input type="text" placeholder="添加新任务..." class="w100p bottommargin">
                          <ul class="nolisttypes" id="todolist">
                              <?php /*foreach($this->todolist as $k => $v){*/?>
                                  <li>
                                      <div class="checkbox check-transparent">
                                          <input type="checkbox" value="<?php /*echo $v['id'];*/?>" onclick="savetodoliststatus(<?php /*echo $v['id'];*/?>,<?php /*echo $v['status'];*/?>)" <?php /*if($v['status'] == 1){echo "checked='checked'";}*/?> id="todo-0<?php /*echo $v['id'];*/?>">
                                          <label for="todo-0<?php /*echo $v['id'];*/?>"><?php /*echo $v['title'];*/?></label>
                                      </div>
                                  </li>
                              <?php /*}*/?>
                          </ul>
                      </div>
                  </section>-->
                  <!-- /tile -->

                <!-- tile -->
                  <section class="tile color transparent-black">
                      <div class="tile-header">
                          <h1><?php echo $this->years;?>年捐赠收入情况<strong>捐赠来源分析</strong></h1>
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>
                      <div class="tile-body">
                          <div id="browser-usage" style="height: 230px;" class="morris-chart"></div>
                          <ul class="inline text-center chart-legend">
                              <?php
                              $color = array('#d9544f', '#2fbbe8', '#72cae7', '#00a3d8', '#ffc100');
                              $ii = 0;
                              $donor_array = array();
                              foreach($this->income_sour_array as $key => $value){
                                  // 捐赠者类型分析
                                  if($key == '个人'){
                                      $donor_array['自然人']['counts'] += $value['counts'];
                                      $donor_array['自然人']['total'] += $value['income'];
                                  }else {
                                      $donor_array['法人']['counts'] += $value['counts'];
                                      $donor_array['法人']['total'] += $value['income'];
                                  }
                                  ?>
                                  <li><span class="badge badge-outline" style="border-color: <?php echo $color[$ii];?>"></span> <?php echo $key;?> <small> <?php echo sprintf("%.2f",$value['income']/10000);?>万元 <?php echo sprintf("%.2f",($value['income']/$this->income_sour_incomes*100));?>%</small>,</li>
                                  <?php $ii++;}?>
                          </ul>
                      </div>
                  </section>
                  <!-- /tile -->


                  <!-- tile -->
                  <section class="tile color transparent-black">
                      <div class="tile-header">
                          <h1><?php echo $this->years;?>年捐赠收入情况<strong>捐赠者类型分析</strong></h1>
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>
                      <div class="tile-body">
                          <div id="browser-usage1" style="height: 230px;" class="morris-chart"></div>
                          <ul class="inline text-center chart-legend">
                              <li><span class="badge badge-outline" style="border-color: #00a3d8"></span> 法人 <small> <?php echo sprintf("%.2f",$donor_array['法人']['total']/10000);?>万元 <?php echo sprintf("%.2f",($donor_array['法人']['total']/$this->income_sour_incomes*100));?>%</small>,</li>
                              <li><span class="badge badge-outline" style="border-color: #ffc100"></span> 自然人 <small> <?php echo sprintf("%.2f",$donor_array['自然人']['total']/10000);?>万元 <?php echo sprintf("%.2f",($donor_array['自然人']['total']/$this->income_sour_incomes*100));?>%</small>,</li>
                          </ul>
                      </div>
                  </section>
                  <!-- /tile -->


                  <!-- tile -->
                  <section class="tile color transparent-black">
                      <div class="tile-header">
                          <h1><?php echo $this->years;?>年捐赠收入情况<strong>校友个人及企业捐赠情况</strong></h1>
                          <div class="controls">
                              <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                              <a href="#" class="remove"><i class="fa fa-times"></i></a>
                          </div>
                      </div>
                      <div class="tile-body">
                          <div id="browser-usage2" style="height: 230px;" class="morris-chart"></div>
                          <ul class="inline text-center chart-legend">
                              <li><span class="badge badge-outline" style="border-color: #00a3d8"></span> 校友及校友企业捐赠 <small> <?php echo sprintf("%.2f",$this->income_pp_array[1]['income']/10000);?>万元 <?php echo sprintf("%.2f",($this->income_pp_array[1]['income']/$this->income_pp_array['incomes']*100));?>%</small>,</li>
                              <li><span class="badge badge-outline" style="border-color: #ffc100"></span> 非校友捐赠 <small> <?php echo sprintf("%.2f",$this->income_pp_array[0]['income']/10000);?>万元 <?php echo sprintf("%.2f",($this->income_pp_array[0]['income']/$this->income_pp_array['incomes']*100));?>%</small>,</li>
                          </ul>
                      </div>
                  </section>
                  <!-- /tile -->


                <!-- tile -->
                <section class="tile color transparent-black textured">
                  <div class="tile-header">
                    <h1>系统信息<strong>Server</strong></h1>
                    <div class="controls">
                      <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a>
                    </div>
                  </div>
                  <div class="tile-widget">
                    <div class="progress-list with-heading">
                      <div class="details">
                        <div class="title"><h2><i class="fa fa-hdd-o"></i> <span class="animate-number" data-value="<?php echo $this->free;?>" data-animation-duration="1600">0</span> GB</h2></div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?php echo round($this->free/$this->total*100, 2);?>" data-animation-duration="1500">0</span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black" style="margin-bottom: 5px">
                        <div class="progress-bar animate-progress-bar" data-percentage="<?php echo round($this->free/$this->total*100, 2);?>%"></div>
                      </div>
                    </div>  
                    <p class="description"><strong><?php echo $this->total;?> GB</strong> 已用 <strong class="white-text"><?php echo $this->free;?></strong> 在服务器中</p>
                  </div>
                  <div class="tile-body paddingtop">
                        <div id="serverload-chart"></div>
                  </div>
                </section>
                <!-- /tile -->

              </div>
              <!-- /col 4 -->
            </div>
            <!-- /row -->
          </div>

            <!--<div id="mmenu" class="right-panel">

            <ul class="nav nav-tabs nav-justified">
                <li class="active"><a href="#mmenu-users" data-toggle="tab"><i class="fa fa-users"></i></a></li>
                <li class=""><a href="#mmenu-history" data-toggle="tab"><i class="fa fa-clock-o"></i></a></li>
                <li class=""><a href="#mmenu-friends" data-toggle="tab"><i class="fa fa-heart"></i></a></li>
                <li class=""><a href="#mmenu-settings" data-toggle="tab"><i class="fa fa-gear"></i></a></li>
            </ul>-->

            <script src="/include/management/assets/js/jquery.js"></script>
            <script language="javascript">
                $(".menu li:eq(0)").addClass("open");
            </script>

            <script type="text/javascript">
            $("#tongji_type").change(function(){
                var tj_type = $(this).val();
                    self.location='/management/index'+'?tongji_type='+tj_type;
                });
                function savetodoliststatus(id,status){
                    $.ajax({
                        url:'/management/index/savetodolist?id='+id,
                        type:'POST', //GET
                        async:true,    //或false,是否异步
                        data:{
                            status:status
                        },
                        timeout:5000,    //超时时间
                        dataType:'json',    //返回的数据格式：json/xml/html/script/jsonp/text
                        success:function(data,textStatus,jqXHR){
                            window.location.reload();
                        },
                        error:function(xhr,textStatus){

                        },
                        complete:function(){

                        }
                    });
                window.location.reload();
            }
            </script>
