<!-- content main container -->
          <div class="main">

            <!-- cards -->
            <div class="row cards">
              
              <div class="card-container col-lg-3 col-sm-6 col-sm-12">
                <div class="card card-redbrown hover">
                  <div class="front"> 

                    <div class="media">        
                      <span class="pull-left">
                        <i class="fa fa-tachometer media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>未认领项目</small>
                        <h2 class="media-heading animate-number" data-value="<?php echo count($this->renling_weirenling_list);?>" data-animation-duration="1500"><?php echo count($this->renling_weirenling_list);?></h2>
                      </div>
                    </div> 

                    <div class="progress-list">
                      <div class="details">
                        <div class="title">本月完成计划  %</div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="83" data-animation-duration="1500">0</span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black">
                        <div class="progress-bar animate-progress-bar" data-percentage="83%"></div>
                      </div>
                    </div>

                  </div>
                  <div class="back">
                    <a href="#">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>点击查看详情</span>
                    </a>  
                  </div>
                </div>
              </div>


              <div class="card-container col-lg-3 col-sm-6 col-sm-12">
                <div class="card card-blue hover">
                  <div class="front">        
                    
                    <div class="media">                  
                      <span class="pull-left">
                        <i class="fa fa-shopping-cart media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>捐赠项目总数</small>
                        <h2 class="media-heading animate-number" data-value="<?php echo $this->pm_count;?>" data-animation-duration="1500"><?php echo $this->pm_count;?></h2>
                      </div>
                    </div> 

                    <div class="progress-list">
                      <div class="details">
                        <div class="title">本月完成计划  %</div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="10" data-animation-duration="1500"><?php echo $this->pm_count;?></span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black">
                        <div class="progress-bar animate-progress-bar" data-percentage="100%"></div>
                      </div>
                    </div>

                  </div>
                  <div class="back">
                    <a href="#">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>点击查看详情</span>
                    </a>
                  </div>
                </div>
              </div>



              <div class="card-container col-lg-3 col-sm-6 col-sm-12">
                <div class="card card-greensea hover">
                  <div class="front">        
                    
                    <div class="media">
                      <span class="pull-left">
                        <i class="fa fa-usd media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>捐赠项目金额</small>
                        <h2 class="media-heading animate-number" data-value="<?php echo $this->allsum;?>" data-animation-duration="1500">allsum</h2>
                      </div>
                    </div>

                    <div class="progress-list">
                      <div class="details">
                        <div class="title">本月完成计划  %</div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="42" data-animation-duration="1500">0</span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black">
                        <div class="progress-bar animate-progress-bar" data-percentage="42%"></div>
                      </div>
                    </div>

                  </div>
                  <div class="back">
                    <a href="#">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>点击查看详情</span>
                    </a>
                  </div>
                </div>
              </div>


              <div class="card-container col-lg-3 col-sm-6 col-xs-12">
                <div class="card card-slategray hover">
                  <div class="front"> 

                    <div class="media">                   
                      <span class="pull-left">
                        <i class="fa fa-eye media-object"></i>
                      </span>

                      <div class="media-body">
                        <small>会议活动</small>
                        <h2 class="media-heading animate-number" data-value="<?php echo $this->meeting_count;?>" data-animation-duration="1500"><?php echo $this->meeting_count;?></h2>
                      </div>
                    </div> 

                    <div class="progress-list">
                      <div class="details">
                        <div class="title">本月完成计划  %</div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="1" data-animation-duration="1500">0</span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black">
                        <div class="progress-bar animate-progress-bar" data-percentage="15%"></div>
                      </div>
                    </div>

                  </div>
                  <div class="back">
                    <a href="#">
                      <i class="fa fa-bar-chart-o fa-4x"></i>
                      <span>点击查看详情</span>
                    </a>
                  </div>
                </div>
              </div>


            </div>
            <!-- /cards -->
            
            


            <!-- row -->
            <div class="row">

              <!-- col 8 -->
              <div class="col-lg-8 col-md-12">

                <!-- tile -->
                <section class="tile transparent">

                  <!-- tile header -->
                  <div class="tile-header color transparent-black textured rounded-top-corners">
                    <h1><strong>Statistic Chart</strong> 静态统计图</h1>
                    <div class="controls">
                      <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a>
                    </div>
                  </div>
                  <!-- /tile header -->

                  <!-- tile widget -->
                  <div class="tile-widget color transparent-black textured">
                    <div id="statistics-chart" class="chart statistics" style="height: 250px;"></div>
                  </div>
                  <!-- /tile widget -->


                  <!-- tile body -->
                  <div class="tile-body color transparent-white rounded-bottom-corners">
                    <div class="row">
                      <ul class="inline">

                        <li class="col-md-8 col-sm-12 col-xs-12 text-center">

                          <h4 class="underline text-left"><strong>Actual Statistics</strong> 访问者</h4>

                          <div class="inner-container inline">
                            <div data-percent="100" data-size="140" class="pie-chart inline" data-scale-color="false" data-track-color="rgba(0,0,0,0)" data-bar-color="#ffffff" data-line-width="5">
                              <div class="text-center">
                                <i class="fa fa-usd fa-5x"></i>
                              </div>
                            </div>
                            <p class="chart-overall text-center medium-thin uppercase"><span class="big-medium animate-number" data-value="6175" data-animation-duration="2500">0</span> Sales</p>
                          </div>


                          <div class="inner-container inline">
                            <div data-percent="85" data-size="140" class="pie-chart inline" data-scale-color="false" data-track-color="rgba(0,0,0,0)" data-bar-color="rgba(0,0,0,.4)" data-line-width="5">
                              <div class="text-center">
                                <span><i class="fa fa-eye fa-5x color-transparent-black"></i></span>
                              </div>
                            </div>
                            <p class="chart-overall text-center medium-thin uppercase color-transparent-black"><span class="big-medium animate-number" data-value="8213" data-animation-duration="2500">0</span> Visits</p>
                          </div>

                        </li>

                        <li class="col-md-4 col-sm-12 col-xs-12">
                          <h4 class="underline"><strong>Visitors</strong> 访问者统计</h4>
                          <ul class="progress-list">
                            <li>
                              <div class="details">
                                <div class="title">Asia</div>
                                <div class="description">来至亚洲</div>
                              </div>
                              <div class="status pull-right">
                                <span class="animate-number" data-value="40" data-animation-duration="1500">0</span>%
                              </div>
                              <div class="clearfix"></div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-green animate-progress-bar" data-percentage="40%" style="width: 0%;"></div>
                              </div>
                            </li>
                            <li>
                              <div class="details">
                                <div class="title">Europe</div>
                                <div class="description">来至欧洲</div>
                              </div>
                              <div class="status pull-right">
                                 <span class="animate-number" data-value="38" data-animation-duration="1000">0</span>%
                              </div>
                              <div class="clearfix"></div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-cyan animate-progress-bar" data-percentage="35%" style="width: 0%;"></div>
                              </div>
                            </li>
                            <li>
                              <div class="details">
                                <div class="title">America</div>
                                <div class="description">来至美洲</div>
                              </div>
                              <div class="status pull-right">
                                <span class="animate-number" data-value="12" data-animation-duration="800">0</span>%
                              </div>
                              <div class="clearfix"></div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-amethyst animate-progress-bar" data-percentage="12%" style="width: 0%;"></div>
                              </div>
                            </li>
                            <li>
                              <div class="details">
                                <div class="title">Africa</div>
                                <div class="description">来至非洲</div>
                              </div>
                              <div class="status pull-right">
                                <span class="animate-number" data-value="7" data-animation-duration="600">0</span>%
                              </div>
                              <div class="clearfix"></div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-orange animate-progress-bar" data-percentage="7%" style="width: 0%;"></div>
                              </div>
                            </li>
                            <li>
                              <div class="details">
                                <div class="title">Other 其他</div>
                              </div>
                              <div class="status pull-right">
                                <span class="animate-number" data-value="6" data-animation-duration="400">0</span>%
                              </div>
                              <div class="clearfix"></div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-red animate-progress-bar" data-percentage="6%" style="width: 0%;"></div>
                              </div>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <!-- /tile body -->



                </section>
                <!-- /tile -->



                <!-- tile -->
                <section class="tile color transparent-black">




                  <!-- tile header -->
                  <!--<div class="tile-header">
                    <h1><strong>Projects  Progress</strong> 项目进程</h1>
                    <div class="search">
                      <input type="text" placeholder="Search...">
                    </div>
                    <div class="controls">
                      <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a>
                    </div>
                  </div>-->
                  <!-- /tile header -->


                  <!-- tile body -->
                  <!--<div class="tile-body no-vpadding">
                    <div class="table-responsive">
                      <table class="table table-custom table-sortable nomargin">
                        <thead>
                          <tr>
                            <th class="sortable sort-numeric sort-asc">ID</th>
                            <th class="sortable sort-alpha">Project</th>
                            <th class="sortable">Priority</th>
                            <th class="sortable sort-amount">Status</th>
                            <th class="text-right">Chart</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>1</td>
                            <td>Graphic Layout for client</td>
                            <td class="color-red priority">High priority</td>
                            <td class="progress-cell">
                              <div class="progress-info">
                                <div class="percent"><span class="animate-number" data-value="50" data-animation-duration="1500">0</span>%</div>
                              </div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-transparent-white animate-progress-bar" data-percentage="50%"></div>
                              </div>
                            </td>
                            <td class="text-right"><span id="projectbar1">87,85,42,90,70,55,82,68</span></td>
                          </tr>
                          <tr>
                            <td>2</td>
                            <td>Make website responsive</td>
                            <td class="color-green priority">Low priority</td>
                            <td class="progress-cell">
                              <div class="progress-info">
                                <div class="percent"><span class="animate-number" data-value="13" data-animation-duration="1500">0</span>%</div>
                              </div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-transparent-white animate-progress-bar" data-percentage="13%"></div>
                              </div>
                            </td>
                            <td class="text-right"><span id="projectbar2">87,99,52,93,42,86,51,93</span></td>
                          </tr>
                          <tr>
                            <td>3</td>
                            <td>Clean css/html/js code</td>
                            <td class="color-red priority">High priority</td>
                            <td class="progress-cell">
                              <div class="progress-info">
                                <div class="percent"><span class="animate-number" data-value="76" data-animation-duration="1500">0</span>%</div>
                              </div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-transparent-white animate-progress-bar" data-percentage="76%"></div>
                              </div>
                            </td>
                            <td class="text-right"><span id="projectbar3">74,77,82,91,69,63,46,42</span></td>
                          </tr>
                          <tr>
                            <td>4</td>
                            <td>Database Optimization</td>
                            <td class="color-orange priority">Normal priority</td>
                            <td class="progress-cell">
                              <div class="progress-info">
                                <div class="percent"><span class="animate-number" data-value="38" data-animation-duration="1500">0</span>%</div>
                              </div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-transparent-white animate-progress-bar" data-percentage="38%"></div>
                              </div>
                            </td>
                            <td class="text-right"><span id="projectbar4">52,45,76,74,77,57,65,86</span></td>
                          </tr>
                          <tr>
                            <td>5</td>
                            <td>Database Migration</td>
                            <td class="color-green priority">Low priority</td>
                            <td class="progress-cell">
                              <div class="progress-info">
                                <div class="percent"><span class="animate-number" data-value="9" data-animation-duration="1500">0</span>%</div>
                              </div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-transparent-white animate-progress-bar" data-percentage="9%"></div>
                              </div>
                            </td>
                            <td class="text-right"><span id="projectbar5">53,70,47,96,62,49,69,55</span></td>
                          </tr>
                          <tr>
                            <td>6</td>
                            <td>Email server backup</td>
                            <td class="color-orange priority">Normal priority</td>
                            <td class="progress-cell">
                              <div class="progress-info">
                                <div class="percent"><span class="animate-number" data-value="29" data-animation-duration="1500">0</span>%</div>
                              </div>
                              <div class="progress progress-little">
                                <div class="progress-bar progress-bar-transparent-white animate-progress-bar" data-percentage="29%"></div>
                              </div>
                            </td>
                            <td class="text-right"><span id="projectbar6">69,80,85,96,67,58,75,82</span></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>-->
                  <!-- /tile body -->


                  <!-- tile footer -->
                  <!--<div class="tile-footer text-center">
                    <ul class="pagination pagination-sm nomargin pagination-custom">
                      <li class="disabled"><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                      <li class="active"><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li><a href="#">5</a></li>
                      <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                    </ul>
                  </div>-->
                  <!-- /tile footer -->



                </section>
                <!-- /tile -->


              </div>
              <!-- /col 8 -->



              <!-- col 4 -->
              <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                



                <!-- tile -->
                <section class="tile color transparent-black textured">




                  <!-- tile header -->
                  <div class="tile-header">
                    <h1><strong>Server</strong> 系统信息</h1>
                    <div class="controls">
                      <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a>
                    </div>
                  </div>
                  <!-- /tile header -->

                  <!-- tile widget -->
                  <div class="tile-widget">
                    <div class="progress-list with-heading">
                      <div class="details">
                        <div class="title"><h2><i class="fa fa-hdd-o"></i> <span class="animate-number" data-value="<?php echo $this->free;?>" data-animation-duration="1600">0</span> GB</h2></div>
                      </div>
                      <div class="status pull-right bg-transparent-black-1">
                        <span class="animate-number" data-value="<?php echo round($this->free/$this->total*100, 2);?>" data-animation-duration="1500">0</span>%
                      </div>
                      <div class="clearfix"></div>
                      <div class="progress progress-little progress-transparent-black" style="margin-bottom: 5px">
                        <div class="progress-bar animate-progress-bar" data-percentage="<?php echo round($this->free/$this->total*100, 2);?>%"></div>
                      </div>
                    </div>  
                    <p class="description"><strong><?php echo $this->total;?></strong> 已用 <strong class="white-text"><?php echo $this->free;?></strong> 在服务器中</p>
                  </div>
                  <!-- /tile widget -->


                  <!-- tile body -->
                  <div class="tile-body paddingtop">
                    <div id="serverload-chart"></div>
                  </div>
                  <!-- /tile body -->
                


                </section>
                <!-- /tile -->


                <!-- tile -->
                <section class="tile color transparent-black">



                  <!-- tile header -->
                  <div class="tile-header">
                    <h1><strong>Browser</strong> 浏览器使用</h1>
                    <div class="controls">
                      <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a>
                    </div>
                  </div>
                  <!-- /tile header -->

                  <!-- tile body -->
                  <div class="tile-body">
                    <div id="browser-usage" style="height: 230px;" class="morris-chart"></div>
                    <ul class="inline text-center chart-legend">
                      <li><span class="badge badge-outline" style="border-color: #00a3d8"></span> Chrome <small>25%</small>,</li>
                      <li><span class="badge badge-outline" style="border-color: #1693A5"></span> Other <small>10%</small>,</li>
                      <li><span class="badge badge-outline" style="border-color: #2fbbe8"></span> Safari <small>5%</small>,</li>
                      <li><span class="badge badge-outline" style="border-color: #72cae7"></span> Firefox <small>15%</small>,</li>
                      <li><span class="badge badge-outline" style="border-color: #ffc100"></span> Internet Explorer <small>40%</small>,</li>
                      <li><span class="badge badge-outline" style="border-color: #d9544f"></span> Opera <small>5%</small></li>
                    </ul>
                  </div>
                  <!-- /tile body --> 




                </section>
                <!-- /tile -->



                <!-- tile -->
                <section class="tile transparent">




                  <!-- tile header -->
                  <!--<div class="tile-header color redbrown rounded-top-corners text-center">
                    <button class="btn pull-left btn-black-transparent" type="button"><i class="fa fa-caret-square-o-down"></i></button>
                    <h2><strong>Todo List</strong> 代办事宜</h2>
                    <div class="controls">
                      <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                      <a href="#" class="remove"><i class="fa fa-times"></i></a>
                    </div>
                  </div>-->
                  <!-- /tile header -->

                  <!-- tile body -->
                  <!--<div class="tile-body color transparent-black rounded-bottom-corners">
                    <input type="text" placeholder="添加新任务..." class="w100p bottommargin">
                    <ul class="nolisttypes" id="todolist">
                      <li>
                        <div class="checkbox check-transparent">
                          <input type="checkbox" value="1" id="todo-01">
                          <label for="todo-01">日常备份</label>
                        </div>
                      </li>
                      <li>
                        <div class="checkbox check-transparent">
                          <input type="checkbox" checked="checked" value="1" id="todo-02">
                          <label for="todo-02" class="done">给领导发送简报</label>
                        </div>
                      </li>
                      <li>
                        <div class="checkbox check-transparent">
                          <input type="checkbox" value="1" id="todo-03">
                          <label for="todo-03">购买办公用品</label>
                        </div>
                      </li>
                      <li>
                        <div class="checkbox check-transparent">
                          <input type="checkbox" value="1" id="todo-04">
                          <label for="todo-04">购买回馈礼品</label>
                        </div>
                      </li>
                      <li>
                        <div class="checkbox check-transparent">
                          <input type="checkbox" value="1" id="todo-05">
                          <label for="todo-05">拜访客户</label>
                        </div>
                      </li>
                      <li>
                        <div class="checkbox check-transparent">
                          <input type="checkbox" value="1" id="todo-06">
                          <label for="todo-06">制作新简报</label>
                        </div>
                      </li>
                    </ul>
                  </div>-->
                  <!-- /tile body -->
                


                </section>
                <!-- /tile -->


              </div>
              <!-- /col 4 -->
              
              
            </div>
            <!-- /row -->


            <!-- row -->
            <div class="row">









            </div>
            <!-- /row -->  



          </div>
          <!-- /content container -->






        </div>
        <!-- Page content end -->




        <div id="mmenu" class="right-panel">
          <!-- Nav tabs -->
          <ul class="nav nav-tabs nav-justified">
            <li class="active"><a href="#mmenu-users" data-toggle="tab"><i class="fa fa-users"></i></a></li>
            <li class=""><a href="#mmenu-history" data-toggle="tab"><i class="fa fa-clock-o"></i></a></li>
            <li class=""><a href="#mmenu-friends" data-toggle="tab"><i class="fa fa-heart"></i></a></li>
            <li class=""><a href="#mmenu-settings" data-toggle="tab"><i class="fa fa-gear"></i></a></li>
          </ul>
              
