<!DOCTYPE html>
<html>
  <head>
    <title>高校教育发展基金会 - 项目管理系统后台登录</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />
	<base href="/include/management/"> 

    <link rel="icon" type="image/ico" href="assets/images/favicon.ico" />
    <!-- Bootstrap -->
    <link href="assets/css/vendor/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/vendor/bootstrap-checkbox.css">
    <link href="assets/css/minimal.css" rel="stylesheet">
	
	
	<link href="assets/css/normalize.css" rel="stylesheet">
	<link href="assets/css/default.css" rel="stylesheet">
	<link href="assets/css/demo.css" rel="stylesheet">
	<link href="assets/css/fakeLoader.css" rel="stylesheet">
	

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
	
	<script src="js/jquery.min.js"></script>
	<script src="js/fakeLoader.min.js"></script>

	
  </head>
  <body class="bg-1">
 
	<div class="fakeloader"></div>
 
    <!-- Wrap all page content here -->
    <div id="wrap">
      <!-- Make page fluid -->
      <div class="row">
        <!-- Page content -->
        <div id="content" class="col-md-12 full-page login">


          <div class="inside-block">
            <!--<img src="assets/images/logo-big.png" alt class="logo">-->
            <h1><strong>Welcome</strong> </h1>
            <h5>高校教育发展基金会</h5>

            <form id="form-signin" class="form-signin" action="/management/index/login" method="post">
              <section>
                <div class="input-group">
                  <input type="text" class="form-control" name="user_name" placeholder="管理员账号">
                  <div class="input-group-addon"><i class="fa fa-user"></i></div>
                </div>
                <div class="input-group">
                  <input type="password" class="form-control" name="user_password" placeholder="密码">
                  <div class="input-group-addon"><i class="fa fa-key"></i></div>
                </div>
                  <div class="input-group">
                      <input type="text" class="form-control" name="code" />
                      <!--<button type="button" onClick="create_code()">更换</button>-->
                      <div class="input-group-addon"><img id="code" src="create_code.php" alt="看不清楚，换一张" style="cursor: pointer; vertical-align:middle;" onClick="create_code()"/></div>
                  </div>
              </section>
              <!--<section class="controls">
                <div class="checkbox check-transparent">
                  <input type="checkbox" value="1" id="remember" checked>
                  <label for="remember">Remember me</label>
                </div>
                <a href="#">Forget password?</a>
              </section>-->
              <section class="log-in">
                <button class="btn btn-dutch" onclick="submit();">登 录</button>
               <!-- <span>or</span>
                <button class="btn btn-slategray" onclick="reset();">重 置</button>-->
                <a href="javascript:void(0);">不记得密码了？请点击忘记密码</a>
              </section>
            </form>
          </div>


        </div>
        <!-- /Page content -->  
      </div>
    </div>
    <!-- Wrap all page content end -->
  </body>
</html>

<script>
    function create_code(){
        document.getElementById('code').src = '/include/management/create_code.php?'+Math.random()*10000;
    }
</script>

<!--<script>
    $(document).ready(function(){
        $(".fakeloader").fakeLoader({
            timeToHide:2500,
            bgColor:"#fff",
            imagePath:"images/login_title.gif"
        });
    });
</script>-->