<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加资金信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目资金管理</li>
            <li class="active">添加电子协议信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-12">
			<section class="tile color transparent-black">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" action="savesign" method="post" encType="multipart/form-data">
				<div class="form-group">
			  	<label class="col-sm-2 control-label" for="input01">项目名称：</label>
                    <div class="col-sm-4">
                	    <input name="pname" type="text" value="<?php echo $this->signifo[0]['pname']?>" readonly="readonly"/>
                        <input name="pm_id" type="hidden" value="<?php echo $this->signifo[0]['id']?>" readonly="readonly"/>
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">项目签约日期：</label>
                    <div class="col-sm-4">
                        <input type="text" size="14" name="sign_time" id="datepicker" data-date-format="YYYY-MM-DD HH:mm:ss" class="form-control">
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">项目电子协议签约：</label>
                    <div class="col-sm-4">
                        <input name="sign_files" type="file" value="" />
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>
					
                <div class="form-group form-footer">
                    <div class="col-sm-offset-5 col-sm-7">
                        <input class="btn btn-primary"  type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                        <input class="btn btn-default" type="reset" value="重 置" />
                    </div>
                </div>
			</form>
            </div>
            </section>
		  </div>
		</div>

        <script language="javascript">
            $(".menu li:eq(0)").addClass("open");
        </script>