<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>来款认领</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目进度管理</li>
            <li class="active">来款认领</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">

			<section class="tile color transparent-black">
				<div class="tile-body nopadding">
                    <form method="post" action="">
                        <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                         <thead>
                              <tr>
                                    <td width="30%">栏目名称</td>
                                    <td width="70%">明细</td>
                              </tr>
                        </thead>
                        <tbody>





                            <!-- 项目相关 start-->
                            <tr>
                                <td>认领到项目：</td>
                                <td>
                                    <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                        <option value="1">请选择项目名称</option>
                                        <?php if($this->pmlist != ""){
                                            foreach ($this->pmlist as $k => $v){
                                                ?>
                                                <option value="<?php echo $v['id'];?>"><?php echo $v['pname'];?></option>
                                            <?php }}?>
                                    </select>
                                    <input id="pname_info" type="hidden" name="pname" value=""/>
                                </td>
                            </tr>

                            <tr>
                                <td>财务系统对应项目：</td>
                                <td id="zw_xm"><input type="text" id="zw_xmmc" name="zw_xmmc" readonly="readonly"/></td>
                                <input type="hidden" name="zw_xmbh" id="zw_xmbh"/>
                            </tr>
                            <!-- 项目相关 end-->






                            <!-- 部门相关信息 start-->
                            <tr>
                                <td>认领到部门：</td>
                                <td>
                                    <select class="chosen-select-1 chosen-transparent form-control" id="department">
                                        <?php if($this->department_list != ""){
                                            foreach ($this->department_list as $k => $v){
                                                ?>
                                                <option value="<?php echo $v['id'];?>"><?php echo $v['pname'];?></option>
                                            <?php }}?>
                                    </select>
                                    <input id="department_id" type="hidden" name="department_id" value=""/>
                                </td>
                            </tr>

                            <tr>
                                <td>财务系统对应部门：</td>
                                <td id="zw_bm"><input class="form-control" type="text" id="zw_bmmc" name="zw_bmmc" readonly="readonly"/></td>
                                <input type="hidden" name="zw_bmbh" id="zw_bmbh"/>
                            </tr>

                            <!-- 部门相关信息  end-->





                            <tr>
                                <td>认领负责人：</td>
                                <td>
                                    <input name="fzr" type="text"/>
                                </td>
                            </tr>
                            <tr>
                                <td>来款单位：</td>
                                <td><input name="lkdw" type="text" readonly="readonly" value="<?php echo $this->zw_lkrl_logs[0]['fkdw'];?>"/></td>
                            </tr>
                            <tr>
                                <td>来款金额：</td>
                                <td><input name="je" type="text" readonly="readonly" value="<?php echo $this->pm_mg_info[0]['zijin_daozheng_jiner'];?>"/> 元</td>
                            </tr>
                            <tr>
                                <td>来款日期：</td>
                                <td><input name="lkrq" type="text" readonly="readonly" value="<?php echo $this->pm_mg_info[0]['zijin_daozhang_datetime'];?>"/> </td>
                            </tr>

                            <tr>
                                <td>来款日期：</td>
                                <td><input name="lkrq" type="text" readonly="readonly" value="<?php echo $this->pm_mg_info[0]['zijin_daozhang_datetime'];?>"/> </td>
                            </tr>

                            <tr>
                                <td>补充其它信息：</td>
                                <td></td>
                            </tr>

                            <tr>
                                <td>捐赠方类型：</td>
                                <td></td>
                            </tr>

                            <tr>
                                <td>资金来源渠道：</td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>选择进度：</td>
                                <td></td>
                            </tr>

                            <tr>
                                <td>发票状态：</td>
                                <td></td>
                            </tr>

                            <tr>
                                <td>添加发票信息：</td>
                                <td></td>
                            </tr>

                        </tbody>

                        <table>
                        <tr>
                            <input type="submit" value="点击认领" class="btn btn-primary btn-block">
                        </tr>
                        </table>
                    </form>
				 </div>
				 </section>
		  </div>
		</div>


        <script language="javascript">
            $(".menu li:eq(0)").addClass("open");

            $(document).ready(function(){
                $("#pname").change(function(){
                    GetZWxm($(this).children('option:selected').val());
                });
            });

            function GetZWxm(pm_id){
                $.ajax({
                    type:'post',
                    url: '/management/zijin/ajaxgetzwxm?pm_id='+pm_id,
                    data:{},
                    cache:false,
                    dataType:'json',
                    success:function(data){
                        if( data != null)
                        {
                            //console.log(data);
                            $("#zw_xmbh").val(data.zw_xmbh);
                            $("#zw_xmmc").val(data.zw_xmmc);
                        }else {
                            alert("对不起，没有对应财务系统项目，请添加对照关系后认领");
                            $("#zw_xmbh").attr("value","");
                            $("#zw_xmmc").attr("value","");'' +
                            alert($("#zw_xmmc").val());
                        }
                    },
                    error:function(){}
                });
            }

            function GetZWbm(){
                var pm_pid = $("#pm_pid").val();
                $.ajax({
                    type:'post',
                    url: '/management/zijin/ajaxgetzwbm?pm_pid='+pm_pid,
                    data:{},
                    cache:false,
                    dataType:'json',
                    success:function(data){
                        if( data != "")
                        {
                            $("#zw_bm").html(data['html']);
                        }
                    },
                    error:function(){}
                });
            }
        </script>
