<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>认领列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目进度管理</li>
            <li class="active">认领列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
			<section class="tile color transparent-black">
			<div class="tile-body">

                <form action="#" method="get">
                    <div class="form-group">

                        <div class="row">
                            <div class="form-group col-sm-4">
                                <label for="input05">项目名称：</label>
                                <input type="text" class="form-control" name="pm_name" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-sm-3">
                                <label for="input01">是否已认领：</label>
                                <select name="is_renling" class="form-control">
                                    <option value="0">未认领</option>
                                    <option value="1">已认领</option>
                                </select>
                            </div>
                            <div class="form-group col-sm-3">
                                <label for="input02"> </label>
                                <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                            </div>
                        </div>
                        <span class="col-sm-3" >* 默认按照来款日期倒序排序 </span>
                    </div>
                </form>

			</div>
			</section>
			<section class="tile color transparent-black">
				<div class="tile-body nopadding">
				<?php if($this->claimlist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="24%">项目名称</td>
						<td width="12%">来款方</td>
                          <td width="18%">到帐日期</td>
						<td width="20%">到帐金额</td>
						<!--<td width="13%">协议捐赠金额</td>-->
						<td width="13%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php 
						foreach($this->claimlist as $k=>$v){?>
						 <tr>
						 	<td>
                                <?php echo $v['pm_name'];?>&nbsp;
                            </td>
                             <td>
                                 <?php echo $v['pm_pp'];?>
                             </td>
                             <td>
                                 <?php echo $v['zijin_daozhang_datetime'];?>
                             </td>
                             <td>
                                 <?php echo $v['zijin_daozheng_jiner'];?> 元
                             </td>
							<td>
                                <?php if($this->is_renling == 0){?>
                                <a onclick="javascript:noTips_click(<?php echo $v['id'];?>);">
                                    <button class="btn btn-greensea margin-bottom-20" type="button">认领项目</button>
                                </a>

                                <a onclick="javascript:delete_click(<?php echo $v['lsh'];?>);">
                                    <button class="btn btn-red margin-bottom-20" type="button">删除</button>
                                </a>

                                <?php }else{ ?>
                                    <a href="/management/zijin/editzijin?id=<?php echo $v['id'];?>">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">编辑</button>
                                    </a>
                                <?php }?>
                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer bg-transparent-black-2">
					<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条项目认领信息          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无网站资讯！</div>
				 <?php }?>
				 </div>
				 </div>
				 </section>
		  </div>
		</div>

        <script>
            var pm_id;
            function noTips_click(pm_id){
                if(confirm("确定要认领该笔款项吗？认领将不能修改。")) {
                    location.href = "/management/zijin/binding-claim?lsh="+lsh;
                    /*$.ajax({
                        type: 'get',
                        url: "/management/zijin/binding-claim",
                        data: "pm_id=" + pm_id,
                        cache: false,
                        dataType: 'json',
                        success: function (data) {
                            $('.theme-popover-mask').fadeIn(100);
                            $('.theme-popover').slideDown(200);
                            $('#popover-msg').html(data['msg']);
                            if (data['return_url'] != '') {
                                $('#popover-close').attr("name", data['return_url']);
                            }
                            if (data['error'] != true) {
                                $('#popover-img img').attr("src", "/include/management/images/yes.png");
                            }
                        },
                        complete: function (data) {

                        },
                        error: function (data) {
                            $('.theme-popover-mask').fadeIn(100);
                            $('.theme-popover').slideDown(200);
                            $('#popover-msg').html(data['msg']);
                        }
                    });*/
                }
            }

            function delete_click(pm_id){
                if(confirm("确定要删除该笔款项吗？删除将不能找回。")) {
                    location.href = "/management/zijin/del-claim?pm_id="+pm_id;
                }
            }

            jQuery(document).ready(function($) {
                $('.theme-poptit .close').click(function(){
                    $('.theme-popover-mask').fadeOut(100);
                    $('.theme-popover').slideUp(200);
                    if($('#popover-close').attr("name") != '') {
                        location.href = $('#popover-close').attr("name");
                    }
                });
            });
        </script>

		
		    <script language="javascript">
                $(".menu li:eq(0)").addClass("open");
			</script>
