<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>
	
    <!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑资金信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目资金管理</li>
            <li class="active">编辑资金信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	<div id="main" class="main">
		<div id="rightstyle02" class="row">
        <div class="col-md-12">
        	<section class="tile color transparent-white">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" id="form1" action="editrszijin" method="post" encType="multipart/form-data">

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">项目名称：</label>
                    <div class="col-sm-4">
                        <select class="chosen-select-1 chosen-transparent form-control" name="pname">
                            <?php if($this->pmlist != ""){
                                foreach ($this->pmlist as $k => $v){
                                    ?>
                                    <option value="<?php echo $v['pname'];?>" <?php if($v['pname'] == $this->zijin[0]['pm_name']){echo "selected='selected'";}?>><?php echo $v['pname'];?></option>
                                <?php }}?>
                        </select>
                        <input id="pname_info" type="hidden" name="pname" value=""/>
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">捐赠到账金额：</label>
                    <div class="col-sm-4">
                        <input class="form-control" type="text"  value="<?php echo $this->zijin[0]['zijin_daozheng_jiner'];?>" name="zijin_daozheng_jiner"  size="14"/>
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">选择进度：</label>
                    <div class="col-sm-4">
                        <input name="jindu" type="checkbox" value="1" <?php if($this->zijin[0]['jindu']) echo "checked='checked'";?>/>已到帐
                    </div>
                    <!--<span class="col-sm-2" > * </span>-->
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input00">捐赠者类型：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="pm_pp_cate">
                            <option value="" >请选择类型</option>
                            <option value="个人" <?php if($this->zijin[0]['pm_pp_cate']=='个人'){echo "selected='selected'";}?>>个人</option>
                            <option value="企业" <?php if($this->zijin[0]['pm_pp_cate']=='企业'){echo "selected='selected'";}?>>企业</option>
                            <option value="事业单位" <?php if($this->zijin[0]['pm_pp_cate']=='事业单位'){echo "selected='selected'";}?>>事业单位</option>
                            <option value="基金会" <?php if($this->zijin[0]['pm_pp_cate']=='基金会'){echo "selected='selected'";}?>> 基金会</option>
                            <option value="其他组织" <?php if($this->zijin[0]['pm_pp_cate']=='其他组织'){echo "selected='selected'";}?>>其他组织</option>
                        </select>
                    </div>
                    <span class="col-sm-2" >* 个人、企业、事业单位、基金会、其他组织</span>
                </div>

                <!--<div class="form-group">
                    <label class="col-sm-2 control-label" for="input00">项目捐赠者：</label>
                        <div class="col-sm-4">
                            <input readonly type="text" value="<?php /*echo $this->zijin[0]['pm_pp'];*/?>"  name="pm_pp"  size="14"/>
                        </div>
                    <span class="col-sm-2" >* </span>
                </div>-->

                <div class="form-group transparent-editor">
                    <label class="col-sm-2 control-label" for="input14">项目捐赠方：</label>
                    <div class="col-sm-4">
                        <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_pp[]" id="pm_pp">
                            <?php if($this->jjh_mg_pp_list != ""){
                                foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                    <option value="<?php echo $v?>" <?php
                                    if(!empty($this->zijin[0]['pm_pp'])){
                                        foreach(explode(',',$this->zijin[0]['pm_pp']) as $key => $value){
                                            if($v == $value){
                                                echo "selected='selected'";
                                            }
                                        }
                                    }?>><?php echo $v?></option>
                                <?php }}?>
                        </select>
                    </div>
                    <span class="col-sm-2 addpp" >添加人员信息</span>
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">捐赠到账日期：</label>
                    <div class="col-sm-4">
                        <input class="form-control" type="text"  value="<?php echo $this->zijin[0]['zijin_daozhang_datetime'];?>" id="datepicker" data-date-format="YYYY-MM-DD"  name="zijin_daozhang_datetime"  size="14"/>
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">资金来源渠道：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="zijin_laiyuan_qudao">
                            <option value="" >请选择类型</option>
                            <option value="境内" <?php if($this->zijin[0]['zijin_laiyuan_qudao']=='境内'){echo "selected='selected'";}?>>境内</option>
                            <option value="境外" <?php if($this->zijin[0]['zijin_laiyuan_qudao']=='境外'){echo "selected='selected'";}?>>境外</option>
                        </select>
                    </div>
                    <span class="col-sm-2" > * </span>
                </div>


                <!--<div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">项目捐赠类型：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="pm_cate">
                            <option value="" >请选择类型</option>
                            <?php /*if($this->pcatelist != ""){
                                foreach ($this->pcatelist as $k => $v){*/?>
                                    <option value="<?php /*echo $v['id']*/?>" <?php /*if($v['id'] == $this->zijin[0]['pm_juanzeng_cate']){echo "selected='selected'";}*/?>><?php /*echo $v['catename']*/?></option>
                                <?php /*}}*/?>
                        </select>
                    </div>
                    <span class="col-sm-2" >  * 教育基金、研究基金等 </span>
                </div>-->

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">票据状态：</label>
                    <div class="col-sm-4">
                        <input type="radio" name="piaoju" value="0"  <?php if ($this->zijin[0]['piaoju'] == 0)echo "checked='checked'";?>/> 未开票（默认）
                        <input type="radio" name="piaoju" value="1"  <?php if ($this->zijin[0]['piaoju'] == 1)echo "checked='checked'";?>/> 已开票
                        <input type="radio" name="piaoju" value="2"  <?php if ($this->zijin[0]['piaoju'] == 2)echo "checked='checked'";?>/> 借票
                    </div>
                </div>

                <div class="form-group addfapiao">
                    <label class="col-sm-2 control-label" for="input01">发票票号：</label>
                    <div class="col-sm-4">
                        <input size="38" name="piaoju_fph" type="text" value="<?php echo $this->zijin[0]['piaoju_fph']?>"/>
                    </div>
                </div>


                <div class="form-group addfapiao">
                    <label class="col-sm-2 control-label" for="input01">发票反馈方式：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="piaoju_fkfs">
                            <option value="1" <?php if ($this->zijin[0]['piaoju_fkfs'] == 1)echo "selected='selected'";?>>领取</option>
                            <option value="2" <?php if ($this->zijin[0]['piaoju_fkfs'] == 2)echo "selected='selected'";?>>寄送</option>
                            <option value="3" <?php if ($this->zijin[0]['piaoju_fkfs'] == 3)echo "selected='selected'";?>>暂存</option>
                        </select>
                    </div>
                </div>


                <div class="form-group addfapiao">
                    <label class="col-sm-2 control-label" for="input01">经办人：</label>
                    <div class="col-sm-4">
                        <input size="38" name="piaoju_jbr" type="text" value="<?php echo $this->zijin[0]['piaoju_jbr']?>"/>
                    </div>
                </div>


                <div class="form-group addfapiao">
                    <label class="col-sm-2 control-label" for="input01">快递单号：</label>
                    <div class="col-sm-4">
                        <input size="38" name="piaoju_kddh" type="text" value="<?php echo $this->zijin[0]['piaoju_kddh']?>"/>
                    </div>
                </div>



                <!--<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">捐赠级别：</label>
            <div class="col-sm-4">
            <select class="form-control" name="pm_juanzeng_jibie">
								<option value="" >请选择类型</option>
								<option value="校级"  <?php /*if($this->zijin[0]['pm_juanzeng_jibie']=='校级'){echo "selected='selected'";}*/?>>校级</option>
								<option value="院级"  <?php /*if($this->zijin[0]['pm_juanzeng_jibie']=='院级'){echo "selected='selected'";}*/?>>院级</option>
								<option value="其他"  <?php /*if($this->zijin[0]['pm_juanzeng_jibie']=='其他'){echo "selected='selected'";}*/?>>其他</option>
			</select>
            </div>
            <span class="col-sm-2" > * 校级、院级、其他</span>
            </div>		


					 
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">捐赠用途：</label>
            <div class="col-sm-4">
            	<select class="form-control" name="pm_juanzeng_yongtu">
								<option value="" >请选择类型</option>
								<option value="资助家庭经济困难学生" <?php /*if($this->zijin[0]['pm_juanzeng_yongtu']=='资助家庭经济困难学生'){echo "selected='selected'";}*/?>>资助家庭经济困难学生</option>
								<option value="奖励优秀学生" <?php /*if($this->zijin[0]['pm_juanzeng_yongtu']=='奖励优秀学生'){echo "selected='selected'";}*/?>>奖励优秀学生</option>
								<option value="支持毕业生就业" <?php /*if($this->zijin[0]['pm_juanzeng_yongtu']=='支持毕业生就业'){echo "selected='selected'";}*/?>>支持毕业生就业</option>
								<option value="奖励教师" <?php /*if($this->zijin[0]['pm_juanzeng_yongtu']=='奖励教师'){echo "selected='selected'";}*/?>>奖励教师</option>
								<option value="教学科研及学科发展" <?php /*if($this->zijin[0]['pm_juanzeng_yongtu']=='教学科研及学科发展'){echo "selected='selected'";}*/?>>教学科研及学科发展</option>
								<option value="学校基建项目" <?php /*if($this->zijin[0]['pm_juanzeng_yongtu']=='学校基建项目'){echo "selected='selected'";}*/?>>学校基建项目</option>
								<option value="其他指定用途" <?php /*if($this->zijin[0]['pm_juanzeng_yongtu']=='其他指定用途'){echo "selected='selected'";}*/?>>其他指定用途</option>
								<option value="非指定用途" <?php /*if($this->zijin[0]['pm_juanzeng_yongtu']=='非指定用途'){echo "selected='selected'";}*/?>>非指定用途</option>
			</select>
            </div>
            <span class="col-sm-2" > * 资助家庭经济困难学生、奖励优秀学生、支持毕业生就业、奖励教师等</span>
            </div>-->
					
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">是否是校友：</label>
            <div class="col-sm-4">
            <input type="radio" name="pm_is_school" value="1" <?php if ($this->zijin[0]['pm_is_school'] == 1)echo "checked='checked'";?>/> 是
			<input type="radio" name="pm_is_school" value="0" <?php if ($this->zijin[0]['pm_is_school'] == 0)echo "checked='checked'";?>/> 否
            </div>
           
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label" for="input01">是否申请配比状态：</label>
                <div class="col-sm-4">
                    <input  type="radio" name="peibi" value="1" <?php if ($this->zijin[0]['peibi'] == 1)echo "checked='checked'";?>  /> 是
                    <input type="radio" name="peibi" value="0" <?php if ($this->zijin[0]['peibi'] == 0)echo "checked='checked'";?> /> 否
                </div>
            </div>
					
			<!--<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">配比状态：</label>
                <div class="col-sm-4">
                    <input  type="radio" name="peibi" value="1" <?php /*if ($this->zijin[0]['peibi'] == 1)echo "checked='checked'";*/?>  onclick="javascript:change_peibi();"/> 是
                    <input type="radio" name="peibi" value="0" <?php /*if ($this->zijin[0]['peibi'] == 0)echo "checked='checked'";*/?>  onclick="javascript:change_peibi();"/> 否
                </div>
            </div>

                <div class="form-group peibi_1">
                    <label class="col-sm-2 control-label" for="input01">配比金额：</label>
                    <div class="col-sm-4">
                        <input class="form-control" value="<?php /*echo $this->zijin[0]['peibi_jiner'];*/?>" type="text" name="peibi_jiner"  size="14"/>
                    </div>
                </div>

                <div class="form-group peibi_1">
                    <label class="col-sm-2 control-label" for="input01">划拨部门：</label>
                    <div class="col-sm-4">
                        <input class="form-control" value="<?php /*echo $this->zijin[0]['peibi_department'];*/?>" type="text" name="peibi_department"  size="14"/>
                    </div>
                </div>

                <div class="form-group peibi_1">
                    <label class="col-sm-2 control-label" for="input01">卡号：</label>

                    <div class="col-sm-4">
                        <input class="form-control" value="<?php /*echo $this->zijin[0]['peibi_card'];*/?>" type="text" name="peibi_card"  size="14"/>
                    </div>

                </div>

                <div class="form-group peibi_1">
                    <label class="col-sm-2 control-label" for="input01">负责人：</label>

                    <div class="col-sm-4">
                        <input class="form-control" value="<?php /*echo $this->zijin[0]['peibi_pp'];*/?>"  type="text" name="peibi_pp"  size="14"/>
                    </div>
                </div>

                <div class="form-group peibi_2">
                    <label class="col-sm-2 control-label" for="input01">拒批原因：</label>
                    <div class="col-sm-8">
                        <textarea id="input05" class="form-control parsley-validated" rows="6" parsley-trigger="keyup" parsley-rangelength="[20,200]" name="peibi_jupi" parsley-validation-minlength="1"><?php /*echo $this->zijin[0]['peibi_jupi'];*/?> </textarea>
                    </div>
                </div>
					

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">证书状态：</label>
                    <div class="col-sm-4">
                    <input type="radio" name="zhengshu" value="1" <?php /*if ($this->zijin[0]['zhengshu'] == 1)echo "checked='checked'";*/?>/> 已开证书
                    <input type="radio" name="zhengshu" value="0" <?php /*if ($this->zijin[0]['zhengshu'] == 0)echo "checked='checked'";*/?>/> 未开证书
                    </div>
                </div>-->

	        <!--<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">相关文档：</label>
            <div class="col-sm-4">
            <input type="file" name="pm_files"  size="14"/><font color="#0474d6" > * 相关文档已打包形式上传 格式为*.rar</font>
							&nbsp;&nbsp;&nbsp;&nbsp;
						<?php /*if($this->zijin[0]['pm_file']!= ""){*/?>
							<a href="<?php /*echo $this->zijin[0]['pm_file'];*/?>" target="_blank">已有相关文件，点击下载</a>
						<?php /*}*/?>
            </div>
            </div>-->
				<!--<div class="form-group">
                <label class="col-sm-2 control-label" for="input01">捐赠单位介绍：</label>
                <div class="col-sm-8">
                <textarea class="ckeditor" name="pm_pp_company">
                <?php /*echo $this->zijin[0]['pm_pp_company'];*/?>
                </textarea>
                </div>
                </div>	-->

                <!--<div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">捐赠仪式：</label>
                    <div class="col-sm-8">
                        <textarea id="input05" class="form-control parsley-validated" rows="6" parsley-trigger="keyup" parsley-rangelength="[20,200]" name="yishi" parsley-validation-minlength="1"><?php /*echo $this->zijin[0]['yishi'];*/?></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">纪念品情况：</label>
                    <div class="col-sm-8">
                        <textarea id="input05" class="form-control parsley-validated" rows="6" parsley-trigger="keyup" parsley-rangelength="[20,200]" name="jinianpin" parsley-validation-minlength="1"><?php /*echo $this->zijin[0]['jinianpin'];*/?></textarea>
                    </div>
                </div>

                <div class="form-group transparent-editor">
                    <label class="col-sm-2 control-label" for="input14">捐赠用途：</label>
                    <div class="col-sm-8">
                        <textarea parsley-validation-minlength="1" name="pm_juanzeng_yongtu" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php /*echo $this->zijin[0]['pm_juanzeng_yongtu'];*/?></textarea>
                    </div>
                    <span class="col-sm-2" > * 资助家庭经济困难学生、奖励优秀学生、支持毕业生就业、奖励教师等</span>
                </div>-->

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">备注：</label>
                    <div class="col-sm-8">
                        <textarea id="input05" class="form-control parsley-validated" rows="6" parsley-trigger="keyup" parsley-rangelength="[20,200]" name="beizhu" parsley-validation-minlength="1"><?php echo $this->zijin[0]['beizhu'];?></textarea>
                    </div>
                </div>


                    <input type="hidden" name="is_renling" value="<?php echo $this->zijin[0]['is_renling']?>"/>
					<input type="hidden" name="id" value="<?php echo $this->zijin[0]['id']?>"/>
					
					<div class="form-group form-footer">
							<div class="col-sm-offset-5 col-sm-7">
								<input class="btn btn-primary"  onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
								<input class="btn btn-default" type="reset" value="重 置" /> 
							</div>
					</div>
			</form>
		  </div>
          </section>
        </div>
		</div>

        <script language="javascript">
            $(".menu li:eq(8)").addClass("open");

            <?php if ($this->zijin[0]['peibi'] == 0){?>
                $(".peibi_1").hide();
            <?php }else {?>
                $(".peibi_2").hide();
            <?php }?>

            /*function change_peibi(status)
            {
                $(".peibi_1").toggle();
                $(".peibi_2").toggle();
            }*/

            $(document).ready(function(){
                $(".addfapiao").show();
                // 切换发票状态
                $(".radioItem").change(function(){
                    var $selectedvalue = $("input[name='piaoju']:checked").val();
                    if ($selectedvalue == 0) {
                        $(".addfapiao").hide();
                    } else if($selectedvalue == 1 || $selectedvalue == 2) {
                        $(".addfapiao").show();
                    }
                });
            });
        </script>