<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目信息编辑</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目信息编辑</li>
            <li class="active">添加签约信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-black">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="newsavesign" method="post" encType="multipart/form-data">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">项目名称：</label>
                            <div class="col-sm-4">
                                <select class="chosen-select-1 chosen-transparent form-control" name="pm_id">
                                    <option value="">请选择项目名称</option>
                                    <?php if($this->pmlist != ""){
                                        foreach ($this->pmlist as $k => $v){
                                            ?>
                                            <option value="<?php echo $v['id'];?>"><?php echo $v['pname'];?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">协议金额：</label>
                            <div class="col-sm-4">
                                <input type="text" size="14" name="xyje" class="form-control">
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">上传协议或补充协议：</label>
                            <div class="col-sm-4">
                                <input name="sign_files" type="file" value="" />
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">是否已办捐赠仪式：</label>
                            <div class="col-sm-4">
                                <input type="radio" name="jzys" class="jzys" value="1"/> 是
                                <input type="radio" name="jzys" class="jzys" value="0" checked/> 否
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group qianyue">
                            <label class="col-sm-2 control-label" for="input01">签约仪式时间：</label>
                            <div class="col-sm-4">
                                <input type="text" size="14" name="sign_time" id="datepicker" data-date-format="YYYY-MM-DD HH:mm:ss" class="form-control">
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group qianyue">
                            <label class="col-sm-2 control-label" for="input01">签约仪式地点：</label>
                            <div class="col-sm-4">
                                <input type="text" name="adress" class="form-control">
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary"  type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>

    <script language="javascript">
        $(".menu li:eq(0)").addClass("open");

        $(document).ready(function(){
            $(".qianyue").hide();
            // 切换发票状态
            $(".jzys").change(function(){
                var $selectedvalue = $("input[name='jzys']:checked").val();
                if ($selectedvalue == 0) {
                    $(".qianyue").hide();
                } else if($selectedvalue == 1) {
                    $(".qianyue").show();
                }
            });
        });
    </script>