<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目进度</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目进度管理</li>
            <li class="active">项目进度</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="tile-body">
			<form action="#" method="post" name="search_form">
				<div class="form-group">

                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="pname" class="col-sm-4 control-label">项目名称：</label>
                            <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                <option value="1">请选择项目名称</option>
                                <?php if($this->pmlist != ""){
                                    foreach ($this->pmlist as $k => $v){
                                        ?>
                                        <option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
                                    <?php }}?>
                            </select>
                            <input id="pname_info" type="hidden" name="pname" value=""/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-sm-3">
                           <!-- <label for="input02"> </label>-->
                            <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                        </div>
                    </div>
				</div>
			</form>
			</div>
			</section>
			<section class="tile color transparent-white">
				<div class="tile-body nopadding">
				<?php if($this->signlist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="25%">项目名称</td>
                        <td width="20%">签约时间</td>
                        <td width="25%">签约协议</td>
                        <td width="20%">协议金额（元）</td>
						<td width="10%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php 
						foreach($this->signlist as $k=>$v){?>
						 <tr>
						 	<td>
                                <a href="/management/chouzi/index?pname=<?php echo $v['pname'];?>" target="_blank" ><?php echo $v['pname'];?></a>&nbsp;
                            </td>
                             <td><?php echo date("Y-m-d",strtotime($v['sign_time']));?></td>
                             <td>
                                 <!--<a href="<?php /*echo $v['sign_files'];*/?>">-->
                                 <a href="/management/zijin/download?id=<?php echo $v['id'];?>">
                                     >>点击下载 <?php if(!empty($v['sign_files_name'])){
                                         echo $v['sign_files_name'];
                                     }elseif(!empty($v['sign_files'])){
                                         echo "协议文件";
                                     }?>
                                 </a></td>
                             <td><?php if(!empty($v['xyje'])){echo number_format($v['xyje'],2);}else{echo "--";}?></td>
                             <td>
                             <!-- <a href="/management/zijin/rateinfo/?pm_id=<?php /*echo $v['id'];*/?>">
                                 <button class="btn btn-greensea margin-bottom-20" type="button">编辑进度</button>
                             </a>-->
                                <a href="/management/zijin/editsign?id=<?php echo $v['id'];?>">
                                    <button class="btn btn-greensea margin-bottom-20" type="button">编辑签订</button>
                                </a>
                                &nbsp;&nbsp;
                                <!--<a href="#" onclick="alert('对不起，项目清单不提供删除功能，请联系管理员');">
                                    <button class="btn btn-danger margin-bottom-20" type="button">删除</button>
                                </a>-->
                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer">
					<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条筹资信息          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无网站资讯！<a href="/management/chouzi/addchouzi">点击添加</a></div>
				 <?php }?>
				 </div>
				 </div>
				 </section>
		  </div>
		</div>

		
		    <script language="javascript">
                $(".menu li:eq(18)").addClass("open");
			</script>
