<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目进度</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目进度管理</li>
            <li class="active">项目进度</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
			<section class="tile color transparent-black">
			<div class="tile-body">
			<form action="#" method="post">
				<div class="form-group">

                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="input05">项目名称：</label>
                            <input type="text" class="form-control" name="pname" />
                        </div>

                    </div>

                    <div class="row">
                        <div class="form-group col-sm-3">
                            <label for="input01">所属部门：</label>
                            <select class="form-control" name="pm_rate">
                                <option value="" >请选择进度</option>
                                <option value="1" >已签订</option>
                                <option value="2" >已到帐</option>
                                <option value="3" >洽谈中</option>
                            </select>
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="input02"> </label>
                            <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                        </div>
                    </div>
				</div>
			</form>
			</div>
			</section>
			<section class="tile color transparent-black">
				<div class="tile-body nopadding">
				<?php if($this->chouzilist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="7%">项目名称</td>
                        <td width="10%">项目进度</td>
						<td width="13%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php 
						foreach($this->chouzilist as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['pname'];?>&nbsp;</td>
                             <td>
                                 <?php if($v['pm_rate'] == ""){ ?>
                                     ---
                                 <?php }elseif(in_array(1,$v['pm_rate'])){ ?>
                                    已签订
                                 <?php }elseif(in_array(2,$v['pm_rate'])){?>
                                    已到帐
                                 <?php }elseif(in_array(3,$v['pm_rate'])){?>
                                    洽谈中
                                 <?php }?>
                              </td>
							<td>
                                <a href="/management/?id=<?php echo $v['id'];?>">
                                    <button class="btn btn-greensea margin-bottom-20" type="button">编辑进度</button>
                                </a>
                                <a href="/management/?id=<?php echo $v['id'];?>">
                                    <button class="btn btn-greensea margin-bottom-20" type="button">查看协议</button>
                                </a>
                                &nbsp;&nbsp;
                                <a href="#" onclick="alert('对不起，项目清单不提供删除功能，请联系管理员');">
                                    <button class="btn btn-danger margin-bottom-20" type="button">删除</button>
                                </a>
                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer bg-transparent-black-2">
					<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条筹资信息          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无网站资讯！<a href="/management/chouzi/addchouzi">点击添加</a></div>
				 <?php }?>
				 </div>
				 </div>
				 </section>
		  </div>
		</div>

		
		    <script language="javascript">
                $(".menu li:eq(4)").addClass("open");
			</script>
