<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:710px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/project_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>筹资项目</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                   	  <?php foreach ($this->my_jjh_pm as $key => $value){
                   	  		if ($value['c_name'] != "推荐项目"){?>
                      	<li>
	                      	<a href="/jjhpm/index?cid=<?php echo $value['c_id'];?>">
	                      		<?php if($this->pm_info[0]['c_id'] == $value['c_id']){?><span><?php }?>
	                      			<?php echo $value['c_name'];?>
	                      		<?php if($this->pm_info[0]['c_id'] == $value['c_id']){?></span><?php }?>
	                      	</a>
                      	</li>
                      <?php }}?>
                   </ul>
                   <div class="jjh_sub_nav_recommond"><a href="/jjhpm/tuijian">推荐项目</a></div>
              </div>
         </div>
         <div class="jjh_content_sub_right">
             <!--<div class="jjh_sub_con_tit"><span>当前位置：<a href="news.html">筹资项目</a> > 推荐项目</span><em>校友年度捐赠--1985校友基金</em></div>--> 
             <div class="jjh_sub_con_content" style="height:530px; padding:0px; width:690px;">
               <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/procomadv1.jpg" /></div><br />
               <div class="jjh_prorecom_detail_left">
                <div class="jjh_prorecom_detit">项目介绍</div> 
                <div class="jjh_prorecom_decon">
                天津大学1895校友基金是由天津大学校友总会募集管理的，以<span class="jjh_font3">天津大学校友年度捐款为主体的低额度捐赠基金</span>，主要用于发展校园文化，支持学生社团活动，研究校史，宣传校友等方面。
                </div>
                <div class="jjh_prorecom_detit">项目进展</div> 
                <div class="jjh_prorecom_decon">
                     <div class="jjh_prorecom_decon_ltit">2009年09月</div>
                     <div class="jjh_prorecom_decon_rtit">为2009年新生印制校歌，校史宣传单页<br />为母校114周年校庆活动印制志愿者T恤衫<br />制作印制校友信息收集卡</div>
                     <div class="cle"></div><br />
                     <div class="jjh_prorecom_decon_ltit">2009年12月</div>
                     <div class="jjh_prorecom_decon_rtit">赞助《求是文集--冬韵如歌》<br />为返校校友制作校园风景卡片</div>
                     <div class="cle"></div><br />
                     <div class="jjh_prorecom_decon_ltit">2010年07月</div>
                     <div class="jjh_prorecom_decon_rtit">编辑制作印刷2010年《校友通讯》</div>
                     <div class="cle"></div><br />
                     <div class="jjh_prorecom_decon_ltit">2010年08月</div>
                     <div class="jjh_prorecom_decon_rtit">为2010年新生印制校歌，校史宣传单页</div>
                     <div class="cle"></div><br />
                     <div class="jjh_prorecom_decon_ltit">2010年10月</div>
                     <div class="jjh_prorecom_decon_rtit">为母校建校115周年文艺晚会赞助</div>
                </div>
               </div>
               <div class="jjh_prorecom_detail_right">
                    <div class="jjh_prorecom_detail_btn">
                    	<a href="/donate/index?cid=30&cname=校友年度捐赠--1985校友基金">我要捐赠</a>
                    </div>
                    <div class="jjh_prorecom_detail_news">
                         <div class="jjh_prorecom_detail_news_tit">最新动态</div>
                           <marquee direction="up" height="200" scrollamount="2" style="margin-top:10px;">
                              <ul>
                                <li>张洁莹 ￥100</li>
                                <li>戴晓橙 ￥200</li>
                                <li>匿名 ￥100</li>
                                <li>谌敦华 ￥500 </li>
                                <li>匿名 ￥1500 </li>
                                <li>匿名 ￥100 </li>
                                <li>孙闻宇 ￥3500 </li>
                                <li>胡腾 ￥200 </li>
                                <li>郑悦 ￥1000 </li>
                                <li>陈华青 ￥200 </li>
                              </ul>
                           </marquee>
                    </div>
               </div>
             </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>