<div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/about"><span>基金会简介</span></a></li>
                      <li><a href="/about/lingdaotici">领导致辞</a></li>
                      <li><a href="/about/zhangcheng">基金会章程</a></li>
                      <li><a href="/about/zuzhi">组织机构设置</a></li>
                      <li><a href="/about/baogao">年度报告</a></li>
                   </ul>
              </div>