<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加所属部门</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>所属部门管理</li>
            <li class="active">添加所属部门</li>
        </ol>
    </div>

</div>
<!-- /page header -->	
<div id="main" class="main">
	<div id="rightstyle02" class="row">
        <div class="col-md-8">
        <section class="tile color transparent-black">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" action="addrsdepartment" method="post" encType="multipart/form-data">           
				<div class="form-group">
					<label class="col-sm-2 control-label" for="input01">所属部门名称：</label>
					<div class="col-sm-8"><input type="text" name="name" /></div>
    				<span class="col-sm-2" >* </span>
				</div>														
				<div class="form-group form-footer">
 					<div class="col-sm-offset-5 col-sm-7">
 						<input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; 
 						<input class="btn btn-default" type="reset" value="重 置" /> 
 					</div>
				</div>
			</form>
		  	</div>
        </section>
        </div>
	</div>