<!-- page header -->
<div class="pageheader">
    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加捐赠方参加学校活动信息</span></h2>
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目捐赠方管理</li>
            <li class="active">添加参加学校活动信息</li>
        </ol>
    </div>
</div>
<!-- /page header -->	
<div id="main" class="main">
	<div id="rightstyle02" class="row">
        <div class="col-md-12">
			<section class="tile color transparent-black">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" id="form1"  action="savepphuodong" method="post" encType="multipart/form-data">

            <div class="form-group">
                <label class="col-sm-2 control-label" for="input01">活动时间：</label>
                <div class="col-sm-4">
                    <input class="form-control" type="text"  data-date-format="YYYY-MM-DD" id="datepicker1"  name="a_date_time"  size="14"/>
                </div>
                <span class="col-sm-2" > * </span>
            </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">活动内容：</label>
                    <div class="col-sm-9">
                        <textarea parsley-validation-minlength="1" name="a_content" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">校方接待人员：</label>
                    <div class="col-sm-9">
                        <textarea parsley-validation-minlength="1" name="a_contact_person" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">纪念品：</label>
                    <div class="col-sm-9">
                        <textarea parsley-validation-minlength="1" name="a_gift" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                    </div>
                </div>

                <input type="hidden" name="pp_id" value="<?php echo $this->pp_id;?>">

			<div class="form-group form-footer">
				<div class="col-sm-offset-5 col-sm-7">
					<input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
					<input class="btn btn-default" type="reset" value="重 置" /> 
				</div>
			</div>
			</form>
            </div>
            </section>
		 </div>
	</div>
        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(20)").addClass("open");
        </script>


    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(10)").addClass("open");
    </script>