<!-- page header -->
<div class="pageheader">
    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加联系人</span></h2>
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目联系人管理</li>
            <li class="active">添加联系人</li>
        </ol>
    </div>
</div>
<!-- /page header -->	
<div id="main" class="main">
	<div id="rightstyle02" class="row">
        <div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" id="form1"  action="addrspp" method="post" encType="multipart/form-data">
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人姓名：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="ppname" /></div>
            <span class="col-sm-2" > * </span>
            </div>	
            
			<div class="form-group">
            	<label class="col-sm-2 control-label" for="input01">相关项目名称：</label>
            	<div class="col-sm-4">
            		<select class="form-control" name="pp_pm_id">
						<?php if($this->pmlist != ""){
							foreach ($this->pmlist as $k => $v){
						?>
						<option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
						<?php }}?>
					</select>
            	</div>
            </div>	
            
			<div class="form-group">
            	<label class="col-sm-2 control-label" for="input01">联系人类型：</label>
            	<div class="col-sm-4">
            		<select class="form-control" name="pp_cate">
						<option value="筹资联系人">筹资联系人</option>
						<option value="资金联系人">资金联系人</option>
						<option value="使用联系人">使用联系人</option>
					</select>
            	</div>
            </div>	
                
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人email：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="ppemail" /></div>
            <span class="col-sm-2" > * </span>
            </div>
                	
            <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人QQ：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="pp_qq" /></div>
            <span class="col-sm-2" > * </span>
            </div>	

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人MSN：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="pp_msn" /></div>
            <span class="col-sm-2" > * </span>
            </div>	
			
           <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人移动电话：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="ppmobile" /></div>
            <span class="col-sm-2" > * </span>
            </div>	
			
            <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人电话：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="ppphone"  size="40"/></div>
            <span class="col-sm-2" > * 可添加多个，以“,”号隔开</span>
            </div>	
           
           	<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人地址：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="pp_address" size="40"/></div>
            <span class="col-sm-2" > * </span>
            </div>	
            
            <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">备注：</label>
                <div class="col-sm-9">
                    <textarea parsley-validation-minlength="1" name="pp_beizhu" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                </div>
            </div>	
							
			<div class="form-group form-footer">
				<div class="col-sm-offset-5 col-sm-7">
					<input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
					<input class="btn btn-default" type="reset" value="重 置" /> 
				</div>
			</div>
			</form>
            </div>
            </section>
		 </div>
	</div>
        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(10)").addClass("open");
        </script>