<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>管理员角色列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>管理组成员管理</li>
            <li class="active">管理员角色列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="detailedbox col-md-6">
			<section class="tile color transparent-white">
			<div class="tile-body nopadding">
				<?php if($this->admingrpouplist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  
					  <tr>
						<td width="20%">序号</td>
						<td width="30%">管理员角色</td>
						<td width="20%">操作</td>
					  </tr>
					
					  <?php 
						foreach($this->admingrpouplist as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['gid'];?></td>
							<td><?php echo $v['gname'];?></td>
							<td>
                            <a href="/management/admin/editadmingroup?gid=<?php echo $v['gid'];?>">
                            <button type="button" class="btn btn-greensea margin-bottom-20">编辑</button></a>

                                <a href="/management/acl?gid=<?php echo $v['gid'];?>" target="_blank">
                                    <button type="button" class="btn btn-greensea margin-bottom-20">编辑权限</button></a>


                             <a onclick="if(confirm('是否要删除管理员角色，如删除将无法找回！') == false){return false;}" href="/management/admin/deladmingroup?gid=<?php echo $v['gid'];?>"><button type="button" class="btn btn-danger margin-bottom-20">删除</button></a></td>
						 </tr>
					   <?php }?>
					</table>
                </div>
					<div class="tile-footer">
                    <div class="row">
				 <?php }else{?>
				 	<div>暂无管理员信息！<a href="/management/admin/addadmingroup">点击添加</a></div>
				 <?php }?>
                 </div>
                 </div>
                 </section>
		  </div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(29)").addClass("open");
        </script>
		
