<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>所属部门列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>所属部门管理</li>
            <li class="active">所属部门列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-8">
				<section class="tile color transparent-black">
					<div class="tile-body nopadding">
				<?php if($this->departmentlist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  <thead>
					  <tr>
						<td width="10%">所属部门id</td>
						<td width="40%">所属部门名称</td>
						<td width="20%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php 
						foreach($this->departmentlist as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['id'];?></td>
							<td><?php echo $v['pname'];?></td>
							<td>
                            <a href="/management/admin/editdepartment?id=<?php echo $v['id'];?>">
                            <button type="button" class="btn btn-greensea margin-bottom-20">编辑</button></a>
                           
                            <a href="/management/admin/deldepartment?id=<?php echo $v['id'];?>" onclick= "if(confirm( '是否确定！ 删除将无法找回该比来款信息。')==false) return false; "><button type="button" class="btn btn-danger margin-bottom-20">删除</button></a></td>
						 </tr>
					   <?php }?>
                      </tbody>
					</table>
					</div>
					<div class="tile-footer bg-transparent-black-2">
					<div class="row">
					<div align="right" class="page col-md-12">
						共  <?php echo $this->total;?> 条          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无所属部门信息！<a href="/management/admin/adddepartment">点击添加</a></div>
				 <?php }?>
		  </div>
		</div> 
        </section>
        	</div>
		</div>
