<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑管理员密码</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>密码管理</li>
            <li class="active">编辑管理员密码</li>
        </ol>
    </div>

</div>
<!-- /page header -->
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		<div class="col-md-6">
        <section class="tile color transparent-white">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" action="editrspwd" id="form1" method="post" encType="multipart/form-data">
				<div class="form-group">		
				<label class="col-sm-2 control-label" for="input01">管理员名称：</label>
				<div class="col-sm-8">
				<select class="form-control" name="admin_id">
					<?php foreach ($this->adminlist as $k => $v){?>
					<option value="<?php echo $v['id'];?>"><?php echo $v['admin_name'];?></option>
					<?php }?>
				</select>
				</div>
				</div>			
				<div class="form-group">
				<label class="col-sm-2 control-label" for="input01">管理员新密码：</label>
				<div class="col-sm-8">
				<input class="form-control" type="password" name="pwd" value=""/>
                </div>
                <span class="col-sm-2" > * </span>
				</div>
				<div class="form-group form-footer">
				<div class="col-sm-offset-4 col-sm-7">
					<input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
					<input class="btn btn-default" type="reset" value="重 置" /> 
				</div>
			</div>
			</form>
		  </div>
        </section>
		</div>

            <script src="/include/management/assets/js/jquery.js"></script>
            <script language="javascript">
				$("#glzcygl").addClass("open");
            </script>