<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑联系人</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目联系人管理</li>
            <li class="active">编辑联系人</li>
        </ol>
    </div>

</div>
<!-- /page header -->		
    <div id="main" class="main">
		<div id="rightstyle02" class="row">
        <div class="col-md-12">
			<section class="tile color transparent-black">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" action="editrspp" method="post" encType="multipart/form-data">
            
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">捐赠方名称：</label>
            <div class="col-sm-8">
            <input class="form-control" type="text" name="ppname" value="<?php echo $this->ppinfo[0]['ppname']?>"/>
            </div>
            <span class="col-sm-2" > * </span>
            </div>	

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">相关项目名称：</label>
            <div class="col-sm-8">
            <select class="form-control" name="pp_pm_id">
							<?php if($this->pmlist != ""){
									foreach ($this->pmlist as $k => $v){
								?>
								<option value="<?php echo $v['pname'];?>" <?php if ($this->ppinfo[0]['pp_pm_id'] == $v['pname']){echo "selected='selected'";}?>><?php echo $v['pname'];?></option>
							<?php }}?>
							</select>
            </div>
           
            </div>	
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人类型：</label>
            <div class="col-sm-8">
            <select class="form-control" name="pp_cate">
								<option value="筹资联系人" <?php if ($this->ppinfo[0]['pp_cate'] == "筹资联系人"){echo "selected='selected'";}?>>筹资联系人</option>
								<option value="资金联系人" <?php if ($this->ppinfo[0]['pp_cate'] == "资金联系人"){echo "selected='selected'";}?>>资金联系人</option>
								<option value="使用联系人" <?php if ($this->ppinfo[0]['pp_cate'] == "使用联系人"){echo "selected='selected'";}?>>使用联系人</option>
							</select>
            </div>
            </div>	

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人email：</label>
            <div class="col-sm-8"><input class="form-control" type="text" name="ppemail" value="<?php echo $this->ppinfo[0]['ppemail']?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>	

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人QQ：</label>
            <div class="col-sm-8"><input type="text" name="pp_qq" value="<?php echo $this->ppinfo[0]['pp_qq']?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>	
            
            <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人MSN：</label>
            <div class="col-sm-8"><input type="text" name="pp_msn" value="<?php echo $this->ppinfo[0]['pp_msn']?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>	

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人移动电话：</label>
            <div class="col-sm-8"><input type="text" name="ppmobile" value="<?php echo $this->ppinfo[0]['ppmobile']?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>	


			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人电话：</label>
            <div class="col-sm-8"><input type="text" name="ppphone"  value="<?php echo $this->ppinfo[0]['ppphone']?>" size="40"/></div>
            <span class="col-sm-2" >* 可添加多个，以“,”号隔开 </span>
            </div>	

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人地址：</label>
            <div class="col-sm-8"><input type="text" name="pp_address" size="40" value="<?php echo $this->ppinfo[0]['pp_address']?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>	
				
            <div class="form-group">
                <label class="col-sm-2 control-label" for="input02">添加子公司信息"</label>
                <div>       <?php
                            if(!empty($this->pp_company_list)){
                                foreach($this->pp_company_list as $key => $value)
                                {
                                    echo ($key+1).",子公司名称：".$value['company_name'];echo "</br>";
                                    echo "&nbsp;&nbsp;&nbsp;联系人：".$value['company_contector'];echo "</br>";
                                    echo "&nbsp;&nbsp;&nbsp;联系方式：".$value['company_cont_style'];echo "</br>";
                                    echo "编辑 || 删除</br>";
                                }
                            }
                            ?>
                    </div>
                   <input class="btn btn-primary" type="submit" value="添加子公司信息" /> &nbsp;&nbsp;&nbsp;&nbsp; 
					</div>
            
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">备注：</label>
            <div class="col-sm-8">
            <textarea class="ckeditor" name="pp_beizhu">
				<?php echo $this->ppinfo[0]['pp_beizhu']?>
			</textarea>
            </div>
            </div>	

                
					<input type="hidden" name="pid" value="<?php echo $this->ppinfo[0]['pid'];?>" />
			<div class="form-group form-footer">
				<div class="col-sm-offset-5 col-sm-7">
                     <input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; 
                     <input class="btn btn-default" type="reset" value="重 置" />
				</div>
			</div>
			</form>
            </div>
            </section>
		  </div>
		</div>