<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑联系人</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目联系人管理</li>
            <li class="active">编辑联系人</li>
        </ol>
    </div>

</div>
<!-- /page header -->		
    <div id="main" class="main">
		<div id="rightstyle02" class="row">
        <div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" action="saveppcompany" id="form1" method="post" encType="multipart/form-data">

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">子公司名称：</label>
                    <div class="col-sm-4"><input class="form-control" value="<?php echo $this->ppcompany[0]['company_name'];?>" type="text" name="company_name" /></div>
                    <span class="col-sm-2" > * </span>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">联系人姓名：</label>
                    <div class="col-sm-4"><input class="form-control" value="<?php echo $this->ppcompany[0]['company_contector'];?>" type="text" name="company_contector" /></div>
                    <span class="col-sm-2" > * </span>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">联系人电话：</label>
                    <div class="col-sm-4"><input class="form-control" value="<?php echo $this->ppcompany[0]['company_cont_style'];?>" type="text" name="company_cont_style" /></div>
                    <span class="col-sm-2" > * </span>
                </div>

            <input type="hidden" name="id" value="<?php echo $this->ppcompany[0]['id'];?>" />
            <input type="hidden" name="pp_id" value="<?php echo $this->ppcompany[0]['pp_id'];?>" />
			<div class="form-group form-footer">
				<div class="col-sm-offset-5 col-sm-7">
                     <input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                     <input class="btn btn-default" type="reset" value="重 置" />
				</div>
			</div>
			</form>
            </div>
            </section>
		  </div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $("#ywxggl").addClass("open");
        </script>