<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑管理员角色</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>管理组成员管理</li>
            <li class="active">编辑管理员角色</li>
        </ol>
    </div>

</div>
<!-- /page header -->	

	<div id="main" class="main">
		<div id="rightstyle02" class="row">
         <div class="col-md-8">
			<section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                <form class="form-horizontal" action="to-addadmingroup"  id="form1" method="post" encType="multipart/form-data">
                    <input type="hidden" name="gid" value="<?php echo $this->admingroupinfo[0]['gid'];?>"/>
                        <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">管理员角色名称：</label>
                        <div class="col-sm-8">
                            <input class="form-control" type="text" name="gname" value="<?php echo $this->admingroupinfo[0]['gname']?>"/>
                        </div>
                        <span class="col-sm-2" > * </span>
                    </div>
                    <div class="form-group form-footer">
                        <div class="col-sm-offset-5 col-sm-7">
                            <input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                            <input class="btn btn-default" type="reset" value="重 置" />
                        </div>
                    </div>
                </form>
                </div>
            </section>
		  </div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $("#glzcygl").addClass("open");
        </script>