	<div id="main">
		<div id="rightstyle02">
		<h4>密码管理<span class="font_red"> >> </span><span class="font_red_big">编辑管理员密码</span></h4>
			<div class="detailedbox">
			<form action="editrspwd" method="post" encType="multipart/form-data">
				<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">		
					 <tr>
					    <td width="20%" style="text-align:right;">管理员名称：</td>
						<td width="80%" style="text-align:left;">
							<select name="admin_id">
								<?php foreach ($this->adminlist as $k => $v){?>
									<option value="<?php echo $v['id'];?>"><?php echo $v['admin_name'];?></option>
								<?php }?>
							</select>
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">管理员新密码：</td>
						<td width="80%" style="text-align:left;">
							<input type="password" name="pwd" value=""/><font color="#0474d6" > * </font>
						</td>
					</tr>
															
					<tr>
					    <td width="20%" style="text-align:right;"> </td>
						<td width="80%" style="text-align:left;">
							<input type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; <input type="reset" value="重 置" /> 
						</td>
					</tr>
				</table>
			</form>
		  </div>
		</div>