<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>管理员列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>管理组成员管理</li>
            <li class="active">管理员列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="detailedbox col-md-6">
			<section class="tile color transparent-white">
			<div class="tile-body nopadding">
				<?php if($this->adminlist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  
					  <tr>
						<td width="20%">管理员类型</td>
						<td width="30%">管理员姓名</td>
						<td width="20%">操作</td>
					  </tr>
					
					  <?php 
						foreach($this->adminlist as $k=>$v){?>
						 <tr>
						 	<!--<td><?php
/*						 		if($v['admin_type'] == 0){
						 			echo "系统管理员";
						 		}elseif($v['admin_type'] == 1){
						 			echo "项目筹资管理员";
						 		}elseif($v['admin_type'] == 2){
						 			echo "项目资金管理员";
						 		}elseif($v['admin_type'] == 3){
						 			echo "项目使用管理员";
						 		}elseif($v['admin_type'] == 4){
						 			echo "项目管理员";
						 		}elseif($v['admin_type'] == 5){
						 			echo "统计管理员";
						 		}elseif($v['admin_type'] == 6){
						 			echo "网站管理员";
						 		}elseif($v['admin_type'] == 7){
									echo "财务人员";
								}
						 	*/?></td>
-->
                             <td><?php
                                    foreach($this->admingrouplist as $key => $value){
                                        if($value['gid'] == $v['gid']){
                                            echo $value['gname'];
                                        }
                                 }
                                 ?></td>

							<td><?php echo $v['admin_name'];?></td>
							<td>
                            <a href="/management/admin/edit?id=<?php echo $v['id'];?>"> 
                            <button type="button" class="btn btn-greensea margin-bottom-20">编辑</button></a>
                             <a onclick="if(confirm('是否要删除管理员，如删除将无法找回！') == false){return false;}" href="/management/admin/del?id=<?php echo $v['id'];?>"><button type="button" class="btn btn-danger margin-bottom-20">删除</button></a></td>
						 </tr>
					   <?php }?>
					</table>
                </div>
					<div class="tile-footer">
                    <div class="row">
				 <?php }else{?>
				 	<div>暂无管理员信息！<a href="/management/admin/add">点击添加</a></div>
				 <?php }?>
                 </div>
                 </div>
                 </section>
		  </div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(29)").addClass("open");
        </script>
		
