<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目<?php echo $_REQUEST['pp_cate']?>列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目<?php echo $_REQUEST['pp_cate']?>管理</li>
            <li class="active">项目<?php echo $_REQUEST['pp_cate']?>列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
	<div id="rightstyle02" class="row">
		<div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="tile-body">
				<form class="form-horizontal" method="get" action="#"  name="search_form">
                    <div class="form-group">
                    	<div class="col-sm-12">
                            <label class="col-sm-1 control-label" for="pname">项目名称：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                    <option value="1">请选择项目名称</option>
                                    <?php if($this->pmlist != ""){
                                        foreach ($this->pmlist as $k => $v){
                                            ?>
                                            <option value="<?php echo $v['pname'];?>" <?php if($this->pname == $v['pname'])echo 'selected="selected"';?>><?php echo $v['pname'];?></option>
                                        <?php }}?>
                                </select>
                                <input type="hidden" name="pp_cate" value="<?php echo $_REQUEST['pp_cate']?>"/>
                                <input id="pname_info" type="hidden" name="pname" value=""/>
                            </div>

                            <label class="col-sm-1 control-label" for="input01"><?php echo $_REQUEST['pp_cate']?>名称：</label>
                            <div class="col-sm-3">
                               <input type="text" name="ppname" value="<?php echo $this->ppname;?>"/>
                            </div>

                            <div class="col-sm-1"><input class="btn btn-primary" type="submit" value="搜索"></div>

                            <?php if($_REQUEST['pp_cate'] == '捐赠方'){?>
                                <div class="col-sm-3">
                                    <input class="btn btn-primary btn-block" type="button" value="同步项目信息中捐赠方" onclick=" javascript:if(confirm('确定要同步捐赠方数据吗？\r\r此操作将过滤捐赠方名称和项目名称相同并已存在的捐赠人信息。\r如果同一捐赠人对应不同项目，则添加多条项目捐赠人信息到人员管理表中。')){window.location.href='/management/admin/syncjzf';}">
                                </div>
                            <?php }?>


                        </div>
                    </div>
					</form>
			</div>
			</section>
            <section class="tile color transparent-white">	
                <div class="tile-body nopadding">				
				<?php if($this->pplist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  <thead>
					  <tr>
						<td width="7%">姓名/名称</td>
                        <td width="7%">类型</td>
						<!--<td width="9%">相关项目</td>-->
						<td width="9%">移动电话</td>
						<td width="10%">操作</td>
                        <td width="10%">其他操作</td>
					  </tr>
						</thead>
                      <tbody>
					  <?php 
						foreach($this->pplist as $k=>$v){?>
						 <tr>
						 	<td>
                                <a href="/management/admin/ppinfo?id=<?php echo $v['pid'];?>" target="_blank" style="text-decoration:underline;">
                                    <?php echo $v['ppname'];?>
                                </a>
                            </td>

                            <td><?php echo $v['pp_cate'];?></td>

							<!--<td><a href="/management/chouzi/index?pname=<?php /*echo $v['pp_pm_id'];*/?>" target="_blank">
                                <?php /*echo $v['pp_pm_id'];*/?>
                            </td>-->

                             <td><?php echo $v['ppmobile'];?></td>
                             <!--<td><?php echo $v['ppemail'];?></td>-->
                             <td>
                                 <!--<a href="/management/admin/ppinfo?id=<?php /*echo $v['pid'];*/?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20">查看</button>
                                 </a>-->

                                 <a href="/management/admin/editpp?id=<?php echo $v['pid'];?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20" >编辑<?php //echo $_REQUEST['pp_cate']?></button>
                                 </a>

                                 <a href="/management/admin/ppcompany?pp_id=<?php echo $v['pid'];?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20">编辑子公司</button>
                                 </a>
                                 <!--<a href="#">
                                     <button type="button" class="btn btn-danger margin-bottom-20">删除</button>
                                 </a>-->
                             </td>
                             <td>
                                 <!--<a href="/management/admin/editpp?id=<?php /*echo $v['pid'];*/?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20" style="margin-bottom:5px;">编辑捐赠方</button>
                                 </a>-->

                                <!-- <a href="/management/admin/ppcompany?pp_id=<?php /*echo $v['pid'];*/?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20" style="margin-bottom:5px;">编辑子公司</button>
                                 </a>-->

                                 <a href="/management/admin/pphuodong?pp_id=<?php echo $v['pid'];?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20" >参加学校活动</button>
                                 </a>

                                 <?php if($_REQUEST['pp_cate'] == '捐赠方'){?>
                                 <a href="/management/admin/ppvisit?pp_id=<?php echo $v['pid'];?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20">拜访捐赠方情况</button>
                                 </a>
                                 <?php }?>
                             </td>
						 </tr>
					   <?php }?>
                       </tbody>
					</table>
				</div>
				<div class="tile-footer transparent-white">
				<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无项目联系人信息！<a href="/management/admin/addpp">点击添加</a></div>
				 <?php }?>
		  </div>
		</div> 
			</section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(0)").addClass("open");
    </script>