<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目捐赠方列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目捐赠方管理</li>
            <li class="active">项目捐赠方列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
	<div id="rightstyle02" class="row">
		<div class="col-md-12">
			<section class="tile color transparent-black">
			<div class="tile-body">
				<form class="form-horizontal" method="post" action="#"  name="search_form">
                    <div class="form-group">
                    	<div class="col-sm-12">
                            <label class="col-sm-2 control-label" for="pname">项目名称：</label>
                            <div class="col-sm-4">
                                <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                    <option value="1">请选择项目名称</option>
                                    <?php if($this->pmlist != ""){
                                        foreach ($this->pmlist as $k => $v){
                                            ?>
                                            <option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
                                        <?php }}?>
                                </select>
                                <input id="pname_info" type="hidden" name="pname" value=""/>
                            </div>

                            <label class="col-sm-2 control-label" for="input01">捐赠方名称：</label>
                            <div class="col-sm-2">
                               <input type="text" name="ppname" />
                            </div>
                            <label class="col-sm-2 control-label" for="input01"> </label>
                            <div class="col-sm-2">
                                <input class="btn btn-primary" type="submit" value="搜索">
                            </div>
                        </div>
                    </div>
					</form>
			</div>
			</section>
            <section class="tile color transparent-black">	
                <div class="tile-body nopadding">				
				<?php if($this->pplist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  <thead>
					  <tr>
						<td width="15%">捐赠方</td>
						<td width="25%">相关项目</td>
						<!--<td width="20%">移动电话</td>-->
						<td width="10%">操作</td>
                          <td width="10%">其他操作</td>
					  </tr>
						</thead>
                      <tbody>
					  <?php 
						foreach($this->pplist as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['ppname'];?></td>
							<td><?php echo $v['pp_pm_id'];?></td>
                             <!--<td><?php echo $v['ppmobile'];?></td>
							<td><?php /*echo $v['ppemail'];*/?></td>-->
                             <td>
                                 <a href="/management/admin/ppinfo?id=<?php echo $v['pid'];?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20">查看</button>
                                 </a>

                                 <a href="#">
                                     <button type="button" class="btn btn-danger margin-bottom-20">删除</button>
                                 </a>
                             </td>
                             <td>
                                 <a href="/management/admin/editpp?id=<?php echo $v['pid'];?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20" style="margin-bottom:5px;">编辑捐赠方</button>
                                 </a>

                                 <a href="/management/admin/ppcompany?pp_id=<?php echo $v['pid'];?>">
                                     <button type="button" class="btn btn-greensea margin-bottom-20" style="margin-bottom:5px;">编辑子公司</button>
                                 </a>
                             </td>
						 </tr>
					   <?php }?>
                       </tbody>
					</table>
				</div>
				<div class="tile-footer bg-transparent-black-2">
				<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无项目联系人信息！<a href="/management/admin/adddepartment">点击添加</a></div>
				 <?php }?>
		  </div>
		</div> 
			</section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(20)").addClass("open");
    </script>