<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目联系人子公司列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目联系人管理</li>
            <li class="active">联系人子公司列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
	<div id="rightstyle02" class="row">
		<div class="col-md-12">
			<section class="tile color transparent-black">
			</section>
            <section class="tile color transparent-black">	
                <div class="tile-body nopadding">				
				<?php if($this->pplist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                        <thead>
                            <tr>
                                <td width="20%">子公司名称</td>
                                <td width="15%">联系人</td>
                                <td width="15%">联系方式</td>
                                <td width="10%">操作</td>
                            </tr>
                        </thead>
                      <tbody>
					  <?php 
						foreach($this->company_list as $k=>$v){?>
                        <tr>
                            <td><?php echo $v['company_name'];?></td>
                            <td><?php echo $v['company_contector'];?></td>
                            <td><?php echo $v['company_cont_style'];?></td>
                            <td>
                            <a href="/management/admin/addppcompany?id=<?php echo $v['pp_id'];?>">
                                <button type="button" class="btn btn-greensea margin-bottom-20">编辑</button>
                            </a>
                            <a href="#">
                                <button type="button" class="btn btn-danger margin-bottom-20">删除</button>
                            </a>
                            </td>
                        </tr>
					   <?php }?>
                       </tbody>
					</table>
				</div>
				<div class="tile-footer bg-transparent-black-2">
				<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无项目联系人子公司信息！<a href="/management/admin/addppcompany">点击添加</a></div>
				 <?php }?>
		  </div>
		</div> 
			</section>
        </div>
    </div>

    <script language="javascript">
        $(".menu li:eq(17)").addClass("open");
    </script>
