<!-- page header -->
<div class="pageheader">
    <script src="/include/management/js/echarts.js"></script>
    <!--<script src="../asset/js/codemirror.js"></script>
    <script src="../asset/js/javascript.js"></script>-->

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>查看联系人</span></h2>

    <!--<div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目联系人管理</li>
            <li class="active">编辑联系人</li>
            <li> <?php /*echo $this->ppinfo[0]['ppname'];*/?> </li>
        </ol>
    </div>-->

</div>
<!-- /page header -->		
    <div id="main" class="main">
        <!--<div class="row">
            <div class="col-md-4">
                <a href="/management/admin/relation?id=<?php /*echo $this->ppinfo[0]['pid']*/?>" target="_blank"><h3>>> 人立方</h3></a>
            </div>
        </div>-->
        <div class="row">
            <!-- col 8 -->
            <div class="col-md-4">


                <style>
                    img {
                        vertical-align: middle;
                        border-style: none;
                    }
                    .card-body {
                        -ms-flex: 1 1 auto;
                        flex: 1 1 auto;
                        padding: 1.25rem;
                    }
                    .text-center {
                        text-align: center!important;
                    }

                    .card-img-top {
                        width: 100%;
                        border-top-left-radius: calc(.25rem - 1px);
                        border-top-right-radius: calc(.25rem - 1px);
                    }
                    .little-profile .pro-img {
                        margin-top: -80px;
                        margin-bottom: 20px;
                    }
                    .little-profile .pro-img img {
                        width: 128px;
                        height: 128px;
                        -webkit-box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
                        box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
                        border-radius: 100%;
                    }
                </style>

                <!-- tile -->
                <section class="tile color transparent-white">
                <div class="card">
                    <img class="card-img-top" src="/include/management/images/profile-bg.jpg" alt="Card image cap">
                    <div class="card-body little-profile text-center">
                        <div class="pro-img">
                            <img src="/include/management/images/4.png" alt="user" style="display: inline;">
                        </div>
                        <h3 class="m-b-0"><?php echo $this->ppinfo[0]['ppname'];?></h3>

                        <p>Name &amp; Company or Organization name</p>
                        <!--<p>Web Designer &amp; Developer</p>-->
                        <!--<a href="javascript:void(0)" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded">Follow</a>-->
                        <div class="row text-center m-t-20">
                            <div class="col-lg-4 col-md-4 m-t-20"><h3 class="m-b-0 font-light"><?php echo count($this->pm_list);?></h3><small>实际捐赠</small></div>
                            <div class="col-lg-4 col-md-4 m-t-20"><h3 class="m-b-0 font-light"><?php echo count($this->meeting_list);?></h3><small>参加会议/活动</small></div>
                            <div class="col-lg-4 col-md-4 m-t-20"><h3 class="m-b-0 font-light"><?php echo count($this->feedback_list);?></h3><small>回访次数</small></div>
                        </div>
                    </div>
                </div>
                </section>

                    <!-- tile -->
                <section class="tile color transparent-white">




                    <!-- tile body -->
                    <div class="tile-body">

                        <!--<h4><strong>捐赠方：<?php echo $this->ppinfo[0]['ppname']?></strong> </h4>
                        <p></p>

                        <h4><strong>相关项目名称：
                            <?php if($this->pmlist != ""){
                                foreach ($this->pmlist as $k => $v){
                                    if ($this->ppinfo[0]['pp_pm_id'] == $v['pname']){echo $v['pname'];}}}?></strong></h4>

                        <h5 class="filled">联系人类型</h5>
                        <p class="filled"></p>-->

                        <!--<h5 class="filled blue">姓名/名称</h5>
                        <p class="filled blue"><?php /*echo $this->ppinfo[0]['ppname']*/?></p>-->

                        <!--<h5 class="filled greensea">相关项目名称</h5>
                        <p class="filled greensea">
                            <?php /*if($this->pmlist != ""){
                                foreach ($this->pmlist as $k => $v){
                                    if ($this->ppinfo[0]['pp_pm_id'] == $v['pname']){
                                        echo $v['pname'];
                                        $pname = $v['pname'];
                                    }
                                }
                            }
                            */?>
                            <a href="/management/chouzi/index?pname=<?php /*echo $pname;*/?>" target="_blank"> 》》点击查看项目 </a>
                        </p>-->


                        <h5 class="filled blue">联系人移动电话</h5>
                        <p class="filled blue"><?php echo $this->ppinfo[0]['ppmobile']?></p>

                        <h5 class="filled greensea">联系人电话</h5>
                        <p class="filled greensea"><?php echo $this->ppinfo[0]['ppphone']?></p>

                        <h5 class="filled slategray">联系人email</h5>
                        <p class="filled slategray"><?php echo $this->ppinfo[0]['ppemail']?></p>

                        <h5 class="filled slategray">联系人地址</h5>
                        <p class="filled slategray"><?php echo $this->ppinfo[0]['pp_address']?></p>

                        <h5 class="filled redbrown">备注</h5>
                        <p class="filled redbrown"><?php echo strip_tags($this->ppinfo[0]['pp_beizhu']);?></p>

                    </div>
                    <!-- /tile body -->

                </section>
                <!-- /tile -->

            </div>
            <!-- /col 8 -->


            <!-- col 4 -->
            <div class="col-md-4">

                <!-- tile -->
                <section class="tile color transparent-white">
                    <!-- tile header -->
                    <div class="tile-header">
                        <h4><strong>项目捐赠人</strong> Information</h4>
                        <div class="controls">
                            <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                            <a href="#" class="remove"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <!-- /tile header -->

                    <!-- tile body -->
                    <div class="tile-body">
                        <h5 class="filled blue">项目名称</h5>
                        <?php
                        if(!empty($this->pm_list)){
                            foreach($this->pm_list as $key => $value) {
                                ?>
                                <p class="filled blue">
                                    <a href="/management/chouzi/repminfo?id=<?php echo $value['id'];?>" target="_blank">
                                        <?php echo $value['pm_name'];?>
                                    </a>
                                </p>
                            <?php }
                        }
                        ?>
                        </h5>
                    </div>
                    <!-- /tile body -->
                </section>
                <!-- /tile -->


                <!-- tile -->
                <section class="tile color transparent-white">
                    <!-- tile header -->
                    <div class="tile-header">
                        <h4><strong>参加学校活动</strong> Information</h4>
                        <div class="controls">
                            <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                            <a href="#" class="remove"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <!-- /tile header -->

                    <!-- tile body -->
                    <div class="tile-body">

                        <?php
                        if(!empty($this->meeting_list)){
                            foreach($this->meeting_list as $key => $value) {
                                ?>
                                <h4 class="filled">
                                    <a href="/management/meeting/edit?id=<?php echo $value['id'];?>" target="_blank">
                                        <?php echo $value['meeting_name'];?>
                                    </a>
                                </h4>
                                <p class="filled">
                                    <small>
                                        类型：<?php echo $this->meeting_cate[$value['meeting_cate']];?></br>
                                        开始时间：<?php echo $value['meeting_start_time'];?></br>
                                        结束时间：<?php echo $value['meeting_end_time'];?></br>
                                        地点：<?php echo $value['meeting_address'];?></br>
                                    </small>
                                </p>
                            <?php }
                        }
                        ?>
                    </div>
                    <!-- /tile body -->
                </section>
                <!-- /tile -->


                <!-- tile -->
                <section class="tile color transparent-white">
                    <!-- tile header -->
                    <div class="tile-header">
                        <h4><strong>相关回馈拜访</strong> Information</h4>
                        <div class="controls">
                            <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                            <a href="#" class="remove"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <!-- /tile header -->

                    <!-- tile body -->
                    <div class="tile-body">

                        <?php
                        if(!empty($this->feedback_list)){
                            foreach($this->feedback_list as $key => $value) {
                                ?>
                                <h4 class="filled">
                                    <a href="/management/feedback/edit?id=<?php echo $value['id'];?>" target="_blank">
                                        <?php echo $value['pm_name'];?>
                                    </a>
                                </h4>
                                <p class="filled">
                                    <small>
                                        回馈方式：<?php echo $value['feedback_type'];?></br>
                                        回馈时间：<?php echo $value['feedback_datetime'];?></br>
                                        备注：<?php echo $value['bz'];?></br>
                                    </small>
                                </p>
                            <?php }
                        }
                        ?>

                        <?php
                        if(!empty($this->gift_list)){
                            foreach($this->gift_list as $key => $value) {
                                ?>
                                <h4 class="filled">
                                    <a href="/management/gift/editusegift?id=<?php echo $value['id'];?>" target="_blank">
                                        <?php echo $value['gift_datetime']."：赠送礼品。用途：".$value['use'];?>
                                    </a>
                                </h4>
                                <p class="filled">
                                    <small>
                                        使用礼品：<?php echo $value['gift_name'];?></br>
                                        礼品数量：<?php echo $value['gift_count'];?></br>
                                        赠送日期：<?php echo $value['gift_datetime'];?></br>
                                        用途：<?php echo $value['use'];?></br>
                                    </small>
                                </p>
                            <?php }
                        }
                        ?>
                    </div>
                    <!-- /tile body -->
                </section>
                <!-- /tile -->

            </div>
            <!-- /col 4 -->


            <!-- col 4 -->
            <div class="col-md-4">

                <!-- tile -->
                <section class="tile color transparent-white">

                    <!-- tile header -->
                    <div class="tile-header">
                        <h4><strong>下属子公司</strong> Information</h4>
                        <div class="controls">
                            <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                            <a href="#" class="remove"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <!-- /tile header -->

                    <!-- tile body -->
                    <div class="tile-body">

                        <?php
                        if(!empty($this->pp_company_list)){
                            foreach($this->pp_company_list as $key => $value) {
                                ?>
                                <h4 class="filled"><?php echo $value['company_name'];?></h4>
                                <p class="filled">
                                    <small>
                                        联系人：<?php echo $value['company_contector'];?></br>
                                        联系方式：<?php echo $value['company_cont_style'];?></br>
                                    </small>
                                </p>
                            <?php }
                        }
                        ?>

                        <!--<h4>Emphasis Classes</h4>
                        <p class="text-muted">Fusce dapibus, tellus ac cursus commodo, tortor mauris nibh.</p>
                        <p class="color-red">Etiam porta sem malesuada magna mollis euismod.</p>
                        <p class="color-cyan">Donec ullamcorper nulla non metus auctor fringilla.</p>
                        <p class="color-green">Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis.</p>
                        <p class="color-orange">Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
                        <p class="color-amethyst">Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
                        <p class="thin">Fusce dapibus, tellus ac cursus commodo, tortor mauris nibh.</p>
                        <p class="uppercase">Etiam porta sem malesuada magna mollis euismod.</p>
                        <p class="italic">Donec ullamcorper nulla non metus auctor fringilla.</p>
                        <p class="bold">Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis.</p>-->

                    </div>
                    <!-- /tile body -->
                </section>
                <!-- /tile -->

            </div>
            <!-- /col 4 -->

        </div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(10)").addClass("open");
        </script>