<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>拜访捐赠方情况列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目捐赠方管理</li>
            <li class="active">拜访捐赠方情况列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
	<div id="rightstyle02" class="row">
		<div class="col-md-12">
			<section class="tile color transparent-black">
			</section>
            <section class="tile color transparent-black">	
                <div class="tile-body nopadding">				
				<?php if(!empty($this->company_list)){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                        <thead>
                            <tr>
                                <td width="20%">序号</td>
                                <td width="15%">时间</td>
                                <td width="15%">地点</td>
                                <td width="15%">纪念品</td>
                                <td width="10%">操作</td>
                            </tr>
                        </thead>
                      <tbody>
					  <?php 
						foreach($this->huodong_list as $k=>$v){?>
                        <tr>
                            <td><?php echo $v['id'];?></td>
                            <td><?php echo $v['visit_date_time'];?></td>
                            <td><?php echo $v['visit_addr'];?></td>
                            <td><?php echo $v['visit_gift'];?></td>
                            <td>
                            <a href="/management/admin/editppvisit?id=<?php echo $v['id'];?>">
                                <button type="button" class="btn btn-greensea margin-bottom-20">编辑</button>
                            </a>
                            <a href="/management/admin/delppvisit?id=<?php echo $v['id'];?>&pp_id=<?php echo $v['pp_id'];?>" onclick="javascript:if(!confirm('确定要删除选择的信息吗？\n此操作不可以恢复！')) { return false; }">
                                <button type="button" class="btn btn-danger margin-bottom-20">删除</button>
                            </a>
                            </td>
                        </tr>
					   <?php }?>
                       </tbody>
					</table>
				</div>
				<div class="tile-footer bg-transparent-black-2">
				<div class="row">
					<!--<div class="page col-md-12" align="right">
						共  <?php /*echo $this->total;*/?> 条          <?php /*echo $this->page;*/?>
                    </div>-->

                    <div class="row">
                        <div class="page col-md-12" style="margin:10px;" >
                            <a href="/management/admin/addppvisit?pp_id=<?php echo $this->pp_id;?>">继续添加（<?php echo $this->pp_info['ppname'];?>）学校活动信息</a>
                        </div>
                    </div>
				 <?php }else{?>
				 	<div class="row">
                        <div class="page col-md-12" style="margin:20px; ">暂无捐赠方（<?php echo $this->pp_info['ppname'];?>）参加学校活动信息！<a href="/management/admin/addppvisit?pp_id=<?php echo $this->pp_id;?>">点击添加</a></div>
                    </div>
				 <?php }?>
		  </div>
		</div> 
			</section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(10)").addClass("open");
    </script>