<!-- page header -->
<div class="pageheader"><h2><i class="fa fa-tachometer"></i> Dashboard<span>联系人</span></h2></div>
<!-- /page header -->		
    <div id="main" class="main">
        <div class="row">
            <!-- col 8 -->
            <div class="col-md-12">

                <!-- tile -->
                <section class="tile color transparent-white">

                    <!-- tile header -->
                    <div class="tile-header">
                        <h4><strong>人立方 - <?php echo $this->ppinfo[0]['ppname'];?> </strong> </h4>
                        <div class="controls">
                            <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                            <a href="#" class="remove"><i class="fa fa-times"></i></a>
                        </div>
                    </div>
                    <!-- /tile header -->

                    <!-- tile body -->
                    <div class="tile-body">
                        <div id="test" style="height:600px;width:1000px;"></div>
                    </div>
                    <!-- /tile body -->

                </section>
                <!-- /tile -->

            </div>
            <!-- /col 8 -->
        </div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script src="/include/management/js/echarts-all.js"></script>
        <script language="javascript">
            $(".menu li:eq(10)").addClass("open");

            var myChart = echarts.init(document.getElementById('test'));
            option = {
                title : {
                    text: '人物关系：<?php echo $this->ppinfo[0]['ppname'];?>',
                    subtext: '数据来自基金会管理系统',
                    x:'right',
                    y:'bottom'
                },
                tooltip : {
                    trigger: 'item',
                    formatter: '{a} : {b}'
                },
                toolbox: {
                    show : true,
                    feature : {
                        restore : {show: true},
                        magicType: {show: true, type: ['force', 'chord']},
                        saveAsImage : {show: true}
                    }
                },
                legend: {
                    x: 'left',
                    data:['项目'<?php if(!empty($this->pp_company_list)){echo ",'下属子公司'";}?>,'相关捐赠方']
                },
                series : [
                    {
                        type:'force',
                        name : "人物关系",
                        ribbonType: false,
                        categories : [
                            {
                                name: '人物'
                            },
                            {
                                name: '项目',
                                symbol: 'diamond'
                            },
                            <?php
                                if(!empty($this->pp_company_list)){
                                    echo "{
                                    name: '下属子公司',
                                    symbol: 'diamond'
                                },";
                                }
                            ?>
                            <?php
                               if(!empty($this->pm_mg_info_1DAO)){
                                   echo "{
                                   name: '相关项目',
                                   symbol: 'diamond'
                               },";
                               }
                           ?>
                            {
                                name:'相关捐赠方'
                            },
                            <?php
                               if(!empty($this->pm_mg_info_activeDAO)){
                                   echo "{
                                   name: '校方联系人',
                                   symbol: 'diamond'
                               },";
                               }
                           ?>
                        ],
                        itemStyle: {
                            normal: {
                                label: {
                                    show: true,
                                    textStyle: {
                                        color: '#333'
                                    }
                                },
                                nodeStyle : {
                                    brushType : 'both',
                                    borderColor : 'rgba(255,215,0,0.4)',
                                    borderWidth : 1
                                }
                            },
                            emphasis: {
                                label: {
                                    show: false
                                    // textStyle: null      // 默认使用全局文本样式，详见TEXTSTYLE
                                },
                                nodeStyle : {
                                    //r: 30
                                },
                                linkStyle : {}
                            }
                        },
                        minRadius : 15,
                        maxRadius : 25,
                        gravity: 1.1,
                        scaling: 1.2,
                        draggable: false,
                        linkSymbol: 'arrow',
                        steps: 10,
                        coolDown: 0.9,
                        //preventOverlap: true,
                        nodes:[
                            /*{
                                category:0, name: '<?php echo $this->ppinfo[0]['ppname'];?>', value : 10,
                                symbol : 'image://http://www.damndigital.com/wp-content/uploads/2010/12/steve-jobs.jpg',
                                symbolSize: [60, 35],
                                draggable: true,
                                itemStyle: {
                                    normal: {
                                        label: {
                                            position: 'right',
                                            textStyle: {
                                                color: 'black'
                                            }
                                        }
                                    }
                                }
                            },*/
                            {category:0, name: '<?php echo $this->ppinfo[0]['ppname'];?>',value : 20,draggable: true},
                            <?php
                                if($this->pm_mg_infoDAO[0]['pm_name'] != ''){
                                    echo "{category:1, name: '".$this->pm_mg_infoDAO[0]['pm_name']."',value : 2},";
                                }
                            ?>

                            <?php
                                if($this->pp_company_list){
                                    foreach($this->pp_company_list as $k => $v){
                                        echo "{category:2, name: '".$v['company_name']."',value : ".rand(1,9)."},";
                                    }
                                }
                            ?>

                            <?php
                                if(!empty($this->pm_mg_info_1DAO)){
                                    foreach($this->pm_mg_info_1DAO as $k => $v){
                                        echo "{category:3, name:  '".$v['pm_name']."',value : ".rand(1,5)."},";
                                    }
                                }
                            ?>

                            <?php
                                if($this->juanzengfang){
                                    foreach($this->juanzengfang as $k => $v){
                                        echo "{category:4, name: '".$v."',value : ".rand(1,9)."},";
                                    }
                                }
                            ?>

                            <?php
                               if(!empty($this->pm_mg_info_activeDAO)){
                                   foreach($this->pm_mg_info_activeDAO as $k => $v){
                                        echo "{category:5, name: '".$v['a_contact_person']."',value : ".rand(1,9)."},";
                                    }
                               }
                            ?>
                        ],
                        links : [
                            <?php
                                if($this->pm_mg_infoDAO[0]['pm_name'] != ''){
                                   echo "{source : '".$this->ppinfo[0]['ppname']."', target : '".$this->pm_mg_infoDAO[0]['pm_name']."', weight : 1, name: '项目".$this->ppinfo[0]['pp_cate']."', itemStyle: {
                                normal: {
                                    width: 1.5,
                                    color: 'red'
                                }
                            }},";
                                }
                            ?>

                            <?php
                                if($this->juanzengfang){
                                    foreach($this->juanzengfang as $k => $v){
                                        echo "{source : '".$v."', target : '".$this->pm_mg_infoDAO[0]['pm_name']."', weight : ".rand(1,9).", name: '其他捐赠方'},";
                                    }
                                }
                            ?>

                            <?php
                                if($this->pp_company_list){
                                    foreach($this->pp_company_list as $k => $v){
                                        echo "{source : '".$v['company_name']."', target : '".$this->ppinfo[0]['ppname']."', weight : ".rand(1,3).", name: '下属子公司'},";
                                    }
                                }
                            ?>

                            <?php
                                if(!empty($this->pm_mg_info_1DAO)){
                                    foreach($this->pm_mg_info_1DAO as $k => $v){
                                        echo "{source : '".$v['pm_name']."', target : '".$this->pm_mg_infoDAO[0]['pm_name']."', weight : ".rand(1,3).", name: '相关项目'},";
                                    }
                                }
                            ?>

                            <?php
                               if(!empty($this->pm_mg_info_activeDAO)){
                                   foreach($this->pm_mg_info_activeDAO as $k => $v){
                                        echo "{source : '".$v['a_contact_person']."', target : '".$this->ppinfo[0]['ppname']."', weight : ".rand(1,3).", name: '校方联系人'},";
                                    }
                               }
                            ?>
                        ]
                    }
                ]
            };

            myChart.setOption(option);
            /*var ecConfig = require('echarts/config');
            function focus(param) {
                var data = param.data;
                var links = option.series[0].links;
                var nodes = option.series[0].nodes;
                if (
                    data.source != null
                    && data.target != null
                ) { //点击的是边
                    var sourceNode = nodes.filter(function (n) {return n.name == data.source})[0];
                    var targetNode = nodes.filter(function (n) {return n.name == data.target})[0];
                    console.log("选中了边 " + sourceNode.name + ' -> ' + targetNode.name + ' (' + data.weight + ')');
                } else { // 点击的是点
                    console.log("选中了" + data.name + '(' + data.value + ')');
                }
            }
            myChart.on(ecConfig.EVENT.CLICK, focus);

            myChart.on(ecConfig.EVENT.FORCE_LAYOUT_END, function () {
                console.log(myChart.chart.force.getPosition());
            });*/
        </script>