<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>
	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
				<h4>项目筹资管理<span class="font_#0474d6"> >> </span><span class="font_#0474d6_big">添加筹资信息</span></h4>
				<section class="tile color transparent-black">
			<div class="detailedbox tile-body">
				<form class="form-horizontal" action="addrschouzi" method="post" encType="multipart/form-data">
				<div class="form-group">
						<label class="col-sm-2 control-label" for="input01">项目名称：</label>
                        <div class="col-sm-9">
                          <input class="form-control" type="text" name="pname" />
                        </div>
						<span class="col-sm-1" > * </span>
				</div>	
				<div class="form-group">
					    <label class="col-sm-2 control-label" for="input02">所属部门：</label>
						<div class="col-sm-9">
							<select class="chosen-select chosen-transparent form-control" name="department">
								<option value="" >请选择类型</option>
								<?php if($this->departmentlist != ""){
								foreach ($this->departmentlist as $k => $v){?>
									<option value="<?php echo $v['id']?>" ><?php echo $v['pname']?></option>
								<?php }}?>
							</select>
						</div>
						<span class="col-sm-1" > * </span>
				</div>
				<div class="form-group">
					    <label class="col-sm-2 control-label" for="input03">项目分类：</label>
						<div class="col-sm-9">
							<select class="chosen-select chosen-transparent form-control" name="pm_cate">
								<option value="" >请选择类型</option>
								<?php if($this->pcatelist != ""){
								foreach ($this->pcatelist as $k => $v){?>
									<option value="<?php echo $v['id']?>" ><?php echo $v['catename']?></option>
								<?php }}?>
							</select>
						</div>
						<span class="col-sm-1" > * </span>
				</div>
				<div class="form-group">
					    <label class="col-sm-2 control-label" for="input04">宣传推动期：</label>
						<div class="col-sm-9">
							<select class="chosen-select chosen-transparent form-control" name="tuidongqi">
								<option value="" >请选择类型</option>
								<option value="初期" >初期</option>
								<option value="中期" >中期</option>
								<option value="末期" >末期</option>
							</select>
						</div>
				</div>
					
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input05">项目孵化期：</label>
						<div class="col-sm-9">
							<select class="chosen-select chosen-transparent form-control" name="fuhuaqi">
								<option value="" >请选择类型</option>
								<option value="初期" >初期</option>
								<option value="中期" >中期</option>
								<option value="末期" >末期</option>
							</select>
						</div>
					</div>
					
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input06">项目签约日期：</label>
						<div class="col-sm-9">
							<input class="form-control" type="text"  id="dateinput"  name="qianyuedate"  size="14"/>
						</div>
					</div>
					
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input07">项目协议电子版：</label>
						<div class="col-sm-9">
							<input id="exampleInputFile" type="file" name="xieyidianzi" />
							<span class="help-block"> 电子版为图片格式存储，文件后缀名为*.jpg,*.gif,*.png</span>
						</div>
					</div>
					
					
					
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input08">项目起始日期：</label>
						<div class="col-sm-9">
							<input class="form-control" type="text"  id="dateinput2"  name="qishi"  size="14"/>
						</div>
						<span class="col-sm-1" > * </span>
					</div>
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input09">项目截止日期：</label>
						<div class="col-sm-9">
							<input class="form-control" type="text"  id="dateinput3"  name="jiezhi"  size="14"/>
						</div>
					</div>
					
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input10">协议捐赠金额：</label>
						<div class="col-sm-8">
							<input class="form-control" type="text"  name="jiner"  size="14"/>
						</div>
						<span class="col-sm-2" >元&nbsp;&nbsp;&nbsp;&nbsp;  * 例如：3000000元</span>
					</div>
					
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input11">项目反馈日期：</label>
						<div class="col-sm-9">
							<input class="form-control" type="text"  id="dateinput1"  name="fankui"  size="14"/>
						</div>
					</div>
					
					
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input12">留本基金：</label>
						<div class="col-sm-2">
							<label class="radio-inline"><input type="radio" name="liuben" value="1" size="14"/> 是  </label>
							<label class="radio-inline"><input type="radio" name="liuben" value="0"  checked="checked"  size="14"/> 否  </label>
						</div>
						<span class="col-sm-1" > * </span>
					</div>
					
					
					<div class="form-group">
					    <label class="col-sm-2 control-label" for="input13">捐赠仪式：</label>
						<div class="col-sm-9">
							<textarea class="ckeditor" name="yishi"></textarea>
						</div>
					</div>
					
					
					<div class="form-group transparent-editor">
					    <label class="col-sm-2 control-label" for="input14">备注：</label>
						<div class="col-sm-9">
							<textarea class="ckeditor form-control" name="beizhu"></textarea>
						</div>
					</div>
					
					
					<div class="form-group form-footer">
						<div class="col-sm-offset-5 col-sm-7">
							<input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; 
							<input class="btn btn-default" type="reset" value="重 置" /> 
						</div>
					</div>
			</form>
			</div>
		 </section>
			</div>
		</div>
	
		<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>
			
			<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput1').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>
			
			
			<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput2').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>
			
			
			<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput3').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>