<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>认领列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目基本信息（筹资）管理</li>
            <li class="active">筹资列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<!--<h4 class="col-md-12">项目筹资管理<span class="font_red"> >> </span><span class="font_red_big">筹资列表</span></h4>-->
			<div class="col-md-12">
			<section class="tile color transparent-black">
			<div class="tile-body">

                <form action="#" method="post">
                    <div class="form-group">

                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label for="input05">项目名称：</label>
                                <input type="text" class="form-control" name="pname" />
                            </div>

                            <div class="form-group col-sm-3">
                                <label for="input02"> </label>
                                <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                            </div>
                        </div>

                    </div>
                </form>

			</div>
			</section>
			<section class="tile color transparent-black">
				<div class="tile-body nopadding">
				<?php if($this->renling_weirenling_list != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="24%">项目名称</td>
						<td width="12%">部门名称</td>
						<td width="20%">项目分类</td>
						<!--<td width="18%">项目签约日期</td>-->
						<td width="13%">协议捐赠金额</td>
						<td width="13%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php 
						foreach($this->renling_weirenling_list as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['pname'];?>&nbsp;</td>
							<td><?php  foreach ($this->departmentlist as $kk => $vv){
								if($vv['id'] == $v['department']){ echo $vv['pname'];}
								}?>&nbsp;</td>
							<td><?php  foreach ($this->pcatelist as $kk => $vv){
								if($vv['id'] == $v['cate']){ echo $vv['catename'];}
								}?>&nbsp;</td>
								
							<!--<td><?php /*echo substr($v['pm_qianyue_datetime'],0,10);*/?>&nbsp;</td>-->
							<td><?php echo $v['pm_xieyi_juanzeng_jiner'];?>&nbsp;元</td>
							<td>
                                <a href="/management/chouzi/editchouzi?id=<?php echo $v['id'];?>">
                                    <button class="btn btn-greensea margin-bottom-20" type="button">认领该项目</button>
                                </a>

                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer bg-transparent-black-2">
					<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条项目认领信息          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无网站资讯！</div>
				 <?php }?>
				 </div>
				 </div>
				 </section>
		  </div>
		</div>

		
		    <script language="javascript">
                $(".menu li:eq(1)").addClass("open");
			</script>
