<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑筹资信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目筹资管理</li>
            <li class="active">编辑筹资信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->
	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
				<section class="tile color transparent-white">
				<div class="detailedbox tile-body">
				<form class="form-horizontal" action="editrschouzi" id="form1"  method="post" encType="multipart/form-data">
					<div class="form-group">
							<label class="col-sm-2 control-label" for="input01">项目名称：</label>
							<div class="col-sm-4">
								<input class="form-control" type="text" name="pname" readonly value="<?php echo $this->chouzi[0]['pname'];?>"/>
							</div>
							<span class="col-sm-1" > * </span>
					</div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input02">所属项目：</label>
                        <div class="col-sm-4">
                            <select class="chosen-select chosen-transparent form-control" name="pm_id">
                                <option value="0" >请选择所属项目名称</option>
                                <?php if($this->chouzi_lists != ""){
                                    foreach ($this->chouzi_lists as $k => $v){?>
                                        <option value="<?php echo $v['id']?>" <?php if($v['id'] ==$this->chouzi[0]['parent_pm_id']) echo "selected='selected'";?>><?php echo $v['pname']?></option>
                                    <?php }}?>
                            </select>
                        </div>
                        <span class="col-sm-2" > 如果有父类项目请选择此项 选填</span>
                    </div>
                    <!--<input class="form-control" type="hidden" name="parent_pm_id_path"  value="<?php /*echo $this->chouzi[0]['pname'];*/?>"/>-->


                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input00">项目编号：</label>
                        <div class="col-sm-4">
                            <input class="form-control" type="text" readonly name="bianhao" value="<?php echo $this->chouzi[0]['pid'];?>"/>
                        </div>
                        <span class="col-sm-2" > 编号自动生成</span>

                    </div>


                    <div class="form-group">
							<label class="col-sm-2 control-label" for="input02">所属部门：</label>
							<div class="col-sm-4">
								<select class="chosen-select chosen-transparent form-control" name="department">
									<option value="" >请选择所属部门</option>
									<?php if($this->departmentlist != ""){
									foreach ($this->departmentlist as $k => $v){?>
										<option value="<?php echo $v['id']?>" <?php if($this->chouzi[0]['department'] == $v['id']){echo "selected='selected'";}?>><?php echo $v['pname']?></option>
									<?php }}?>
								</select>
							</div>
							<span class="col-sm-1" > * </span>
					</div>

                    <?php
                        /**
                         * 递归实现无限极分类
                         * @param $array 分类数据
                         * @param $pid 父ID
                         * @param $level 分类级别
                         * @return $list 分好类的数组 直接遍历即可 $level可以用来遍历缩进
                         */

                        function generateTree($arr, $id, $step){
                            static $tree=[];
                            foreach($arr as $key=>$val) {
                                if($val['t_cate_pid'] == $id) {
                                    $flg = str_repeat('|－－',$step);
                                    $val['t_cate_name'] = $flg.$val['t_cate_name'];
                                    $tree[] = $val;
                                    generateTree($arr , $val['t_cate_id'] ,$step+1);
                                }
                            }
                            return $tree;
                        }
                    ?>

					<div class="form-group">
							<label class="col-sm-2 control-label" for="input03">项目分类：</label>
							<div class="col-sm-4">
                                <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_cate[]" id="pm_cate">
                                    <option value="" >请选择项目类型</option>
                                    <?php if($this->pcatelist != ""){
                                        $tree = generateTree($this->pcatelist, 0, 0);
                                        foreach ($tree as $val){
                                            echo $str .='<option value="'.$val['t_cate_id'].'"';
                                            if(in_array($val, explode(',',$this->chouzi[0]['pm_cate'])))
                                            {
                                                $str .=" selected='selected'";
                                            }
                                            $str .= ">".$val['t_cate_name'].'</option>';
                                            echo $str;
                                            $str = '';
                                        }
                                    }?>
                                </select>
							</div>
							<span class="col-sm-1" > * </span>
					</div>


                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">项目负责人：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_fzr[]" id="pm_fzr">
                                <?php if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                        <option value="<?php echo $k?>" <?php
                                        if(!empty($this->chouzi[0]['pm_fzr'])){
                                            foreach(explode(',',$this->chouzi[0]['pm_fzr']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }?>><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">项目负责人邮箱：</label>
                        <div class="col-sm-3">
                            <input class="form-control" value="<?php /*echo $this->chouzi[0]['pm_fzr_email']*/?>" type="text"  name="pm_fzr_email"  size="14"/>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">项目负责人电话：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_fzr_tel']*/?>" type="text"  name="pm_fzr_tel"  size="14"/>
                        </div>
                    </div>-->


                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">项目联络人：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_llr[]" id="pm_llr">
                                <?php if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                        <option value="<?php echo $k?>" <?php
                                        if(!empty($this->chouzi[0]['pm_llr'])){
                                            foreach(explode(',',$this->chouzi[0]['pm_llr']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }?>><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">联络人邮箱：</label>
                        <div class="col-sm-3">
                            <input class="form-control" value="<?php /*echo $this->chouzi[0]['pm_llr_email']*/?>" type="text"  name="pm_llr_email"  size="14"/>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">联络人电话：</label>
                        <div class="col-sm-3">
                            <input class="form-control" value="<?php /*echo $this->chouzi[0]['pm_llr_tel']*/?>" type="text"  name="pm_llr_tel"  size="14"/>
                        </div>
                    </div>-->

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">执行负责人：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="execute_fzr[]" id="execute_fzr">
                                <?php if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                        <option value="<?php echo $k?>" <?php
                                        if(!empty($this->chouzi[0]['execute_fzr'])){
                                            foreach(explode(',',$this->chouzi[0]['execute_fzr']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }?>><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">使用联络人：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="execute_llr[]" id="execute_llr">
                                <?php if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                        <option value="<?php echo $k?>" <?php
                                        if(!empty($this->chouzi[0]['execute_llr'])){
                                            foreach(explode(',',$this->chouzi[0]['execute_llr']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }?>><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">筹款负责人：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_ckfzr[]" id="pm_ckfzr">
                                <?php /*if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){*/?>
                                        <option value="<?php /*echo $k*/?>" <?php
/*                                        if(!empty($this->chouzi[0]['pm_ckfzr'])){
                                            foreach(explode(',',$this->chouzi[0]['pm_ckfzr']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }*/?>><?php /*echo $v*/?></option>
                                    <?php /*}}*/?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>-->

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">筹款负责人邮箱：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_ckfzr_email']*/?>" type="text"  name="pm_ckfzr_email"  size="14"/>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">筹款负责人电话：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_ckfzr_tel']*/?>"  type="text"  name="pm_ckfzr_tel"  size="14"/>
                        </div>
                    </div>-->

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">捐赠方：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_jzf[]" id="pm_jzf">
                                <?php /*if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){*/?>
                                        <option value="<?php /*echo $k*/?>" <?php
/*                                        if(!empty($this->chouzi[0]['pm_jzf'])){
                                            foreach(explode(',',$this->chouzi[0]['pm_jzf']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }*/?>><?php /*echo $v*/?></option>
                                    <?php /*}}*/?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>-->

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">捐赠方邮箱：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_jzf_email']*/?>" type="text"  name="pm_jzf_email"  size="14"/>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">捐赠方电话：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_jzf_tel']*/?>" type="text"  name="pm_jzf_tel"  size="14"/>
                        </div>
                    </div>-->

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">捐赠联络人：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_jzfllr[]" id="pm_jzfllr">
                                <?php /*if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){*/?>
                                        <option value="<?php /*echo $k*/?>" <?php
/*                                        if(!empty($this->chouzi[0]['pm_jzfllr'])){
                                            foreach(explode(',',$this->chouzi[0]['pm_jzfllr']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }*/?>><?php /*echo $v*/?></option>
                                    <?php /*}}*/?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>-->

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">捐赠方联络人邮箱：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_jzfllr_email']*/?>" type="text"  name="pm_jzfllr_email"  size="14"/>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">捐赠方联络人电话：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_jzfllr_tel']*/?>"  type="text"  name="pm_jzfllr_tel"  size="14"/>
                        </div>
                    </div>-->

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">实际捐赠方：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_sjjzf[]" id="pm_sjjzf">
                                <?php /*if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){*/?>
                                        <option value="<?php /*echo $k*/?>" <?php
/*                                        if(!empty($this->chouzi[0]['pm_sjjzf'])){
                                            foreach(explode(',',$this->chouzi[0]['pm_sjjzf']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }*/?>><?php /*echo $v*/?></option>
                                    <?php /*}}*/?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>-->

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">实际捐赠方邮箱：</label>
                        <div class="col-sm-3">
                            <input class="form-control" value="<?php /*echo $this->chouzi[0]['pm_sjjzf_email']*/?>"  type="text"  name="pm_sjjzf_email"  size="14"/>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">实际捐赠方电话：</label>
                        <div class="col-sm-3">
                            <input class="form-control" value="<?php /*echo $this->chouzi[0]['pm_sjjzf_tel']*/?>" type="text"  name="pm_sjjzf_tel"  size="14"/>
                        </div>
                    </div>-->


                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">实际捐赠方联络人：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_sjjzfllr[]" id="pm_sjjzfllr">
                                <?php /*if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){*/?>
                                        <option value="<?php /*echo $k*/?>" <?php
/*                                        if(!empty($this->chouzi[0]['pm_sjjzfllr'])){
                                            foreach(explode(',',$this->chouzi[0]['pm_sjjzfllr']) as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }*/?>><?php /*echo $v*/?></option>
                                    <?php /*}}*/?>
                            </select>
                        </div>
                        <span class="col-sm-2 addpp" >添加人员信息</span>
                    </div>-->

                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">实际捐赠方联络人邮箱：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_sjjzfllr_email']*/?>" type="text"  name="pm_sjjzfllr_email"  size="14"/>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">实际捐赠方联络人电话：</label>
                        <div class="col-sm-3">
                            <input class="form-control"  value="<?php /*echo $this->chouzi[0]['pm_sjjzfllr_tel']*/?>"  type="text"  name="pm_sjjzfllr_tel"  size="14"/>
                        </div>
                    </div>-->

					<!--<div class="form-group">
							<label class="col-sm-2 control-label" for="input04">宣传推动期：</label>
							<div class="col-sm-4">
								<select class="chosen-select chosen-transparent form-control" name="tuidongqi">
									<option value="" >请选择类型</option>
									<option value="初期" <?php /*if($this->chouzi[0]['pm_tuidongqi'] == "初期"){echo "selected='selected'";}*/?>>初期</option>
									<option value="中期" <?php /*if($this->chouzi[0]['pm_tuidongqi'] == "中期"){echo "selected='selected'";}*/?>>中期</option>
									<option value="末期" <?php /*if($this->chouzi[0]['pm_tuidongqi'] == "末期"){echo "selected='selected'";}*/?>>末期</option>
								</select>
							</div>
							<span class="col-sm-1" > * </span>
					</div>
						
					<div class="form-group">
							<label class="col-sm-2 control-label" for="input05">项目孵化期：</label>
							<div class="col-sm-4">
								<select class="chosen-select chosen-transparent form-control" name="fuhuaqi">
									<option value="" >请选择类型</option>
									<option value="初期" <?php /*if($this->chouzi[0]['pm_fuhuaqi'] == "初期"){echo "selected='selected'";}*/?>>初期</option>
									<option value="中期" <?php /*if($this->chouzi[0]['pm_fuhuaqi'] == "中期"){echo "selected='selected'";}*/?>>中期</option>
									<option value="末期" <?php /*if($this->chouzi[0]['pm_fuhuaqi'] == "末期"){echo "selected='selected'";}*/?>>末期</option>
								</select>
							</div>
							<span class="col-sm-1" > * </span>
					</div>-->
						
					<!--<div class="form-group">
							<label class="col-sm-2 control-label" for="input06">项目签约日期：</label>
							<div class="col-sm-4">
								<input class="form-control" type="text"  id="dateinput"  value="<?php /*echo $this->chouzi[0]['pm_qianyue_datetime'];*/?>"  name="qianyuedate"  size="14"/>
							</div>
							<span class="col-sm-1" > * </span>
					</div>
						
					<div class="form-group">
							<label class="col-sm-2 control-label" for="input07">项目协议电子版：</label>
							<div class="col-sm-4">
								<input id="exampleInputFile" type="file" name="xieyidianzi" />
							</div>
							<div class="col-sm-1"><?php /*if($this->chouzi[0]['pm_xieyii_dianziban'] != ""){*/?><a class="btn btn-default" target="_blank" href="<?php /*echo $this->chouzi[0]['pm_xieyii_dianziban'];*/?>"><strong>点击下载</strong></a><?php /*}else{*/?>
									暂无项目协议电子版
								<?php /*}*/?></div>
							<span class="col-sm-1" > * </span>
					</div>
						
					<div class="form-group">
						<label class="col-sm-2 control-label" for="input08">项目反馈日期：</label>
						<div class="col-sm-4">
							<input class="form-control" type="text"  id="dateinput1"  value="<?php echo $this->chouzi[0]['pm_fankui_datetime'];?>"  name="fankui"  size="14"/>
						</div>
						<span class="col-sm-1" > * </span>
					</div>-->

                    <!--<div class="form-group">
							<label class="col-sm-2 control-label" for="input09">项目限期：</label>
							<div class="col-sm-4">
								<input class="form-control" type="text" name="xianqi"   value="<?php /*echo $this->chouzi[0]['pm_qixian'];*/?>" size="14"/>
							</div>
							<span class="col-sm-2" >* 例如：45天。</span>
					</div>-->

                    <!--<div class="form-group">
                        <label class="col-sm-2 control-label" for="input09">协议起始年份：</label>
                        <div class="col-sm-4">
                            <select name="qishi" class="form-control">
                                <option name="qishi" value="">请选择</option>
                                <?php /*for($i=1990; $i<2050; $i++){*/?>
                                    <option name="qishi" value="<?php /*echo $i;*/?>" <?php /*if($i==$this->chouzi[0]['pm_qishi_datetime']){echo 'selected="selected"';}*/?>><?php /*echo $i;*/?></option>
                                <?php /*}*/?>
                            </select>
                        </div>
                        <span class="col-sm-1" > * </span>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input10">协议截止年份：</label>
                        <div class="col-sm-4">
                            <select name="jiezhi" class="form-control">
                                <option name="jiezhi" value="">请选择</option>
                                <?php /*for($i=1990; $i<2050; $i++){*/?>
                                    <option name="jiezhi" value="<?php /*echo $i;*/?>" <?php /*if($i==$this->chouzi[0]['pm_jiezhi_datetime']){echo 'selected="selected"';}*/?>><?php /*echo $i;*/?></option>
                                <?php /*}*/?>
                            </select>
                        </div>
                        <span class="col-sm-1" > * </span>
                    </div>
						
					<div class="form-group">
							<label class="col-sm-2 control-label" for="input11">协议捐赠金额：</label>
							<div class="col-sm-4">
								<input class="form-control" type="text"  name="jiner"  value="<?php /*echo $this->chouzi[0]['pm_xieyi_juanzeng_jiner'];*/?>" size="14"/>
							</div>
							<span class="col-sm-2">元&nbsp;&nbsp;&nbsp;&nbsp;  * 例如：3000000元 </span>
					</div>-->

					<div class="form-group">
						<label class="col-sm-2 control-label" for="input10">资金使用限额：</label>
						<div class="col-sm-1">
							<input class="form-control" type="text"  name="percent" value="<?php echo $this->chouzi[0]['percent'];?>"  size="3"/>
						</div>
						<span class="col-sm-2" >% &nbsp;&nbsp;&nbsp;&nbsp;* 例如：设置为30%，每次支出使用不能超过余额的30%。</span>
					</div>
						
						
					<div class="form-group">
							<label class="col-sm-2 control-label" for="input12">留本基金：</label>
							<div class="col-sm-2">
								<label class="radio-inline"><input type="radio" name="liuben" value="1" <?php if($this->chouzi[0]['pm_liuben'] == 1){echo " checked='checked'";}?> size="14"/> 是 </label> 
								<label class="radio-inline"><input type="radio" name="liuben" value="0" <?php if($this->chouzi[0]['pm_liuben'] == 0){echo " checked='checked'";}?> size="14"/> 否 </label> 
							</div>
							<span class="col-sm-1" >  </span>
					</div>


                    <!--<div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">捐赠仪式：</label>
                        <div class="col-sm-9">
                            <textarea parsley-validation-minlength="1" name="yishi" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php /*echo $this->chouzi[0]['pm_yishi'];*/?></textarea>
                        </div>
                    </div>-->

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">是否立项：</label>
                        <div class="col-sm-3">
                            <div class="checkbox check-transparent" style="padding-left:0px;">
                                <input type="checkbox" id="opt03" name="is_lixiang" value="1" <?php if(preg_match("/1/", $this->rate_list_new[0]['pm_rate']))echo 'checked=""';?>>
                                <label for="opt03">已立项</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">捐赠用途（备注）：</label>
                        <div class="col-sm-9">
                            <script type="text/plain" id="beizhu" name="beizhu" style="width:100%;height:240px;"><?php echo htmlspecialchars_decode($this->chouzi[0]['beizhu']);?></script>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">项目介绍：</label>
                        <div class="col-sm-9">
                            <script type="text/plain" id="introduce" name="introduce" style="width:100%;height:240px;"><?php echo htmlspecialchars_decode($this->chouzi[0]['introduce']);?></script>
                        </div>
                    </div>

                    <div class="form-group transparent-editor">
                        <label class="col-sm-2 control-label" for="input14">项目负责人变更：</label>
                        <div class="col-sm-9">
                            <textarea parsley-validation-minlength="1" name="history_pm_fzr" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php echo $this->chouzi[0]['history_pm_fzr'];?></textarea>
                        </div>
                    </div>

						<input type="hidden" name="id" value="<?php echo $this->chouzi[0]['id'];?>"/>
						<input type="hidden" name="oldpic" value="<?php echo $this->chouzi[0]['pm_xieyii_dianziban'];?>"/>
						
					<div class="form-group form-footer">
							<div class="col-sm-offset-5 col-sm-7">
								<input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;
								<input class="btn btn-default" type="reset" value="重 置" /> 
							</div>
					</div>
				</form>
			  </div>
			  </section>
			</div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="/include/management/css/bootstrap-select.min.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="/include/management/js/bootstrap-select.min.js"></script>

        <script language="javascript">
            $("#xmxxbj").addClass("open");

            /*$('#pm_fzr').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#pm_llr').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#execute_fzr').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#execute_llr').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#pm_ckfzr').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#pm_jzf').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#pm_jzfllr').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#pm_sjjzf').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#pm_sjjzfllr').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            var str1='<?php echo $this->chouzi[0]['pm_fzr']?>';
            var arr1=str1.split(',');
            $('#pm_fzr').selectpicker('val', arr1);

            var str2='<?php echo $this->chouzi[0]['pm_llr']?>';
            var arr2=str2.split(',');
            $('#pm_llr').selectpicker('val', arr2);

            var str3='<?php echo $this->chouzi[0]['pm_ckfzr']?>';
            var arr3=str3.split(',');
            $('#pm_ckfzr').selectpicker('val', arr3);

            var str4='<?php echo $this->chouzi[0]['pm_jzf']?>';
            var arr4=str4.split(',');
            $('#pm_jzf').selectpicker('val', arr4);

            var str5='<?php echo $this->chouzi[0]['pm_jzfllr']?>';
            var arr5=str5.split(',');
            $('#pm_jzfllr').selectpicker('val', arr5);

            var str6='<?php echo $this->chouzi[0]['pm_sjjzf']?>';
            var arr6=str6.split(',');
            $('#pm_sjjzf').selectpicker('val', arr6);

            var str7='<?php echo $this->chouzi[0]['pm_sjjzfllr']?>';
            var arr7=str7.split(',');
            $('#pm_sjjzfllr').selectpicker('val', arr7);

            var str7='<?php echo $this->chouzi[0]['execute_fzr']?>';
            var arr7=str7.split(',');
            $('#execute_fzr').selectpicker('val', arr7);

            var str7='<?php echo $this->chouzi[0]['execute_llr']?>';
            var arr7=str7.split(',');
            $('#execute_llr').selectpicker('val', arr7);*/
        </script>