<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑财务系统对照</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>编辑财务系统对照</li>
            <li class="active">编辑财务系统对照</li>
        </ol>
    </div>

</div>
<!-- /page header -->
<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="editrscompare" id="form1" method="post" encType="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">项目编号：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="pm_id" value="<?php echo $this->ppinfo[0]['pm_id']?>"/>
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">项目名称：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="pm_name" value="<?php echo $this->ppinfo[0]['pm_name']?>"/>
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">财务项目编号：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="zw_xmbh" value="<?php echo $this->ppinfo[0]['zw_xmbh']?>"/>
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">财务项目名称：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="zw_xmmc" value="<?php echo $this->ppinfo[0]['zw_xmmc']?>"/>
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">财务部门编号：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="zw_bmbh" value="<?php echo $this->ppinfo[0]['zw_bmbh']?>"/>
                            </div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <!--<div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">备注：</label>
                            <div class="col-sm-9">
                                <textarea parsley-validation-minlength="1" name="pp_beizhu" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php /*echo $this->ppinfo[0]['pp_beizhu']*/?></textarea>
                            </div>
                        </div>-->

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">编辑权限授权码：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="qxsqm" value=""/>
                            </div>
                            <span class="col-sm-2" > * 编辑对照表需要输入编辑权限授权码</span>
                        </div>

                        <input type="hidden" name="id" value="<?php echo $this->ppinfo[0]['id'];?>" />
                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>