<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<link rel="stylesheet" href="/include/management/assets/css/vendor/animate/animate.css">
<link type="text/css" rel="stylesheet" media="all" href="/include/management/assets/js/vendor/mmenu/css/jquery.mmenu.all.css" />
<link rel="stylesheet" href="/include/management/assets/js/vendor/videobackground/css/jquery.videobackground.css">
<link rel="stylesheet" href="/include/management/assets/css/vendor/bootstrap-checkbox.css">

<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote-bs3.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen.min.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen-bootstrap.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/datepicker/css/bootstrap-datetimepicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpalette/bootstrap-colorpalette.css">
<link href="/include/management/assets/css/minimal.css" rel="stylesheet">

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>筹资列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目筹资管理</li>
            <li class="active">筹资列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">

			<div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="tile-body">
			<form action="#" method="get" name="search_form">
				<div class="form-group">

                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="pname" class=" control-label">项目名称：</label>
                            <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                <option value="">请选择项目名称</option>
                                <?php if($this->pmlist != ""){
                                    foreach ($this->pmlist as $k => $v){
                                        ?>
                                        <option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
                                    <?php }}?>
                            </select>
                            <input id="pname_info" type="hidden" name="pname" value=""/>
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="input02">项目进度选择：</label>
                            <select class="chosen-select-1 chosen-transparent form-control" name="rate[]">
                                <option value="" >请选择类型</option>
                                <?php if($this->rate_config != ""){
                                    foreach ($this->rate_config as $k => $v){?>
                                        <option value="<?php echo $k?>" ><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>

                    </div>

                    <div class="row">
                       <!-- <div class="form-group col-sm-3">
                                <label for="input03">项目起始日期：</label>
                                <input name="starttime" data-date-format="YYYY-MM-DD HH:mm:ss"  type="text" class="form-control" id="datepicker">
                        </div>
                        <div class="form-group col-sm-3">
                                <label for="input04">项目截止日期：</label>
                                <input type="text" name="endtime" data-date-format="YYYY-MM-DD HH:mm:ss" class="form-control" id="datepicker1">
                        </div>-->
                    </div>

                    <div class="row">
                        <div class="form-group col-sm-2">
                            <label for="input01">所属部门：</label>
                            <select class="form-control" name="department">
                                <option value="" >请选择类型</option>
                                <?php if($this->departmentlist != ""){
                                    foreach ($this->departmentlist as $k => $v){?>
                                        <option value="<?php echo $v['id']?>" ><?php echo $v['pname']?></option>
                                    <?php }}?>
                            </select>
                        </div>

                        <div class="form-group col-sm-2">
                            <label for="input02">项目类型：</label>
                            <select class="form-control" name="cate">
                                <option value="" >请选择类型</option>
                                <?php if($this->pcatelist != ""){
                                    foreach ($this->pcatelist as $k => $v){?>
                                        <option value="<?php echo $v['id']?>" ><?php echo $v['catename']?></option>
                                    <?php }}?>
                            </select>
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="input02"> </label>
                            <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                        </div>
                    </div>
				</div>
			</form>
			</div>
			</section>
			<section class="tile color transparent-white">
				<div class="tile-body nopadding">
				<?php if($this->chouzilist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="24%">项目名称</td>
                        <td width="20%">项目类型</td>
                        <td width="18%">项目进度</td>
						<!--<td width="12%">部门名称</td><td width="18%">项目签约日期</td>
						<td width="13%">协议捐赠金额</td>-->
                          <?php if (in_array($this->admininfo['admin_info']['admin_type'],array(0,1,2,3,4,5))){?>
						        <td width="13%">操作</td>
                          <?php }?>
					  </tr>
					</thead>
                    <tbody>
					  <?php 
						foreach($this->chouzilist as $k=>$v){?>
						 <tr>
						 	<td><a href="/management/chouzi/pminfo?id=<?php echo $v['id'];?>" target="_blank"><?php echo $v['pname'];?></a>&nbsp;</td>
                             <td><?php  foreach ($this->pcatelist as $kk => $vv){
                                     if($vv['id'] == $v['cate']){ echo $vv['catename'];}
                                 }?>&nbsp;</td>
							<!--<td><?php  foreach ($this->departmentlist as $kk => $vv){
								if($vv['id'] == $v['department']){ echo $vv['pname'];}
								}?>&nbsp;</td>
                             <!--
								
							<td><?php /*echo substr($v['pm_qianyue_datetime'],0,10);*/?>&nbsp;</td>
							<td><?php echo $v['pm_xieyi_juanzeng_jiner'];?>&nbsp;元</td>-->

                             <td>
                                 <?php if($v['pm_rate'] == ""){ ?>
                                     ---
                                 <?php }if(preg_match("/1/", $v['pm_rate'])){ ?>
                                     已立项&nbsp;
                                 <?php }if(preg_match("/2/", $v['pm_rate'])){?>
                                     已签约&nbsp;
                                 <?php }if(preg_match("/3/", $v['pm_rate'])){?>
                                     已到帐&nbsp;
                                 <?php }if(preg_match("/4/", $v['pm_rate'])){ ?>
                                     已执行&nbsp;
                                 <?php }if(preg_match("/5/", $v['pm_rate'])){?>
                                     已回馈&nbsp;
                                 <?php }if(preg_match("/6/", $v['pm_rate'])){?>
                                     已完结&nbsp;
                                 <?php }if(preg_match("/7/", $v['pm_rate'])){?>
                                     待催款&nbsp;
                                 <?php }if(preg_match("/8/", $v['pm_rate'])){?>
                                     正常执行&nbsp;
                                 <?php }if(preg_match("/9/", $v['pm_rate'])){?>
                                     待结项&nbsp;
                                 <?php }?>
                             </td>
                             <?php if (in_array($this->admininfo['admin_info']['admin_type'],array(0,1,2,3,4,5))){?>
                                <td>
                                    <a href="/management/chouzi/editchouzi?id=<?php echo $v['id'];?>">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">编辑</button>
                                    </a>
                                    &nbsp;&nbsp;
                                    <a href="/management/zijin/rateinfo/?pm_id=<?php echo $v['id'];?>">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">编辑进度</button>
                                    </a>
                                    &nbsp;&nbsp;
                                    <a href="#" onclick="alert('对不起，项目清单不提供删除功能，请联系管理员');">
                                        <button class="btn btn-danger margin-bottom-20" type="button">删除</button>
                                    </a>
                                </td>
                             <?php }?>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer">
					<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条筹资信息          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无网站资讯！<a href="/management/chouzi/addchouzi">点击添加</a></div>
				 <?php }?>
				 </div>

                        <div class="row">
                            <div class="form-group col-sm-3">
                                <label for="input02"></label>
                                <a href="/management/report/newchouzitoexcel?pname=<?php echo $this->pname;?>&cate=<?php echo $this->cate;?>&department_id=<?php echo $this->department;?>"><button class="btn btn-primary btn-block">导出Excel</button></a>
                            </div>
                        </div>

				 </div>
				 </section>
		  </div>
		</div>

        <script language="javascript">
            $(".menu li:eq(18)").addClass("open");
        </script>