<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<link rel="stylesheet" href="/include/management/assets/css/vendor/animate/animate.css">
<link type="text/css" rel="stylesheet" media="all" href="/include/management/assets/js/vendor/mmenu/css/jquery.mmenu.all.css" />
<link rel="stylesheet" href="/include/management/assets/js/vendor/videobackground/css/jquery.videobackground.css">
<link rel="stylesheet" href="/include/management/assets/css/vendor/bootstrap-checkbox.css">

<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote-bs3.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen.min.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen-bootstrap.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/datepicker/css/bootstrap-datetimepicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpalette/bootstrap-colorpalette.css">
<link href="/include/management/assets/css/minimal.css" rel="stylesheet">

<!-- bootstrap-switch-master 单选按钮 -->
<link rel="stylesheet" href="/include/management/bootstrap-switch-master/css/highlight.css">
<link rel="stylesheet" href="/include/management/bootstrap-switch-master/css/bootstrap-switch.min.css">
<link rel="stylesheet" href="/include/management/bootstrap-switch-master/css/main.css">

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>筹资列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目筹资管理</li>
            <li class="active">筹资列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">

			<div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="tile-body">
			<form action="#" method="get" name="search_form">
				<div class="form-group">

                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="pname" class=" control-label">项目名称：</label>
                            <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                <option value="">请选择项目名称</option>
                                <?php if($this->pmlist != ""){
                                    foreach ($this->pmlist as $k => $v){
                                        ?>
                                        <option value="<?php echo $v['pname'];?>" <?php if($_REQUEST['pname'] == $v['pname']){echo "selected='selected'";}?>><?php echo $v['pname'];?></option>
                                    <?php }}?>
                            </select>
                            <input id="pname_info" type="hidden" name="pname" value=""/>
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="input02">项目进度选择：</label>
                            <select class="chosen-select-1 chosen-transparent form-control" name="rate[]">
                                <option value="" >请选择类型</option>
                                <?php if($this->rate_config != ""){
                                    foreach ($this->rate_config as $k => $v){?>
                                        <option value="<?php echo $k?>" <?php if($_GET['rate'][0]==$k){echo 'selected="selected"';}?>><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="input02">项目负责人：<?php //var_dump($_REQUEST['pm_fzr'])?></label>
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_fzr[]" id="pm_fzr">
                                <?php if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                        <option value="<?php echo $k?>" <?php
                                        if(!empty($_REQUEST['pm_fzr'])){
                                            foreach($_REQUEST['pm_fzr'] as $key => $value){
                                                if($k == $value){
                                                    echo "selected='selected'";
                                                }
                                            }
                                        }?>><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>

                    </div>

                    <!--<div class="row">
                       <div class="form-group col-sm-3">
                                <label for="input03">项目起始日期：</label>
                                <input name="starttime" data-date-format="YYYY-MM-DD" value="<?php /*echo $_REQUEST['starttime'];*/?>" type="text" class="form-control" id="datepicker">
                        </div>
                        <div class="form-group col-sm-3">
                                <label for="input04">项目截止日期：</label>
                                <input type="text" name="endtime" data-date-format="YYYY-MM-DD" value="<?php /*echo $_REQUEST['endtime'];*/?>" class="form-control" id="datepicker1">
                        </div>
                    </div>-->

                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="input02">第一笔来款（创建时间）</label>
                            <input name="create_time" data-date-format="YYYY-MM-DD" id="datepicker" class="btn btn-primary btn-block" type="text" value="<?php echo $this->create_time;?>"/>
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="input02">收入时间（至今）</label>
                            <input name="srsj" data-date-format="YYYY-MM-DD" id="datepicker1" class="btn btn-primary btn-block" type="text" value="<?php echo $this->srsj;?>"/>
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="input02">支出时间（至今）</label>
                            <input name="zcsj" data-date-format="YYYY-MM-DD" id="datepicker2" class="btn btn-primary btn-block" type="text" value="<?php echo $this->zcsj;?>"/>
                        </div>
                    </div>

                    <div class="row">

                        <div class="form-group col-sm-4">
                            <label for="input02">项目类型：</label>
                            <select class="form-control" name="cate">
                                <option value="" >请选择类型</option>
                                <?php if($this->pcatelist != ""){
                                    foreach ($this->pcatelist as $k => $v){?>
                                        <option value="<?php echo $v['id']?>" <?php if($_REQUEST['cate']==$v['id']){echo "selected='selected'";}?>><?php echo $v['catename']?></option>
                                    <?php }}?>
                            </select>
                        </div>

                        <?php
                        /**
                         * 递归实现无限极分类
                         * @param $array 分类数据
                         * @param $pid 父ID
                         * @param $level 分类级别
                         * @return $list 分好类的数组 直接遍历即可 $level可以用来遍历缩进
                         */

                        function generateTree($arr, $id, $step){
                            static $tree=[];
                            foreach($arr as $key=>$val) {
                                if($val['t_cate_pid'] == $id) {
                                    $flg = str_repeat('|－－',$step);
                                    $val['t_cate_name'] = $flg.$val['t_cate_name'];
                                    $tree[] = $val;
                                    generateTree($arr , $val['t_cate_id'] ,$step+1);
                                }
                            }
                            return $tree;
                        }
                        ?>

                        <!--<div class="form-group col-sm-4">
                            <label for="input02">项目类型：<?php /*//print_r($_REQUEST['pm_cate'])*/?></label>
                            <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="pm_cate[]" id="pm_cate">
                                <option value="" >请选择项目类型</option>
                                <?php /*if($this->pcatelist != ""){
                                    $tree = generateTree($this->pcatelist, 0, 0);
                                    foreach ($tree as $val){
                                        echo $str .='<option value="'.$val['t_cate_id'].'"';
                                        if(in_array($val['t_cate_id'], $_REQUEST['pm_cate']))
                                        {
                                            $str .=" selected='selected'";
                                        }
                                        $str .= ">".$val['t_cate_name'].'</option>';
                                        echo $str;
                                        $str = '';
                                    }
                                }*/?>
                            </select>
                        </div>-->

                        <div class="form-group col-sm-3">
                            <label for="input01">所属部门：</label>
                            <select class="form-control" name="department">
                                <option value="" >请选择所属部门</option>
                                <?php if($this->departmentlist != ""){
                                    foreach ($this->departmentlist as $k => $v){?>
                                        <option value="<?php echo $v['id']?>" <?php if($_REQUEST['department']==$v['id']){echo "selected='selected'";}?>><?php echo $v['pname']?></option>
                                    <?php }}?>
                            </select>
                        </div>

                        <div class="form-group col-sm-3">
                            <label for="input01">是否只显示收藏项目：</label>
                            <select class="form-control" name="collect">
                                <option value="0" <?php if($_REQUEST['collect']==0 || $_REQUEST['collect']==''){echo "selected='selected'";}?>>否</option>
                                <option value="1" <?php if($_REQUEST['collect']==1){echo "selected='selected'";}?>>是</option>
                            </select>
                        </div>

                        <!--<div class="form-group col-sm-3">
                            <label for="input01">排序规则：</label>
                            <select class="form-control" name="order">
                                <option value="" >请选择排序规则</option>
                                <option value="" >总捐赠收入降序</option>
                                <option value="" >总协议金额降序</option>
                                <option value="" >余额升序</option>
                                <option value="" >余额降序</option>
                                <option value="" >第一笔来款降序</option>
                            </select>
                        </div>-->

                    </div>

                    <div class="row">
                        <div class="form-group col-sm-3">
                            <label for="input02"> </label>
                            <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                        </div>
                    </div>
				</div>
			</form>
			</div>
			</section>
			<section class="tile color transparent-white">
				<tr class="tile-body nopadding">
				<?php if($this->chouzilist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						  <td width="20%">项目名称</td>

                          <td width="6%">所属部门</td>
                          <td width="12%">项目类型</td>
                          <!--<td width="8%">负责人</td>-->
                          <td width="15%">总捐赠收入/总协议金额/余额（元）</td>
                          <!--<td width="8%">执行年限</td>-->

                          <td width="15%">
                              <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                                  <tr>
                                      最近一笔收入
                                  </tr>
                                  <tr>
                                      <td width="50%">金额（元）</td>
                                      <td width="50%" style="border-right: 1px solid #ddd;">时间</td>
                                  </tr>
                              </table>
                          </td>

                          <td width="15%">
                              <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                                  <tr>
                                      最近一笔支出
                                  </tr>
                                  <tr>
                                      <td width="50%">金额（元）</td>
                                      <td width="50%" style="border-right: 1px solid #ddd;">时间</td>
                                  </tr>
                              </table>
                          </td>


                        <!--<td width="12%">项目进度</td>-->
                        <!-- <td width="10%">星级</td>-->
						<!--<td width="12%">部门名称</td><td width="18%">项目签约日期</td>
						<td width="13%">协议捐赠金额</td>-->

                          <td width="10%">是否收藏</td>

                          <?php if (in_array($this->admininfo['admin_info']['admin_type'],array(0,1,2,3,4,5))){?>
						        <td width="20%">操作</td>
                          <?php }?>
					  </tr>
					</thead>
                    <tbody>
					  <?php
						foreach($this->chouzilist as $k=>$v){?>
						 <tr>
						 	<td style="padding: 2px;"><a href="/management/chouzi/repminfo?id=<?php echo $v['id'];?>" target="_blank">
                                <?php //if($v['star'] != 0){echo '<font color="red">';}?>    <?php echo $v['pname'];?>
                                <?php //if($v['star'] != 0){echo '</font>';}?>
                                </a>&nbsp;</td>

                             <td>
                                 <?php  foreach ($this->departmentlist as $kk => $vv){
                                     if($vv['id'] == $v['department']){ echo $vv['pname'];}
                                 }?>&nbsp;
                             </td>

                             <td style="padding: 2px;"><?php  foreach ($this->pcatelist as $kk => $vv){
                                     if($vv['id'] == $v['cate']){ echo $vv['catename'];}
                                 }?>&nbsp;</td>

                             <!--<td style="padding: 2px;">
                                 <?php /*if($this->pcatelist != ""){
                                     $_count = count(explode(',',$v['cate']));
                                     $iii = 1;
                                     foreach($this->pcatelist as $key => $value){
                                         if(in_array($value['t_cate_id'],explode(',',$v['cate']))){
                                             if($iii < $_count){
                                                 echo $value['t_cate_name']. '，';
                                                 $iii ++;
                                             }else{
                                                 echo $value['t_cate_name'];
                                                 $iii ++;
                                             }
                                         }
                                     }
                                 }*/?>&nbsp;
                             </td>-->

                             <!--<td>
                                 <?php /* foreach ($this->jjh_mg_pp_list as $kk => $vv){
                                     if($kk == $v['pm_fzr']){ echo "<a href='/management/pp/ppinfo?id=".$kk."' target='_blank'>".$vv."</a>";}
                                 }*/?>

                                 <?php
/*                                    if(empty($v['pm_fzr'])){
                                     echo "---";
                                 }*/?>&nbsp;
                             </td>-->

                             <td>
                                 <?php echo number_format(sprintf("%.2f",$v['srhj']),2);?> / <a href="/management/zijin/newaddsign?pname=<?php echo $v['pname'];?>" target="_blank"><?php echo number_format(sprintf("%.2f",$v['xyzje']),2);?></a> / <?php echo number_format(sprintf("%.2f",$v['xmye']),2);?>
                             </td>

                             <!--<td>
                                <?php /*if($v['pm_jiezhi_datetime']!='0000-00-00 00:00:00'){echo substr($v['pm_jiezhi_datetime'],0, 10);}else{echo "---";}*/?>
                             </td>-->


                             <!--<td>
                                 <?php /*if(!empty($v['last_zijin'][0])){*/?>
                                 最后来款：<?php /*echo substr($v['last_zijin'][0],0,10)." ". sprintf("%.2f",$v['last_zijin'][1]).'元';}*/?>
                                 <?php /*if(!empty($v['last_shiyong'][0])){*/?><br/>
                                 最后支出：<?php /*echo substr($v['last_shiyong'][0],0,10)." ". sprintf("%.2f",$v['last_shiyong'][1]).'元';}*/?>
                             </td>-->

                             <td>
                                <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                                    <tr>
                                        <td width="50%"><?php echo number_format(sprintf("%.2f",$v['last_zijin'][1]),2);?></td>
                                        <td width="50%" style="border-right: 1px solid #ddd;"><?php echo substr($v['last_zijin'][0],0,10);?></td>
                                    </tr>
                                </table>
                             </td>

                            <td>
                                <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                                    <?php if(!empty($v['last_shiyong'][0])){?>
                                        <tr>
                                            <td width="50%"><?php echo number_format(sprintf("%.2f",$v['last_shiyong'][1]),2);?></td>
                                            <td width="50%" style="border-right: 1px solid #ddd;"><?php echo substr($v['last_shiyong'][0],0,10);?></td>
                                        </tr>
                                    <?php }?>
                                </table>
                            </td>

                             <!--

							<td><?php /*echo substr($v['pm_qianyue_datetime'],0,10);*/?>&nbsp;</td>
							<td><?php echo $v['pm_xieyi_juanzeng_jiner'];?>&nbsp;元</td>-->

                             <!--<td style="padding: 2px;">
                                 <?php /*if($v['pm_rate'] == ""){ */?>
                                     ---
                                 <?php /*}if(preg_match("/1/", $v['pm_rate'])){ */?>
                                     已立项&nbsp;
                                 <?php /*}if(preg_match("/2/", $v['pm_rate'])){*/?>
                                     已签约&nbsp;
                                 <?php /*}if(preg_match("/3/", $v['pm_rate'])){*/?>
                                     已到帐&nbsp;
                                 <?php /*}if(preg_match("/4/", $v['pm_rate'])){ */?>
                                     已执行&nbsp;
                                 <?php /*}if(preg_match("/5/", $v['pm_rate'])){*/?>
                                     已回馈&nbsp;
                                 <?php /*}if(preg_match("/6/", $v['pm_rate'])){*/?>
                                     已完结&nbsp;
                                 <?php /*}if(preg_match("/7/", $v['pm_rate'])){*/?>
                                     待催款&nbsp;
                                 <?php /*}if(preg_match("/8/", $v['pm_rate'])){*/?>
                                     正常执行&nbsp;
                                 <?php /*}if(preg_match("/9/", $v['pm_rate'])){*/?>
                                     待结项&nbsp;
                                 <?php /*}*/?>
                             </td>-->

                            <!--<td style="padding: 2px;">
                                 <div class="starbox1">
                                     <ul class="star_ul1 fl1">
                                         <li><a class="one-star1 <?php /*if($v['star'] == 1)echo 'active-star';*/?>" title="1" href="#"></a></li>
                                         <li><a class="two-star1 <?php /*if($v['star'] == 2)echo 'active-star';*/?>" title="2" href="#"></a></li>
                                         <li><a class="three-star1 <?php /*if($v['star'] == 3)echo 'active-star';*/?>" title="3" href="#"></a></li>
                                         <li><a class="four-star1 <?php /*if($v['star'] == 4)echo 'active-star';*/?>" title="4" href="#"></a></li>
                                         <li><a class="five-star1 <?php /*if($v['star'] == 5)echo 'active-star';*/?>" title="5" href="#"></a></li>
                                     </ul>
                                 </div>
                             </td>-->

                             <td>
                                 <input class="switch-onText" id="is_collect_<?php echo $v['id'];?>" type="checkbox" schValue="<?php echo $v['id'];?>" <?php if(in_array($v['id'], $this->collectlist)){echo 'checked="checked"';}?> data-on-text="是" data-off-text="否" name="is_collect"/>
                             </td>

                             <?php if (in_array($this->admininfo['admin_info']['admin_type'],array(0,1,2,3,4,5))){?>
                                <td>
                                    <a href="/management/chouzi/editchouzi?id=<?php echo $v['id'];?>">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">编辑项目</button>
                                    </a>
                                    <!--&nbsp;&nbsp;
                                    <a href="javascript:void(0);" onclick="addstar(this)" pm_id="<?php /*echo $v['id'];*/?>" star="<?php /*echo $v['star'];*/?>">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">标星</button>
                                    </a>-->
                                    <a href="/management/zijin/rateinfo/?pm_id=<?php echo $v['id'];?>">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">编辑进度</button>
                                    </a>
                                    <!-- <a href="#" onclick="alert('对不起，项目清单不提供删除功能，请联系管理员');">
                                       <button class="btn btn-danger margin-bottom-20" type="button">删除</button>
                                    </a>-->
                                </td>
                             <?php }?>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
                    <div class="tile-footer">
                        <div class="row">
                            <div class="page col-md-12" align="right">
                                共  <?php echo $this->total;?> 条筹资信息          <?php echo $this->page;?></div>

                            <?php }else{?>
                                <div>暂无网站资讯！<a href="/management/chouzi/addchouzi">点击添加</a></div>
                            <?php }?>
                        </div>

                        <div class="row">
                            <div class="form-group col-sm-3">
                                <label for="input02"></label>
                                <a href="/management/report/newschouzitoexcel?pname=<?php echo $this->pname;?>&cate=<?php echo $this->cate;?>&department_id=<?php echo $this->department;?>&srsj=<?php echo $this->srsj;?>&create_time=<?php echo $this->create_time;?>"><button class="btn btn-primary btn-block">导出Excel</button></a>
                            </div>
                        </div>

                    </div>
					</div>

				 </section>
		  </div>
		</div>


        <!--<div class="theme1-popover" style="display: none;">
            <div class="theme1-poptit">
                <a href="javascript:void(0);" title="关闭" class="close" id="popover1-close" name="">×</a>
            </div>
            <div class="theme1-popbod dform">
                <form class="theme1-signin form-horizontal" id="add_star" name="add_star" method="post" enctype="multipart/form-data">
                    <div class="starbox">
                        <span class="s_name">请标星：</span>
                        <ul class="star_ul fl">
                            <li><a class="one-star" title="1" href="#"></a></li>
                            <li><a class="two-star" title="2" href="#"></a></li>
                            <li><a class="three-star" title="3" href="#"></a></li>
                            <li><a class="four-star" title="4" href="#"></a></li>
                            <li><a class="five-star" title="5" href="#"></a></li>
                        </ul>
                        <span class="s_result fl"><a title="0" href="#">取消星级</a></span>
                    </div>
                    <input id="input_star" type="hidden" name="star" value="0"/>
                    <input id="input_pm_id" type="hidden" name="pm_id" value=""/>
                </form>
            </div>
        </div>-->

        <style type="text/css">
            /*{margin:0;padding:0;list-style-type:none;}
            a,img{border:0;}
            body{font:12px/180% Arial, Helvetica, sans-serif, "新宋体";}*/
            /* starbox */
            .starbox{width:480px;margin:10px auto;height:30px;}
            .fl{float:left;display:inline;}
            .s_name{float:left;display:block;width:60px;text-align:right;}
            .star_ul{background:url(/include/management/assets/images/star.png) no-repeat 0 -150px;width:132px;z-index:10;position:relative;height:25px;}
            .star_ul li{float:left;margin-right:1px;width:25px;height:25px;}
            .star_ul li a{display:block;height:25px;position:absolute;left:0;top:0;text-indent:-999em;}
            .star_ul li .active-star{background:url(/include/management/assets/images/star.png) no-repeat;}
            .star_ul li .one-star{width:25px;background-position:0 -120px;z-index:50;}
            .star_ul li .two-star{width:51px;background-position:0 -90px;z-index:40;}
            .star_ul li .three-star{width:79px;background-position:0 -60px;z-index:30;}
            .star_ul li .four-star{width:105px;background-position:0 -30px;z-index:20;}
            .star_ul li .five-star{width:129px;margin-right:0;background-position:0 0;z-index:10;}

            .starbox1{margin:10px auto;height:30px;}
            .fl1{float:left;display:inline;}
            .star_ul1{background:url(/include/management/assets/images/star.png) no-repeat 0 -150px;width:132px;z-index:10;position:relative;height:25px;}
            .star_ul1 li{float:left;margin-right:1px;width:25px;height:25px;}
            .star_ul1 li a{display:block;height:25px;position:absolute;left:0;top:0;text-indent:-999em;}
            .star_ul1 li .active-star{background:url(/include/management/assets/images/star.png) no-repeat;}
            .star_ul1 li .one-star1{width:25px;background-position:0 -120px;z-index:50;}
            .star_ul1 li .two-star1{width:51px;background-position:0 -90px;z-index:40;}
            .star_ul1 li .three-star1{width:79px;background-position:0 -60px;z-index:30;}
            .star_ul1 li .four-star1{width:105px;background-position:0 -30px;z-index:20;}
            .star_ul1 li .five-star1{width:129px;margin-right:0;background-position:0 0;z-index:10;}

            .s_result{padding:6px 0 0 5px;}
        </style>


        <script language="javascript">
            //$(".menu li:eq(18)").addClass("open");

            jQuery(document).ready(function($) {
                // 消息提示框
                $('.theme-poptit .close').click(function(){
                    $('.theme-popover-mask').fadeOut(100);
                    $('.theme-popover').slideUp(200);
                    if($('#popover-close').attr("name") != '') {
                        location.href = $('#popover-close').attr("name");
                    }
                });

                // 添加人员信息
                $('#addstar').click(function(){
                    $('.theme1-popover').show();
                });
                $('.theme1-poptit .close').click(function(){
                    $('.theme1-popover-mask').fadeOut(100);
                    $('.theme1-popover').slideUp(200);
                });
            });

            // 初始化加载星级
            function addstar(obj){
                $('.theme1-popover').show();
                $('#input_pm_id').val($(obj).attr('pm_id'));
                //$('#input_star').val($(obj).attr('star'));

                $('.star_ul a').removeClass('active-star');

                if($(obj).attr('star') == 1){
                    $('.one-star').addClass('active-star');
                }else if($(obj).attr('star') == 2){
                    $('.two-star').addClass('active-star');
                }else if($(obj).attr('star') == 3){
                    $('.three-star').addClass('active-star');
                }else if($(obj).attr('star') == 4){
                    $('.four-star').addClass('active-star');
                }else if($(obj).attr('star') == 5){
                    $('.five-star').addClass('active-star');
                }
            }

            // 标星
            $(function(){
                $('.star_ul a').hover(function(){
                    $(this).addClass('active-star');
                },function(){
                    $(this).removeClass('active-star');
                    //$('.s_result').css('color','#333').html('请打分');
                });

                $('.star_ul a').click(function(){
                    $('#input_star').val($(this).attr('title'));
                    $('.theme1-popover').fadeOut(100);
                    ajaxaddstar();
                });

                //取消标星
                $('.s_result a').click(function(){
                    $('#input_star').val($(this).attr('title'));
                    $('.theme1-popover').fadeOut(100);
                    ajaxaddstar();
                });
            })


            function ajaxaddstar(){
                var formParam = $("#add_star").serialize();//序列化表格内容为字符串

                $.ajax({
                    type:'post',
                    url: '/management/chouzi/ajaxaddstar',
                    data:formParam,
                    cache:false,
                    dataType:'json',
                    success:function(data){
                        if(data['status'] == 'error'){
                            alert(data['message']);
                        }else if(data['status'] == 'success'){
                            // 加载新数据
                            alert(data['message']);
                            parent.location.reload();
                        }
                    },
                    complete:function(data){

                    },
                    error:function(data){
                        //console.log(data);
                        alert('添加失败！');
                    }
                });
            }

        </script>


    </div><!-- tab-pane -->
</div><!-- tab-content -->
</div>
</div>
<!-- Make page fluid-->

</div>
<!-- Wrap all page content end -->
<section class="videocontent" id="video"></section>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/include/management/assets/js/jquery.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/include/management/assets/js/vendor/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/mmenu/js/jquery.mmenu.min.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/sparkline/jquery.sparkline.min.js"></script>

<?php if($this->controller == "index") {?>
    <script type="text/javascript" src="/include/management/assets/js/vendor/nicescroll/jquery.nicescroll.min.js"></script>
    <script src="/include/management/assets/js/vendor/easypiechart/jquery.easypiechart.min.js"></script>
    <!--<script src="/include/management/assets/js/vendor/flot/jquery.flot.orderBars.js"></script>-->

    <script type="text/javascript" src="/include/management/assets/js/vendor/animate-numbers/jquery.animateNumbers.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/videobackground/jquery.videobackground.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/blockui/jquery.blockUI.js"></script>

    <script src="/include/management/assets/js/vendor/flot/jquery.flot.min.js"></script>
    <script src="/include/management/assets/js/vendor/flot/jquery.flot.time.min.js"></script>
    <script src="/include/management/assets/js/vendor/flot/jquery.flot.selection.min.js"></script>
    <script src="/include/management/assets/js/vendor/flot/jquery.flot.animator.min.js"></script>

    <script src="/include/management/assets/js/vendor/rickshaw/raphael-min.js"></script>
    <script src="/include/management/assets/js/vendor/rickshaw/d3.v2.js"></script>
    <script src="/include/management/assets/js/vendor/rickshaw/rickshaw.min.js"></script>

    <script src="/include/management/assets/js/vendor/morris/morris.min.js"></script>
    <script src="/include/management/assets/js/vendor/tabdrop/bootstrap-tabdrop.min.js"></script>
    <script src="/include/management/assets/js/vendor/summernote/summernote.min.js"></script>
    <script src="/include/management/assets/js/vendor/chosen/chosen.jquery.min.js"></script>
<?php }?>

<script type="text/javascript" src="/include/management/assets/js/vendor/mmenu/js/jquery.mmenu.min.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/sparkline/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/nicescroll/jquery.nicescroll.min.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/animate-numbers/jquery.animateNumbers.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/videobackground/jquery.videobackground.js"></script>
<script type="text/javascript" src="/include/management/assets/js/vendor/blockui/jquery.blockUI.js"></script>

<script src="/include/management/assets/js/vendor/summernote/summernote.min.js"></script>

<script src="/include/management/assets/js/vendor/chosen/chosen.jquery.min.js"></script>

<script src="/include/management/assets/js/vendor/momentjs/moment-with-langs.min.js"></script>
<script src="/include/management/assets/js/vendor/datepicker/bootstrap-datetimepicker.min.js"></script>

<script src="/include/management/assets/js/minimal.min.js"></script>

<!-- bootstrap-switch-master -->
<script type="text/javascript" src="/include/management/bootstrap-switch-master/js/highlight.js"></script>
<!--<script src="https://unpkg.com/bootstrap-switch"></script>-->
<script type="text/javascript" src="/include/management/bootstrap-switch-master/js/main.js"></script>
<script type="text/javascript" src="/include/management/bootstrap-switch-master/js/bootstrap-switch.js"></script>

<script type="text/javascript">
    $('.switch-onText').on('switchChange.bootstrapSwitch', function (event,state) {
        if(state==true){
            params_val = 1;
        }else {
            params_val = 0;
        }

        var data_info = {
            "id": $(this).attr("schValue"),
            "params_name":$(this).attr("name"),
            "params_val": params_val
        };

        if(state==true){
            //启用
            $.ajax({
                type: 'POST',
                url: 'ajaxcollect',
                dataType:'json',
                data: data_info,
                success:function(data){
                    if(data.success){
                        alert("编辑成功");
                    }else{
                        alert(data.errorMessage);
                    }
                },
                error:function(XMLHttpRequest,textStatus){
                    alert(textStatus);
                    //layer.msg(textStatus);
                }
            })
        }else{
            //停用
            $.ajax({
                type: 'POST',
                url: 'ajaxcollect',
                dataType:'json',
                data: data_info,
                success:function(data){
                    if(data.success){
                        alert("编辑成功");
                    }else{
                        alert(data.errorMessage);
                        //layer.msg(data.errorMessage);
                    }
                },
                error:function(XMLHttpRequest,textStatus){
                    alert(textStatus);
                }
            })
        }
    });
</script>




<script>
    $(function(){
        //initialize datepicker
        $('#datepicker').datetimepicker({
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            }
        });

        $("#datepicker").on("dp.show",function (e) {
            var newtop = $('.bootstrap-datetimepicker-widget').position().top - 45;
            $('.bootstrap-datetimepicker-widget').css('top', newtop + 'px');
        });

        //initialize datepicker
        $('#datepicker1').datetimepicker({
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            }
        });

        $("#datepicker1").on("dp.show",function (e) {
            var newtop1 = $(".bootstrap-datetimepicker-widget").position(relative).top - 45;
            alert(newtop1);
            $('.bootstrap-datetimepicker-widget').css('top', newtop1 + 'px');
        });

        //initialize datepicker
        $('#datepicker2').datetimepicker({
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            }
        });

        $("#datepicker2").on("dp.show",function (e) {
            var newtop2 = $('.bootstrap-datetimepicker-widget').position(relative).top - 45;
            $('.bootstrap-datetimepicker-widget').css('top', newtop2 + 'px');
        });


    });

</script>

<!-- //遮罩层效果 -->
<style>
    .theme-popover-mask {
        z-index: 9998;
        position:fixed;
        top:0;  left:0;  width:100%;
        height:100%;  background:#000;  opacity:0.4;
        filter:alpha(opacity=40);  display:none;
    }
    .theme-popover {
        z-index:9999;  position:fixed;
        top:20%;  left:35%;
        width:45%;
        max-height:220px;
        /*margin:-180px 0 0 -330px;*/
        border-radius:5px;  border:solid 2px #666;
        display:none;
        box-shadow: 0 0 10px #666;
        background-color: #f7f7f7;
        border-bottom: 1px solid #ebebeb;
        border-radius: 5px 5px 0 0;
        font-size: 14px;
    }
    .theme-signin{
        margin-top: 40px;
    }
    #popover-close{
        float: right;
        margin-right: 12px;
        margin-top: 12px;
    }
    #popover-msg{
        margin-top: 12px;
        align-content: center;
        text-align: center;
    }
    #popover-img{
        margin: 0 auto;
        text-align: center;
    }
    #popover-img img{
        display: inline;
        max-width:30%;
        height:auto;

    }

    /* 添加人员信息弹出框*/
    .theme1-popover-mask {
        z-index: 9998;
        position:fixed;
        top:0;  left:0;  width:100%;
        height:100%;  background:#000;  opacity:0.4;
        filter:alpha(opacity=40);  display:none;
    }
    .theme1-popover {
        z-index:9999;  position:fixed;
        top:21%;
        left:35%;
        width:45%;
        /*max-height:220px;
        margin:-180px 0 0 -330px;*/
        border:solid 2px #999;
        display:none;
        box-shadow: 0 0 10px #666;
        background-color: #f7f7f7;
        border-radius: 5px;
        font-size: 14px;
        padding:5px 15px;
    }
    .theme1-signin{
        margin-top: 40px;
    }
    #popover1-close{
        float: right;
        margin-right: 12px;
        margin-top: 12px;
    }
    #popover1-msg{
        margin-top: 12px;
        align-content: center;
        text-align: center;
    }
    #popover1-img{
        margin: 0 auto;
        text-align: center;
    }
    #popover1-img img{
        display: inline;
        max-width:30%;
        height:auto;

    }
</style>

<div class="theme-popover">
    <div class="theme-poptit">
        <a href="javascript:void(0);" title="关闭" class="close" id="popover-close" name="">×</a>
    </div>
    <div class="theme-popbod dform">
        <form class="theme-signin" name="loginform" action="" method="post">
            <ol>
                <li id="popover-img"><img src="/include/management/images/warning.png" width="100" height="100" alt=""></li>
                <li id="popover-msg"><?php echo $mess = "系统消息提示";?></li>
            </ol>
        </form>
    </div>
</div>
<div class="theme-popover-mask"></div>


<!-- //遮罩层效果 -->

<style>
    .margin-bottom-20{
        margin-bottom: 0px;
        padding: 2px 12px;
        font-size: 12px;
    }
    body{
        padding-bottom:0px;
    }
</style>

<script language="javascript">
    //搜索功能采用get方式 关键词下拉提示，
    $(".chosen-select-1").chosen({
        search_contains: true,
        no_results_text : "未找到此选项!",
        //width:"70%",
        height:"60%",
        disable_search_threshold: 10
    });

    $(".chosen-select-2").chosen({
        search_contains: true,
        disable_search_threshold: 10
    });

    $("[name='search_form']").submit(function(){
        if($(".chosen-single span").html() != "请选择项目名称"){
            $("#pname_info").val($(".chosen-single span").html());
        }
        return true;
    });

    $("#xmxxcxytj").addClass("open");
</script>