<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>人员类型管理列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>人员类型管理</li>
            <li class="active">人员类型列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->
<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-8">
            <section class="tile color transparent-white">
                <div class="tile-body nopadding">
                    <?php if(count($this->ppcatelist)!=0){?>
                    <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
                        <thead>
                        <tr>
                            <td width="10%">序号</td>
                            <td width="40%">人员类型</td>
                            <td width="20%">操作</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach($this->ppcatelist as $k=>$v){?>
                            <tr>
                                <td><?php echo $v['id'];?></td>
                                <td><?php echo $v['pp_cate_name'];?></td>
                                <td>
                                    <a href="/test/pp/editppcate?id=<?php echo $v['id'];?>">
                                        <button type="button" class="btn btn-greensea margin-bottom-20">编辑</button></a>

                                    <a href="/test/pp/delppcate?id=<?php echo $v['id'];?>" onclick= "if(confirm( '是否确定！ 删除将无法找回该人员类型信息。')==false) return false; "><button type="button" class="btn btn-danger margin-bottom-20">删除</button></a></td>
                            </tr>
                        <?php }?>
                        </tbody>
                    </table>
                </div>
                <div class="tile-footer">
                    <div class="row">
                        <div align="right" class="page col-md-12">
                            共  <?php echo $this->total;?> 条          <?php echo $this->page;?></div>

                        <?php }else{?>
                            <div>暂无人员类型信息！<a href="/test/pp/addppcate">点击添加</a></div>
                        <?php }?>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(10)").addClass("open");
    </script>