<?= $this->partial("common/header.phtml");?>
 <div class="jjh_content_sub" style="height:1680px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/project_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>捐赠使用</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="usage1.html"><span>学生资助</span></a></li>
                      <li><a href="usage2.html">教师发展</a></li>
                      <li><a href="usage3.html">校友（校庆）活动</a></li>
                      <li><a href="usage4.html">校园文化</a></li>
                      <li><a href="usage5.html">天津大学发展</a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><em>学生资助--奖学金</em><span>当前位置：<a href="usage.html">捐赠使用</a> > 奖学金</span></div>
              <div class="jjh_sub_con_content" style="height:1500px;">
              <div><span class="jjh_font3">我们正尽我们的最大努力，将每一点爱心播撒在最需要它的地方!</span><br /><br /><span class="jjh_font4">进行中的项目：</span></div>
                <ul class="jjh_report">
                    <li><a href="newdetail.html">关于本基金会基本户账号变更的通知 </a></li>
                    <li><a href="#">电话运动第二季—— 感谢您接听母校志愿者电话 </a></li>
                    <li><a href="#">2011年新鸿基地产郭氏基金英国剑桥大学博士/硕士奖学金申请启动 </a></li>
                    <li><a href="#">关于本基金会基本户账号变更的通知 </a></li>
                </ul>
              </div>
         </div>
     </div>
<?= $this->partial('common/footer.phtml'); ?>   