<?= $this->partial("common/header.phtml");?>
 <div class="jjh_content_sub">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/project_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>捐赠使用</span></div>
              <?= $this->partial('pmuse/left.phtml'); ?> 
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/pmuse">捐赠使用</a> > 奖学金</span><em>学生资助--奖学金</em></div>
              <!--<div class="jjh_sub_con_content">
              <div><span class="jjh_font3">我们正尽我们的最大努力，将每一点爱心播撒在最需要它的地方!</span><br /><br /><span class="jjh_font4">进行中的项目：</span></div>
                <ul class="jjh_report">
                    <li><a href="">关于本基金会基本户账号变更的通知 </a></li>
                    <li><a href="#">电话运动第二季—— 感谢您接听母校志愿者电话 </a></li>
                    <li><a href="#">2011年新鸿基地产郭氏基金英国剑桥大学博士/硕士奖学金申请启动 </a></li>
                    <li><a href="#">关于本基金会基本户账号变更的通知 </a></li>
                </ul>
              </div>
         --><?php echo $this->info[0]['content'];?></div>
	<div class="cle">&nbsp;</div>
     </div>
<?= $this->partial('common/footer.phtml'); ?>   