<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->newsinfo[0]['my_infor_title'];?></title>
    <meta name="description" content="天津大学北洋教育发展基金会" />
    <meta name="keywords" content="天津大学，天津大学北洋教育发展基金会，基金会" />
    <link href="<?php echo __DEFAULTINCLUDEPATH__;?>css/style.css" rel="stylesheet"  type="text/css"/>
    <script src="<?php echo __DEFAULTINCLUDEPATH__;?>js/silder.js" type="text/javascript" language="javascript"></script>
    <script src="<?php echo __DEFAULTINCLUDEPATH__;?>js/tab.js" type="text/javascript"></script>
</head>
<body>
<?php
$front = Zend_Controller_Front::getInstance();
$controller_name = $front->getRequest()->getControllerName();
//var_dump($controller_name);
?>
<div class="jjh_container">
    <div class="jjh_header">
        <div class="jjh_topadv"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/topadv.jpg" /></div>
        <div class="jjh_nav">
            <ul>
                <li><a <?php if($controller_name == "index"){?>id="linkon"<?php }?> href="/">首页</a></li>
                <li><a <?php if($controller_name == "about" && $_GET['true'] != 1){?>id="linkon"<?php }?> href="/about">基金会概况</a></li>
                <li><a <?php if($controller_name == "news"){?>id="linkon"<?php }?> href="/news/index?cid=xinwen">新闻中心</a></li>
                <li><a <?php if($controller_name == "jjhpm"){?>id="linkon"<?php }?> href="/jjhpm">项目介绍</a></li>
                <li><a <?php if($controller_name == "pmuse"){?>id="linkon"<?php }?> href="/pmuse">捐赠使用</a></li>
                <li><a <?php if($controller_name == "about"  && $_GET['true'] == 1){?>id="linkon"<?php }?> href="/about?true=1">信息披露</a></li>
                <li><a <?php if($controller_name == "heart"){?>id="linkon"<?php }?> href="/heart">捐赠故事</a></li>
                <li><a <?php if($controller_name == "donate"){?>id="linkon"<?php }?> href="/donate/mianshui">捐赠政策</a></li>
                <li><a <?php if($controller_name == "contact"){?>id="linkon"<?php }?> href="/contact">联系我们</a></li>
                <li style="background:none;"><a <?php if($controller_name == "en"){?>id="linkon"<?php }?> href="/en">English</a></li>
            </ul>
        </div>
    </div>

<div class="jjh_content_sub">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/news_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>新闻中心</span></div>
              <div class="jjh_sub_nav_con">
                    <ul>
                      <li><a href="/news/index?cid=gonggao">
                      <?php if($this->c_name == "基金会公告"){?>
                      <span>基金会公告</span>
                      <?php }else{?>
                     	 基金会公告
                      <?php }?>
                      </a></li>
					  
					  <!--<li><a href="/news/index?cid=zizhuxinxi">
					  <?php if($this->c_name == "资助信息"){?>
                      <span>资助信息</span>
                      <?php }else{?>
                     	 资助信息
                      <?php }?></a></li> -->
					  
                      <li><a href="/news/index?cid=xinwen">
					  <?php if($this->c_name == "基金会新闻"){?>
                      <span>基金会新闻</span>
                      <?php }else{?>
                     	基金会新闻
                      <?php }?></a></li>
					  
                      <!--<li><a href="/news/index?cid=gongshi">
					  <?php if($this->c_name == "捐赠公示"){?>
                      <span>捐赠公示</span>
                      <?php }else{?>
                     	捐赠公示
                      <?php }?>
					  </a></li> -->
                   </ul>

              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/news">新闻中心</a> > <?= $this->c_name;?></span><em>新闻正文</em></div>
              <div class="jjh_sub_con_content" >
                <div class="jjh_news_detail_tit"><font class="jjh_font3"><?php echo $this->newsinfo[0]['my_infor_title'];?></font><br /><font class="jjh_font6"><?php echo substr($this->newsinfo[0]['my_infor_datetime'], 0 ,10);?></font> </div>
                <div class="jjh_news_detail_con">
                 	<!--<?php echo $this->newsinfo[0]['my_infor_sumary'];?><br /><br />-->
                  	<?php echo $this->newsinfo[0]['my_infor_content'];?>
                </div>
				<div style="clear:both;"></div>
              </div>
         </div>
		 
		 <div style="clear:both;"></div>
     </div>
     
	 
	 <div style="clear:both;"></div>
    <?= $this->partial("common/footer.phtml");?>
