<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>


	<div id="main">
		<div id="rightstyle02">
		<h4>项目筹资管理<span class="font_red"> >> </span><span class="font_red_big">筹资列表</span></h4>
			<div class="detailedbox">
				<div class="search">
					<form action="#" method="post">
						所属部门：
						<select name="department">
							<option value="" >请选择类型</option>
								<?php if($this->departmentlist != ""){
								foreach ($this->departmentlist as $k => $v){?>
									<option value="<?php echo $v['id']?>" ><?php echo $v['pname']?></option>
								<?php }}?>
						</select>
						
						&nbsp;&nbsp;&nbsp;
						项目类型：
						<select name="cate">
							<option value="" >请选择类型</option>
								<?php if($this->pcatelist != ""){
								foreach ($this->pcatelist as $k => $v){?>
									<option value="<?php echo $v['id']?>" ><?php echo $v['catename']?></option>
								<?php }}?>
						</select>
						<br/>
						<br/>
						
						
						项目起始日期：<input type="text"  id="dateinput"  name="starttime"  size="14"/>
						项目截止日期：<input type="text"  id="dateinput2"  name="endtime"  size="14"/>
						项目名称：<input type="text" name="pname" />
						<input type="submit" value="搜索"/>
					</form>
				</div>
	
				<?php if($this->chouzilist != ""){?>
					<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  
					  <tr>
						<td width="24%" bgcolor="#f5f5f5">项目名称</td>
						<td width="12%" bgcolor="#f5f5f5">部门名称</td>
						<td width="20%" bgcolor="#f5f5f5">项目分类</td>
						<td width="18%" bgcolor="#f5f5f5">项目签约日期</td>
						<td width="13%" bgcolor="#f5f5f5">协议捐赠金额</td>
						<td width="13%" bgcolor="#f5f5f5">操作</td>
					  </tr>
					
					  <?php 
						foreach($this->chouzilist as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['pname'];?>&nbsp;</td>
							<td><?php  foreach ($this->departmentlist as $kk => $vv){
								if($vv['id'] == $v['department']){ echo $vv['pname'];}
								}?>&nbsp;</td>
							<td><?php  foreach ($this->pcatelist as $kk => $vv){
								if($vv['id'] == $v['cate']){ echo $vv['catename'];}
								}?>&nbsp;</td>
								
							<td><?php echo substr($v['pm_qianyue_datetime'],0,10);?>&nbsp;</td>
							<td><?php echo $v['pm_xieyi_juanzeng_jiner'];?>&nbsp;元</td>
							<td><a href="/management/chouzi/editchouzi?id=<?php echo $v['id'];?>">编辑</a> || <a href="#">删除</a></td>
						 </tr>
					   <?php }?>
					</table>
					
					<div align="right" style="margin-right: 10px;margin-top: 5px;">
						共  <?php echo $this->total;?> 条筹资信息          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div>暂无网站资讯！<a href="/management/chouzi/addchouzi">点击添加</a></div>
				 <?php }?>
		  </div>
		</div> 
		
		<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>
			
			<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput2').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>
