<link rel="stylesheet" href="/include/management/datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="/include/management/datepicker/ui.datepicker.css" type="text/css"  /> 
<!--<script src="/include/management/datepicker/jquery.js"></script>-->

<link rel="stylesheet" href="/include/management/jiansuo/base/jquery.ui.all.css">
<script src="/include/management/jiansuo/jquery-1.6.2.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.core.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.widget.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.button.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.position.js"></script>
<script src="/include/management/jiansuo/ui/jquery.ui.autocomplete.js"></script>

<script src="/include/management/jiansuo/ui/jquery.ui.datepicker.js"></script>
<!--<script src="/include/management/datepicker/ui.datepicker.js"></script>-->

<style>
	.ui-button-icon-only .ui-button-text, .ui-button-icons-only .ui-button-text{
		padding:0em;
	}
	.ui-widget .ui-widget{
		font-size: 12px;
	}
	.ui-menu .ui-menu-item a{
		font-size: 12px;
	}

</style>
<script>
	(function( $ ) {
		$.widget( "ui.combobox", {
			_create: function() {
				var self = this,
					select = this.element.hide(),
					selected = select.children( ":selected" ),
					value = selected.val() ? selected.text() : "";
				var input = this.input = $( "<input>" )
					.insertAfter( select )
					.val( value )
					.autocomplete({
						delay: 0,
						minLength: 0,
						source: function( request, response ) {
							var matcher = new RegExp( $.ui.autocomplete.escapeRegex(request.term), "i" );
							response( select.children( "option" ).map(function() {
								var text = $( this ).text();
								if ( this.value && ( !request.term || matcher.test(text) ) )
									return {
										label: text.replace(
											new RegExp(
												"(?![^&;]+;)(?!<[^<>]*)(" +
												$.ui.autocomplete.escapeRegex(request.term) +
												")(?![^<>]*>)(?![^&;]+;)", "gi"
											), "<strong style='color:red'>$1</strong>" ),
										value: text,
										option: this
									};
							}) );
						},
						select: function( event, ui ) {
							ui.item.option.selected = true;
							self._trigger( "selected", event, {
								item: ui.item.option
							});
						},
						change: function( event, ui ) {
							if ( !ui.item ) {
								var matcher = new RegExp( "^" + $.ui.autocomplete.escapeRegex( $(this).val() ) + "$", "i" ),
									valid = false;
								select.children( "option" ).each(function() {
									if ( $( this ).text().match( matcher ) ) {
										this.selected = valid = true;
										return false;
									}
								});
								if ( !valid ) {
									// remove invalid value, as it didn't match anything
									$( this ).val( "" );
									select.val( "" );
									input.data( "autocomplete" ).term = "";
									return false;
								}
							}
						}
					})
					.addClass( "ui-widget ui-widget-content ui-corner-left" );

				input.data( "autocomplete" )._renderItem = function( ul, item ) {
					return $( "<li></li>" )
						.data( "item.autocomplete", item )
						.append( "<a>" + item.label + "</a>" )
						.appendTo( ul );
				};

				this.button = $( "<button type='button'>&nbsp;</button>" )
					.attr( "tabIndex", -1 )
					.attr( "title", "Show All Items" )
					.insertAfter( input )
					.button({
						icons: {
							primary: "ui-icon-triangle-1-s"
						},
						text: false
					})
					.removeClass( "ui-corner-all" )
					.addClass( "ui-corner-right ui-button-icon" )
					.click(function() {
						// close if already visible
						if ( input.autocomplete( "widget" ).is( ":visible" ) ) {
							input.autocomplete( "close" );
							return;
						}

						// work around a bug (likely same cause as #5265)
						$( this ).blur();

						// pass empty string as value to search for, displaying all results
						input.autocomplete( "search", "" );
						input.focus();
					});
			},

			destroy: function() {
				this.input.remove();
				this.button.remove();
				this.element.show();
				$.Widget.prototype.destroy.call( this );
			}
		});
	})( jQuery );

	$(function() {
		$( "#combobox" ).combobox();
		$( "#toggle" ).click(function() {
			$( "#combobox" ).toggle();
		});
	});
	</script>
	
	<div id="main">
		<div id="rightstyle02">
		<h4>项目使用管理<span class="font_#0474d6"> >> </span><span class="font_#0474d6_big">编辑使用信息</span></h4>
			<div class="detailedbox">
			<form action="editrsshiyong" method="post" encType="multipart/form-data">
				<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
			  
					  <tr>
					    <td width="20%" style="text-align:right;">项目名称：</td>
						<td width="80%" style="text-align:left;">
							<select name="pname" id="combobox">
									<?php if($this->pmlist != ""){
											foreach ($this->pmlist as $k => $v){
										?>
										<option value="<?php echo $v['pname'];?>" <?php if($v['pname'] == $this->pm_mg_info[0]['pm_name']){echo "selected='selected'";}?>><?php echo $v['pname'];?></option>
									<?php }}?>
								</select><font color="#0474d6" > * </font>
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">项目捐赠类型：</td>
						<td width="80%" style="text-align:left;">
							<select name="pm_cate">
								<option value="" >请选择类型</option>
								<?php if($this->pcatelist != ""){
								foreach ($this->pcatelist as $k => $v){?>
									<option value="<?php echo $v['id']?>" <?php if ($this->pm_mg_info[0]['pm_juanzeng_cate'] == $v['id']){echo "selected='selected'";}?>><?php echo $v['catename']?></option>
								<?php }}?>
							</select><font color="#0474d6" > * 教育基金、研究基金等</font>
						</td>
					  </tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">项目支出日期：</td>
						<td width="80%" style="text-align:left;">
							<input type="text"  id="dateinput1"  value="<?php echo $this->pm_mg_info[0]['shiyong_zhichu_datetime'];?>"  name="shiyong_zhichu_datetime"  size="14"/><font color="#0474d6" > * </font>
						</td>
					</tr> 
					
					<tr>
					    <td width="20%" style="text-align:right;">项目支出金额：</td>
						<td width="80%" style="text-align:left;">
							<input type="text" name="shiyong_zhichu_jiner"  value="<?php echo $this->pm_mg_info[0]['shiyong_zhichu_jiner'];?>"  size="14"/><font color="#0474d6" > * </font>
						</td>
					</tr>  
					
					<tr>
					    <td width="20%" style="text-align:right;">捐赠范围：</td>
						<td width="80%" style="text-align:left;">
							<select name="fanwei">
								<option value="" >请选择类型</option>
								<option value="本科生" <?php if($this->pm_mg_info[0]['jiangli_fanwei'] == "本科生"){echo "selected='selected'";}?>>本科生</option>
								<option value="研究生"  <?php if($this->pm_mg_info[0]['jiangli_fanwei'] == "研究生"){echo "selected='selected'";}?>>研究生</option>
								<option value="本科研究生"  <?php if($this->pm_mg_info[0]['jiangli_fanwei'] == "本科研究生"){echo "selected='selected'";}?>>本科研究生</option>
								<option value="其他"  <?php if($this->pm_mg_info[0]['jiangli_fanwei'] == "其他"){echo "selected='selected'";}?>>其他</option>
							</select><font color="#0474d6" > * 本科生、研究生、本科研究生、其他</font>
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">奖励人数：</td>
						<td width="80%" style="text-align:left;">
							<input type="text" name="jiangli_renshu"  value="<?php echo $this->pm_mg_info[0]['jiangli_renshu'];?>"  size="14"/><font color="#0474d6" > * </font>
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">相关文档：</td>
						<td width="80%" style="text-align:left;">
							<input type="file" name="pm_files"  size="14"/><font color="#0474d6" > * 相关文档已打包形式上传 格式为*.rar</font><br/>
							<?php if($this->pm_mg_info[0]['pm_file'] != ""){?>
								<!--<a href="<?php echo $this->pm_mg_info[0]['pm_file'];?>">已经存在该文件如果再次上传,那么之前文件将被覆盖    -- 点击下载源文件</a>-->
								
								<a href="/include/upload_file/jjh_download/download.php?filename=<?php echo mb_substr($this->pm_mg_info[0]['pm_file'],34,100);?>">已经存在该文件如果再次上传,那么之前文件将被覆盖    -- 点击下载源文件</a>
							<?php }?>
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">备注：</td>
						<td width="80%" style="text-align:left;">
							<textarea class="ckeditor" name="beizhu">
								<?php echo $this->pm_mg_info[0]['beizhu'];?>
							</textarea>
						</td>
					</tr>
					
					<input type="hidden" name="id" value="<?php echo $this->pm_mg_info[0]['id'];?>"/>
					
					<tr>
					    <td width="20%" style="text-align:right;"> </td>
						<td width="80%" style="text-align:left;">
							<input type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; <input type="reset" value="重 置" /> 
						</td>
					</tr>
				</table>
			</form>
		  </div>
		</div>
	
			<script language="javascript"> 
			$(document).ready(function() {   
			       $('#dateinput1').datepicker({   
			           dateFormat: 'yy-mm-dd',  //日期格式，自己设置 
			           buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置 
			           buttonImageOnly: true,  //Show an image trigger without any button. 
			           //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效 
			       yearRange: '2008:2020',//年份范围 
			       clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置 
			       closeText:'关闭', 
			       prevText:'前一月', 
			       nextText:'后一月', 
			       currentText:' ', 
			       monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
			       });   
			   });   
			</script>
		