<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:500px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/donate_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>在线捐赠</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                   	  <li><a href="/donate/fangshi">捐赠方式</a></li>
                      <li><a href="/donate/zhanghu">基金会账户</a></li>
                      <li><a href="/donate/mianshui"><span>免税政策</span></a></li>
                      <li><a href="/donate/shuoming">捐赠说明</a></li>
                      <li><a href="/donate">我要捐赠</a></li>
                      <!--<li><a href="/donate/query">捐款到账查询</a></li>
                      --><li><a href="/donate/wuxie">捐赠鸣谢</a></li>
                   </ul>
              </div>
              <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/serline.jpg" /></div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/donate">在线捐赠</a> > 免税政策</span><em>免税政策</em></div>
              <div class="cle"></div>
              <div class="jjh_sub_con_content" style="height:320px;">
                  <p class="jjh_font3" align="center">天津大学北洋教育发展基金会已获得天津市“公益性捐赠税前扣除资格”</p>
                  <div class="jjh_donate_methods_con">根据《中华人民共和国企业所得税法》和《中华人民共和国个人所得税法》及其实施条例的有关规定，财政部、国家税务总局、民政部联合下发《关于公益性捐赠税前扣除有关问题的通知》（财政部财税[2008]160号），对公益性捐赠所得税税前扣除有关问题明确如下：<br /><br />
	一、企业通过公益性社会团体或者县级以上人民政府及其部门，用于公益事业的捐赠支出，在年度利润总额12%以内的部门，准予在计算应纳税所得额时扣除。<br />
	二、个人通过社会团体、国家机关向公益事业的捐赠支出，按照现行税收法律、行政法规及相关政策规定准予在所得税税前扣除。根据《中华人民共和国个人所得税法》及其实施条例的有关规定，对个人将其所得通过中国境内的社会团体、国家机关向教育和其他社会公益事业以及遭受严重自然灾害、贫困地区的捐赠。捐赠额未超过纳税义务人申报的应纳税所得额30%的部分，可以从其应纳税所得额中扣除。</div>
              </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>