<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:630px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/donate_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>在线捐赠</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/donate/fangshi">捐赠方式</a></li>
                      <li><a href="/donate/zhanghu">基金会账户</a></li>
                      <li><a href="/donate/mianshui">免税政策</a></li>
                      <li><a href="/donate/shuoming">捐赠说明</a></li>
                      <li><a href="/donate">我要捐赠</a></li>
                      <li><a href="/donate/query"><span>捐款到账查询</span></a></li>
                      <li><a href="/donate/wuxie">捐赠鸣谢</a></li>
                   </ul>
              </div>
              <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/serline.jpg" /></div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><em>捐款到账查询</em><span>当前位置：<a href="donate.html">在线捐赠</a> > 捐款到账查询</span></div>
              <div class="cle"></div>
              <div class="jjh_sub_con_content" style="height:450px;">
                  <p class="jjh_font3" align="center">谨向关心和支持天津大学教育事业的社会各界人士，表示最衷心的感谢！</p><br />
                  <div class="jjh_donate_saerch">
                    <form action="" method="get" name="jjh_donate_search">
                       <table cellpadding="0" cellspacing="0" width="100%" align="center">
                           <tr>
                             <td width="80%"><input name="jjh_searcon" type="text" id="jjh_searcon" class="jjh_donate_saerch_con"  value="按捐款人姓名或手机号查询" style="color:#afafaf;  font-size:14px; font-family:'微软雅黑', '宋体';"/></td>
                             <td width="20%"><input type="submit" id="jjh_dk_searbtn" value="查询"  class="jjh_donate_saerch_btn"/></td>
                           </tr>
                       </table><br />
                       <span class="jjh_font2">查询结果：</span><br />
                       <table cellpadding="0" cellspacing="0" width="100%" align="center" style="margin-top:10px;">
                           <tr>
                             <td bgcolor="#f0f0f0" width="4">&nbsp;</td>
                             <td width="51" height="35" bgcolor="#f0f0f0"><b>姓名</b></td>
                             <td width="93" bgcolor="#f0f0f0"><b>手机号</b></td>
                             <td width="165" bgcolor="#f0f0f0"><b>捐款项目</b></td>
                             <td width="64" bgcolor="#f0f0f0"><b>捐款金额</b></td>
                             <td width="77" bgcolor="#f0f0f0"><b>捐款日期</b></td>
                             <td width="74" bgcolor="#f0f0f0"><b>到账日期</b></td>
                           </tr>
                           <tr>
                             <td width="4" height="35" class="jjh_border1">&nbsp;</td>
                             <td class="jjh_border1">miya</td>
                             <td class="jjh_border1">13820916512</td>
                             <td class="jjh_border1">学生资助项目--奖学金</td>
                             <td class="jjh_border1">100元</td>
                             <td class="jjh_border1">2010-03-05</td>
                             <td class="jjh_border1">2010-03-06</td>
                           </tr>
                       </table>
                    </form>
                  </div>
              </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>