<?= $this->partial("common/header.phtml");?>
 <div class="jjh_content_sub" style="height:630px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/donate_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>在线捐赠</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/donate/fangshi">捐赠方式</a></li>
                      <li><a href="/donate/zhanghu">基金会账户</a></li>
                      <li><a href="/donate/mianshui">免税政策</a></li>
                      <li><a href="/donate/shuoming"><span>捐赠说明</span></a></li>
                      <li><a href="/donate">我要捐赠</a></li>
                      <!--<li><a href="/donate/query">捐款到账查询</a></li>
                      --><li><a href="/donate/wuxie">捐赠鸣谢</a></li>
                   </ul>
              </div>
              <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/serline.jpg" /></div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/donate">在线捐赠</a> > 捐赠说明</span><em>捐赠说明</em></div>
              <div class="cle"></div>
              <div class="jjh_sub_con_content" style="height:450px;">
                  <p class="jjh_font3">谨向关心和支持天津大学教育事业的社会各界人士，表示最衷心的感谢！</p>
                  <p class="jjh_font4">捐赠鸣谢说明</p>
                  <div class="jjh_donate_methods_con">	一、天津大学热诚欢迎海内外企事业单位、团体、个人为我校的教育事业捐资。对每一位关心支持天津大学的朋友，我们都表示忠心的感谢。凡为天津大学捐资，为学校教育科研事业发展做出贡献的各界人士，都将永载天津大学的史册。<br />	二、凡为天津大学捐资，无论金额大小，教育基金会均开具天津市财政部门印制的天津市公益事业捐赠统一收据，并可签订书面协议，写明捐资金额、捐赠意向以及校方的承诺，并将捐资者名单列入名册存档。<br />三、对于部分捐赠项目，如基础设施建设、教席、奖助学金等，如捐赠达到一定额度，可以捐赠者或者捐赠者指定的名称命名。<br />	四、对提供捐赠的海内外企业、事业单位、机关、团体及个人，在国家法律、法规和学校规章制度准许的范围内，可优先享用学校的教学、科研等优质资源，优先享有开展合作、共建等权利。<br /></div>
                  <p class="jjh_font4">具体：</p>
                  <div class="jjh_donate_methods_con">1.巨额捐资者可成为天津大学北洋教育发展基金会名誉理事单位或理事，颁发捐资证书及纪念牌，北洋基金会组织捐赠仪式，通过新闻媒介报道消息，并根据捐赠者意愿在捐赠项目上予以冠名。<br />
	2.捐资在 100 万元或累积捐资金额在 100 万元以上者，可成为天津大学北洋教育发展基金会名誉理事单位或理事，颁发捐资证书及纪念牌，北洋基金会组织捐赠仪式，并通过新闻媒介报道消息。<br />
	3.捐资在 50 万元以上者，颁发捐资证书及纪念牌，基金会组织捐赠仪式并通过新闻媒介报道消息。<br />
	4.捐资在 10 万元以上者，颁发捐资证书及纪念牌。<br />
	5.捐资在 10000 元以上者，颁发捐资证书及纪念品。<br />
	6.捐资在 100 元以上者，颁发捐资证书。<br />
	7.捐资者的单位名称、姓名及捐赠金额将分批刊登在天津大学北洋教育发展基金会年度工作报告及基金会网站上，捐资名册将存档。同时，天津大学设立“捐资纪念墙（碑），铭刻所有捐赠者的单位名称、姓名永久纪念。</div>
              </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>