<?= $this->partial("common/header.phtml");?>
 <div class="jjh_content_sub" style="height:630px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/donate_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>在线捐赠</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/donate/fangshi">捐赠方式</a></li>
                      <li><a href="/donate/zhanghu">基金会账户</a></li>
                      <li><a href="/donate/mianshui">免税政策</a></li>
                      <li><a href="/donate/shuoming">捐赠说明</a></li>
                      <li><a href="/donate">我要捐赠</a></li>
                      <!--<li><a href="/donate/query">捐款到账查询</a></li>
                      --><li><a href="/donate/wuxie"><span>捐赠鸣谢</span></a></li>
                   </ul>
              </div>
              <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/serline.jpg" /></div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/donate">在线捐赠</a> > 捐赠鸣谢</span><em>最新捐赠</em></div>
              <div class="cle"></div>
              <div class="jjh_sub_con_content" style="height:450px;">
                  <p class="jjh_font2">衷心感谢您鼎力支持天津大学发展项目，您对学校事业的支持、对基金会工作的信任是我们成就卓越的重要推力！<br />
我们始终坚信，一分一分的积累，一次一次心的碰撞，我们收获的不仅仅是支撑着天津大学发展项目背后的数字，更是每一分爱心堆积的人与人之间、学子与母校之间的情感！
</p>
                  <table cellpadding="0" cellspacing="0" width="100%" align="center" style="margin-top:10px;">
                           <tr>
                             <td bgcolor="#f0f0f0" width="4">&nbsp;</td>
                             <td width="51" height="35" bgcolor="#f0f0f0"><b>姓名</b></td>
                             <td width="165" bgcolor="#f0f0f0"><b>捐款项目</b></td>
                             <td width="64" bgcolor="#f0f0f0"><b>捐款金额</b></td>
                           </tr>
                           <tr>
                             <td width="4" height="35" class="jjh_border1">&nbsp;</td>
                             <td class="jjh_border1">miya</td>
                             <td class="jjh_border1">学生资助项目--奖学金</td>
                             <td class="jjh_border1">￥100</td>
                           </tr>
                       </table>
                <div class="jjh_pagebar">
                共<font class="jjh_font5">1</font>页&nbsp;&nbsp;14/页&nbsp;&nbsp;首页&nbsp;&nbsp;上一页&nbsp;&nbsp;下一页&nbsp;&nbsp;尾页
                </div>

              </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>