<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:500px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/donate_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>捐赠政策</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                  	  <li><a href="/donate/fangshi">捐赠方式</a></li>
                      <li><a href="/donate/zhanghu"><span>基金会账户</span></a></li>
                      <li><a href="/donate/mianshui">免税政策</a></li>
                      <li><a href="/donate/shuoming"><span>捐赠说明</span></a></li>
                       <!--<li><a href="/donate">我要捐赠</a></li>
                       <li><a href="/donate/query">捐款到账查询</a></li>
                      <li><a href="/donate/wuxie">捐赠鸣谢</a></li> -->
                   </ul>
              </div>
              <div><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/serline.jpg" /></div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/donate">捐赠政策</a> > 基金会账户</span><em>基金会账户</em></div>
              <div class="cle"></div>
              <div class="jjh_sub_con_content" style="height:320px;">
                  <p class="jjh_font4">天津大学北洋教育发展基金会</p>
                  <div class="jjh_donate_methods_con">银行账户名称：天津大学北洋教育发展基金会<br /> 开户银行：天津银行兴科支行 <br /> 银行账号：103601201090035769</div>
              </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>