<!-- page header -->
<div class="pageheader">
	<h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加项目分类</span></h2>
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目分类管理</li>
            <li class="active">添加项目分类</li>
        </ol>
    </div>
</div>
<!-- /page header -->	
<!-- page mian -->   
<div id="main" class="main">
	<div id="rightstyle02" class="row">
        <div class="col-md-8">
			<section class="tile color transparent-white">
				<div class="detailedbox tile-body">
					<form class="form-horizontal" id="form1"  action="addrscate" method="post" encType="multipart/form-data">
						<div class="form-group">
           					 <label class="col-sm-2 control-label" for="input01">项目分类名称：</label>
            				<div class="col-sm-8"><input class="form-control" type="text" name="name" /></div>
            				<span class="col-sm-2" > * </span>
            			</div>	
						<div class="form-group form-footer">
							<div class="col-sm-offset-5 col-sm-7">
								<input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
								<input class="btn btn-default" type="reset" value="重 置" /> 
							</div>
						</div>
					</form>
            	</div>
             </section>
		  </div>
	</div>


    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(10)").addClass("open");
    </script>