<!-- page header -->
<div class="pageheader">
    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目分类列表</span></h2>
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目分类管理</li>
            <li class="active">项目分类列表</li>
        </ol>
    </div>
</div>
<!-- /page header -->

<div id="main" class="main">
	<div id="rightstyle02" class="row">
		<div class="col-md-8">
			<section class="tile color transparent-white">
				<div class="tile-body nopadding">
					<?php if($this->catelist != ""){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  <thead>
					  <tr>
						<td width="20%">项目分类id</td>
						<td width="40%">项目分类名称</td>
						<td width="20%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php 
						foreach($this->catelist as $k=>$v){?>
						 <tr>
						 	<td><?php echo $v['id'];?></td>
							<td><?php echo $v['catename'];?></td>
							<td><a href="/test/admin/editcate?id=<?php echo $v['id'];?>">
                            <button type="button" class="btn btn-greensea margin-bottom-20">编辑</button></a>
                            &nbsp;&nbsp;
                             <a href="#"><button type="button" class="btn btn-danger margin-bottom-20">删除</button></a>
                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
				</div>
				<div class="tile-footer">
					<div class="row">
                        <div align="right" class="page col-md-12">
                         共  <?php echo $this->total;?> 条          <?php echo $this->page;?></div>
                     <?php }else{?>
                        <div>暂无项目分类信息！<a href="/test/admin/addcate">点击添加</a></div>
                     <?php }?>
		  			</div>
				</div> 
        	</section>
		</div>
	</div>


    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(10)").addClass("open");
    </script>