<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑联系人</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目联系人管理</li>
            <li class="active">编辑联系人</li>
        </ol>
    </div>

</div>
<!-- /page header -->		
    <div id="main" class="main">
		<div id="rightstyle02" class="row">
        <div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="detailedbox tile-body">
			<form class="form-horizontal" action="editrspp" id="form1" method="post" encType="multipart/form-data">
            
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">人员姓名/组织机构名称：</label>
            <div class="col-sm-4">
            <input class="form-control" type="text" name="ppname" value="<?php echo $this->ppinfo[0]['ppname']?>"/>
            </div>
            <span class="col-sm-2" > * </span>
            </div>	

			<!--<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">相关项目名称：</label>
            <div class="col-sm-8">
                <select class="form-control" name="pp_pm_id">
                    <?php /*if($this->pmlist != ""){
                            foreach ($this->pmlist as $k => $v){
                        */?>
                        <option value="<?php /*echo $v['pname'];*/?>" <?php /*if ($this->ppinfo[0]['pp_pm_id'] == $v['pname']){echo "selected='selected'";}*/?>><?php /*echo $v['pname'];*/?></option>
                    <?php /*}}*/?>
                </select>
            </div>
           
            </div>-->

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">联系人类型：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="pp_cate" id="pp_cate">
                            <?php foreach($this->pp_config['pp_cate'] as $k => $v){?>
                                <option value="<?php echo $k;?>" <?php if ($this->ppinfo[0]['pp_cate'] == $k){echo "selected='selected'";}?>><?php echo $v;?></option>
                            <?php }?>
                        </select>
                    </div>
                </div>
                <!-- 捐赠方信息-->
                <div class="form-group jzf">
                    <label class="col-sm-2 control-label" for="input01">捐赠方类型：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="pp_jzf_cate">
                            <option value="">请选择捐赠方类型</option>
                            <?php foreach($this->pp_config['pp_jzf_cate'] as $k => $v){?>
                                <option value="<?php echo $k;?>" <?php if ($this->ppinfo[0]['pp_jzf_cate'] == $k){echo "selected='selected'";}?>><?php echo $v;?></option>
                            <?php }?>
                        </select>
                    </div>
                </div>
                <div class="form-group jzf">
                    <label class="col-sm-2 control-label" for="input01">捐赠方属性一：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="pp_jzf_attr1">
                            <option value="">请选择捐赠方属性一</option>
                            <?php foreach($this->pp_config['pp_jzf_attr1'] as $k => $v){?>
                                <option value="<?php echo $k;?>"  <?php if ($this->ppinfo[0]['pp_jzf_attr1'] == $k){echo "selected='selected'";}?>><?php echo $v;?></option>
                            <?php }?>
                        </select>
                    </div>
                </div>
                <div class="form-group jzf">
                    <label class="col-sm-2 control-label" for="input01">捐赠方属性二：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="pp_jzf_attr2">
                            <option value="">请选择捐赠方属性二</option>
                            <?php foreach($this->pp_config['pp_jzf_attr2'] as $k => $v){?>
                                <option value="<?php echo $k;?>"  <?php if ($this->ppinfo[0]['pp_jzf_attr2'] == $k){echo "selected='selected'";}?>><?php echo $v;?></option>
                            <?php }?>
                        </select>
                    </div>
                </div>
                <!-- 捐赠方信息-->

                <!-- 使用方信息-->
                <div class="form-group syf" style="display: none;">
                    <label class="col-sm-2 control-label" for="input01">使用方类型：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="pp_syf_cate">
                            <option value="">请选择使用方类型</option>
                            <?php foreach($this->pp_config['pp_syf_cate'] as $k => $v){?>
                                <option value="<?php echo $k;?>"  <?php if ($this->ppinfo[0]['pp_syf_cate'] == $k){echo "selected='selected'";}?>><?php echo $v;?></option>
                            <?php }?>
                        </select>
                    </div>
                </div>
                <!-- 使用方信息-->

                <!-- 业务方信息-->
                <div class="form-group yuf" style="display: none;">
                    <label class="col-sm-2 control-label" for="input01">业务方类型：</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="pp_yuf_cate">
                            <option value="">请选择业务方类型</option>
                            <?php foreach($this->pp_config['pp_yuf_cate'] as $k => $v){?>
                                <option value="<?php echo $k;?>"  <?php if ($this->ppinfo[0]['pp_yuf_cate'] == $k){echo "selected='selected'";}?>><?php echo $v;?></option>
                            <?php }?>
                        </select>
                    </div>
                </div>
                <!-- 业务方信息-->

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">Email：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="ppemail" value="<?php echo $this->ppinfo[0]['ppemail']?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>	

			<!--<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人QQ：</label>
            <div class="col-sm-8"><input type="text" name="pp_qq" value="<?php /*echo $this->ppinfo[0]['pp_qq']*/?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>	
            
            <div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系人MSN：</label>
            <div class="col-sm-8"><input type="text" name="pp_msn" value="<?php /*echo $this->ppinfo[0]['pp_msn']*/?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>-->

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">移动电话：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="ppmobile" value="<?php echo $this->ppinfo[0]['ppmobile']?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>	


			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">办公电话：</label>
            <div class="col-sm-4">
                <input class="form-control" type="text" name="ppphone"  value="<?php echo $this->ppinfo[0]['ppphone']?>" /></div>
            <span class="col-sm-2" >* 可添加多个，以“,”号隔开 </span>
            </div>	

			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">联系地址：</label>
            <div class="col-sm-4"><input class="form-control" type="text" name="pp_address" value="<?php echo $this->ppinfo[0]['pp_address']?>"/></div>
            <span class="col-sm-2" > * </span>
            </div>
            
			<div class="form-group">
            <label class="col-sm-2 control-label" for="input01">备注：</label>
                <div class="col-sm-9">
                    <textarea parsley-validation-minlength="1" name="pp_beizhu" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php echo $this->ppinfo[0]['pp_beizhu']?></textarea>
                </div>
            </div>	

					<input type="hidden" name="pid" value="<?php echo $this->ppinfo[0]['pid'];?>" />
			<div class="form-group form-footer">
				<div class="col-sm-offset-5 col-sm-7">
                     <input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                     <input class="btn btn-default" type="reset" value="重 置" />
				</div>
			</div>
			</form>
            </div>
            </section>
		  </div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(0)").addClass("open");

            if( $("#pp_cate").val() == '捐赠方' || $("#pp_cate").val() == '实际捐赠方'){
                $(".jzf").show();
                $(".syf").hide();
                $(".yuf").hide();
            }else if($("#pp_cate").val() == '使用方'){
                $(".jzf").hide();
                $(".syf").show();
                $(".yuf").hide();
            }else if($("#pp_cate").val() == '业务方'){
                $(".jzf").hide();
                $(".syf").hide();
                $(".yuf").show();
            }else{
                $(".jzf").hide();
                $(".syf").hide();
                $(".yuf").hide();
            }

            $("#pp_cate").change(function(){
                if( $("#pp_cate").val() == '捐赠方' || $("#pp_cate").val() == '实际捐赠方'){
                    $(".jzf").show();
                    $(".syf").hide();
                    $(".yuf").hide();
                }else if($("#pp_cate").val() == '使用方'){
                    $(".jzf").hide();
                    $(".syf").show();
                    $(".yuf").hide();
                }else if($("#pp_cate").val() == '业务方'){
                    $(".jzf").hide();
                    $(".syf").hide();
                    $(".yuf").show();
                }else{
                    $(".jzf").hide();
                    $(".syf").hide();
                    $(".yuf").hide();
                }
            });
        </script>