<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑历届理事会</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>历届理事会管理</li>
            <li class="active">编辑历届理事会</li>
        </ol>
    </div>

</div>
<!-- /page header -->

<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-6">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="editrsdirector"  id="form1" method="post" encType="multipart/form-data">
                        <input type="hidden" name="id" value="<?php echo $this->directorinfo[0]['id'];?>"/>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">历届理事会：</label>
                            <div class="col-sm-8">
                                <select name="director" class="control-label col-sm-6">
                                    <?php for($i=1;$i<20;$i++){?>
                                        <option value="第<?php echo $i;?>届理事" <?php if($this->directorinfo[0]['director'] == "第".$i."届理事")echo 'selected="selected"';?>>第<?php echo $i;?>届理事</option>
                                    <?php }?>
                                </select>
                            </div>
                            <span class="col-sm-2" >* </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">起始日期：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" type="text" value="<?php echo $this->directorinfo[0]['star_datetime']?>"  id="datepicker"  name="star_datetime" size="14"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">结束日期：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" type="text" value="<?php echo $this->directorinfo[0]['end_datetime']?>"  id="datepicker1"  name="end_datetime" size="14"/>
                            </div>
                        </div>

                        <div class="form-group form-footer">
                            <div class="col-sm-offset-4 col-sm-7">
                                <input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $(".menu li:eq(10)").addClass("open");
        </script>