	<div id="main">
		<div id="rightstyle02">
		<h4>管理组成员管理<span class="font_red"> >> </span><span class="font_red_big">添加管理员</span></h4>
			<div class="detailedbox">
			<form action="addrs" method="post" encType="multipart/form-data">
				<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					<tr>
					    <td width="20%" style="text-align:right;">管理员类型：</td>
						<td width="80%" style="text-align:left;">
							<select name="type">
								<option value="0">系统管理员</option>
								<option value="1">项目筹资管理员</option>
								<option value="2">项目资金管理员</option>
								<option value="3">项目使用管理员</option>
								<option value="4">项目管理员</option>
								<option value="5">统计管理员</option>
								<option value="6">网站管理员</option>
								<option value="7">财务人员</option>
							</select>
							<font color="#0474d6" > * </font>
						</td>
					</tr>

					 <tr>
					    <td width="20%" style="text-align:right;">管理员名称：</td>
						<td width="80%" style="text-align:left;">
							<input type="text" name="name" /><font color="#0474d6" > * </font>
						</td>
					</tr>
					 <tr>
					    <td width="20%" style="text-align:right;">管理员初始化密码：</td>
						<td width="80%" style="text-align:left;">
							<input type="password" name="pwd" /><font color="#0474d6" > * </font>
						</td>
					</tr>
										
					<tr>
					    <td width="20%" style="text-align:right;"> </td>
						<td width="80%" style="text-align:left;">
							<input type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; <input type="reset" value="重 置" /> 
						</td>
					</tr>
				</table>
			</form>
		  </div>
		</div>