	<div id="main">
		<div id="rightstyle02">
		<h4>管理组成员管理<span class="font_red"> >> </span><span class="font_red_big">编辑管理员</span></h4>
			<div class="detailedbox">
			<form action="editrs" method="post" encType="multipart/form-data">
				<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					<tr>
					    <td width="20%" style="text-align:right;">管理员类型：</td>
						<td width="80%" style="text-align:left;">
							<select name="type">
								<option value="0" <?php if($this->adminlist[0]['admin_type'] == 0){echo "selected='selected'";}?>>系统管理员</option>
								<option value="1" <?php if($this->adminlist[0]['admin_type'] == 1){echo "selected='selected'";}?>>项目筹资管理员</option>
								<option value="2" <?php if($this->adminlist[0]['admin_type'] == 2){echo "selected='selected'";}?>>项目资金管理员</option>
								<option value="3" <?php if($this->adminlist[0]['admin_type'] == 3){echo "selected='selected'";}?>>项目使用管理员</option>
								<option value="4" <?php if($this->adminlist[0]['admin_type'] == 4){echo "selected='selected'";}?>>项目管理员</option>
								<option value="5" <?php if($this->adminlist[0]['admin_type'] == 5){echo "selected='selected'";}?>>统计管理员</option>
								<option value="6" <?php if($this->adminlist[0]['admin_type'] == 6){echo "selected='selected'";}?>>网站管理员</option>
							</select>
							<font color="#0474d6" > * </font>
						</td>
					</tr>

					 <tr>
					    <td width="20%" style="text-align:right;">管理员名称：</td>
						<td width="80%" style="text-align:left;">
							<input type="text" name="name" value="<?php echo $this->adminlist[0]['admin_name'];?>"/><font color="#0474d6" > * </font>
						</td>
					</tr>

					<input type="hidden" name="id" value="<?php echo $this->adminlist[0]['id'];?>"/>					
					<tr>
					    <td width="20%" style="text-align:right;"> </td>
						<td width="80%" style="text-align:left;">
							<input type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; <input type="reset" value="重 置" /> 
						</td>
					</tr>
				</table>
			</form>
		  </div>
		</div>