<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加回馈信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目信息管理</li>
            <li class="active">添加回馈信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	
	<div id="main" class="main">
		<div id="rightstyle02" class="row">
			<div class="col-md-12">
				<section class="tile color transparent-white">
			<div class="detailedbox tile-body">
                <form class="form-horizontal" action="to-add" id="form11" method="post" encType="multipart/form-data">
				<div class="form-group">
						<label class="col-sm-2 control-label" for="input01">所属项目名称：</label>
                        <div class="col-sm-3">
                            <select class="chosen-select-1 chosen-transparent form-control" name="pm_id">
                                <option value="">请选择项目名称</option>
                                <?php if($this->pmlist != ""){
                                    foreach ($this->pmlist as $k => $v){
                                        ?>
                                        <option value="<?php echo $v['id'];?>"><?php echo $v['pname'];?></option>
                                    <?php }}?>
                            </select>
                            <input id="pname_info" type="hidden" name="pm_name" value=""/>
                        </div>
						<span class="col-sm-1" > * </span>
				</div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input06">回馈时间：</label>
                        <div class="col-sm-4">
                            <input class="form-control" data-date-format="YYYY-MM-DD" type="text"  id="datepicker"  name="feedback_datetime" size="14"/>
                        </div>
                    </div>

				<div class="form-group">
					    <label class="col-sm-2 control-label" for="input02">回馈方式：</label>
						<div class="col-sm-3">
							<select class="chosen-select chosen-transparent form-control" name="feedback_type">
								<option value="" >请选择类型</option>
                                <option value="致电" >致电</option>
                                <option value="致函" >致函</option>
                                <option value="当面拜访" >当面拜访</option>
                                <option value="赠送纪念品" >赠送纪念品</option>
                                <option value="其他" >其他</option>
							</select>
						</div>
						<span class="col-sm-1" > * </span>
				</div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">文档：</label>
                        <div class="col-sm-4">
                            <input name="files" type="file" value="" />
                        </div>
                        <span class="col-sm-2" > * </span>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">回馈人：</label>

                        <div class="col-sm-9">
                            <select class="selectpicker show-tick form-control" multiple data-live-search="false" name="feedbacker[]" id="feedbacker">
                                <?php if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                        <option value="<?php echo $k?>"><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">经办人：</label>

                        <div class="col-sm-9">
                            <select class="selectpicker show-tick form-control" multiple data-live-search="false" name="jbr[]" id="jbr">
                                <?php if($this->jjh_mg_pp_list != ""){
                                    foreach ($this->jjh_mg_pp_list as $k => $v){?>
                                        <option value="<?php echo $k?>"><?php echo $v?></option>
                                    <?php }}?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">选择进度：</label>
                        <div class="col-sm-4">
                            <input name="jindu" type="checkbox" value="1" />已回馈
                        </div>
                        <span class="col-sm-2" > * </span>
                    </div>

					<div class="form-group form-footer">
						<div class="col-sm-offset-5 col-sm-7">
                            <!--<input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;-->
                            <input class="btn btn-primary" type="button" onclick="dosubmit();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
							<input class="btn btn-default" type="reset" value="重 置" /> 
						</div>
					</div>
			</form>
			</div>
		 </section>
			</div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="/include/management/css/bootstrap-select.min.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="/include/management/js/bootstrap-select.min.js"></script>

        <script language="javascript">
            $(".menu li:eq(8)").addClass("open");

            function dosubmit(){
                if($(".chosen-single span").html() != "请选择项目名称"){
                    $("#pname_info").val($(".chosen-single span").html());
                    $("#form11").submit();
                }
            }

            $('#feedbacker').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

            $('#jbr').selectpicker({
                selectedText: 'cat',
                liveSearch: true,
                size:8
            });

        </script>

