	  		</div><!-- tab-pane -->
          </div><!-- tab-content -->
		</div>
	</div>
      <!-- Make page fluid-->

    </div>
    <!-- Wrap all page content end -->
	<section class="videocontent" id="video"></section>

	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="/include/management/assets/js/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/include/management/assets/js/vendor/bootstrap/bootstrap.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/mmenu/js/jquery.mmenu.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/sparkline/jquery.sparkline.min.js"></script>

    <?php if($this->controller == "index") {?>
        <script type="text/javascript" src="/include/management/assets/js/vendor/nicescroll/jquery.nicescroll.min.js"></script>
        <script src="/include/management/assets/js/vendor/easypiechart/jquery.easypiechart.min.js"></script>
        <!--<script src="/include/management/assets/js/vendor/flot/jquery.flot.orderBars.js"></script>-->

        <script type="text/javascript" src="/include/management/assets/js/vendor/animate-numbers/jquery.animateNumbers.js"></script>
        <script type="text/javascript" src="/include/management/assets/js/vendor/videobackground/jquery.videobackground.js"></script>
        <script type="text/javascript" src="/include/management/assets/js/vendor/blockui/jquery.blockUI.js"></script>

        <script src="/include/management/assets/js/vendor/flot/jquery.flot.min.js"></script>
        <script src="/include/management/assets/js/vendor/flot/jquery.flot.time.min.js"></script>
        <script src="/include/management/assets/js/vendor/flot/jquery.flot.selection.min.js"></script>
        <script src="/include/management/assets/js/vendor/flot/jquery.flot.animator.min.js"></script>

        <script src="/include/management/assets/js/vendor/rickshaw/raphael-min.js"></script>
        <script src="/include/management/assets/js/vendor/rickshaw/d3.v2.js"></script>
        <script src="/include/management/assets/js/vendor/rickshaw/rickshaw.min.js"></script>

        <script src="/include/management/assets/js/vendor/morris/morris.min.js"></script>
        <script src="/include/management/assets/js/vendor/tabdrop/bootstrap-tabdrop.min.js"></script>
        <script src="/include/management/assets/js/vendor/summernote/summernote.min.js"></script>
        <script src="/include/management/assets/js/vendor/chosen/chosen.jquery.min.js"></script>
    <?php }?>

    <script type="text/javascript" src="/include/management/assets/js/vendor/mmenu/js/jquery.mmenu.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/sparkline/jquery.sparkline.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/nicescroll/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/animate-numbers/jquery.animateNumbers.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/videobackground/jquery.videobackground.js"></script>
    <script type="text/javascript" src="/include/management/assets/js/vendor/blockui/jquery.blockUI.js"></script>

    <script src="/include/management/assets/js/vendor/summernote/summernote.min.js"></script>

    <script src="/include/management/assets/js/vendor/chosen/chosen.jquery.min.js"></script>
    
    <script src="/include/management/assets/js/vendor/momentjs/moment-with-langs.min.js"></script>
    <script src="/include/management/assets/js/vendor/datepicker/bootstrap-datetimepicker.min.js"></script>
   
    <script src="/include/management/assets/js/minimal.min.js"></script>


    
