<!DOCTYPE html>
<html>
  <head>
    <title>高校教育发展基金会 - 项目管理系统后台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta charset="UTF-8" />

    <!--<link rel="icon" type="image/ico" href="http://tattek.com/minimal/assets/images/favicon.ico" />-->
    <!-- Bootstrap -->
    <link href="/include/management/assets/css/vendor/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="/include/management/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="/include/management/assets/css/vendor/animate/animate.min.css">
    <link type="text/css" rel="stylesheet" media="all" href="/include/management/assets/js/vendor/mmenu/css/jquery.mmenu.all.css" />
    <link rel="stylesheet" href="/include/management/assets/js/vendor/videobackground/css/jquery.videobackground.css">
    <link rel="stylesheet" href="/include/management/assets/css/vendor/bootstrap-checkbox.css">

    <!--<link rel="stylesheet" href="/include/management/assets/js/vendor/rickshaw/css/rickshaw.min.css">-->
    <link rel="stylesheet" href="/include/management/assets/js/vendor/morris/css/morris.css">
    <link rel="stylesheet" href="/include/management/assets/js/vendor/tabdrop/css/tabdrop.css">
    <link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote.css">
    <link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote-bs3.css">
    <link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen.min.css">
    <link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen-bootstrap.css">
    <link rel="stylesheet" href="/include/management/assets/js/vendor/datepicker/css/bootstrap-datetimepicker.css">
	<link rel="stylesheet" href="/include/management/assets/css/minimal.css">
	<link rel="stylesheet" href="/include/management/assets/css/jjhstyle-bg0.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
  </head>
  <body class="bg-0">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Make page fluid -->
      <div class="row">

        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top navbar-transparent-white mm-fixed-top" role="navigation" id="navbar">
          
          <!-- Branding -->
          <div class="navbar-header col-md-2">
            <a class="navbar-brand" href="/management">
              高校教育发展基金会
            </a>
            <div class="sidebar-collapse">
              <a href="#">
                <i class="fa fa-bars"></i>
              </a>
            </div>
          </div>
          
          <!-- .nav-collapse -->
          <div class="navbar-collapse">
                        
            <!-- Page refresh -->
            <ul class="nav navbar-nav refresh">
              <li class="divided">
                <a href="#" class="page-refresh"><i class="fa fa-refresh"></i></a>
              </li>
            </ul>
            <!-- /Page refresh -->

            <!-- Search -->
            <!--<div class="search" id="main-search">
              <i class="fa fa-search"></i> <input type="text" placeholder="全局搜索站内内容">
            </div>-->
            <!-- Search end ---->

            <!-- Quick Actions -->
            <ul class="nav navbar-nav quick-actions">

              <li class="dropdown divided user" id="current-user">

                <a class="dropdown-toggle options" data-toggle="dropdown" href="#">
                    您好，<?php $admininfo = SessionUtil::getAdmininfo();print_r($admininfo['admin_name']);?> <i class="fa fa-caret-down"></i>
                </a>
                
                <ul class="dropdown-menu arrow settings">

                  <li class="divider"></li>

                  <li>
                    <a href="/support/user/editpwd"><i class="fa fa-lock" style="font-size:20px;"></i> 修改密码</a>
                  </li>

                  <!--<li>
                    <a href="#"><i class="fa fa-envelope"></i> 消息Indexs <span class="badge badge-red" id="user-inbox">3</span></a>
                  </li>-->

                  <li class="divider"></li>

                  <li>
                    <a href="/support/index/logout"><i class="fa fa-power-off"></i> 安全退出</a>
                  </li>
                </ul>
              </li>

            </ul>
            <!-- /Quick Actions -->



            <!-- Sidebar -->
            <ul class="nav navbar-nav side-nav collapsed" id="sidebar">


              <li class="navigation" id="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="#navigation">Navigation 导航<i class="fa fa-angle-up"></i></a>
                
                <ul class="menu">

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bar-chart-o"></i> 项目信息查询与统计 <b class="fa fa-plus dropdown-plus"></b>
                        </a>
                        <ul class="dropdown-menu">
                                <li>
                                    <a href="/management/chouzi/index">
                                        <i class="fa fa-caret-right"></i> 项目信息列表
                                    </a>
                                </li>

                                <li>
                                    <a href="/management/zijin/rate">
                                        <i class="fa fa-caret-right"></i> 项目签约信息统计
                                    </a>
                                </li>
                                <li>
                                    <a href="/management/report/index">
                                        <i class="fa fa-caret-right"></i> 项目管理统计
                                    </a>
                                </li>
                                <li>
                                    <a href="/management/report/chouzi">
                                        <i class="fa fa-caret-right"></i> 项目筹资管理统计
                                    </a>
                                </li>
                                <li>
                                    <a href="/management/report/zijin">
                                        <i class="fa fa-caret-right"></i> 项目收入信息统计
                                    </a>
                                </li>
                                <li>
                                    <a href="/management/report/shiyong">
                                        <i class="fa fa-caret-right"></i> 项目支出信息统计
                                    </a>
                                </li>
                                <li>
                                    <a href="/management/report/pmshouzhi">
                                        <i class="fa fa-caret-right"></i> 项目收支统计
                                    </a>
                                </li>
                                <li>
                                    <a href="/management/feedback/">
                                        <i class="fa fa-caret-right"></i> 项目回馈统计
                                    </a>
                                </li>
                                <li>
                                    <a href="/management/report/allpeibi">
                                        <i class="fa fa-caret-right"></i> 项目可申请项目配比查询
                                    </a>
                                </li>
                                <li>
                                    <a href="/management/report/huabo">
                                        <i class="fa fa-caret-right"></i> 项目已划拨项目配比查询
                                    </a>
                                </li>

                        </ul>
                    </li>


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-tasks"></i> 事务/任务管理 <b class="fa fa-plus dropdown-plus"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/management/task">
                                    <i class="fa fa-caret-right"></i>事务/任务管理
                                </a>
                            </li>
                        </ul>
                    </li>


                </ul>

              </li>
			<!--统计-->
              <!--<li class="summary" id="order-summary">
                <a href="#" class="sidebar-toggle underline" data-toggle="#order-summary">Orders Summary <i class="fa fa-angle-up"></i></a>

                <div class="media">
                  <a class="pull-right" href="#">
                    <span id="sales-chart"></span>
                  </a>
                  <div class="media-body">
                    This week sales
                    <h3 class="media-heading">26, 149</h3>
                  </div>
                </div>

                <div class="media">
                  <a class="pull-right" href="#">
                    <span id="balance-chart"></span>
                  </a>
                  <div class="media-body">
                    This week balance
                    <h3 class="media-heading">318, 651</h3>
                  </div>
                </div>

              </li>-->

              <!--<li class="settings" id="general-settings">
                <a href="#" class="sidebar-toggle underline" data-toggle="#general-settings">General Settings <i class="fa fa-angle-up"></i></a>

                <div class="form-group">
                  <label class="col-xs-8 control-label">Switch ON</label>
                  <div class="col-xs-4 control-label">
                    <div class="onoffswitch greensea">
                      <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="switch-on" checked="">
                      <label class="onoffswitch-label" for="switch-on">
                        <span class="onoffswitch-inner"></span>
                        <span class="onoffswitch-switch"></span>
                      </label>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-xs-8 control-label">Switch OFF</label>
                  <div class="col-xs-4 control-label">
                    <div class="onoffswitch greensea">
                      <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="switch-off">
                      <label class="onoffswitch-label" for="switch-off">
                        <span class="onoffswitch-inner"></span>
                        <span class="onoffswitch-switch"></span>
                      </label>
                    </div>
                  </div>
                </div>

              </li>-->

            </ul>
            <!-- Sidebar end -->

          </div>
          <!--/.nav-collapse -->

        </div>
        <!-- Fixed navbar end -->

        <!-- Page content -->
        <div id="content" class="col-md-12">
          	
          	<link href="/include/management/css/common.css" rel="stylesheet" type="text/css" />
			<!--<link href="/include/management/css/submain.css" rel="stylesheet" type="text/css" />-->
			
			<!--<script type="text/javascript" src="/include/ckeditor/ckeditor.js"></script>-->
