<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑任务信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>任务信息</li>
            <li class="active">编辑任务信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" id="form1" action="to-addtaskmain" method="post" encType="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">任务名称：</label>
                            <div class="col-sm-3">
                                <input class="form-control" type="text" name="title" value="<?php echo $this->task_info[0]['title']?>" />
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">任务类型：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="type">
                                    <option value="" >请选择...</option>
                                    <?php if($this->task_init_array['type'] != ""){
                                        foreach ($this->task_init_array['type'] as $k => $v){?>
                                            <option value="<?php echo $k?>" <?php if($this->$task_info[0]["type"] == $v) echo "selected='selected'";?>><?php echo $v?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">任务指派给：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="executor">
                                    <option value="" >请选择...</option>
                                    <?php if($this->admin_list != ""){
                                        foreach ($this->admin_list as $k => $v){?>
                                            <option value="<?php echo $v['id']?>" <?php if($this->$task_info[0]["executor"] == $v) echo "selected='selected'";?>><?php echo $v['admin_name']?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">开始时间：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" value="<?php echo $this->task[0]['star_time']?>" type="text"  id="datepicker"  name="star_time" size="14"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">预计结束时间：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" value="<?php echo $this->task[0]['end_time']?>"  type="text"  id="datepicker1"  name="end_time" size="14"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">协助者：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="helper">
                                    <option value="" >请选择...</option>
                                    <?php if($this->admin_list != ""){
                                        foreach ($this->admin_list as $k => $v){?>
                                            <option value="<?php echo $v['id']?>" <?php if($this->$task_info[0]["helper"] == $v['id']) echo "selected='selected'";?>><?php echo $v['admin_name']?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">优先级：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="schedule">
                                    <!--<option value="" >请选择...</option>-->
                                    <?php if($this->task_init_array['priority'] != ""){
                                        foreach ($this->task_init_array['priority'] as $k => $v){?>
                                            <option value="<?php echo $k?>" <?php if($this->$task_info[0]["priority"] == $k) echo "selected='selected'";?>><?php echo $v?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">进度完成度：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="schedule">
                                    <!--<option value="" >请选择...</option>-->
                                    <?php if($this->task_init_array['schedule'] != ""){
                                        foreach ($this->task_init_array['schedule'] as $k => $v){?>
                                            <option value="<?php echo $k?>" <?php if($this->$task_info[0]["schedule"] == $k) echo "selected='selected'";?>><?php echo $v?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">描述：</label>s
                            <div class="col-sm-8">
                                <textarea parsley-validation-minlength="1" name="description" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php echo $this->task_info[0]['description'];?></textarea>
                            </div>
                        </div>

                        <input class="btn btn-default" name="id" type="hidden" value="<?php echo $this->task_info[0]['id'];?>" />
                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>

                    </form>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(53)").addClass("open");
    </script>

