<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>任务详情</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>事物/任务管理</li>
            <li class="active">任务详情</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-white">

                <!-- tile header -->
                <div class="tile-header">
                    <div class="row">
                        <div class="col-md-9"><h3>任务详情<strong>T-Info</strong></h3></div>
                        <!--<div class="col-md-3"><h5><a href="/management/task" target="_blank">查看全部消息>></a></h5></div>-->
                    </div>
                    <div class="controls">
                        <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                        <a href="#" class="remove"><i class="fa fa-times"></i></a>
                    </div>
                </div>
                <!-- /tile header -->


                <div class="detailedbox tile-body">
                    <form class="form-horizontal" id="form1" action="to-add" method="post" encType="multipart/form-data">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">任务名称：</label>
                            <div class="col-sm-3">
                                <?php echo $this->task_info[0]['title'];?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">优先级：</label>
                            <div class="col-sm-3">
                                <?php if($this->task_init_array['priority'] != ""){
                                    foreach ($this->task_init_array['priority'] as $k => $v){?>
                                        <?php if($this->task_info[0]["priority"] == $k) echo $v;?>
                                    <?php }}?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">进度完成度：</label>
                            <div class="col-sm-3">
                                <?php echo $this->task_info[0]['schedule'];?> %
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">任务执行日期：</label>
                            <div class="col-sm-3">
                                <?php echo $this->task_info[0]['star_time'];?> ~ <?php echo $this->task_info[0]['end_time'];?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">任务指派给：</label>

                            <div class="col-sm-6">
                                <?php
                                        if(!empty($this->task_info[0]['executor'])){
                                            foreach($this->admin_list_info as $key => $value){
                                                if($key == $this->task_info[0]['executor']){
                                                    echo $value;
                                                }
                                            }
                                        }
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">协助者：</label>

                            <div class="col-sm-6">
                                <?php if($this->admin_list_info != ""){
                                    foreach ($this->admin_list_info as $k => $v){?>
                                        <?php
                                        if(!empty($this->task_info[0]['helper'])){
                                            foreach(explode(',',$this->task_info[0]['helper']) as $key => $value){
                                                if($k == $value){
                                                    echo $v.'&nbsp;&nbsp;';
                                                }
                                            }
                                        }?>
                                    <?php }}?>
                            </div>
                        </div>


                    </form>
                </div>
            </section>
        </div>
    </div>


    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-white">


                <!-- tile header -->
                <div class="tile-header">
                    <div class="row">
                        <div class="col-md-9"><h3>项目进度变更<strong>T-Changeing</strong></h3></div>
                        <!--<div class="col-md-3"><h5><a href="/management/task" target="_blank">查看全部消息>></a></h5></div>-->
                    </div>
                    <div class="controls">
                        <a href="#" class="refresh"><i class="fa fa-refresh"></i></a>
                        <a href="#" class="remove"><i class="fa fa-times"></i></a>
                    </div>
                </div>
                <!-- /tile header -->


                <div class="detailedbox tile-body">
                    <form class="form-horizontal"  id="form1" action="to-addtaskmain" method="post" encType="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">任务指派给：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="executor">
                                    <option value="" >请选择...</option>
                                    <?php if($this->admin_list != ""){
                                        foreach ($this->admin_list as $k => $v){?>
                                            <option value="<?php echo $v['id']?>" ><?php echo $v['admin_name']?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>


                        <!--<div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">开始时间：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" type="text"  id="datepicker"  name="star_time" size="14"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">预计结束时间：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" type="text"  id="datepicker1"  name="end_time" size="14"/>
                            </div>
                        </div>-->

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">协助者：</label>
                            <div class="col-sm-4">
                                <select class="chosen-select-1 chosen-transparent form-control" multiple data-live-search="false" name="helper[]" id="helper">
                                    <!--<option value="" >请选择...</option>-->
                                    <?php if($this->admin_list != ""){
                                        foreach ($this->admin_list as $k => $v){?>
                                            <option value="<?php echo $v['id']?>" ><?php echo $v['admin_name']?></option>
                                        <?php }}?>
                                </select>
                            </div>
                        </div>

                        <!--<div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">优先级：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="priority">
                                    <?php /*if($this->task_init_array['priority'] != ""){
                                        foreach ($this->task_init_array['priority'] as $k => $v){*/?>
                                            <option value="<?php /*echo $k*/?>" ><?php /*echo $v*/?></option>
                                        <?php /*}}*/?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>-->


                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">进度完成度：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="schedule">
                                    <!--<option value="" >请选择...</option>-->
                                    <?php if($this->task_init_array['schedule'] != ""){
                                        foreach ($this->task_init_array['schedule'] as $k => $v){?>
                                            <option value="<?php echo $k?>" ><?php echo $v?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">描述：</label>
                            <div class="col-sm-8">
                                <textarea parsley-validation-minlength="1" name="description" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                            </div>
                        </div>

                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" type="submit" value="提 交 变 更" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <!--<input class="btn btn-default" type="reset" value="重 置" />-->
                            </div>
                        </div>

                        <input name="status" type="hidden" value="1"/> <!-- 默认为新建任务 -->
                    </form>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>