<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>任务详情</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>事物/任务管理</li>
            <li class="active">任务详情</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" id="form1" action="to-add" method="post" encType="multipart/form-data">
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">任务名称：</label>
                            <div class="col-sm-3">
                                <?php echo $this->task_info[0]['title'];?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">优先级：</label>
                            <div class="col-sm-3">
                                <?php if($this->task_init_array['priority'] != ""){
                                    foreach ($this->task_init_array['priority'] as $k => $v){?>
                                        <?php if($this->task_info[0]["priority"] == $k) echo $v;?>
                                    <?php }}?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">进度完成度：</label>
                            <div class="col-sm-3">
                                <?php echo $this->task_info[0]['schedule'];?> %
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">任务执行日期：</label>
                            <div class="col-sm-3">
                                <?php echo $this->task_info[0]['star_time'];?> ~ <?php echo $this->task_info[0]['end_time'];?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">任务指派给：</label>

                            <div class="col-sm-6">
                                <?php
                                        if(!empty($this->task_info[0]['executor'])){
                                            foreach($this->admin_list_info as $key => $value){
                                                if($key == $this->task_info[0]['executor']){
                                                    echo $value;
                                                }
                                            }
                                        }
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">协助者：</label>

                            <div class="col-sm-6">
                                <?php if($this->admin_list_info != ""){
                                    foreach ($this->admin_list_info as $k => $v){?>
                                        <?php
                                        if(!empty($this->task_info[0]['helper'])){
                                            foreach(explode(',',$this->task_info[0]['helper']) as $key => $value){
                                                if($k == $value){
                                                    echo $v.'&nbsp;&nbsp;';
                                                }
                                            }
                                        }?>
                                    <?php }}?>
                            </div>
                        </div>


                    </form>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>