<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:500px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/contact_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>联系我们</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                       <li><a href="/contact"><span>联系方式</span></a></li>
                       <li><a href="/contact/frilink">友情链接</a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/contact">联系我们</a> > 联系我们</span><em>联系方式</em></div>
              <div class="cle"></div>
              <div class="jjh_sub_con_content" style="height:320px; background:url(<?php echo __DEFAULTINCLUDEPATH__;?>images/contactrcon.jpg) no-repeat 300px 60px;">
                  <span class="jjh_font4">天津大学北洋教育发展基金会联系方式</span><br /><br />
                  <span class="jjh_font2">电话：</span><?php echo $this->info[0]['web_tel'];?><br />
                  <span class="jjh_font2">传真：</span><?php echo $this->info[0]['web_fax'];?><br />
                  <span class="jjh_font2">E-mail：</span><?php echo $this->info[0]['web_email'];?><br />
                  <span class="jjh_font2">网址：</span><?php echo $this->info[0]['web_url'];?><br />
                  <span class="jjh_font2">地址：</span><?php echo $this->info[0]['web_address'];?><br />
                  <span class="jjh_font2">邮编：</span><?php echo $this->info[0]['web_weibo'];?><br />
                  <span class="jjh_font2">联系人：</span><?php echo $this->info[0]['web_recall'];?>
              </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>