<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:500px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/contact_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>联系我们</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                       <li><a href="/contact"><span>联系方式</span></a></li>
                       <li><a href="/contact/frilink">友情链接</a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><em>联系方式</em><span>当前位置：<a href="/contact">联系我们</a> > 联系我们</span></div>
              <div class="cle"></div>
              <div class="jjh_sub_con_content" style="height:320px; background:url(<?php echo __DEFAULTINCLUDEPATH__;?>images/contactrcon.jpg) no-repeat 300px 60px;">
                  <span class="jjh_font4">天津大学北洋教育发展基金会联系方式</span><br /><br />
                  <span class="jjh_font2">电话：</span>86-22-2740 3247<br />
                  <span class="jjh_font2">传真：</span>86-22-2740 3247<br />
                  <span class="jjh_font2">E-mail：</span>zhouyantj@tju.edu.cn<br />
                  <span class="jjh_font2">网址：</span>http://pyedf.tju.edu.cn<br />
                  <span class="jjh_font2">地址：</span>天津市南开区卫津路92号天津大学第九教学楼302-3<br />
                  <span class="jjh_font2">邮编：</span>300072<br />
                  <span class="jjh_font2">联系人：</span>李老师 范老师 周老师
              </div>
         </div>
     </div>
<?= $this->partial("common/footer.phtml");?>