<!-- page header -->
<div class="pageheader">
    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加学院管理员</span></h2>
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>学院管理员管理</li>
            <li class="active">添加学院管理员</li>
        </ol>
    </div>
</div>
<!-- /page header -->	
<div id="main" class="main">
	<div id="rightstyle02" class="row">
        <div class="col-md-8">
			<section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="toadd" method="post"  encType="multipart/form-data">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">管理员名称：</label>
                        <div class="col-sm-6"><input class="form-control" type="text" name="username" /></div>
                        <span class="col-sm-2" > * </span>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input01">用户密码：</label>
                        <div class="col-sm-6"><input class="form-control" type="password" name="password" /></div>
                        <span class="col-sm-2" >  *</span>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input02">所属部门：</label>
                        <div class="col-sm-6">
                            <select class="chosen-select chosen-transparent form-control" name="department_id">
                                <option value="" >请选择所属部门</option>
                                <?php if($this->departmentlist != ""){
                                    foreach ($this->departmentlist as $k => $v){?>
                                        <option value="<?php echo $v['id']?>" ><?php echo $v['pname']?></option>
                                    <?php }}?>
                            </select>
                        </div>
                        <span class="col-sm-1" > * </span>
                    </div>



                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">移动电话：</label>
                            <div class="col-sm-6"><input class="form-control" type="text" name="mobile" /></div>
                            <span class="col-sm-3" > * 可添加多个，以“,”号隔开</span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">E-mail：</label>
                            <div class="col-sm-6"><input class="form-control" type="text" name="email" /></div>
                            <span class="col-sm-2" > * </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">微信号：</label>
                            <div class="col-sm-6"><input class="form-control" type="text" name="wechat" /></div>
                            <span class="col-sm-2" >  </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">联系地址：</label>
                            <div class="col-sm-6"><input class="form-control" type="text" name="address" size="40"/></div>
                        </div>

               <!-- <div class="form-group">
                    <label class="col-sm-2 control-label" for="input01">备注：</label>
                    <div class="col-sm-9">
                        <textarea parsley-validation-minlength="1" name="pp_beizhu" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"></textarea>
                    </div>
                </div>-->
							
			<div class="form-group form-footer">
				<div class="col-sm-offset-5 col-sm-7">
					<input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
					<input class="btn btn-default" type="reset" value="重 置" /> 
				</div>
			</div>
			</form>
            </div>
            </section>
		 </div>
	</div>
        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $("#glzcygl").addClass("open");
        </script>