<!-- page header -->
<div class="pageheader">
    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加归属项目</span></h2>
    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>学院管理员管理</li>
            <li class="active">添加归属项目</li>
        </ol>
    </div>
</div>
<!-- /page header -->
<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-8">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="addpm" method="get" encType="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-2 control-label">项目名称：</label>
                            <div class="col-sm-4">
                                <select class="chosen-select-1 chosen-transparent form-control" name='pid' id="pname">
                                    <option value="">请选择项目名称</option>
                                    <?php if($this->pmlist != ""){
                                        foreach ($this->pmlist as $k => $v){
                                            ?>
                                            <option value="<?php echo $v['id'];?>"><?php echo $v['pname'];?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>

                        <input type="hidden" name="id" value="<?php echo $_REQUEST['id']?>"/>
                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $("#glzcygl").addClass("open");
    </script>