<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>学院管理员列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>人员管理</li>
            <li class="active">学院管理员列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
	<div id="rightstyle02" class="row">
		<div class="col-md-12">
			<section class="tile color transparent-white">
			<div class="tile-body">
                <form action="#" method="get">
                    <div class="form-group">

                        <div class="row">
                            <div class="form-group col-sm-3">

                                <label for="input01">管理员名称：</label>
                                <input type="text" class=" form-control" value="<?php echo $_REQUEST['username']?>" name="username"/>

                            </div>

                            <div class="form-group col-sm-3">
                                <label for="input01">移动电话：</label>
                                <input type="text" class=" form-control" value="<?php echo $_REQUEST['mobile']?>" name="mobile"/>
                            </div>

                            <div class="form-group col-sm-3">
                                <label for="input01">E-mail：</label>
                                <input type="text" class=" form-control" value="<?php echo $_REQUEST['email']?>" name="email"/>
                            </div>

                        </div>

                        <div class="row">
                            <div class="form-group col-sm-3">
                                <label for="input05">所属部门：</label>
                                <select class="chosen-select-1 chosen-transparent form-control" id="department_id" name="department_id">
                                    <option value="" >请选择所属部门</option>
                                    <?php if($this->departmentlist != ""){
                                        foreach ($this->departmentlist as $k => $v){?>
                                            <option value="<?php echo $v['id']?>" <?php if($_REQUEST['department_id']==$v['id']){echo "selected='selected'";}?>><?php echo $v['pname']?></option>
                                        <?php }}?>
                                </select>
                            </div>

                            <div class="form-group col-sm-3">
                                <label for="input01">微信：</label>
                                <input type="text" class=" form-control" value="<?php echo $_REQUEST['wechat']?>" name="wechat"/>
                            </div>

                            <div class="form-group col-sm-3">
                                <label for="input01">联系地址：</label>
                                <input type="text" class=" form-control" value="<?php echo $_REQUEST['address']?>" name="address"/>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group">
                                <div class="col-sm-1">
                                    <label for="input01"> </label>
                                    <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                                </div>

                                <div class="col-sm-2">
                                    <label for="input01"> </label>
                                    <a href="/management/support/add" target="_blank"><input class="btn btn-primary btn-block" type="button" value="添加人员信息"/></a>
                                </div>

                            </div>
                        </div>

                    </div>
                </form>

			</div>
			</section>
            <section class="tile color transparent-white">	
                <div class="tile-body nopadding">				
				<?php if(count($this->userlist) > 0){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					  <thead>
                          <tr>
                            <td width="10%">管理员用户名</td>
                            <td width="10%">所属部门</td>
                            <td width="10%">移动电话</td>
                            <td width="10%">E-mail</td>
                            <td width="10%">微信</td>
                            <td width="10%">联系地址</td>
                            <td width="10%">操作</td>
                          </tr>
						</thead>
                      <tbody>
					  <?php 
						foreach($this->userlist as $k=>$v){?>
						 <tr>
						 	 <td><?php echo $v['username'];?></td>
                             <td><?php echo $this->department_list[$v['department_id']];?></td>
                             <td><?php echo $v['mobile'];?></td>
                             <td><?php echo $v['email'];?></td>
                             <td><?php echo $v['wechat'];?></td>
                             <td><?php echo $v['address'];?></td>
                             <td>
                                    <a href="/management/support/edit?id=<?php echo $v['id'];?>" target="_blank">
                                        <button class="btn btn-greensea margin-bottom-20" type="button">编辑</button>
                                    </a>
                                    &nbsp;&nbsp;
                                     <a href="/management/support/editpwd?id=<?php echo $v['id'];?>" target="_blank">
                                         <button class="btn btn-greensea margin-bottom-20" type="button">修改密码</button>
                                     </a>
                                     &nbsp;&nbsp;
                                    <a href="/management/support/del?id=<?php echo $v['id'];?>" onclick="return window.confirm('确定要删除这条信息吗?');">
                                        <button class="btn btn-danger margin-bottom-20" type="button">删除</button>
                                    </a>
                                </td>
                            </tr>
					   <?php }?>
                       </tbody>
					</table>
				</div>

                <div style="border:2px dashed #ccc;border-radius: 5px;padding:0px;margin: 10px 5px 10px 5px;" class="row">
                    <a href="/management/support/add" target="_blank"><p style="text-align:center;font-size: 14px;"><span>+&nbsp; 添加</span></p></a>
                </div>


				<div class="tile-footer transparent-white">
				<div class="row">
					<div class="page col-md-12" align="right">
						共  <?php echo $this->total;?> 条          <?php echo $this->page;?></div>
					
				 <?php }else{?>
				 	<div style="padding:20px;">暂无学院管理员信息！<a href="/management/support/add" target="_blank">点击添加</a></div>
				 <?php }?>
		  </div>
		</div> 
			</section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(0)").addClass("open");
    </script>