<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  />
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  />
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑投资明细</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>投资明细信息</li>
            <li class="active">编辑投资明细</li>
        </ol>
    </div>

</div>
<!-- /page header -->


<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="to-addlog" method="post" encType="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input02">产品名称：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control" name="investment_product_id">
                                    <option value="" >请选择产品名称</option>
                                    <?php if($this->pm_mg_investment_product_list != ""){
                                        foreach ($this->pm_mg_investment_product_list as $k => $v){?>
                                            <option value="<?php echo $v['id']?>" <?php if($this->log_info[0]['investment_product_id']== $v['id'])echo 'selected="selected"';?>><?php echo $v['product_name']?></option>
                                        <?php }}?>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">类型：</label>
                            <div class="col-sm-3">
                                <select class="chosen-select chosen-transparent form-control type" name="type">
                                    <option value="1" <?php if($this->log_info[0]['type']==1)echo 'selected="selected"';?>>投入</option>
                                    <option value="2" <?php if($this->log_info[0]['type']==2)echo 'selected="selected"';?>>支出</option>
                                </select>
                            </div>
                            <span class="col-sm-1" > * </span>
                        </div>


                        <div class="form-group receipts">
                            <label class="col-sm-2 control-label" for="input06">投入支出操作时间：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" type="text" value="<?php echo $this->log_info[0]['account_re_datetime']?>"  id="datepicker"  name="account_re_datetime" size="14"/>
                            </div>
                        </div>

                        <div class="form-group shouru">
                            <label class="col-sm-2 control-label" for="input01">投资金额：</label>
                            <div class="col-sm-3">
                                <input class="form-control" type="text" name="account_receipts"  value="<?php echo $this->log_info[0]['account_receipts']?>"/>
                            </div>
                            <span class="col-sm-1" >元 * </span>
                        </div>

                        <div class="form-group shouru">
                            <label class="col-sm-2 control-label" for="input01">年化收益率：</label>
                            <div class="col-sm-3">
                                <input class="form-control" type="text" name="rate_of_return"  value="<?php echo $this->log_info[0]['rate_of_return']?>"/>
                            </div>
                            <span class="col-sm-1" > %</span>
                        </div>


                        <div class="form-group zhichu" style="display: none;">
                            <label class="col-sm-2 control-label" for="input01">支出金额：</label>
                            <div class="col-sm-3">
                                <input class="form-control" type="text" name="account_expenses"  value="<?php echo $this->log_info[0]['account_expenses']?>"/>
                            </div>
                            <span class="col-sm-1" >元 * </span>
                        </div>

                        <div class="form-group transparent-editor">
                            <label class="col-sm-2 control-label" for="input14">备注：</label>
                            <div class="col-sm-9">
                                <textarea parsley-validation-minlength="1" name="remark" parsley-rangelength="[20,200]" parsley-trigger="keyup" rows="6" id="input05" class="form-control parsley-validated"><?php echo $this->log_info[0]['remark']?></textarea>
                            </div>
                        </div>

                        <input value="<?php echo $this->log_info[0]['id'];?>" name="id" type="hidden"/>

                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(2)").addClass("open");
        <?php if($this->log_info[0]['type'] == 1){?>
            $(".shouru").show();
            $(".zhichu").hide();
        <?php }else{ ?>
            $(".shouru").hide();
            $(".zhichu").show();
        <?php }?>
        $(".type").change(function(){
            if($(".type").val() == '1'){
                $(".shouru").show();
                $(".zhichu").hide();
            }else if($(".type").val() == '2'){
                $(".shouru").hide();
                $(".zhichu").show();
            }
        });
    </script>

