<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑个人信息</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>个人中心</li>
            <li class="active">编辑个人信息</li>
        </ol>
    </div>

</div>
<!-- /page header -->
<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-12">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="edituserinfo" id="form1" method="post" encType="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">用户名：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="admin_name" value="<?php echo $this->admininfo['admin_name']?>" readonly="readonly"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input12">性别：</label>
                            <div class="col-sm-2">
                                <label class="radio-inline"><input type="radio" name="sex" value="1" <?php if($this->admininfo['sex']==1){echo 'checked="checked"';}?> size="14"/> 男  </label>
                                <label class="radio-inline"><input type="radio" name="sex" value="2"  <?php if($this->admininfo['sex']==2){echo 'checked="checked"';}?>  size="14"/> 女  </label>
                            </div>
                            <span class="col-sm-1" >  </span>
                        </div>
                        

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">办公电话：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="phone"  value="<?php echo $this->admininfo['phone']?>" /></div>
                            <span class="col-sm-2" >* 可添加多个，以“,”号隔开 </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">移动电话：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="mobile"  value="<?php echo $this->admininfo['mobile']?>" /></div>
                            <span class="col-sm-2" >* 可添加多个，以“,”号隔开 </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">邮箱：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="email"  value="<?php echo $this->admininfo['email']?>" /></div>
                            <span class="col-sm-2" >* 可添加多个，以“,”号隔开 </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">微信：</label>
                            <div class="col-sm-4">
                                <input class="form-control" type="text" name="wechat"  value="<?php echo $this->admininfo['wechat']?>" /></div>
                            <span class="col-sm-2" >* 可添加多个，以“,”号隔开 </span>
                        </div>

                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" type="submit"  value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>

    <script src="/include/management/assets/js/jquery.js"></script>
