<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>添加人员类型</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>人员类型管理</li>
            <li class="active">添加人员类型</li>
        </ol>
    </div>

</div>
<!-- /page header -->
<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-8">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="addrsdirector"  id="form1" method="post" encType="multipart/form-data">

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">历届理事会：</label>
                            <div class="col-sm-8">
                                <select class="form-control" name="director" class="control-label col-sm-6">
                                    <?php for($i=1;$i<20;$i++){?>
                                        <option value="第<?php echo $i;?>届理事">第<?php echo $i;?>届理事</option>
                                    <?php }?>
                                </select>
                            </div>
                            <span class="col-sm-2" >* </span>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">起始日期：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" type="text"  id="datepicker"  name="star_datetime" size="14"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input06">结束日期：</label>
                            <div class="col-sm-4">
                                <input class="form-control" data-date-format="YYYY-MM-DD" type="text"  id="datepicker1"  name="end_datetime" size="14"/>
                            </div>
                        </div>

                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>


    <script src="/include/management/assets/js/jquery.js"></script>
    <script language="javascript">
        $(".menu li:eq(10)").addClass("open");
    </script>