<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>编辑人员类型</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>人员类型管理</li>
            <li class="active">编辑人员类型</li>
        </ol>
    </div>

</div>
<!-- /page header -->

<div id="main" class="main">
    <div id="rightstyle02" class="row">
        <div class="col-md-8">
            <section class="tile color transparent-white">
                <div class="detailedbox tile-body">
                    <form class="form-horizontal" action="editrsppcate"  id="form1" method="post" encType="multipart/form-data">

                        <div class="form-group" style="margin:-7px 42px 3px">
                            <h4>编辑人员类型</h4>
                        </div>

                        <input type="hidden" name="id" value="<?php echo $this->ppcateinfo[0]['id'];?>"/>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="input01">人员类型名称：</label>
                            <div>
                                <input class="col-sm-4" class="form-control" type="text" name="pp_cate_name" value="<?php echo $this->ppcateinfo[0]['pp_cate_name']?>"/>
                            </div>
                            <span class="col-sm-4" > * 例如：项目负责人、项目捐赠方、实际来款方等。</span>
                        </div>

                        <div class="form-group form-footer">
                            <div class="col-sm-offset-5 col-sm-7">
                                <input class="btn btn-primary" type="button" onclick="javascript:noTips();" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="btn btn-default" type="reset" value="重 置" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            $("#ywxggl").addClass("open");
        </script>