	<div id="main">
		<div id="rightstyle02">
		<h4>资讯管理<span class="font_red"> >> </span><span class="font_red_big">添加网站资讯</span></h4>
			<div class="detailedbox">
			<form action="addresault" method="post" encType="multipart/form-data">
				<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					<tr>
					    <td width="20%" style="text-align:right;">资讯标题：</td>
						<td width="80%" style="text-align:left;">
							<input type="text" name="title" /><font color="red" > * </font>
						</td>
					</tr>
										  
					  <tr>
					    <td width="20%" style="text-align:right;">资讯副标题：</td>
						<td width="80%" style="text-align:left;">
							<input type="text" name="ctitle" /><font color="red" > * </font>
						</td>
					</tr>
					
										
					<tr>
					    <td width="20%" style="text-align:right;">资讯类型：</td>
						<td width="80%" style="text-align:left;">
							<select name="cate">
								<option value="gonggao" >基金会公告 </option>
								<option value="zizhuxinxi" >资助信息</option>
								<option value="xinwen" >基金会新闻</option>
								<option value="gongshi" >捐赠公示</option>
								<option value="baogao" >年度报告</option>
								<option value="tuwen" >图文新闻</option>
								<option value="renwu" >人物故事</option>
								<option value="shouyi" >受益感言</option>
							</select><font color="red" > * </font>
						</td>
					  </tr>
					
					
					<tr>
					    <td width="20%" style="text-align:right;">资讯图片：</td>
						<td width="80%" style="text-align:left;">
							<input type="file" name="pic" /> 当资讯为图片新闻时需添加图片。
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">资讯是否显示：</td>
						<td width="80%" style="text-align:left;">
							默认显示<input type="radio" name="display" value="1" checked="checked"/>
							不显示<input type="radio" name="display" value="0"/>
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">资讯内容：</td>
						<td width="80%" style="text-align:left;">
							<textarea class="ckeditor" name="content"></textarea>
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;">资讯描述：</td>
						<td width="80%" style="text-align:left;">
							<textarea class="ckeditor" name="miaoshu"></textarea>
						</td>
					</tr>
					
					<tr>
					    <td width="20%" style="text-align:right;"> </td>
						<td width="80%" style="text-align:left;">
							<input type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; <input type="reset" value="重 置" /> 
						</td>
					</tr>
				</table>
			</form>
		  </div>
		</div>