	<div id="main">
		<div id="rightstyle02">
		<h4>所属部门管理<span class="font_red"> >> </span><span class="font_red_big">添加所属部门</span></h4>
			<div class="detailedbox">
			<form action="addrsdepartment" method="post" encType="multipart/form-data">
				<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					
					 <tr>
					    <td width="20%" style="text-align:right;">所属部门名称：</td>
						<td width="80%" style="text-align:left;">
							<input type="text" name="name" /><font color="red" > * </font>
						</td>
					</tr>
															
					<tr>
					    <td width="20%" style="text-align:right;"> </td>
						<td width="80%" style="text-align:left;">
							<input type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; <input type="reset" value="重 置" /> 
						</td>
					</tr>
				</table>
			</form>
		  </div>
		</div>