	<div id="main">
		<div id="rightstyle02">
		<h4>项目分类管理<span class="font_red"> >> </span><span class="font_red_big">编辑项目分类</span></h4>
			<div class="detailedbox">
			<form action="editrscate" method="post" encType="multipart/form-data">
				<table class="table01" border="0" cellspacing="0" cellpadding="0" style="text-align:center">

					<input type="hidden" name="id" value="<?php echo $this->departmentinfo[0]['id'];?>"/>
					
					 <tr>
					    <td width="20%" style="text-align:right;">所项目分类名称：</td>
						<td width="80%" style="text-align:left;">
							<input type="text" name="name" value="<?php echo $this->departmentinfo[0]['catename']?>"/><font color="red" > * </font>
						</td>
					</tr>
															
					<tr>
					    <td width="20%" style="text-align:right;"> </td>
						<td width="80%" style="text-align:left;">
							<input type="submit" value="提 交" /> &nbsp;&nbsp;&nbsp;&nbsp; <input type="reset" value="重 置" /> 
						</td>
					</tr>
				</table>
			</form>
		  </div>
		</div>