<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" >
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/heart_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>捐赠故事</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/heart/shouyi">心声感恩</a></li>
                      <li><a href="/heart/renwu">捐赠故事</a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/heart">捐赠故事</a></span><em>捐赠故事</em></div>
              <div class="jjh_sub_con_content">
              	  <div class="jjh_heart_tit">捐赠故事<span><a href="/heart/renwu">更多>></a></span></div>
                  <div class="jjh_heart_con">
                      <ul class="jjh_report">
						<?php foreach ($this->renwu as $k => $v){?>
                      		<li><a href="/heart/renwuinfo?id=<?php echo $v['my_infor_id'];?>"><?php echo $v['my_infor_title'];?> </a><span>[ <?php echo $v['my_infor_datetime'];?> ]</span></li>
                      	<?php }?>
                      </ul>
                  </div>
              	  <div class="jjh_heart_tit" style="margin-top:10px;">心声感恩<span><a href="/heart/shouyi">更多>></a></span></div>
                  <div class="jjh_heart_con">
                      <ul class="jjh_report">
                      	<?php foreach ($this->info as $k => $v){?>
                      		<li><a href="/heart/shouyiinfo?id=<?php echo $v['my_infor_id'];?>"><?php echo $v['my_infor_title'];?> </a><span>[ <?php echo $v['my_infor_datetime'];?> ]</span></li>
                      	<?php }?>
                      </ul>
                  </div>
              </div>
         </div>
	<div class="cle">&nbsp;</div>
     </div>
<?= $this->partial('common/footer.phtml'); ?>