<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/news_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>捐赠故事</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/heart/shouyi"><span>心声感恩</span></a></li>
                      <li><a href="/heart/renwu">捐赠故事</a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/heart">捐赠故事</a> >心声感恩</span><em>心声感恩</em></div>
              <div class="jjh_sub_con_content">
                <div class="jjh_news_detail_tit"><font class="jjh_font3"><?php echo $this->info[0]['my_infor_title'];?></font><br /><font class="jjh_font6"><?php echo $this->info[0]['my_infor_datetime'];?></font> </div>
                <div class="jjh_news_detail_con">
                 	<?php echo $this->info[0]['my_infor_sumary'];?><br /><br />
                  	<?php echo $this->info[0]['my_infor_content'];?>
                </div>
              </div>
         </div>
	<div class="cle">&nbsp;</div>
</div>
<?= $this->partial("common/footer.phtml");?>