<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub" style="height:480px;">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/heart_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>捐赠故事</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/heart/renwu">心声感恩</a></li>
                      <li><a href="/heart/shouyi"><span>捐赠故事</span></a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><em>捐赠故事</em><span>当前位置：<a href="/heart">捐赠故事</a> >捐赠故事</span></div>
              <div class="jjh_sub_con_content" style="height:400px;">
                   <ul class="jjh_report">
                        <li><a href="newdetail.html">新鸿基地产郭氏基金助学金受益人——肖珊感言 </a><span>[ 2010-02-08 ]</span></li>
                        <li><a href="#">“袁天凡西吉农村教师培训”学员—吕晓燕学习心得</a><span>[ 2009-03-12 ]</span></li>
                        <li><a href="#">2011年新鸿基地产郭氏基金英国剑桥大学博士/硕士奖学金申请启动 </a><span>[ 2008-03-05 ]</span></li>
                        <li><a href="#">关于本基金会基本户账号变更的通知 </a><span>[ 2010-02-08 ]</span></li>
                   </ul>   
                   <div class="jjh_pagebar">
                共<font class="jjh_font5">1</font>页&nbsp;&nbsp;14/页&nbsp;&nbsp;首页&nbsp;&nbsp;上一页&nbsp;&nbsp;下一页&nbsp;&nbsp;尾页
                </div>               
              </div>
         </div>
     </div>
     <?= $this->partial('common/footer.phtml'); ?>