<?= $this->partial("common/header.phtml");?>
<div class="jjh_content_sub">
         <div class="jjh_content_sub_left">
              <div class="jjh_sub_topimg"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/heart_top_img.jpg" /></div>
              <div class="jjh_sub_nav_tit"><span>捐赠故事</span></div>
              <div class="jjh_sub_nav_con">
                   <ul>
                      <li><a href="/heart/shouyi"><span>心声感恩</span></a></li>
                      <li><a href="/heart/renwu">捐赠故事</a></li>
                   </ul>
              </div>
         </div>
         <div class="jjh_content_sub_right">
              <div class="jjh_sub_con_tit"><span>当前位置：<a href="/heart">捐赠故事</a> >心声感恩</span><em>心声感恩</em></div>
              <div class="jjh_sub_con_content">
                   <ul class="jjh_report">
                   <?php foreach ($this->shouyilist as $k => $v){?>
                   		<li><a href="/heart/shouyiinfo?id=<?php echo $v['my_infor_id'];?>"><?php echo mb_substr($v['my_infor_title'],0,40);?> </a><span>[ <?php echo $v['my_infor_datetime'];?> ]</span></li>
                   <?php }?>
                   </ul>   
                   <div class="jjh_pagebar"><!--
                共<font class="jjh_font5">1</font>页&nbsp;&nbsp;14/页&nbsp;&nbsp;首页&nbsp;&nbsp;上一页&nbsp;&nbsp;下一页&nbsp;&nbsp;尾页
                -->
                	<?php echo $this->page;?></div>               
              </div>
         </div>
	<div class="cle">&nbsp;</div>
     </div>
     <?= $this->partial('common/footer.phtml'); ?>