<?= $this->partial('en/header.phtml'); ?>

       <div class="jjh_en_con">
            <div class="jjh_en_sub_left">
                <div class="jjh_en_sub_left_tit">About PYEDF</div>
                <div class="jjh_en_sub_left_con">
                     <ul>
                        <li><a href="#introduction">Introduction</a></li>
                        <li><a href="#organization">Organization</a></li>
                        <li><a href="#leadership">Leadership</a></li>
                     </ul>
                </div>
            </div>
            <div class="jjh_en_sub_right">
               <div class="jjh_en_sub_right_tit"><a name="introduction" id="introduction"></a>Introduction to Tianjin University Peiyang Education Foundation</div>
               <div class="jjh_en_sub_right_con">
               Tianjin University Peiyang Education Development Foundation, a non-profit public benefit organization, was established in 1995 by Tianjin University. It is a non public offering foundation registered in Tianjin Administration Bureau of NGOs with Tianjin Education Commission as its competent business unit. <br /><br />
    The purpose of the foundation is to improve the education quality and promote the development of education and research of the University and nationwide by raising educational funds from domestic and foreign enterprises, social organizations and individuals. In accordance with the constitution, laws, regulations, national policies and moral standards, the foundation coordinates and manages the social donations to Tianjin University.<br /><br />
    The foundation supports various activities for the university development:<br />■ Construction and upgrade of teaching and research facilities;<br />
■ Development of key courses, disciplines and laboratories;<br />
■ Award to faculty and staff for their outstanding contribution in teaching and research;<br />
■ Award to outstanding students and aid to students with financial difficulties;<br />
■ Aid to academic publications, international exchange and cooperation;<br />
■ Other initiatives related with education and research;<br />
■ Specific items upon donators’ requirements.
               </div>
               <div class="jjh_en_sub_right_tit"><a name="organization" id="organization"></a>Organization</div>
               <div class="jjh_en_sub_right_con">The Foundation is governed by a Board of Directors that includes Chairperson, Vice Chairperson and 24 Directors from academic schools and administrative offices of the university. A Secretariat is set up to deal with daily affairs. There is also one supervisor who reviews the foundation's governance policies and procedures; budget and spending policy; staff compensation and benefit policy; general management, legal and personnel policies; and such other matters as directed by the Board of Directors.<br /><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/organnization.jpg" />
</div>
               <div class="jjh_en_sub_right_tit"><a name="leadership" id="leadership"></a>Leadership</div>
               <div class="jjh_en_sub_right_con"><span class="jjh_en_font1">Chairperson, Board of Directors</span>   Feng Yaqing<br />
<span class="jjh_en_font1">Vice Chairperson, Board of Directors</span>   Yang Xianjin&nbsp;&nbsp;&nbsp;&nbsp;Shu Gequn&nbsp;&nbsp;&nbsp;&nbsp;Li Yidan<br />
<span class="jjh_en_font1">Directors</span>  Yang Yuqin&nbsp;&nbsp;&nbsp;&nbsp;Hang Jianmin&nbsp;&nbsp;&nbsp;&nbsp;Xiao Songshan&nbsp;&nbsp;&nbsp;&nbsp;Lei Ming&nbsp;&nbsp;&nbsp;&nbsp;Gu Yao&nbsp;&nbsp;&nbsp;&nbsp;Bai Haili&nbsp;&nbsp;&nbsp;&nbsp;Yang Fuling&nbsp;&nbsp;&nbsp;&nbsp;Ma Guiqiu&nbsp;&nbsp;&nbsp;&nbsp;Kang Yilan&nbsp;&nbsp;&nbsp;&nbsp;Zang Wei&nbsp;&nbsp;&nbsp;&nbsp;Lian Jijian&nbsp;&nbsp;&nbsp;&nbsp;Jia Shaoyi&nbsp;&nbsp;&nbsp;&nbsp;Xu Youhao&nbsp;&nbsp;&nbsp;&nbsp;Jiang Enyong&nbsp;&nbsp;&nbsp;&nbsp;Sun Yugeng&nbsp;&nbsp;&nbsp;&nbsp;Pu Dongmei&nbsp;&nbsp;&nbsp;&nbsp;Hong Zaisheng&nbsp;&nbsp;&nbsp;&nbsp;Chen Yisong&nbsp;&nbsp;&nbsp;&nbsp;Wang Guohua&nbsp;&nbsp;&nbsp;&nbsp;Li Xiumin <br /><br />

<span class="jjh_en_font1">Supervisor</span>  Ma Chunyou<br />
<span class="jjh_en_font1">Secretary General</span>  Li Xiumin <br />
<span class="jjh_en_font1">Vice Secretary General</span>  Fan Chaoying&nbsp;&nbsp;&nbsp;&nbsp;Shang Yuguang&nbsp;&nbsp;&nbsp;&nbsp;Wang Wei<br />
<span class="jjh_en_font1">Consultants</span>  Shan Ping&nbsp;&nbsp;&nbsp;&nbsp;Wang Yulin&nbsp;&nbsp;&nbsp;&nbsp;Gao Wenxin<br />

</div>
            </div>
        </div>
   </div>
   <div class="jjh_en_footer"><span>Copyright © Tianjin University Peiyang Education Development Foundation  2011</span></div>
</div>  
</body>
</html>
