<?= $this->partial('en/header.phtml'); ?>
       <div class="jjh_en_con">
            <div class="jjh_en_sub_left">
                <div class="jjh_en_sub_left_tit">Contact Us</div>
                <div class="jjh_en_sub_left_con">
                     <ul>
                        <li><a href="#tax">Contact Us</a></li>
                     </ul>
                </div>
            </div>
            <div class="jjh_en_sub_right">
               <div class="jjh_en_sub_right_tit"><a name="tax" id="tax"></a>Contact Us</div>
               <div class="jjh_en_sub_right_con">
                 <span class="jjh_en_font2">You can contact us as follows:</span><br /><br />
                 <span class="jjh_en_font1"><font color="#901823">Tel:</font> 0086-22-2740 3247</span><br /><br />
                 <span class="jjh_en_font1"><font color="#901823">Fax:</font> 0086-22-2740 3247</span><br /><br />
                 <span class="jjh_en_font1"><font color="#901823">Email:</font> zhouyantj@tju.edu.cn</span><br /><br />
                 <span class="jjh_en_font1"><font color="#901823">Address:</font> Tianjin University Peiyang Education Development Foundation, 92 Weijin Road, Nankai District, Tianjin 300072, P. R. China</span><br /><br />
                 <span class="jjh_en_font1"><font color="#901823">Zip Code:</font> 0086-22-2740 3247</span><br /><br />
                 <span class="jjh_en_font1"><font color="#901823">Contact Person:</font> Ms. Li,&nbsp;&nbsp;&nbsp;&nbsp;Mr. Fan,&nbsp;&nbsp;&nbsp;&nbsp;Ms. Zhou</span><br />
               </div>
        </div>
     </div>
   </div>
   <div class="jjh_cle"></div>
   <div class="jjh_en_footer"><span>Copyright © Tianjin University Peiyang Education Development Foundation  2011</span></div>
</div>  
</body>
</html>
