<?= $this->partial('en/header.phtml'); ?>
       <div class="jjh_en_con">
            <div class="jjh_en_sub_left">
                <div class="jjh_en_sub_left_tit">Ways of Giving</div>
                <div class="jjh_en_sub_left_con">
                     <ul>
                        <li><a href="#forms">Forms of Donation</a></li>
                        <li><a href="#ways">The way of giving</a></li>
                     </ul>
                </div><br />
                <div class="jjh_en_sub_left_tit">Counseling hotline</div>
                <div class="jjh_en_sub_left_con"><span class="jjh_en_font3">0086-22-2740 3247</span></div>
            </div>
            <div class="jjh_en_sub_right">
               <div class="jjh_en_sub_right_tit"><a name="forms" id="forms"></a>Forms of Donation</div>
               <div class="jjh_en_sub_right_con">
               Tianjin University Peiyang Education Development Foundation can receive donation in the following forms: <br /><span class="jjh_en_font2">cash, cheque, bills of exchange, stocks, bonds and other securities, books, facilities, software, real estates, bequests and other property or goods</span>.
<br />
               </div>
               <div class="jjh_en_sub_right_tit"><a name="ways" id="ways"></a>The way of giving</div>
               <div class="jjh_en_sub_right_con">
               <span class="jjh_en_font1">1. Domestic Bank Transfer</span><br /><br />
<span class="jjh_en_font2">Bank Account Name:</span> Tianjin University Peiyang Education Development Foundation<br />
<span class="jjh_en_font2">Bank of Deposit:</span> Tianjin Bank Xingke Sub-Branch <br />
<span class="jjh_en_font2">Banking Account:</span>1036,0120,1090,035769<br />
<span class="jjh_en_font2">swift code:</span>TCCBCNBT<br /><br />
               <span class="jjh_en_font1">2. Postal Remittance</span><br /><br />
<span class="jjh_en_font2">Address:</span> Tianjin University Peiyang Education Development Foundation, 92 Weijin Road, Nankai District, Tianjin 300072, P. R. China <br />
<span class="jjh_en_font2">Remittee:</span> Tianjin University Peiyang Education Development Foundation <br /><br />
               <span class="jjh_en_font1">3. Cash and check from overseas</span><br /><br />
               <span class="jjh_en_font2">Please post the fulfilled cash cheque to the address as follow:</span><br />
Peiyang Education Development Foundation, Tianjin University, 92 Weijin Road, Nankai District, Tianjin 300072, P.R. China <br /><br />
               <span class="jjh_en_font1">4. Overseas Bank Remittance and Transfer</span><br />
               Peiyang Foundation receives overseas donation in the way of bank remittance and transfer through Tianjin Bank. To ensure your donation will reach Peiyang Foundation account safely and promptly, please fulfill Tianjin Bank swift code（TCCBCNBT）in standard form.
            </div>
        </div>
     </div>
   </div>
   <div class="jjh_cle"></div>
   <div class="jjh_en_footer"><span>Copyright © Tianjin University Peiyang Education Development Foundation  2011</span></div>
</div>  
</body>
</html>
