<?= $this->partial('en/header.phtml'); ?>

       <div class="jjh_en_con">
            <div class="jjh_en_con_left">
                 <div class="jjh_en_spolight"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/enadvtop.jpg" /></div>
                 <div class="jjh_en_con_spe">
                     <div class="jjh_en_con_spe_tit">Introduction to Tianjin University Peiyang Education Foundation<span>>>learn more</span></div>
                     <div class="jjh_en_con_spe_con">Tianjin University Peiyang Education Development Foundation, a non-profit public benefit organization, was established in 1995 by Tianjin University. It is a non public offering foundation registered in Tianjin Administration Bureau of ngos with Tianjin Education Commission as its competent business unit.<br /><br /> The purpose of the foundation is to improve the education quality and promote the development of education and research of the University and nationwide by raising educational funds from domestic and foreign enterprises, social organizations and individuals. In accordance with the constitution, laws, regulations, national policies and moral standards, the foundation coordinates and manages the social donations to Tianjin University.......</div>
                 </div>
                 <div class="jjh_en_con_spe_tit">Tax-Exemption Policy<span>>>learn more</span></div>
                     <div class="jjh_en_con_spe_con">
                          <div class="jjh_en_con_img"><img src="<?php echo __DEFAULTINCLUDEPATH__;?>images/taximg.jpg" /></div>
                          <div>Tianjin University Peiyang Education Development Foundation has got the
 “Qualification for Pre-tax Deduction of Charitable Donations” of Tianjin 
Municipality........</div>
                    </div>
             </div>
             <div class="jjh_en_con_right">
                <div class="jjh_en_con_right_content" style="margin-top:13px;">
                     <div class="jjh_en_con_right_tit">Foundation Account</div>
                     <div class="jjh_en_con_right_con">
                          <ul>
                            <li><span>Account Name :</span><br />Tianjin University Peiyang Education Development Foundation</li>
                            <li><span>Account Number :</span><br />1036,0120,1090,035769 </li>
                            <li><span>Bank's Name :</span><br />Tianjin Bank Xingke Sub-Branch </li>
                            <li><span>Bank's Swift Code :</span><br />TCCBCNBT</li>
                          </ul>
                     </div>
                </div>
                <div class="jjh_en_con_right_content" style="background:#f0f0f0;">
                     <div class="jjh_en_con_right_tit1">Contact Us Quickly</div>
                     <div class="jjh_en_con_right_con" style="height:155px; margin-top:5px;  line-height:5px;">
                          <ul>
                            <li>
                              <div class="jjh_en_fleft">Addr. :</div>
                              <div class="jjh_en_fright">
                              Tianjin University Peiyang Education Development Foundation, 92 Weijin Road, Nankai District, Tianjin 300072, P. R. China </div>
                              <div class="jjh_cle"></div>
                            </li>
                            <br />
                            <li>
                              <div class="jjh_en_fleft">Tel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</div>
                              <div class="jjh_en_fright">0086-22-2740 3247</div>
                              <div class="jjh_cle"></div>
                            </li>
                             <br />
                             <li>
                              <div class="jjh_en_fleft">Fax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</div>
                              <div class="jjh_en_fright">0086-22-2740 3247</div>
                              <div class="jjh_cle"></div>
                            </li>
                             <br />
                            <li>
                              <div class="jjh_en_fleft">Email :</div>
                              <div class="jjh_en_fright">zhouyantj@163.com</div>
                              <div class="jjh_cle"></div>
                            </li>
                          </ul>
                     </div>
                </div>
             </div>
        </div>
   </div>
   <div class="jjh_en_footer"><span>Copyright © Tianjin University Peiyang Education Development Foundation  2011</span></div>
</div>  
</body>
</html>
