<?= $this->partial('en/header.phtml'); ?>
       <div class="jjh_en_con">
            <div class="jjh_en_sub_left">
                <div class="jjh_en_sub_left_tit">Donation Project</div>
                <div class="jjh_en_sub_left_con">
                     <ul>
                        <li><a href="#student">Student Finance Assistance Scheme</a></li>
                        <li><a href="#faculty">Faculty Development Scheme</a></li>
                        <li><a href="#campus">Campus Culture Scheme</a></li>
                        <li><a href="#alumni">Alumni events (University’s anniversary) Scheme</a></li>
                        <li><a href="#university">University Development Scheme</a></li>
                     </ul>
                </div>
            </div>
            <div class="jjh_en_sub_right">
               <div class="jjh_en_sub_right_tit"><a name="student" id="student"></a>Student Finance Assistance Scheme</div>
               <div class="jjh_en_sub_right_con">
               ■ Scholarship—for excellent students to stimulate their potential.<br />
■ Financial Aid—for students with financial difficulties to finish their studies.<br />
■ Peiyang Fellowship---for excellent students with financial difficulties to call for self-improvement.<br />  
■ Fund for Overseas Experience Program—encouraging students to get involved in international exchange so as to broaden their horizon and advertise the university.<br />
■ Fund for Student Health—focusing on the healthy growth of students.<br />
               </div>
               <div class="jjh_en_sub_right_tit"><a name="faculty" id="faculty"></a>Faculty Development Scheme </div>
               <div class="jjh_en_sub_right_con">■ Award for outstanding teachers with teaching achievements.<br />
■ Fund for Talent Recruitment---absorbing first-class talents for the university’s prosperity.<br />
■ Fund for Overseas Research and Studies—promoting faculty development in global environment.<br />
■ Fund for Academic Publications ----advertising academic achievements and upgrading academic standards.<br />
</div>
               <div class="jjh_en_sub_right_tit"><a name="campus" id="campus"></a>Campus Culture Scheme</div>
               <div class="jjh_en_sub_right_con">■ Fund for Students’ Art Education---encouraging students to get involved in art education and enriching campus culture.<br />
■ Fund for Students’ Societies—proposing the application of theory into practice and strengthening students’ hands-on ability.<br />
■ Fund for Students’ Scientific and Technological Activities—advocating innovation and practice.<br />
■ Fund for Peiyang Lectures—developing wisdom by listening to celebrities in every walk of life.<br />
■ Fund for Sport Activities-- contributing to better health.<br />
■ Fund for Student Carve-out—encouraging carve-out to promote employment.<br />
</div>
               <div class="jjh_en_sub_right_tit"><a name="alumni" id="alumni"></a>Alumni events (University’s anniversary) Scheme</div>
               <div class="jjh_en_sub_right_con">■ Fund for the university’s anniversary events<br />&nbsp;&nbsp;&nbsp;&nbsp;>>1895 Alumni Fund<br />
■ Fund for Alumni Memorial—alumni tree, alumni garden, etc.<br />
</div>
               <div class="jjh_en_sub_right_tit"><a name="university" id="university"></a>University Development Scheme</div>
               <div class="jjh_en_sub_right_con">■ Fund for the capital construction of the university— campus infrastructure, new campus, named buildings etc.<br />
■ Fund for teaching and research--named labs, research centers, etc.<br />
■ Fund for academic school development—supporting the development of academic schools and departments.<br />
■ Tianjin University Development Fund—receiving all kinds of donations to support the university’s development.<br />
</div>
            </div>
        </div>
   </div>
   <div class="jjh_en_footer"><span>Copyright © Tianjin University Peiyang Education Development Foundation  2011</span></div>
</div>  
</body>
</html>
