<?= $this->partial('en/header.phtml'); ?>
       <div class="jjh_en_con">
            <div class="jjh_en_sub_left">
                <div class="jjh_en_sub_left_tit">Donor Recognition</div>
                <div class="jjh_en_sub_left_con">
                     <ul>
                        <li><a href="#donor">Donor Recognition</a></li>
                     </ul>
                </div>
            </div>
            <div class="jjh_en_sub_right">
               <div class="jjh_en_sub_right_tit"><a name="donor" id="donor"></a>Donor Recognition</div>
               <div class="jjh_en_sub_right_con">
               1. Tianjin University welcomes donations from enterprises, public institutions, organizations and individuals both at home and abroad, and deeply appreciates those who show concerns for or give supports to the university. <span class="jjh_en_font2">Anyone who donates to Tianjin University or makes contribution to the course of education and scientific research of the university will be marked in the history of Tianjin University. </span><br /><br />
2. Donors, regardless of the donated amount, will<span class="jjh_en_font2"> get a unified receipt issued by the Financial Sector of Tianjin Municipal Government from the Peiyang Education Development Foundation</span>. Written agreement can be signed to clarify donation amount, intent and commitment. The donor will be filed in the honor list.<br /><br />
3. Donors<span class="jjh_en_font2"> can name some of the donation programs</span> on the understanding that those donations reach a certain amount and lie within areas e.g. infrastructure construction, teaching post, merit fund and, etc.  <br /><br />
4. Given the laws and regulations of China and the rule & regulations of the university permit, enterprises, public institutions, organizations or individuals at home and abroad who give donation to the university <span class="jjh_en_font2">share a priority of using the teaching, research and other high quality resources of the university, as well as establishing collaboration or joint construction programs with the university</span>.<br />
               </div>
            </div>
        </div>
   </div>
   <div class="jjh_en_footer"><span>Copyright © Tianjin University Peiyang Education Development Foundation  2011</span></div>
</div>  
</body>
</html>
