<?= $this->partial('en/header.phtml'); ?>
       <div class="jjh_en_con">
            <div class="jjh_en_sub_left">
                <div class="jjh_en_sub_left_tit">Tax-Exemption Policy</div>
                <div class="jjh_en_sub_left_con">
                     <ul>
                        <li><a href="#tax">Tax-Exemption Policy</a></li>
                     </ul>
                </div>
            </div>
            <div class="jjh_en_sub_right">
               <div class="jjh_en_sub_right_tit"><a name="tax" id="tax"></a>Tax-Exemption Policy</div>
               <div class="jjh_en_sub_right_con">
               According to “Enterprise Income Tax Law of the People's Republic of China”, “Individual Income Tax Law of the People's Republic of China” and the implementation rules of the two laws, the Chinese Ministry of Finance, State Administration of Taxation, Ministry of Civil Affairs jointly issued “Notification of Pre-tax Deduction on Charitable Donations”(Ministry of Finance, [2008] 160), which clarifies that : <br /><br />
              <span class="jjh_en_font1">1. On condition that the donation of enterprise is given through public welfare organizations or government above county level including its departments, the portion of the donation that is within 12% of the enterprise’s total annual profit can be deducted from taxable income.</span><br /><br />
              <span class="jjh_en_font1">2. According to “Individual Income Tax Law of People’s Republic of China” and its implementation rules, on condition that the donation of individual is given to education and other public welfare through China's social organizations and government agencies, with respect to the charitable donations incurred by individuals, the portion of the donation that is within 30% of the individual’s total annual income is eligible to be deducted from the taxable income.</span> <br /><br />
              <span class="jjh_en_font2">Tianjin University Peiyang Education Development Foundation has got the “Qualification for Pre-tax Deduction of Charitable Donations” of Tianjin Municipality.</span>


               </div>
        </div>
     </div>
   </div>
   <div class="jjh_cle"></div>
   <div class="jjh_en_footer"><span>Copyright © Tianjin University Peiyang Education Development Foundation  2011</span></div>
</div>  
</body>
</html>
