<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>资金列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目进度管理</li>
            <li class="active">资金列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->

	<div id="main" class="main">
		<div id="rightstyle02" class="row">
		
        	<div class="col-md-12">
                <section class="tile color transparent-white">
                	<div class="tile-body">
                    	<form class="form-horizontal" action="#" method="post" name="search_form">
                        	<div class="form-group">
                            	<div class="row"> 
                                    <div class="form-group col-sm-9">
                                        <div class="col-sm-6" style="margin: -6px 20px 0px 20px;">
                                            <label class="control-label" for="input01">项目名称：</label>
                                            <select class="chosen-select-1 chosen-transparent form-control" name="pname">
                                                <option value="1">请选择项目名称</option>
                                                <?php if($this->pmlist != ""){
                                                    foreach ($this->pmlist as $k => $v){
                                                        ?>
                                                        <option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
                                                    <?php }}?>
                                            </select>
                                            <input id="pname_info" type="hidden" name="pname" value=""/>
                                        </div>
                                        <div class="col-sm-3">
                                            <label for="input02"> </label>
                                            <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                                        </div>
                                    </div>
                        		</div>
                        	</div>
                    	</form>
                    </div>
        		</section>
                <section class="tile color transparent-white">
					<div class="tile-body nopadding">
                    <?php if(count($this->zijinlist) != 0){?>
                        <table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center"> 
                        <thead>
					  		<tr>
                            <td width="24%">项目名称</td>
                            <td width="24%">项目捐赠者</td>
                            <!--<td width="12%">捐赠级别</td>-->
                            <td width="14%">捐赠到账日期</td>
                            <td width="13%">捐赠到账金额</td>
                            <td width="13%">操作</td>
                           </tr>
						</thead>
                        <tbody>
                          <?php 
                            foreach($this->zijinlist as $k=>$v){?>
                             <tr>
                                <td><?php echo $v['pm_name'];?>&nbsp;</td>
                                <td><?php echo $v['pm_pp'];?>&nbsp;</td>
                               <!-- <td><?php /*echo $v['pm_juanzeng_jibie'];*/?>&nbsp;</td>-->
                                <td><?php echo substr($v['zijin_daozhang_datetime'],0,10);?>&nbsp;</td>
                                <td><?php echo $v['zijin_daozheng_jiner'];?>&nbsp;元</td>
                                <td>
                                <a href="/test/zijin/editzijin?id=<?php echo $v['id'];?>">
                                <button class="btn btn-greensea margin-bottom-20" type="button">编辑</button>
                                </a> 
                                &nbsp;&nbsp;
                                <a href="/test/zijin/delzijin?id=<?php echo $v['id'];?>" onclick= "if(confirm( '是否确定！ 删除将无法找回该比来款信息。')==false) return false; "><button class="btn btn-danger margin-bottom-20" type="button">删除</button></a></td>
                             </tr>
                           <?php }?>
                        </tbody>
                        </table>
                    </div>
                    <div class="tile-footer">
					<div class="row">
					<div class="page col-md-12" align="right">
                            共  <?php echo $this->total;?> 条资金信息          <?php echo $this->page;?></div>
                        
                     <?php }else{?>
                        <div>暂无资金信息！<a href="/admin/zijin/addzijin">点击添加</a></div>
                     <?php }?>
              		 </div>
				 	 </div>
				</section>  
			</div> 
		</div>

        <script language="javascript">
            $(".menu li:eq(8)").addClass("open");
        </script>
