<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<link rel="stylesheet" href="/include/management/assets/css/vendor/animate/animate.css">
<link type="text/css" rel="stylesheet" media="all" href="/include/management/assets/js/vendor/mmenu/css/jquery.mmenu.all.css" />
<link rel="stylesheet" href="/include/management/assets/js/vendor/videobackground/css/jquery.videobackground.css">
<link rel="stylesheet" href="/include/management/assets/css/vendor/bootstrap-checkbox.css">

<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote-bs3.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen.min.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen-bootstrap.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/datepicker/css/bootstrap-datetimepicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpalette/bootstrap-colorpalette.css">
<link href="/include/management/assets/css/minimal.css" rel="stylesheet">

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目收益列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目收益管理</li>
            <li class="active">项目收益列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">

			<div class="col-md-12">
                <section class="tile color transparent-white">
                    <div class="tile-body">
                        <form action="#" method="get" name="search_form" >
                            <div class="form-group col-md-6">
                                <div class="row">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label" for="input01">项目名称：</label>
                                        <div class="col-sm-8">
                                            <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                                <option value="">请选择项目名称</option>
                                                <?php if($this->pmlist != ""){
                                                    foreach ($this->pmlist as $k => $v){
                                                        ?>
                                                        <option value="<?php echo $v['pname'];?>"><?php echo $v['pname'];?></option>
                                                    <?php }}?>
                                            </select>
                                            <input id="pname_info" type="hidden" name="pname" value=""/>
                                        </div>
                                    </div>

                                    <div class="form-group col-sm-3">
                                        <label class="col-sm-2 control-label" for="input01">项目名称：</label>
                                        <div class="col-sm-4">
                                            <input class="form-control" type="text" name="pname" />
                                        </div>
                                        <span class="col-sm-1" > * </span>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="input01">开始时间 ：</label>
                                        <div class="col-sm-4">
                                            <input class="form-control" type="text"  id="dateinput"  name="starttime"  size="14"/>
                                        </div>
                                        <label class="col-sm-2 control-label" for="input01">结束时间 ：</label>
                                        <div class="col-sm-4">
                                            <input class="form-control" type="text"  id="dateinput2"  name="endtime"  size="14"/></div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="form-group col-sm-4">
                                        <label for="input02"></label>
                                        <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                                    </div>

                                    <div class="form-group col-sm-4">
                                        <label for="input02"> </label>
                                        <input class="btn btn-primary btn-block" type="button" value="添加收益" onclick="window.location.href='/management/income/add'">
                                    </div>
                                </div>



                            </div>
                        </form>
                    </div>
                </section>

			<section class="tile color transparent-white">
				<div class="tile-body nopadding">
				<?php if(!empty($this->pageData)){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="24%">收益名称</td>
						<td width="12%">收益日期</td>
                        <td width="20%">收益金额</td>
                        <td width="20%">操作人</td>
                        <td width="20%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php
						foreach($this->pageData as $k=>$v){?>
						 <tr>
						 	<td>
                                <?php echo $v['pname'];?>
                            </td>
                             <td>
                                 <?php echo date("Y-m-s H:i:s",$v['income_datetime']);?>
                             </td>
                             <td>
                                     <?php echo $v['jje'];?>
                             </td>
                             <td>
                                 <?php echo $v['admin_name'];?>
                             </td>

							<td>
                                <a href="/management/income/edit?id=<?php echo $v['id'];?>">
                                    <button class="btn btn-greensea margin-bottom-20" type="button">编辑</button>
                                </a>
                                &nbsp;&nbsp;
                                <a href="#" onclick="alert('对不起，收益不提供删除功能，请联系管理员');">
                                    <button class="btn btn-danger margin-bottom-20" type="button">删除</button>
                                </a>
                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer">
					<div class="row">
					<div class="page col-md-12" align="right">
                        共  <?php echo $this->totalItems;?> 条收益信息         <?php echo $this->page['all'];?></div>
					
				 <?php }else{?>
                        <div class="row"><div style="margin: 10px;padding: 10px;">暂无收益信息！<a href="/management/income/add">点击添加</a></div></div>
				 <?php }?>
				 </div>

				 </div>
				 </section>
		  </div>
		</div>


        <script language="javascript">
            $(document).ready(function() {
                $('#dateinput').datepicker({
                    dateFormat: 'yy-mm-dd',  //日期格式，自己设置
                    buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置
                    buttonImageOnly: true,  //Show an image trigger without any button.
                    //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效
                    yearRange: '2008:2020',//年份范围
                    clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置
                    closeText:'关闭',
                    prevText:'前一月',
                    nextText:'后一月',
                    currentText:' ',
                    monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
                });
            });
        </script>

        <script language="javascript">
            $(document).ready(function() {
                $('#dateinput2').datepicker({
                    dateFormat: 'yy-mm-dd',  //日期格式，自己设置
                    buttonImage: 'calendar.gif',  //按钮的图片路径，自己设置
                    buttonImageOnly: true,  //Show an image trigger without any button.
                    //showOn: 'both',//触发条件，both表示点击文本域和图片按钮都生效
                    yearRange: '2008:2020',//年份范围
                    clearText:'清除',//下面的就不用详细写注释了吧，呵呵，都是些文本设置
                    closeText:'关闭',
                    prevText:'前一月',
                    nextText:'后一月',
                    currentText:' ',
                    monthNames:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
                });
            });
        </script>

        <script language="javascript">
            //$(".menu li:eq(33)").addClass("open");
        </script>