<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/jquery-ui-1.8.2.custom.css" type="text/css"  /> 
<link rel="stylesheet" href="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.css" type="text/css"  /> 
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/jquery.js"></script>
<script src="<?= __ADMININCLUDEPATH__;?>datepicker/ui.datepicker.js"></script>

<link rel="stylesheet" href="/include/management/assets/css/vendor/animate/animate.css">
<link type="text/css" rel="stylesheet" media="all" href="/include/management/assets/js/vendor/mmenu/css/jquery.mmenu.all.css" />
<link rel="stylesheet" href="/include/management/assets/js/vendor/videobackground/css/jquery.videobackground.css">
<link rel="stylesheet" href="/include/management/assets/css/vendor/bootstrap-checkbox.css">

<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/summernote/css/summernote-bs3.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen.min.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/chosen/css/chosen-bootstrap.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/datepicker/css/bootstrap-datetimepicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpicker/css/bootstrap-colorpicker.css">
<link rel="stylesheet" href="/include/management/assets/js/vendor/colorpalette/bootstrap-colorpalette.css">
<link href="/include/management/assets/css/minimal.css" rel="stylesheet">

<!-- page header -->
<div class="pageheader">

    <h2><i class="fa fa-tachometer"></i> Dashboard
        <span>项目收益列表</span></h2>

    <div class="breadcrumbs">
        <ol class="breadcrumb">
            <li>您的位置</li>
            <li>项目收益管理</li>
            <li class="active">项目收益列表</li>
        </ol>
    </div>

</div>
<!-- /page header -->


	<div id="main" class="main">
		<div id="rightstyle02" class="row">

			<div class="col-md-12">
                <section class="tile color transparent-white">
                    <div class="tile-body">
                        <form action="#" method="get" name="search_form" id="search_form1">
                            <div class="form-group">

                                <div class="row">
                                    <div class="form-group col-sm-6">
                                        <label class="col-sm-12 control-label" for="input01">项目名称：</label>
                                        <div class="col-sm-8">
                                            <select class="chosen-select-1 chosen-transparent form-control" id="pname">
                                                <option value="">请选择项目名称</option>
                                                <?php if($this->pmlist != ""){
                                                    foreach ($this->pmlist as $k => $v){
                                                        ?>
                                                        <option value="<?php echo $v['pname'];?>" <?php if($_REQUEST['pname'] == $v['pname'])echo 'selected="selected"';?>><?php echo $v['pname'];?></option>
                                                    <?php }}?>
                                            </select>
                                            <input id="pname_info" type="hidden" name="pname" value=""/>
                                        </div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="form-group col-sm-3">
                                        <label class="col-sm-12 control-label" for="input01">开始时间 ：</label>
                                        <div class="col-sm-12">
                                            <input class="form-control" type="text" id="datepicker1" data-date-format="YYYY-MM-DD"  name="starttime"  size="14" <?php if($this->starttime !=''){echo $this->starttime;}?>/>
                                        </div>
                                    </div>
                                    <div class="form-group col-sm-3">
                                        <label class="col-sm-12 control-label" for="input01">结束时间 ：</label>
                                        <div class="col-sm-12">
                                            <input class="form-control" type="text"  id="datepicker2" data-date-format="YYYY-MM-DD"  name="endtime"  size="14" <?php if($this->endtime !=''){echo $this->endtime;}?>/>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">

                                    <div class="form-group col-sm-2">
                                        <label for="input02"></label>
                                        <input class="btn btn-primary btn-block" type="submit" value="搜索"/>
                                    </div>


                                    <div class="form-group col-sm-2">
                                        <label for="input02"> </label>
                                        <input class="btn btn-primary btn-block" type="button" value="添加收益" onclick="window.location.href='/management/income/add'">
                                    </div>

                                    <div class="form-group col-sm-2">
                                        <label for="input02"></label>
                                        <input class="btn btn-primary btn-greensea" style="width: 100%;-webkit-appearance: button;    cursor: pointer;    display: block;
    width: 100%;    padding-left: 0;    padding-right: 0;margin-bottom: 0;    font-weight: 400;    text-align: center;    vertical-align: middle;    background-image: none;    border: 1px solid transparent;    white-space: nowrap;    padding: 6px 12px;    font-size: 14px;    line-height: 1.42857143;" onclick="post_submit()" type="button" value="下载excel报表"/>
                                    </div>

                                </div>

                                <div class="row">

                                </div>

                            </div>
                        </form>
                    </div>
                </section>

			<section class="tile color transparent-white">
				<div class="tile-body nopadding">
				<?php if(!empty($this->incomelist)){?>
					<table class="table table-bordered" border="0" cellspacing="0" cellpadding="0" style="text-align:center">
					 <thead>
					  <tr>
						<td width="24%">收益名称</td>
						<td width="12%">收益日期</td>
                        <td width="20%">收益金额</td>
                        <td width="20%">操作人</td>
                        <td width="20%">操作</td>
					  </tr>
					</thead>
                    <tbody>
					  <?php
						foreach($this->incomelist as $k=>$v){?>
						 <tr>
						 	<td>
                                <?php echo $v['pname'];?>
                            </td>
                             <td>
                                 <?php echo date("Y-m-d",$v['income_datetime']);?>
                             </td>
                             <td>
                                     <?php echo $v['income_jje'];?>
                             </td>
                             <td>
                                 <?php echo $v['admin_name'];?>
                             </td>

							<td>
                                <a href="/management/income/edit?id=<?php echo $v['id'];?>">
                                    <button class="btn btn-greensea margin-bottom-20" type="button">编辑</button>
                                </a>
                                &nbsp;&nbsp;
                                <a href="#" onclick="alert('对不起，收益不提供删除功能，请联系管理员');">
                                    <button class="btn btn-danger margin-bottom-20" type="button">删除</button>
                                </a>
                            </td>
						 </tr>
					   <?php }?>
                     </tbody>
					</table>
					</div>
					<div class="tile-footer">
					<div class="row">
					<div class="page col-md-12" align="right">
                        共  <?php echo $this->total;?> 条收益信息，合计：<?php echo number_format($this->jjehj,2);?> 元 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->page;?></div>
					
				 <?php }else{?>
                        <div class="row"><div style="margin: 10px;padding: 10px;">暂无收益信息！<a href="/management/income/add">点击添加</a></div></div>
				 <?php }?>
				 </div>

				 </div>
				 </section>
		  </div>
		</div>

        <script src="/include/management/assets/js/jquery.js"></script>
        <script language="javascript">
            //$(".menu li:eq(18)").addClass("open");

            function post_submit(){
                var inputNumber=$("<input type='hidden' name='excel' value='true'/>");
                $('#search_form1').append(inputNumber);
                $('#search_form1').submit();
            }
        </script>